### ISSUE TITLE
variables are not global as they were before? (re-opening #999 with demo repo!)

### ISSUE THREAD

**Issue by patrick99e99** [webpack-contrib/sass-loader#1000]
I previously opened this issue: #998 and #999, I am now re-opening a 3rd time with a demo repo showing the problem.

### Bug report

I have recently upgraded from webpack 4 to webpack 5, after doing this, global variables no longer are accessible in imported stylesheets.  When I have asked about this, others have tried to tell me things like "`@import` is an anti-pattern and you should be using `@use` instead!" ...

However, it is impossible to use `@use` for all situations, such as for example with `bootstrap-sass`, the documentation says to do:

```
$icon-font-path: "bootstrap-sass/assets/fonts/bootstrap/";
@import "bootstrap-sass/assets/stylesheets/bootstrap";
```

This no longer works because `$icon-font-path` is now (as of Webpack 5) undefined within that import statement.

I have asked questions on StackOverflow and webpack Gitter, and have not gotten any useful responses.

### Actual Behavior
```
ERROR in ./app/javascript/stylesheets/application.scss 1:0
Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ./node_modules/sass-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
> .colorized {
|   color: red;
| }

ERROR in ./app/javascript/stylesheets/base.scss
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
2 │   color: $color;
  │          ^^^^^^
  ╵
  app/javascript/stylesheets/base.scss 2:10  root stylesheet
SassError: SassError: Undefined variable.
  ╷
2 │   color: $color;
  │          ^^^^^^
  ╵
  app/javascript/stylesheets/base.scss 2:10  root stylesheet
    at /Users/patrick/coding/ruby/rails/sass-variable-test/node_modules/sass-loader/dist/index.js:54:16
    at Function.call$2 (/Users/patrick/coding/ruby/rails/sass-variable-test/node_modules/sass/sass.dart.js:96399:16)
    at render_closure1.call$2 (/Users/patrick/coding/ruby/rails/sass-variable-test/node_modules/sass/sass.dart.js:82305:12)
    at _RootZone.runBinary$3$3 (/Users/patrick/coding/ruby/rails/sass-variable-test/node_modules/sass/sass.dart.js:28284:18)
    at _FutureListener.handleError$1 (/Users/patrick/coding/ruby/rails/sass-variable-test/node_modules/sass/sass.dart.js:26806:21)
    at _Future__propagateToListeners_handleError.call$0 (/Users/patrick/coding/ruby/rails/sass-variable-test/node_modules/sass/sass.dart.js:27113:49)
    at Object._Future__propagateToListeners (/Users/patrick/coding/ruby/rails/sass-variable-test/node_modules/sass/sass.dart.js:12137:77)
    at _Future._completeError$2 (/Users/patrick/coding/ruby/rails/sass-variable-test/node_modules/sass/sass.dart.js:26959:9)
    at _AsyncAwaitCompleter.completeError$2 (/Users/patrick/coding/ruby/rails/sass-variable-test/node_modules/sass/sass.dart.js:26618:12)
    at Object._asyncRethrow (/Users/patrick/coding/ruby/rails/sass-variable-test/node_modules/sass/sass.dart.js:11940:17)
```

### Expected Behavior

Sass' documentation says:
> Variables declared at the top level of a stylesheet are global

Therefore, having :
```
# application.scss
$color: red
@import 'base';

# base.scss
.colorized {
  color: $color;
}
```

I expect that the variable `$color` should be available within the `base.scss` file, since `$color` should be global as it was declared "at the top".

### How Do We Reproduce?

1: clone the repo: https://github.com/patrick99e99/sass-variable-test

2: `npm i`

3: `RAILS_ENV=development ./node_modules/.bin/webpack --config config/webpack/development.js`

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 8.50 GB / 32.00 GB
  Binaries:
    Node: 14.18.1 - /opt/homebrew/opt/node@14/bin/node
    npm: 6.14.15 - /opt/homebrew/opt/node@14/bin/npm
  Browsers:
    Brave Browser: 96.1.32.106
    Chrome: 95.0.4638.69
    Firefox: 93.0
    Safari: 15.1
  Packages:
    sass-loader: ^12.3.0 => 12.3.0
    style-loader: ^3.3.1 => 3.3.1
    webpack: ^5.64.2 => 5.64.2
    webpack-dev-server: ^4.5.0 => 4.5.0
  Global Packages:
    webpack: 5.59.1
```

**Comment by alexander-akait** [comment]
Because you have `entry` in your `webpack.config.js`:
```js
{
entry: {
    'channels/consumer': '/path/to/sass-variable-test/app/javascript/channels/consumer.js',
    'channels/index': '/path/to/sass-variable-test/app/javascript/channels/index.js',
    'packs/application': '/path/to/sass-variable-test/app/javascript/packs/application.js',
    'stylesheets/application': '/path/to/sass-variable-test/app/javascript/stylesheets/application.scss',
     // No color variable
    'stylesheets/base': '/path/to/sass-variable-test/app/javascript/stylesheets/base.scss'
  },
}
```

Each entry point is independent, as well each `import`/`require` sass/scss file inside `JS`/`TS`/`Entrypoint`.

You can use https://github.com/webpack-contrib/sass-loader#additionaldata to share common imports.

We can't bundle sass from multiple entries in one file, it is impossible due conflicts and other fundamentals problems.

**Comment by patrick99e99** [comment]
I see..  Thank you very much for this information, this is finally starting to make sense.

When I upgraded to webpack 5, I also had upgraded @rails/webpacker-v6, which had told me to set the config's `source_entry_path` to `/` and that apparently means it was making an entry point for every single file.

So previously it looks like when I was using webpack 4 and webpacker-v5, i was just having an entry like:

```
entry: {
  'application': '/path/to/my_app/application.js'
}
```

and application.js was doing:

```
import 'stylesheets/application.scss'
```

Is that what I should still be doing?  Or is it better to have the entry config be something more similar to what you have above?  Something like
```
entry: {
  'packs/application': '/path/to/my_app/application.js',
  'stylesheets/application': '/path/to/my_app/application.scss'
}
```

?

**Comment by patrick99e99** [comment]
I pushed up a new commit to that demo branch..  I made a single `application.js` entry which imports `application.scss` and I get:
```
ERROR in ./app/javascript/stylesheets/application.scss 1:0
Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ./node_modules/sass-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
> .colorized {
|   color: red;
| }

webpack 5.64.2 compiled with 1 error in 410 ms
```

**Comment by alexander-akait** [comment]
Sorry, it is bug tracker, I can't say how to better setup your application... if you need to generate multiple css files from multiple scss you can share variables using https://github.com/webpack-contrib/sass-loader#additionaldata (you can use `@import`/`@use` there to keep variables in separated file).

Anyway you can still setup `css-loader` and `mini-css-extract-plugin` and use `import 'stylesheets/application.scss'` inside JS to generate styles.

**Comment by patrick99e99** [comment]
Thank you.

**Comment by patrick99e99** [comment]
So wait, I just tried this and it appears that global variables are NOT available inside modules when making use of `@use` ... Is this correct?

After adjusting my entry points, this now works:
```
# application.scss
$color: red
@import 'base';

# base.scss
.colorized {
  color: $color;
}
```

but if I do:

```
# base.scss
@use 'something' as something;
.colorized {
  color: $color;
}

# something.scss
h1 { color: $color }
```

Then it says undefined variable again.  Are global variables not accessible inside modules?

**Comment by alexander-akait** [comment]
We don't modify your code, just run sass

**Comment by patrick99e99** [comment]
I don't understand...  I just pushed up a commit to my demo repo, can you please pull and tell me why I am getting:
```
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
2 │   color: $color;
  │          ^^^^^^
```

**Comment by alexander-akait** [comment]
It means you don't have this variables, sorry, sass can't find it

**Comment by ef4** [comment]
@patrick99e99 `@use` makes the variable available under a namespace. You need `something.$color`, not `$color`. If you really want no namespace you can do `@use 'something' as *;`

**Comment by alexander-akait** [comment]
We can close it, because we can't fix it here and yes, please use `@use` for sass
