### ISSUE TITLE
SassError: This file is already being loaded.

### ISSUE THREAD

**Issue by dltmdrbtjd1** [webpack-contrib/sass-loader#1004]
<img width="352" alt="스크린샷 2021-12-20 오후 6 31 31" src="https://user-images.githubusercontent.com/93508746/146744930-59d8fb64-1b04-4e4e-8327-9e66a7bd8f81.png">

SassError: This file is already being loaded.

<img width="284" alt="스크린샷 2021-12-20 오후 6 33 00" src="https://user-images.githubusercontent.com/93508746/146745137-a6643320-5e15-4be4-a262-d01511201a77.png">

I'm currently setting up to use the storybook, but the error continues to occur in the corresponding part in webpackFinal in the main.js file of the storybook. What's the reason ?

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by alexander-akait** [comment]
Please fix it and I will reopen and help you
