### ISSUE TITLE
Incompatibility with latest node-sass and sass package versions

### ISSUE THREAD

**Issue by silverbackdan** [webpack-contrib/sass-loader#1005]
### Bug report

When building with Vercel (and not locally) there is an issue with the types declaration causing an error

### Actual Behavior

This is what shows in the output logs
```
FATAL  Nuxt build error
--
17:49:44.987 |  
17:49:44.987 | ERROR in node_modules/@types/sass-loader/interfaces.d.ts
17:49:44.987 | ERROR in node_modules/@types/sass-loader/interfaces.d.ts(410,43):
17:49:44.987 | 410:43 Generic type 'Options<sync>' requires 1 type argument(s).
17:49:44.987 | 408 \|     type Callback<T> = (loaderContext: Webpack.loader.LoaderContext) => T;
17:49:44.988 | 409 \|
17:49:44.988 | > 410 \|     type SassOptions = NodeSass.Options \| Sass.Options;
17:49:44.988 | \|                                           ^
17:49:44.988 | 411 \| }
17:49:44.988 | 412 \|
```

### Expected Behavior

The build should work

### How Do We Reproduce?

I would love to give a concise reproduction. However when building locally I could not replicate this. All I can see is in the Vercel builder, which is also using Node 14.x, when I use sass v1.45 which was released 10 days ago (and I tried with the latest node-sass instead as well) I get this error. If I use sass v1.44 it does not happen.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
I'm afraid I can't because this is a closed system in Vercel carrying out the build and it does not happen locally.. I know this makes it difficult and perhaps very hard to trace the issue. I'm sorry for this and understand if it means you are not able to look into it further.

In case the issue is with the builder package running I've also opened an issue on that repo here: https://github.com/nuxt/vercel-builder/issues/645

I'm afraid this is not my area of expertise but whatever I can do to try and help, please reach out.

Thanks.

**Comment by alexander-akait** [comment]
But it is typescript problem, we don't have types for `sass` here and can't fix it, sorry

**Comment by alexander-akait** [comment]
Maybe `sass` command change own types and before it was not generic, now it is generic, I think better to open an issue in `sass` (`dart-sass`) repo

**Comment by silverbackdan** [comment]
OK thank you, I'll try there.

**Comment by silverbackdan** [comment]
Although.. I see the types are in a dir `node_modules/@types/sass-loader` - is there any clues why there would be types in an sass-loader dir?

**Comment by alexander-akait** [comment]
We won't have types here yet, if you have problems with types from `node_modules/@types/sass-loader`, please open an issue in https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by alexander-akait** [comment]
The problem here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sass-loader/interfaces.d.ts#L410

**Comment by silverbackdan** [comment]
Brill, thanks very much!
