### ISSUE TITLE
Wrong link for Dart Sass Docs

### ISSUE THREAD

**Issue by kamatheuska** [webpack-contrib/sass-loader#1007]
Documentation Is:

- [X] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
The link [for Dart Sass options](https://github.com/sass/dart-sass#javascript-api) that is on **sass-loader** README on [line 324](https://github.com/webpack-contrib/sass-loader/blob/master/README.md?plain=1#L324) does not point to the right documentation. It seems that the [Dart Sass readme changed](https://github.com/sass/dart-sass/commit/811cffa2c1d2755883519e67d8c7b44cc994b8d1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L37) leaving an orphan link on **sass-loader** Docs

### Your Proposal for Changes
It would be awesome to be pointed to the right documentation, and the version of sass that this package is supporting.

**Comment by kamatheuska** [comment]
Also, it seems that this API is deprecated. If someone can point me out on how the docs should be updated I can do a PR for it :)

**Comment by alexander-akait** [comment]
We can change it on https://sass-lang.com/documentation/js-api/interfaces/Options
