### ISSUE TITLE
why the sass-loader still want the node-sass even if I am using dart-sass

### ISSUE THREAD

**Issue by jiangxiaoqiang** [webpack-contrib/sass-loader#1015]
This is the detail information of this problem:

https://stackoverflow.com/questions/70727487/is-it-possible-to-make-sass-loader-using-dart-sass-not-node-sass

**Comment by alexander-akait** [comment]
Please use the issue template, sorry I don't have enough information to help you, fix it and I reopen an issue and help you, thanks
