### ISSUE TITLE
pull the plug on node-sass?

### ISSUE THREAD

**Issue by jimmywarting** [webpack-contrib/sass-loader#1024]
### Feature Proposal

On https://www.npmjs.com/package/node-sass they say that node-sass and libsass is are deprecated. I have also had problem with this to build its binary on my machine... would it make since to just pull the plug on it and remove node-sass entirely from this sass-loader tool? 

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.13 GB / 32.00 GB
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Safari: 15.2
  Packages:
    clean-webpack-plugin: ^3.0.0 => 3.0.0 
    compression-webpack-plugin: ^7.1.2 => 7.1.2 
    dotenv-webpack: ^1.7.0 => 1.7.0 
    html-webpack-plugin: ^5.2.0 => 5.2.0 
    lodash-webpack-plugin: ^0.11.6 => 0.11.6 
    webpack: ^5.24.2 => 5.24.2 
    webpack-bundle-analyzer: ^4.4.0 => 4.4.0 
    webpack-cli: ^4.5.0 => 4.5.0 
    webpack-dev-server: ^3.11.2 => 3.11.2 
```

**Comment by alexander-akait** [comment]
We don't install `node-sass`, they are optional https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L46, so just don't install `node-sass`, and sorry we can't do it because many project still use `node-sass`
