### ISSUE TITLE
Resolution of node_modules imports broken with `sass-embedded`

### ISSUE THREAD

**Issue by francescocaveglia** [webpack-contrib/sass-loader#1028]
### Actual Behavior

Not sure is this is more a bug of `sass-loader` or `sass-embedded`
Using `sass-embedded` implementation, if the project structure contains multiple imports from node_modules if possible to get this error:
`SassError: TypeError: Cannot read properties of undefined (reading 'url')`

### Expected Behavior

The imports should be correctly resolved

### How Do We Reproduce?

Repository reproduce the error https://github.com/francescocaveglia/sass-loader-bug

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

In the example repo I used `boostrap-sass` but the problem can be reproduced adding multiple imports (3-4) from every package (tried `boostrap`, `swiper`, and combnations).

```
 System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 17.92 GB / 31.69 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.55)   
    Internet Explorer: 11.0.19041.1566
  Packages:
    css-loader: ^6.6.0 => 6.6.0
    sass-loader: ^12.6.0 => 12.6.0
    webpack: ^5.69.0 => 5.69.0
    webpack-cli: ^4.9.2 => 4.9.2

**Comment by alexander-akait** [comment]
Known bug in `sass-embedded` - https://github.com/webpack-contrib/sass-loader/issues/774#issuecomment-1041493056, we wait fixes from sass team, we can't fix it here
