### ISSUE TITLE
additionalData does not respect webpack resourceQuery

### ISSUE THREAD

**Issue by rooshan1234** [webpack-contrib/sass-loader#1033]
### Actual Behavior

Currently, when we provide additionalData with the following:
```
{
  loader: "sass-loader",
  options: {
    webpackImporter: true,
    additionalData: `@import "styles/foo.scss?lint";`
  }
}
```

The `resourceQuery`: `lint` at the end is ignored by the webpack importer and the normal `sass-loader` processes it. It should instead be reprocessed one of the existing loaders with the matching resource query.

### Expected Behavior

When we have `additionalData: @import "styles/foo.scss?lint";` being passed into the `sass-loader` option, we should expect that import to be processed by the appropriate loader matching that specific `resourceQuery`.

### How Do We Reproduce?

Using the following webpack rules:
```
{
  test: /\.s[ac]ss$/i,
  oneOf:[
    {
      resourceQuery: /some-resource-query/,
      loader: 'some-loader-here'
    },
    {
      resourceQuery: /lint/,
      loader: 'some-loader-here'
    },
    {
      use:[
        MiniCssExtractPlugin.loader,
        "css-loader",
        {
          loader: "sass-loader",
          options: {
            webpackImporter: true,
            additionalData: `@import "styles/foo.scss?lint";`
          }
        }
      ]  
  }
}
```

The `@import "styles/foo.scss?lint` provided by `additionalData` should hit the second matching `resourceQuery`.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 450.69 MB / 16.00 GB
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 96.0.2
    Safari: 14.0.3
  Packages:
    css-loader: ^6.5.1 => 6.5.1 
    file-loader: ^6.2.0 => 6.2.0 
    null-loader: ^4.0.1 => 4.0.1 
    postcss-loader: ^6.2.1 => 6.2.1 
    sass-loader: ^12.3.0 => 12.3.0 
    style-loader: ^3.3.1 => 3.3.1 
    stylelint-webpack-plugin: ^3.1.1 => 3.1.1 
    webpack: ^5.64.4 => 5.64.4 
    webpack-cli: ^4.9.1 => 4.9.1 
 ```

**Comment by alexander-akait** [comment]
Expected, `@import` inside `sass` only for SASS, webpack doesn't handle it, it is not fixable, sorry

**Comment by rooshan1234** [comment]
> Expected, `@import` inside `sass` only for SASS, webpack doesn't handle it, it is not fixable, sorry

Thank you for the quick reply! I guess my next question is, what is the job of the `webpackImporter: true` option then? I thought by swapping out the sass importer with webpack's importer, we would see the desired results?

**Comment by alexander-akait** [comment]
`webpackImporter` use https://github.com/webpack/enhanced-resolve/ to resolve `@import` (i.e. aliases and many other options), but it is not the same as rule for loader, we don't have sass graph, so we can't do it

**Comment by rooshan1234** [comment]
I see, thanks for the help! I wanted to target lint `.scss` files but will end up sticking to include and excludes for file targeting instead of custom resourceQuery.
