### ISSUE TITLE
Sass-Loader doesn't understand Maps

### ISSUE THREAD

**Issue by Mr-Nicolai** [webpack-contrib/sass-loader#1039]
### Bug report
Sass-Loader doesn't understand Maps

### Actual Behavior
When i'm using a Map Datastructure in my .scss File and i want it to transform (with the webpack command) from scss (sass-loader) to css (css-loader) to inline-style (style-loader) i get an error (see screenshot below)

### Expected Behavior
It should transform the Sass-Map to valid CSS... I'm using the latest Version of all loaders, webpack, webpack-cli and sass....

### How Do We Reproduce?
Just create a simple project with webpack and a scss-file which contains a map (like in the screenshot)... i also attached a screenshot with my webpack configuration...

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
![Screenshot1](https://user-images.githubusercontent.com/38925535/161489795-e6bef1ac-ce6e-4b3f-a8a3-ce76d3bbc3dc.PNG)
![webpack config](https://user-images.githubusercontent.com/38925535/161491060-c842c3e5-a5c0-454a-bb5f-e23c451dcc9a.PNG)

**Comment by alexander-akait** [comment]
You have broken sass code, sorry we can't fix it, if you provide code I will show how to fix it
