### ISSUE TITLE
Add --ascii-only flag to avoid emitting Unicode at all

### ISSUE THREAD

**Issue by mbohovic** [webpack-contrib/sass-loader#1050]
Source SCSS:

#test:before { content: "\2713"; }

Compiled css:

#test:before {  content: "✓"; }

The html entity '\2713' is replaced with the actual symbol '✓' in the complied css and then, it's shown like this "eâœ“" on browsers.

The correct output should be like the input.

**Comment by alexander-akait** [comment]
Please migrate on `dart-sass` or `sass-embeded`, known issue with `node-sass`, we can't fix it here

Anyway I reccomend to set `charset` to `UTF-8` in your HTML, I don't think your expected do not use utf-8 for your HTML document
