### ISSUE TITLE
fibers package is deprated 

### ISSUE THREAD

**Issue by inetbiz** [webpack-contrib/sass-loader#1058]
# Fibers package is depreated.

_April 13th, 2021_ [**Node v16.x**](https://github.com/laverdet/node-fibers "Node Fibers") see their README.md
https://github.com/webpack-contrib/sass-loader/blob/8cd2b19b15d00300d9cb3a4893698181af8651ce/README.md?plain=1#L243

**Comment by alexander-akait** [comment]
Feel free to send a PR and remove it

**Comment by amareshsm** [comment]
I would like to work on this issue. Can I pick this?

**Comment by alexander-akait** [comment]
Yes, PR welcome
