### ISSUE TITLE
Node-sass is deprecated

### ISSUE THREAD

**Issue by amareshsm** [webpack-contrib/sass-loader#1060]
## node-sass is deprecated

https://github.com/sass/node-sass#node-sass

<img width="913" alt="image" src="https://user-images.githubusercontent.com/30730124/172042472-6bdc0a18-be60-48ee-bb92-69572524d6c4.png">

Can we remove `node-sass` and migrate to `dart-sass`?
### Participation
- [x] I am willing to submit a pull request for this change.

**Comment by snitin315** [comment]
I suppose we support options from both https://github.com/webpack-contrib/sass-loader#sassoptions

**Comment by alexander-akait** [comment]
We will continue `node-sass` support, it is still popular
