### ISSUE TITLE
SassError: This file is already being loaded. (mixing additionalData and file imported in js)

### ISSUE THREAD

**Issue by iNeoO** [webpack-contrib/sass-loader#1073]
### Actual Behavior

Using additionalData in webpack and import scss file in js create a conflict

import file in additionalData that is also imported in js file (to extract variable) create an SassError: This file is already being loaded

### Expected Behavior

It should be possible to import scss file in js to get some variables and at same time import them globaly with additionalData.

### How Do We Reproduce?

Repo to reproduce
[https://github.com/iNeoO/vue-sass-test](https://github.com/iNeoO/vue-sass-test)

Tried to use @use, but it doesn't change anything

**Comment by alexander-akait** [comment]
`additionalData` is not do something magic, it is jsut contents that we include at top of file, so if it will create duplication you get this error, sorry we can't fix it

**Comment by iNeoO** [comment]
ok thanks

**Comment by alexander-akait** [comment]
Just try to include only variables (and exclude import them from loader) (also you can switch them based on externals options, for example - different themes)
