### ISSUE TITLE
Add support for node-sass v8 to  release v10 branch

### ISSUE THREAD

**Issue by pitgrap** [webpack-contrib/sass-loader#1101]
We're still relying on webpack4 and stuck to sass-loader v10. But we want to use node-sass v8 and node 18.

So please integrate #1100 into v10. Thank you.

**Comment by alexander-akait** [comment]
Feel free to send a PR

**Comment by alexander-akait** [comment]
@pitgrap Yeah, I got the same request from other originization and people, so I done it fast, released https://github.com/webpack-contrib/sass-loader/releases/tag/v10.4.0

**Comment by alexander-akait** [comment]
I think we can close it

**Comment by pitgrap** [comment]
I think you missed this part in your PR: https://github.com/webpack-contrib/sass-loader/pull/1072/files
