### ISSUE TITLE
[Windows]: sass-loader@13.2.1 will throw a python not found error

### ISSUE THREAD

**Issue by yoyo837** [webpack-contrib/sass-loader#1124]
### Actual Behavior

```
PS E:\sport-master\ydmap-web-cloud> npm install
npm ERR! code 1
npm ERR! path E:\sport-master\ydmap-web-cloud\node_modules\fibers
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node build.js || nodejs build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.19.1 | win32 | x64
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Admin\AppData\Local\Programs\Python\Python39\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\Admin\AppData\Local\Programs\Python\Python39\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Admin\AppData\Local\Programs\Python\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\Admin\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Admin\AppData\Local\Programs\Python\Python38\python.exe
npm ERR! gy
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 108.55 MB / 32.00 GB
  Binaries:
    Node: 16.19.1 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 110.0.1
    Safari: 16.3
  Packages:
    eslint-import-resolver-webpack: ^0.13.2 => 0.13.2 
```

**Comment by yoyo837** [comment]
sass-loader@13.2.0 works well.

**Comment by yoyo837** [comment]
I don't depend on fibers.

**Comment by alexander-akait** [comment]
As you can see `fibers` is optinal https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L58, so we don't install it by default, please double check

**Comment by yoyo837** [comment]
> As you can see `fibers` is optinal https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L58, so we don't install it by default, please double check

I also checked what you said. Strange that locking to version 13.2.0 did fix the problem, all else being equal

**Comment by yoyo837** [comment]
> > As you can see `fibers` is optinal https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L58, so we don't install it by default, please double check
> 
> I also checked what you said. Strange that locking to version 13.2.0 did fix the problem, all else being equal.

**Comment by alexander-akait** [comment]
Can you try to remove lock file and install all deps again?

**Comment by yoyo837** [comment]
> Can you try to remove lock file and install all deps again?

Yes, I tried.

Some additional information that may be useful:

![image](https://user-images.githubusercontent.com/6134547/227079541-7275c75d-73d0-4e65-9d8a-faaaa9407481.png)

![image](https://user-images.githubusercontent.com/6134547/227079555-55af45af-633f-4e71-9e2f-655b4f7a1650.png)

![image](https://user-images.githubusercontent.com/6134547/227079561-ab0b8eaa-8e26-4022-a9e8-8709e42e140f.png)

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/6134547/227079572-93020624-939e-41cf-b1fe-5cf459b36ba2.png">

**Comment by yoyo837** [comment]
I also found no clues from https://github.com/webpack-contrib/sass-loader/compare/v13.2.0...v13.2.1.

**Comment by alexander-akait** [comment]
@yoyo837 Can you try `npm ls fibers` and `npm why fibers`?

**Comment by yoyo837** [comment]
> @yoyo837 Can you try `npm ls fibers` and `npm why fibers`?

It's here:
![image](https://user-images.githubusercontent.com/6134547/227139930-13c346bf-fcc8-4e76-8460-3fddfd5d45a5.png)

**Comment by yoyo837** [comment]
`peerDependencies` `fibers` existed two years ago.

**Comment by yoyo837** [comment]
Thanks for your reply, I'll check it again.

**Comment by yoyo837** [comment]
If I install sass-loader -D directly, I also have this problem, on macos

![image](https://user-images.githubusercontent.com/6134547/229672988-915d43ae-dbcc-48d1-8814-2c80b87fef90.png)

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/229674244-36e2fcfa-afc9-48c7-8829-896ee0c9c9be.png)

I can't find the reason, can only lock in version `13.2.0`, it can works again.

**Comment by alexander-akait** [comment]
Sorry, I really can't reproduce, check your other deps, also try to update npm to the latest version

**Comment by yoyo837** [comment]
Thanks for your reply.

**Comment by alexander-akait** [comment]
Can you try another computer/os?

**Comment by yoyo837** [comment]
Sadly, both Windows and macOS have the same problem, my new discovery is that the 13.2.0 version can also reproduce the problem, I restored my old lock file to skip the problem in this moment.

**Comment by alexander-akait** [comment]
Do you try to update `npm`/`yarn` to the latest version? A lot of developers use `sass-loader` and many of them use `Node.js 18`, if we really a such problems we have a lot of reports here... So I think something wrong with npm/yarn. Can you start a new project and try to install sass-loader?

**Comment by yoyo837** [comment]
```shell
npm init (new project)
npm i sass-loader -D
```

lock file has no `fibers`.

**Comment by yoyo837** [comment]
> Do you try to update npm/yarn to the latest version?

I'll try to update npm later on `nodejs@16.x`.

**Comment by alexander-akait** [comment]
> lock file has no fibers.

It can be, but it should not be installed and no scripts will be run

**Comment by yoyo837** [comment]
I'm not means there is no `fibers` keyword characters, just that there is no `node_modules/fibers: {`.

**Comment by alexander-akait** [comment]
So, it works, right? It means something wrong with packages (i.e. someone installed fibers) or due to bugs in a package manager

**Comment by yoyo837** [comment]
> So, it works, right? It means something wrong with packages (i.e. someone installed fibers) or due to bugs in a package manager

Yes, right. 

> someone installed fibers

i confirm i didn't do that.

> or due to bugs in a package manager

Let me try to update npm@latest.

**Comment by alexander-akait** [comment]
Yeah :+1: Also try to search `fibers` in lock file, because you can found there is it in `dependecies`

**Comment by alexander-akait** [comment]
Okay, maybe you can invite me (or create reproducible example), so I can investigate it?

**Comment by yoyo837** [comment]
Thank you for your patience, how about a mini repo zip file?

**Comment by alexander-akait** [comment]
It is fine too

**Comment by yoyo837** [comment]
Could it be a problem with my private npm mirror? I used a private npm mirror.

**Comment by yoyo837** [comment]
Here is a 165 second screen recording to illustrate the above suspicion.


https://user-images.githubusercontent.com/6134547/230039139-2abf4c43-630e-402e-adf1-513210d73b82.mov

**Comment by yoyo837** [comment]
Good news, the private npm mirror cloud service provider I am using has confirmed that they may have related problems about above.

Thanks again for your reply.
