### ISSUE TITLE
VueJs is not compiling parent selector 

### ISSUE THREAD

**Issue by pddec** [webpack-contrib/sass-loader#1127]
Compling with vue JS
![sasscss](https://user-images.githubusercontent.com/73551981/227950846-12966e8c-ce60-43ca-80a8-8f230f73802c.png)

![sasshtml](https://user-images.githubusercontent.com/73551981/227947779-d5ac640a-0d1d-4f76-af24-772da399d9ee.png)

![vuecomp](https://user-images.githubusercontent.com/73551981/227948038-72d2b584-4ef1-4649-adb9-1ca8a98269d7.png)

Compiling with sass application works

![css](https://user-images.githubusercontent.com/73551981/227949921-8a8f77ae-c203-4db7-bfb2-5dd4947e3395.png)

**Comment by alexander-akait** [comment]
Sorry, please ask this in the vue-cli repository or the vue template rendering engine, we don't response for scoped styles and logic for their generation
