### ISSUE TITLE
Before publish to npm , 'prepare' scripts should be removed

### ISSUE THREAD

**Issue by RichieChoo** [webpack-contrib/sass-loader#1149]
When npm install command-line app with sass-loader，npm install global will [install devDep fibers](https://docs.npmjs.com/cli/v6/commands/npm-install) because the [prepare](https://github.com/webpack-contrib/sass-loader/blob/0cdc4dbf21372dfa30639fda56c2995e6063105f/package.json#L38).

fibers build error like :
<img width="757" alt="image" src="https://github.com/webpack-contrib/sass-loader/assets/17178139/0d5d2028-257c-4848-bd83-950ef3b9a221">

**Comment by alexander-akait** [comment]
Please update npm to the latest stable version, we don't install `fibers`, it is optional https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L62

**Comment by RichieChoo** [comment]
> Please update npm to the latest stable version, we don't install `fibers`, it is optional https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L62
npm install global will auto install  devDeps if it has a prepare script
<img width="652" alt="image" src="https://github.com/webpack-contrib/sass-loader/assets/17178139/6bf79451-a7b0-4983-9850-39510c2af8cb">

**Comment by RichieChoo** [comment]
> Please update npm to the latest stable version, we don't install `fibers`, it is optional https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L62

my npm version is v9.6.6

**Comment by alexander-akait** [comment]
As minimum please provide your package.json

**Comment by RichieChoo** [comment]
> As minimum please provide your package.json

I had reproduce the issue at https://github.com/RichieChoo/npm-global-test-sass-loader#readme, only sass-loader in [package.json](https://github.com/RichieChoo/npm-global-test-sass-loader/blob/main/package.json)

**Comment by alexander-akait** [comment]
You should never install `sass-loader` globally

**Comment by alexander-akait** [comment]
Check your npm configuration, maybe you have som flags

**Comment by RichieChoo** [comment]
Everyone, look at what a stubborn person!!! He still refuses to acknowledge theories and facts in front of him. How difficult is it to execute `npm install --verbose`?? Only a dynamic script can fix it ...

**Comment by alexander-akait** [comment]
@RichieChoo Are you seriously? We don't install fibers, `sass-loader` has `13,163,611` downloads per week and fibers doesn't work on Node.js 18 and above, If that were the case, we would have thousands of people here with problems. We cleary say https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L62 that `fibers` is optinal and **every** package manager should follow this

>  How difficult is it to execute npm install --verbose??

I done it multi times and I don't have `fibers`, even more I tried it using different versions and again I don't have `fibers`.

> If the package being installed contains a prepare script, its dependencies and devDependencies will be installed, and the prepare script will be run, before the package is packaged and installed.

Only for `npm install <git remote url>:` Do you have it? I don't see


>  He still refuses to acknowledge theories and facts in front of him.

Which acknowledge theories and facts? Read documentation again

**Comment by RichieChoo** [comment]
Run  `**npm install npm-global-test-sass-loader -g --verbose**`, and then you can found that fibers is fetched
<img width="996" alt="image" src="https://github.com/webpack-contrib/sass-loader/assets/17178139/e0281a72-d156-4d9c-a66f-828d933ff121">
The test package is  https://www.npmjs.com/package/npm-global-test-sass-loader, a npm package which has only sass-loader dependency!
Please tell me where the fibers come from , bro?

**Comment by RichieChoo** [comment]
<img width="1442" alt="image" src="https://github.com/webpack-contrib/sass-loader/assets/17178139/a569c017-c9ec-458b-b040-0ff3604bc743">

**Comment by RichieChoo** [comment]
Tired. If you do not want fixed, ignore thems even some people have

**Comment by RichieChoo** [comment]
> @RichieChoo Sorry for delay, do you still have a problem?

Yes~
