### ISSUE TITLE
v10.5.1 still not support node-sass 9

### ISSUE THREAD

**Issue by svyatoslavius** [webpack-contrib/sass-loader#1175]
### Bug report
sass-loader v10.5.1 still not support node-sass 9 because of this condition https://github.com/webpack-contrib/sass-loader/blob/v10/src/utils.js#L83

### Actual Behavior
after build i get this error:

`Node Sass version 9.0.0 is incompatible with ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0.`

### Expected Behavior
condition should have node-sass version ^9.0.0

**Comment by alexander-akait** [comment]
Fixed, release will be soon
