### ISSUE TITLE
Global variable scope when using `additionalData` option

### ISSUE THREAD

**Issue by xavierfoucrier** [webpack-contrib/sass-loader#1181]
Hello 👋 

I am using `additionalData` option to **pass my build environment mode** (dev/stage/prod/etc.) to scss.

Unfortunately, since I am using sass modules, it looks like the variable is only available in the main entry point `index.scss`, and not passed to other modules. I can understand the behavior, introduced by the scss module system.

Here is a short example:

```scss
// index.scss
@use 'navigation/header';

@debug $mode; // ✅ available
```

```scss
// header.scss
@debug $mode; // ❌ not found
```

Is there a way to declare a global variable through `additionalData` option and make it globally accessible in all files?
Currently the only way I found to pass it is to use `@use 'navigation/header' with ( $mode: $mode );` and put `$mode: 'dev' !default;` at the top of `header.scss` file... but not enough clean from my point of view.

Thanks for the feedback!

> The main goal behind this is to be able to output or not scss code based on build environment mode, may be there is a more fluent solution.

**Comment by alexander-akait** [comment]
`additionalData` is not magic or somethinf special from sass, it is just content which we inject into original content https://github.com/webpack-contrib/sass-loader/blob/master/src/utils.js#L113, you can use `function` to implement what you want, but no, we can't declare something globally, but yes, you can insert it in the each file

**Comment by xavierfoucrier** [comment]
Hey @alexander-akait 👋 

Yeah I can understand regarding the new module system of scss, I though I was missing something in the sass-loader, but no 😅, but yes I will give a try with `function` which is my only solution I guess!

Thanks again for the fast answer 🚀

**Comment by xavierfoucrier** [comment]
FYI, I just dive into the documentation again and test, but unfortunately, `additionalData` will only expose variables in the entry point, not in all other files. I am using `@use` everywhere and no more `@import`, that's why.

Anyway, I ended making it work following the scss module convention 🎉 
Here is a short example below:

```js
// webpack.config.js
additionalData: `$mode: '${env.mode}';`,
```
> Where `env.mode` follow my environment build mode (dev/stage/etc.)

```scss
// index.scss
@use 'utils/build' with (
  $mode: $mode
);

[...]
```
> Where `index.scss` is my scss entry point.

```scss
// utils/build.scss
$mode: 'development' !default;
```

```scss
// utils/debug.scss
@use 'utils/build';

@if build.$mode == 'development' {
  // debug stuff only for development environment
}
```

Thanks again for the fast answer Alex 🚀
