### ISSUE TITLE
webpack condition is not accepted when loading from packages

### ISSUE THREAD

**Issue by spike-rabbit** [webpack-contrib/sass-loader#1187]
### Actual Behavior

When loading files from other modules, webpack allows authors to specify conditions in the exports field. According to the [webpack documentation](https://webpack.js.org/guides/package-exports/#conditions-preprocessor-and-runtimes) there is a condition checking if `webpack` is used.

Therefore, an export field like this should provide different style sheets for webpack than for other tools.

```json
  "exports": {
    "./styles/*": {
      "webpack": {
        "sass": "./dist/styles/webpack/*.scss",
        "style": "./dist/styles/webpack/*.css"
      },
      "sass": "./dist/styles/*.scss",
      "style": "./dist/styles/*.css"
    }
  },
```

Currently, the webpack exports are ignored and the normal ones are used instead.

### Expected Behavior

I would expect, that webpack is using the files listed in the webpack section.

### How Do We Reproduce?

I currently face this using the angular version listed below. We need this check, as webpack imports fonts differently than esbuild and there is no way to have the same import path for both.

It seems like an easy task to fix this, so I could contribute.

Angular CLI: 17.1.0
Node: 20.10.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3

**Comment by alexander-akait** [comment]
Please create reproducible test repo, works fine locally

**Comment by alexander-akait** [comment]
I added a test case - https://github.com/webpack-contrib/sass-loader/pull/1189 and looks like it works fine, the `webpack` field works fine, I recommend to open an issue in angular repo, because I can't reproduce it using pure sass-loader

Anyway feel free to feedback, if you need a deep investigation you need to create a minimum reproducible example, thank you

**Comment by spike-rabbit** [comment]
Thanks a lot for verifying this. I created an issue at the angular repo: https://github.com/angular/angular-cli/issues/27100
