### ISSUE TITLE
I try to import custom theme and want to use css file in scss using @use but its got error 

### ISSUE THREAD

**Issue by ShabiRana** [webpack-contrib/sass-loader#1188]
./src/styles.scss - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
Can't find stylesheet to import.
  ╷
1 │ @use '~@angular/material' as mat;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\assets\css\partials\_utility.scss 1:1   @import
  src\assets\css\partials\_includes.scss 4:9  @import
  src\styles.scss 6:9                         root stylesheet

./src/styles.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):       
Can't find stylesheet to **import.**
  
**I'm using angular version 16
  node version 18**

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
