### ISSUE TITLE
Heads up: the Sass legacy JS API will start emitting warnings soon

### ISSUE THREAD

**Issue by nex3** [webpack-contrib/sass-loader#1210]
The Sass team is planning to release a version of Sass soon that begins to emit deprecation warnings for uses of [the legacy JS API](https://sass-lang.com/documentation/js-api/#md:legacy-api). Since this is currently the default for Next.js, it might be a good idea to move to using the [modern API](https://sass-lang.com/documentation/js-api/#md:usage) as the default instead.

**Comment by G-Rath** [comment]
@alexander-akait I'm not sure that this was resolved by #1211 as that was only meant to change the load order? I can only find a bunch of checks for the `api` being modern, but nowhere where the value actually defaults.

**Comment by alexander-akait** [comment]
I see, yeah

**Comment by alexander-akait** [comment]
Looks like I was very fast and we need a new major release :smile:

**Comment by xavierfoucrier** [comment]
@alexander-akait I would say "as usual" IMHO 😅☕✌️
