### ISSUE TITLE
Asset module source map `sources` are invalid and omit `sourcesContent`

### ISSUE THREAD

**Issue by colinrotherham** [webpack-contrib/sass-loader#1222]
### Bug report

When using the new [webpack@5.93.0](https://github.com/webpack/webpack/releases/tag/v5.93.0) `binary` generator option (see [issue #962](https://github.com/webpack-contrib/sass-loader/issues/962)) the source map JSON is missing `sourcesContent` and has invalid `webpack:///data:;` content inside the `sources` array.

This also affects previous releases using `modern` or `modern-compiler` API option too.

**Note:** Unlike the legacy compiler, missing `sourcesContent` can be restored with ~[`sourceMapContents: true`](https://sass-lang.com/documentation/js-api/interfaces/legacystringoptions/#sourceMapContents)~ [`sourceMapIncludeSources: true`](https://sass-lang.com/documentation/js-api/interfaces/options/#sourceMapIncludeSources) but the `sources` property remains invalid.

### Actual Behavior

Source map `sourcesContent` is missing and `sources` content includes encoded content

```patch
- {"version":3,"sourceRoot":"","sources":["webpack:///../node_modules/govuk-frontend/dist/govuk/core/_govuk-frontend-properties.scss",
+ {"version":3,"sourceRoot":"","sources":["webpack:///data:;charset=utf-8,:root%20%7B%0A%20%20//
```

In Safari web inspector, this is logged with **`Failed to load resource: unsupported URL`**

### Expected Behavior

Source map `sourcesContent` is included by default and `sources` content is correctly encoded

### How Do We Reproduce?

See minimal reproduction repo in [colinrotherham/**sass-loader-source-maps**](https://github.com/colinrotherham/sass-loader-source-maps)

This follows the [README asset module](https://github.com/webpack-contrib/sass-loader?tab=readme-ov-file#2-asset-modules) approach via the following rule:

```js
{
  test: /\.scss$/,
  type: 'asset/resource',
  generator: {
    binary: false,
    filename: '[name].css[query]'
  },
  use: [
    {
      loader: 'sass-loader',
      options: {
        // api: 'legacy', // ✅
        // api: 'modern', // ❌
        // api: 'modern-compiler', // ❌
        sassOptions: {
          quietDeps: true,
          style: 'expanded'
        }
      }
    }
  ]
}
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```console
  System:
    OS: macOS 14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 565.87 MB / 32.00 GB
  Binaries:
    Node: 20.11.0 - ~/.asdf/installs/nodejs/20.11.0/bin/node
    Yarn: 1.22.22 - ~/.asdf/installs/nodejs/20.11.0/bin/yarn
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.5
  Packages:
    sass-loader: ^16.0.0 => 16.0.0
    webpack: ^5.93.0 => 5.93.0
    webpack-cli: ^5.1.4 => 5.1.4
```

**Comment by alexander-akait** [comment]
hm, I think bug in `webpack`, maybe we don't have `data:` protocal properly, I will look deeply
