### ISSUE TITLE
option to disable escape char transformation to display char in scss

### ISSUE THREAD

**Issue by mbohovic** [webpack-contrib/sass-loader#1236]
What problem does this feature solve?
I have scss or css file in which, for example, this

.icon-calendar:before {
  content: '\e94e';
}
and sas-loader transforms it to this for me

.icon-calendar:before {
    content: "";
}

How to prevent it, I want it to stay in flood shape. The solution would be to add a setting to the configuration that would prevent this.

**Comment by alexander-akait** [comment]
please use https://sass-lang.com/documentation/js-api/interfaces/options/#charset, we can't solve it here, it is just a sass runner
