### ISSUE TITLE
resolve aliases in @import work during initial compile but error out during recompiles

### ISSUE THREAD

**Issue by jedwards1211** [webpack-contrib/sass-loader#173]
I have the following alias in my webpack config:

``` js
  resolve: {
    alias: {
      'mindfront-react-components': path.join(__dirname, '../mindfront-react-components'),
    }
  }
```

I have a sass file using this alias:

``` sass
@import mindfront-react-components/css3-mixins
```

When I start up webpack-dev-server for the first time, the sass file compiles just fine.  But if I make any changes to it, I get the following error when webpack-dev-server recompiles:

```
ERROR in ./~/css-loader!./~/sass-loader?indentedSyntax&outputStyle=expanded!./app/components/InventoryList.sass
Module build failed: 
@import mindfront-react-components/css3-mixins
       ^
      File to import not found or unreadable: mindfront-react-components/css3-mixins
      in /home/andy/jcore-portal/app/components/InventoryList.sass (line 1, column 9)
 @ ./app/components/InventoryList.sass 4:14-166 14:20-172
```

**Comment by jhnns** [comment]
Thx for reporting this.

Could you come up with a minimal test example that reproduces the error?

**Comment by jedwards1211** [comment]
Hmmm...no luck reproducing in a minimal example yet :(  I even tried duplicating how I'm using `context` and `resolve.root` in the webpack config.

**Comment by jhnns** [comment]
Just remove stuff step by step until it's working again :grin:

**Comment by jedwards1211** [comment]
There's a lot to remove :)  So I can't guarantee when I'll come up with a minimal example

**Comment by Tux1** [comment]
Same issue

**Comment by Anahkiasen** [comment]
Same issue here as well, works fine during initial compilation but as soon as I change a file and HMR kicks in, my resolve.alias get ignored

**Comment by e110c0** [comment]
it looks like a similar issue here with webpack 2:

alias: {
Styles:     path.resolve(__dirname, 'styles')
}

when I import in a sass file like this:

@import 'Styles/imports';

compile works, but the file imports is not watched.

@import '../../../styles/imports';

compile and watch works.

If found in webpack 1 configs that the import should use ~:

@import '~Styles/imports';

this also works for compile and watch. 
It looks like @import 'Styles/imports'; is not adding the files to the dependency tree for some reason.

**Comment by rudolfschmidt** [comment]
Ran into same issue.
Import of css files not working.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/sass-loader/issues/410, If somebody don't agree please create a separate issue. Thanks for helping `sass-loader` doing better :+1:
