### ISSUE TITLE
I made a thing!

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack-contrib/sass-loader#181]
Please review and let me know if there is anything you preffer that I change:

https://www.npmjs.com/package/sassport-loader
https://github.com/IngwiePhoenix/sassport-loader

Thanks!

**Comment by jedwards1211** [comment]
You know, this gives me an idea.  So this bridge of sorts between JS and Sass is cool.  But I'd have a hunch that a Webpack macro preprocessor type loader would solve a lot of the same problems -- and automatically enable one to use shared variables/functions between source files of *any type*.  Boom!

**Comment by evilebottnawi** [comment]
@IngwiePhoenix thanks for interesting project, but it is not issue, use `reddit`, `medium` or other platform for promotion this project :+1:
