### ISSUE TITLE
.. works inside npm module but not outside (bug)

### ISSUE THREAD

**Issue by SeeThruHead** [webpack-contrib/sass-loader#207]
package-name/lib/alert/index.js:

```
require('./alert.scss');
```

package-name/lib/alert/alert.scss

```
@import '../shared-scss/theme'; // theme contains some sass variables
```

this works perfectly fine when using webpack in a test environment inside package-name

but as soon as i try to use package-name inside an actual app (package-name is a ui component library)
webpack inside the app barfs up over the ".." (presumably)

How can I address this issue?
Where does the issue come from?

Thanks :smile:

**Comment by jhnns** [comment]
Please provide a small example project to demonstrate the issue. You can just commit the `node_modules` folder to simulate different packages.

**Comment by evilebottnawi** [comment]
@SeeThruHead friendly ping, problems now exists?

**Comment by evilebottnawi** [comment]
Fell free to reopen issue if your problem not solved.
