### ISSUE TITLE
Loading transient sass modules through npm

### ISSUE THREAD

**Issue by eastwood** [webpack-contrib/sass-loader#227]
Hey guys, 
Firstly, really loving the project, very easy to setup and get started. I have an interesting problem that I"m trying to solve, which involves transiently trying to resolve scss files from `node_modules`. Let's say for example we have:

```
test-project/
├── app
│   └── index.scss
└── node_modules
    ├── bar
    │   └── colors.scss
    └── foo
        └── variables.scss
```

In `index.scss` we want to do the following:

```
@import "~bar/colors"
body {
  background-color: $red;
}
```

Subsequently, `colors.scss` is importing stuff from the `variables.scss`

```
@import "foo/variables"
$red: $some_variable;
```

It's a pretty silly example, but outlines the fact that some legacy code requires the importing of other modules. When I resolve the `index.scss`, it manages to find the `colors.scss` file, but because the path of `colors.scss` is `foo/variables` and not `~foo/variables`, it cannot find the module.

Is this something, where I'd have to modify the `colors.scss` file manually, or is there some webpack configuration or node-sass configuration I can do that will be able to resolve the `@import 'foo/variables' from the node_module?

It's probably worth mentioning that I'm not doing anything special in the `webpack.config.js`. Relative to the above example it's just a basic `style!css!sass!index.scss` 

Thanks guys :)

**Comment by jameslnewell** [comment]
I think #234 would allow you to work around this issue

**Comment by jhnns** [comment]
I think it makes sense to add the `node_modules` folder to node-sass' `includePath` option. After that, this code should work.

**Comment by jcteague** [comment]
I'm having a similar problem.  I'm importing a scss file from an installed npm node module.  The imported file, in turn, has an import with coming from a node module but has the syntax `@import 'plugin'`
sass loader is choking on the secondary import statement.

**Comment by evilebottnawi** [comment]
Seems duplicate https://github.com/webpack-contrib/sass-loader/issues/466. Feel free to reopen if it is different problem. Fast solution as said jhnns https://github.com/webpack-contrib/sass-loader/issues/227#issuecomment-228594718
