### ISSUE TITLE
@import statement with memory-fs do not working

### ISSUE THREAD

**Issue by mikeifomin** [webpack-contrib/sass-loader#249]
This issue is from https://github.com/christianalfoni/webpack-bin/issues/144

And it happened because node-sass `importer` function return `file` instead of `contents` paramter.
[direct link to source](https://github.com/jtangelder/sass-loader/blob/v3.2.0/index.js#L182)

---

memory-fs use patch filesystem [link](https://github.com/webpack/webpack/issues/1562#issuecomment-165506401)

``` coffee
  webpackCompiler.inputFileSystem = fsIn
  webpackCompiler.outputFileSystem = fsOut
  webpackCompiler.resolvers.normal.fileSystem = webpackCompiler.inputFileSystem;
  webpackCompiler.resolvers.context.fileSystem = webpackCompiler.inputFileSystem;
```

**Comment by jhnns** [comment]
We are returning `file` instead of `contents` because of current source map file paths if I remember correctly. I'm not sure we can change that so easily.

**Comment by evilebottnawi** [comment]
@mikeifomin is problem actual?

**Comment by mikeifomin** [comment]
@evilebottnawi I solved this with some magic. I do not remember how. Sorry
