### ISSUE TITLE
Webpack packaging More than one bracket @font-face

### ISSUE THREAD

**Issue by chengzhuotc** [webpack-contrib/sass-loader#265]
![image](https://cloud.githubusercontent.com/assets/9107399/17507485/653f9c68-5e42-11e6-97c5-ebb446c27978.png)

**Comment by chengzhuotc** [comment]
![image](https://cloud.githubusercontent.com/assets/9107399/17507579/fc854c1c-5e42-11e6-8b59-a6bbaf5562a5.png)

**Comment by francesco-carrella** [comment]
same problem here

**Comment by SergeyKorchevskiy** [comment]
Same problem here. 
Any good news?

**Comment by SergeyKorchevskiy** [comment]
I was having same problem and here's solution.
https://github.com/webpack/css-loader/issues/233#issuecomment-247042470

**Comment by evilebottnawi** [comment]
Yep, not related to `sass-loader`. Original issue https://github.com/webpack-contrib/css-loader/issues/233. If you still have error, please create minimal reproducible test repo and send comment in https://github.com/webpack-contrib/css-loader/issues/233.
