### ISSUE TITLE
webpack-dev-server not watching changes in my imports

### ISSUE THREAD

**Issue by Velds** [webpack-contrib/sass-loader#266]
Exactly as set by #130, but a year later.
- Webpack recompiles on main.scss changes
- main.scss imports _header.scss
- Webpack doesn't recompile on _header.scss changes

**Comment by tvanro** [comment]
Same issue here.
Using webpack `1.13.3` and sass-loader `4.0.2`

**Comment by jhnns** [comment]
Please provide a **minimal** test that demonstrates the problem. I'm using the webpack-dev-server in my setup and everything is working as expected.

**Comment by claudio4** [comment]
Same here,
There is a demostartion https://cloud.byte-time.com/s/pIjPxewHdbf7HxL.

**Comment by evilebottnawi** [comment]
Please update `webpack` to `v2` and `sass-loader` to latest version.

Closing this out, please feel free to reopen if this doesn't resolve your issue. Thanks!
