### ISSUE TITLE
[Bug] Font face with primeng and url-resolve-loader broken

### ISSUE THREAD

**Issue by luchillo17** [webpack-contrib/sass-loader#273]
This is my scss:

``` scss
@import '~primeui/themes/omega/theme';
// @import '~primeui/primeui-ng-all.min';
```

Here's my loader config:

``` js
      /**
      * Scss loader support for *.scss files.
      *
      * See: https://github.com/jtangelder/sass-loader
      */
      {
        test: /\.scss$/,
        loaders: [
          // ExtractTextPlugin.extract("style", "css?sourceMap"),
          'to-string-loader',
          'css-loader',
          'resolve-url-loader',
          'sass-loader' +
          '?sourceMap&' +
          'outputStyle=expanded&' +
          'root=' + helpers.root('src') + '&' +
          '&includePaths[]' + helpers.root('node_modules') + '&' +
          '&includePaths[]' + helpers.root('src')
        ]
      }
```

And here's my terminal output:
![image](https://cloud.githubusercontent.com/assets/9698639/18028752/f27473d0-6c4b-11e6-94d8-03c30fee55bd.png)

**Comment by evilebottnawi** [comment]
@luchillo17 Thanks for using `webpack` and `sass-loader`!
Some things:
1. Don't use `'&includePaths[]' + helpers.root('node_modules')` and `@import '~primeui/themes/omega/theme';` after using `~` `webpack/sass-loader` already known `primeui` package locate in `resolve.modules` directories (for webpack 2) and `resolve.modulesDirectories` (for webpack 1).
2. Also `to-string-loader` do not support `webpack 2` (We strongly recommend to update to `webpack` 2).
3. Please update to latest `sass-loader` version.
4. In provided screenshot seems bug not `sass-loader`, inside in `to-string-loader`.
5. Also maybe your don't have `file-loader`.

Not active more 90 days. Closing this out, please feel free to reopen if this doesn't resolve your issue. Thanks!

**Comment by luchillo17** [comment]
Hehe sorry about this issue, it's very old, i end up fixing my issue one way or another, i just didn't remember i put this issue, after all has been like half a year since i put it.

Anyway thanks for taking your time.
