### ISSUE TITLE
travis ci support

### ISSUE THREAD

**Issue by lorenzomigliorero** [webpack-contrib/sass-loader#284]
Hi,
i recently notice that the build with Travis CI fail with this error:

`Cannot find module "./scss/main.scss"`

This is my webpack config:

`{
        test: /\.scss$/,
        loader: 'style!css?sourceMap!postcss!sass?sourceMap'
},`

This is very strange, locally build works perfect...
I think that is a problem with sass-loader and Travis CI Platform.
Do you have any information about this?

Thanks
L.

**Comment by jensvdh** [comment]
Hi,

Our team is also using TravisCI. We're not seeing any issues with it. Are you running Travis in container mode? (sudo: false option).

Here's the configuration for the loader on our end. We are using node version 5.8.0

`test: /\.scss$/, loader: ExtractTextPlugin.extract('style', 'css?sourceMap!sass?sourceMap')`

**Comment by evilebottnawi** [comment]
@lorenzomigliorero Is there a problem or has it been solved?

**Comment by lorenzomigliorero** [comment]
Sorry for the delay @evilebottnawi.
I just forgot to add sass-loader in package.json... 

Thanks for your answer.
