### ISSUE TITLE
webpack 2.1.0-beta23+ breaks webpack.config.options

### ISSUE THREAD

**Issue by gpazo** [webpack-contrib/sass-loader#289]
Original webpack issue: https://github.com/webpack/webpack/issues/3018

Fix documentation to change:

```
module.exports = {
  ...
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loaders: ["style", "css", "sass"]
      }
    ]
  },
  sassLoader: {
    includePaths: [path.resolve(__dirname, "./some-folder")]
  }
};
```

to: 

```
module.exports = {
  ...
  module: {
    plugins: [
      new webpack.LoaderOptionsPlugin({
        options: {
          sassLoader: {
             includePaths: [path.resolve(__dirname, "./some-folder")]
        }
     })
    ],
    loaders: [
      {
        test: /\.scss$/,
        loaders: ["style", "css", "sass"]
      }
    ]
  }
};

```

**Comment by tleunen** [comment]
The sass loader should be updated to the new way of passing options instead of using the `LoaderOptionsPlugin`.

**Comment by Luchillo** [comment]
@tleunen So in the mean time we need to stick with webpack beta.22?

**Comment by tleunen** [comment]
No not really.. there's a fix explained here for the context: https://github.com/webpack/webpack/issues/3018#issuecomment-248445176

**Comment by Luchillo** [comment]
Yeah i saw that, however in my case it didn't work.

**Comment by leaves4j** [comment]
@gpazo TypeError: webpack.LoaderOptionsPlugin is not a constructor
I got this error

**Comment by cmckni3** [comment]
I switched to using the module.rules `use` syntax.

```
{
  test: /\.scss$/,
  use: [
    'style-loader',
    'css-loader',
    {
      loader: 'sass-loader',
      query: {
        includePaths: [path.resolve(__dirname, "./some-folder")]
      }
    }
  ]
}
```

**Comment by evilebottnawi** [comment]
@gpazo @tleunen @luchillo17 @leaves4j please update to latest `webpack` version :+1: 

Closing this out, please feel free to reopen if this doesn't resolve your issue. Thanks!

**Comment by pretentiousgit** [comment]
This is still a bug in webpack-cli with webpack 2.5.1, fresh install of everything.

**Comment by luchillo17** [comment]
@pretentiousgit Seems only with cli, i don't get this issue any more with latest webpack.
