### ISSUE TITLE
Accessing `addNormalizedDependency` from within a custom importer

### ISSUE THREAD

**Issue by jameslnewell** [webpack-contrib/sass-loader#303]
I'm using a custom importer and the [WatchMissingNodeModulesPlugin](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/WatchMissingNodeModulesPlugin.js) plugin. With this plugin Webpack recompiles immediately after I install any missing packages imported from the JS, but not when I install missing packages imported from SCSS files.

I think it's due to `node-sass` throwing an error so that `addNormalizedDependency` is never getting called with the included files (as decsribed [here](https://github.com/jtangelder/sass-loader/blob/master/index.js#L135)).

Can you think of a nice way to provide the `addNormalizedDependency` function to a custom importer?

**Comment by evilebottnawi** [comment]
@jameslnewell can you provide minimal reproducible test repo?

**Comment by jameslnewell** [comment]
Not without breaking the current signature 😌. As per my comments on another issue, I'm no longer actively using sass on any projects so you're welcome to close if no one else wants this.

**Comment by evilebottnawi** [comment]
Closing this out, please feel free to reopen or create new issue if this doesn't resolve your issue. Thanks!
