### ISSUE TITLE
Export instance of compiler

### ISSUE THREAD

**Issue by niksy** [webpack-contrib/sass-loader#311]
Is it possible to export instance of node-sass used by sass-loader so it can be used for advanced use cases? Something along the lines of https://github.com/dlmanning/gulp-sass/blob/master/index.js#L184-L189

Use case: you want to write simple [importer function](https://github.com/sass/node-sass#importer--v200---experimental) and in cases where you don’t want to handle particular import, you should return `sass.NULL`, where `sass` is instance of node-sass.

**Comment by jhnns** [comment]
Yeah, that makes sense. I didn't realize that you need the `sass` instance to access to their types. Would you be open to do a PR? Please also write a small test and a note in the README for that.

**Comment by niksy** [comment]
If you use `null`, from recent versions of node-sass it actually doesn’t need it, but if you’re using Sass types like numbers of strings as return values, you need those Sass types.

I’ve made a PR for this.

**Comment by jhnns** [comment]
Wait ... is this change really necessary? Why couldn't you just require `node-sass` in your project? It's a peer dependency and should return the exact same object.

**Comment by niksy** [comment]
Hmmm, I guess you’re right. I guess I thought node-sass is dependancy.

**Comment by evilebottnawi** [comment]
@niksy Is there a problem or has it been solved?

**Comment by niksy** [comment]
@evilebottnawi I think this can be closed, requiring `node-sass` in project is sufficient I suppose.
