### ISSUE TITLE
Forces webpack rebuild when stylesheet errors

### ISSUE THREAD

**Issue by deiga** [webpack-contrib/sass-loader#312]
I'm running `webpack --watch` and everything get s rebuilt nicely when changes occur, except for when I make a typo in my SCSS files then it throws a huge `Module build failed` stacktrace and after fixing it rebuilds my whole webpack build.

This is a bit awkward as errors happen frequently and the build can take up to 1 minute, without the watch process saying anything

**Comment by jhnns** [comment]
I assume that this is somehow related to your setup. When using `--watch`, webpack will only rebuild the files that had an error. Can you try to provide a minimal example repository that demonstrates the problem?

Please note that we can only recompile starting from the *entry SASS file*. So, if you have one monolithic SASS file with a lot of imports, we need to rebuild that one – even when the syntax error was just in a little file that was imported. Unfortunately, that's the way how the SASS language was designed.

**Comment by deiga** [comment]
Ah, yes. My problem seems to be the monolithic entry. Is there any point in splitting one entry into multiple files or should I try and actually build multiple entries?

**Comment by evilebottnawi** [comment]
@deiga thanks for using `webpack` and `sass-loader`, but it is not issue, it is question, we don't have time to respond on all question here :sob: , please use `stackoverflow` for this, also you can read http://eng.localytics.com/faster-sass-builds-with-webpack/ about speedup build, also your can see on new loader https://github.com/webpack-contrib/cache-loader.

Closing this out, please feel free to reopen if this doesn't resolve your issue. Thanks!
