### ISSUE TITLE
webpack@beta dependency

### ISSUE THREAD

**Issue by markbrown4** [webpack-contrib/sass-loader#326]
Is there a version of sass-loader that works with the new webpack release?

https://medium.com/webpack/webpack-2-2-the-release-candidate-2e614d05d75f

```bash
npm init -y
npm install webpack@beta node-sass sass-loader --save-dev
```

> UNMET PEER DEPENDENCY webpack@2.2.0-rc.1

Installing `webpack@2.1.0-beta.28` was the latest compatible release that I could see.

**Comment by evilebottnawi** [comment]
@markbrown4 can we close this issue? We have stable version `webpack@2` :+1: and `sass-loader` now support only `webpack@2` version https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L36

**Comment by michael-ciniawsky** [comment]
@markbrown4 Feel free to reopen if still any problems
