### ISSUE TITLE
Custom extension for CSS modules

### ISSUE THREAD

**Issue by borela** [webpack-contrib/sass-loader#339]
In my project I used the `.mscss` extension to identify a css module vs normal css in webpack. Would you consider adding support for extension aliases? I could send a PR and I believe the change would be minimal.

The main idea is that this loader would map an alias to one of the extensions supported already like `mscss => scss` or `msass => sass`.

Another (better) option would be to read the extensions from webpack settings.

**Comment by evilebottnawi** [comment]
@borela why just don't use `test: /\.(mscss|scss)$/` and `test: /\.(msass|sass)$/,`?

**Comment by borela** [comment]
I do on webpack but when I use the `@import './someDir/someFile` command from sass with relative paths, it doesn't use webpack's resolver so I can't omit the extension. Is there any setting to allow this?

**Comment by evilebottnawi** [comment]
@borela what about add this extension to `resolve.extensions` webpack option?

**Comment by evilebottnawi** [comment]
@borela If it does not help, just create minimal test repo and describer in readme what logic your can want. it is allow to helping :smile:

**Comment by borela** [comment]
Yeah, I'been using this [config](https://github.com/ctrine/webpack-settings/blob/master/src/main.js) and at the time of this issue, it wasn't adding the extensions from webpack's config but I see that there changes made to the repo.

 I'll check if the error still exists :D.

**Comment by borela** [comment]
[The current behaviour is actually a bug as mentioned here](https://github.com/webpack-contrib/sass-loader/issues/466).
