### ISSUE TITLE
Why do you prepend with exclamation mark?

### ISSUE THREAD

**Issue by wzup** [webpack-contrib/sass-loader#343]
Look at `css-loader`:

![webpack_css-loader_ css loader module for webpack - google chrome 2017-01-05 23 01 00](https://cloud.githubusercontent.com/assets/3880497/21685098/36855e3e-d39b-11e6-8d21-d7912fffb017.png)

Look at Webpack docs on loaders:

![loaders - google chrome 2017-01-05 23 01 43](https://cloud.githubusercontent.com/assets/3880497/21685124/4cc39daa-d39b-11e6-99f8-55c65576f9e2.png)

Look at your docs now. Why do you prepend everything with `!` exclamation mark?

![jtangelder_sass-loader_ sass loader for webpack - google chrome 2017-01-05 23 02 32](https://cloud.githubusercontent.com/assets/3880497/21685143/5cd4d574-d39b-11e6-82f0-c11338588149.png)

**Comment by jhnns** [comment]
By prepending the string with exclamation mark, you can disable the loaders configured in the webpack.config.js.

However, it is recommended to use the `webpack.config.js` anyway. The inline syntax should only be used in certain exceptions. That's why I removed it from the README.

**Comment by zindel** [comment]
What is the difference between one and two exclamation marks in the beginning?

**Comment by smac89** [comment]
@zindel https://stackoverflow.com/a/35820113/2089675

**Comment by heruiwoniou** [comment]
Hi, @smac89 
The document you provided is very old, the official document does  not mention this use at present.

**Comment by Izhaki** [comment]
`!` vs `!!` vs `-!`:

https://webpack.js.org/concepts/loaders/#inline
