### ISSUE TITLE
Using in webpack to load sass in node_modules

### ISSUE THREAD

**Issue by golinmarq** [webpack-contrib/sass-loader#346]
In documentation says:

> Thus you can import your Sass modules from node_modules. Just prepend them with a ~ to tell webpack that this is not a relative import

So, I'm using React Toolbox for my components and they recommend to add this loader. I added to my webpack.development.config but when I run this, the styles are not loaded. 

My web pack.development.config code is:
```
...
loaders: [
      {
        test: /\.global\.css$/,
        loaders: [
          'style-loader',
          'css-loader?sourceMap'
        ]
      },

      {
        test: /^((?!\.global).)*\.css$/,
        loaders: [
          'style-loader',
          'css-loader?modules&sourceMap&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]'
        ]
      },

      {
        test: /\.scss$/,
        loaders: ["style-loader", "css-loader", "sass-loader"]
      }, 
...
```

**Comment by modosc** [comment]
i'm seeing this too with `"node-sass": "^4.4.0"` (and `4.5.0` as of today, just tested) - when i switch back to `node-sass@^3.13.1` it works again. i've also tried setting `includeDirectories` in my `sass-loader` query per comments [here](https://github.com/sass/node-sass/issues/1876) but it didn't help.

**Comment by jhnns** [comment]
Sorry, there is not enough information to reproduce this. Please provide a minimal test repository that demonstrates the problem so I can check that out. Try to remove as much stuff as possible since it helps tracking down the problem.

**Comment by evilebottnawi** [comment]
@modosc for `import` from `modules` please read https://github.com/webpack-contrib/sass-loader#imports

More 90 days inactive (no provided test repo :disappointed: ). Closing this out, please feel free to reopen if this doesn't resolve your issue. Thanks!
