### ISSUE TITLE
Failed to Compile with no error detail.

### ISSUE THREAD

**Issue by gkhno** [webpack-contrib/sass-loader#353]
I have a webpack configuration. I ejected create-react-app and added sass-loader like this:

      {
        test: /\.(scss|sass)$/,
        loader: 'style!css?sourceMap!postcss!sass?sourceMap'
      },

it just works fine. but when there is an syntax error on the scss file, I get this error. Can't get the error details:

    Failed to compile.

    Error in ./src/components/HomeLink/style.scss
    Module build failed: 
     @ ./src/components/HomeLink/style.scss 4:14-196 13:2-17:4 14:20-202

can't get to print error details.

this is the chrome console error details:

    style.scss:4Uncaught Error: Cannot find module "!!./../../../node_modules/css-loader/index.js?sourceMap!./../../../node_modules/postcss-loader/index.js!./../../../node_modules/sass-loader/index.js?sourceMap!./style.scss"
        at webpackMissingModule (style.scss:4)
        at Object.<anonymous> (style.scss:4)
        at __webpack_require__ (bootstrap ace66ed…:555)
        at fn (bootstrap ace66ed…:86)
        at Object.<anonymous> (index.js:5)
        at Object.<anonymous> (index.js:23)
        at Object.<anonymous> (index.js:23)
        at __webpack_require__ (bootstrap ace66ed…:555)
        at fn (bootstrap ace66ed…:86)
        at Object.<anonymous> (index.js:4)
    webpackMissingModule @ style.scss:4
    (anonymous) @ style.scss:4
    __webpack_require__ @ bootstrap ace66ed…:555
    fn @ bootstrap ace66ed…:86
    (anonymous) @ index.js:5
    (anonymous) @ index.js:23
    (anonymous) @ index.js:23
    __webpack_require__ @ bootstrap ace66ed…:555
    fn @ bootstrap ace66ed…:86
    (anonymous) @ index.js:4
    (anonymous) @ index.js:23
    (anonymous) @ index.js:23
    __webpack_require__ @ bootstrap ace66ed…:555
    fn @ bootstrap ace66ed…:86
    (anonymous) @ index.js:5
    (anonymous) @ index.js:15
    (anonymous) @ index.js:15
    __webpack_require__ @ bootstrap ace66ed…:555
    fn @ bootstrap ace66ed…:86
    (anonymous) @ index.js:7
    (anonymous) @ index.js:16
    (anonymous) @ index.js:16
    __webpack_require__ @ bootstrap ace66ed…:555
    fn @ bootstrap ace66ed…:86
    (anonymous) @ bootstrap ace66ed…:578
    __webpack_require__ @ bootstrap ace66ed…:555
    (anonymous) @ bootstrap ace66ed…:578
    (anonymous) @ bootstrap ace66ed…:578
    webpackHotDevClient.js:231 Error in ./src/components/HomeLink/style.scss
    Module build failed: 
     @ ./src/components/HomeLink/style.scss 4:14-196 13:2-17:4 14:20-202
    handleErrors @ webpackHotDevClient.js:231
    connection.onmessage @ webpackHotDevClient.js:258
    EventTarget.dispatchEvent @ eventtarget.js:49
    (anonymous) @ main.js:274
    SockJS._transportMessage @ main.js:272
    EventEmitter.emit @ emitter.js:44
    WebSocketTransport.ws.onmessage @ websocket.js:35

**Comment by evilebottnawi** [comment]
@gkhno Is there a problem or has it been solved? If problem not solved please create minimal reproducible test repo, thanks!

**Comment by evilebottnawi** [comment]
Fell free to reopen issue if your problem not solved.
