### ISSUE TITLE
Have an examples directory

### ISSUE THREAD

**Issue by kahwee** [webpack-contrib/sass-loader#358]
What do you think of having an examples directory to show some sample configurations for webpack 2?

I have a few that I can contribute if you're interested.

**Comment by jhnns** [comment]
That would be awesome. Could you create a PR? 👍 

Just create a directory called `examples` (thus it will be ignored by npm as configured in the `.npmignore`). Please also setup eslint for the examples directory.

**Comment by borela** [comment]
@kahwee https://github.com/ctrine/webpack-settings/blob/master/packages/shared/src/rules/sass-module.js

**Comment by arsduo** [comment]
This would be a huge help. I've spent an hour trying to figure out why it's not working for me despite using the code directly from the readme, so far with no luck. Having complete, runnable examples to compare against would be great.

**Comment by evilebottnawi** [comment]
Feel free to send PRs with example in `README.md` (example) section. Close due inactivity.
