### ISSUE TITLE
Ignore external resources

### ISSUE THREAD

**Issue by ramakrishnamundru** [webpack-contrib/sass-loader#359]
when I tried to import google fonts with sass an error is thrown,

```
Module build failed: Unexpected formathttps://fonts.googleapis.com/css?family=Hind:600,400 (2:0)
  1 | 
> 2 | @charset "UTF-8";
  3 | @import https://fonts.googleapis.com/css?family=Hind:600,400;
  4 | /*!
  5 |  * Bootstrap v3.3.7 (http://getbootstrap.com)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-6ab636a8!./~/sass-loader?indentedSyntax!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-263 13:2-17:4 14:20-269

```
 But when I use @import in a normal css file I dont get that error from webpack, so can you allow the loader to ignore imports from external resources.

**Comment by evilebottnawi** [comment]
@ramakrishnamundru thanks for issue, but `sass-loader` don't handle external resources, seems bug was https://github.com/webpack-contrib/css-loader/blob/master/lib/processCss.js#L51. Is there a problem or has it been solved? If not please create minimal reproducible test repo

**Comment by ramakrishnamundru** [comment]
I have solved the problem by using the url() syntax to import external resources.
so now I use
```
@import url('https://fonts.googleapis.com/css?family=Hind:600,400');
```
And I didn't face this problem again.
Thanks
