### ISSUE TITLE
Error to compile .sass syntax

### ISSUE THREAD

**Issue by brunoravanhani** [webpack-contrib/sass-loader#361]
When i add bulma framework with .sass syntax have this error:

`Media query expression must begin with '('`

 Without this, works fine.

My loader: 
```
{
        test: [/\.[s]css$/, /\.sass$/],
        loader: ExtractTextPlugin.extract({
                loader: ["css-loader", "sass-loader"]
        })
}
```

Any suggestions?

**Comment by thibmaek** [comment]
Seeing the same issue over here

**Comment by jhnns** [comment]
The file must have the `sass` extension if it's written in sass syntax. Try to narrow down the exact file, that is causing the issue and try to compile it with `node-sass`. Does it work with `node-sass`?

**Comment by emericmourot** [comment]
Did you try to compile your file in sass syntax with ?indentedSyntax parameter set ?
`loader: ["css-loader", "sass-loader?indentedSyntax"]`

**Comment by jhnns** [comment]
You don't need to set the option explicitly anymore. The sass-loader derives it automatically for files ending on `.sass`

**Comment by evilebottnawi** [comment]
@brunoravanhani seems your have wrong `sass` syntax, can your provide `sass` example file?

**Comment by brunoravanhani** [comment]
The code was in a framework called [bulma](http://bulma.io/), but i changed my framework in that project.

**Comment by evilebottnawi** [comment]
@brunoravanhani As I understand the problem is no more? Can we close this issue?

**Comment by brunoravanhani** [comment]
Yes, can close.
