### ISSUE TITLE
Resolve index.scss file "main", "style" fields in package.json automatically

### ISSUE THREAD

**Issue by vanesyan** [webpack-contrib/sass-loader#382]
Hello there! I have some issue (or feature) while working with sass-loader, i'd like sass-loader to automatically resolve imports to `index.scss` or fields define in `package.json` (`main` or `style`) if filename is omitted i.e.
```scss
// Assume we have it in our node_modules dirname
@import "@barebone/var-z-index"; // => path/to/node_modules/@barebone/var-z-index/index.scss
```

**Comment by jhnns** [comment]
If you prepend `~` to the import statement, it will use webpack's usual module resolving engine: `@import "~@barebone/var-z-index"`

**Comment by vanesyan** [comment]
A bit late, but your solution doesn't work. Webpack still throw `File to import not found or unreadable: ...` error, when importing in the way of `@import "~@barebone/var-z-index"`, while `style` and `main` (tried both and separately) fields in `package.json` are set to existing `index.scss` file path. But when I import it like this `@import "~@barebone/var-z-index/index.scss"`, it works.

**Comment by vanesyan** [comment]
I found similar problem in #293
