### ISSUE TITLE
AoT support, build failed

### ISSUE THREAD

**Issue by vincent-cm** [webpack-contrib/sass-loader#390]
running Angular2 project on Webpack starter project, has to roll back to 4.1.1 to build as AoT.

ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js!./config/resource-override.js
Module build failed: No input specified: provide a file name or a source string to process
 @ ./src/app/components/core/custom.scss 2:21-134
 @ ./src/app/components/core/core.ts
 @ ./compiled/src/app/app.module.ngfactory.ts
 @ ./src/main.browser.aot.ts

**Comment by MangeshPimpalkar** [comment]
This is related to https://github.com/webpack-contrib/sass-loader/issues/373

**Comment by jhnns** [comment]
Please provide more context. What is AoT? Do you have a code example that demonstrates the error?

**Comment by d3viant0ne** [comment]
@jhnns - AOT is Angular's Ahead of Time compilation

See: https://angular.io/docs/ts/latest/cookbook/aot-compiler.html if you are curious

**Comment by d3viant0ne** [comment]
And IMO, this should be closed in favor of #373 which actually provides error context of value. AOT will fail as soon as it can't resolve something, an undefined path would certainly do it.

**Comment by jhnns** [comment]
This has been addressed with #398 and shipped with `6.0.3`.
