### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by IFmiss** [webpack-contrib/sass-loader#391]
var htmlWebpackPlugin = require('html-webpack-plugin');
var path = require ('path');
var webpack = require('webpack');

module.exports = {
	context: __dirname,
	entry:'./src/app.js',
	output:{
		path:'./dist',
		filename:'js/[name].bundle.js',
	},

	module:{
		loaders:[{
					test:/\.js$/,
					loader:'babel-loader',
					exclude:path.resolve(__dirname,'node_modules'),
					include:path.resolve(__dirname,'src'),
					query:{
						presets:['latest'],
					},
				},

				{
					test:/\.css$/,
					loader:'style-loader!css-loader?importLoaders=1!postcss-loader',
				},{
					test:/\.sass$/,
					loader:'style-loader!css-loader!sass-loader',
				},]
	},

	plugins:[
		new htmlWebpackPlugin({
			filename:'index.html',
			template:'index.html',
			inject:'body',
			title:'aaaaaaaaaa',
		}),

		new webpack.LoaderOptionsPlugin({
			options:{
				postcss:[
			      require('autoprefixer')({

			      })
			    ],

			}
		}),
	]
}

an error : You may need an appropriate loader to handle this file type.

**Comment by jhnns** [comment]
Looks like you're trying to import a `scss` file but you've only configured the sass-loader for `sass` files. That's the only thing I can spot with the given information.

---

Things you should consider in the future before opening an issue:

- Please format your issue with code blocks ```
- Omit stuff that is probably not relevant
- Don't omit stuff that could be helpful: Error message + stack trace for instance

If you want to help us to find the problem: Provide a small test repository that demonstrates the bug.

In case, you're not sure whether it's a bug or whether there's something wrong with your configuration, ask a [question on StackOverflow an tag them with `webpack`](http://stackoverflow.com/questions/tagged/webpack) or go to the [webpack gitter channel](https://github.com/webpack-contrib/sass-loader/issues/391).

Thank you :)
