### ISSUE TITLE
Build fails with empty SCSS files

### ISSUE THREAD

**Issue by kryops** [webpack-contrib/sass-loader#403]
When I import a .scss file that is empty, the build fails with the following error:

```
ERROR in ./styles-empty.scss
Module build failed: No input specified: provide a file name or a source string to process
 @ ./main.js 2:0-28
```

Environment:

* Windows 10
* Node.js 6.10.0
* Webpack 2.2.1
* sass-loader 6.0.2 with css-loader 0.26.2

I haven't been able to test in other environments yet.

Minimal reproduction: https://github.com/kryops/sass-loader-empty-file-error

Known workarounds:

* Downgrade to sass-loader 4.1.1
* Add content to the empty file

Related issues:

* #390 
* https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/422
* https://github.com/AngularClass/angular2-webpack-starter/issues/1555

Related StackOverflow question:

* http://stackoverflow.com/questions/42151205/webpack-extracttextplugin-extract-module-build-failed-no-input-specified-p

**Comment by jhnns** [comment]
Thx for creating a detailed report. This has been addressed with #398 and shipped with `6.0.3`.
