### ISSUE TITLE
Can't use @mixins

### ISSUE THREAD

**Issue by wsfuller** [webpack-contrib/sass-loader#414]
Having another issue with this loader pertaining to Mixins. For years have just done something like: 

    @mixin [breakpoint]{
        @media only screen and (min-width: [breakpoint]){
            @content;
        }
    }

But now I'm getting errors trying to do Mixins

**error** 

    ERROR in ./src/index.scss
    Module build failed: ModuleBuildError: Module build failed: Undefined mixin break-xs (3:1)

    1 | @import "../settings/breakpoints.scss";
    2 |
    > 3 | @mixin break-xs {
    ...

---

**index.jsx**

    require('./index.scss');

---

**index.scss**
  
    @import "assets/stylesheets/settings/breakpoints.scss";
    @import "assets/stylesheets/tools/media-queries";

---

**media-queries.scss**

    @mixin break-xs {
      @media only screen and (min-width: $screen-xs) {
        @content;
      }
    }

I've also added `import "../settings/breakpoints.scss";` to the top of the file because I was reading in places that you may have to import resources since Webpack silos global variables with my other declarations so jury still out on that.

---

**webpack.config**

    ...
    {
      test: /\.(s?)css$/,
      use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader', 'resolve-url-loader', 'postcss-loader']
      })
    },
    ...
    new ExtractTextPlugin({
      filename: 'app.css',
      disable: false,
      allChunks: true
    }),
    ...

* Webpack 2.2.1
* node-sass 4.5.0
* sass-loader 6.0.2
* style-loader 0.13.2
* postcss-loader 1.3.5
* extract-text-webpack-plugin 2.0.2

**Comment by wsfuller** [comment]
Looks like the loaders are in the incorrect order. Have updated to `use: ['css-loader','resolve-url-loader','postcss-loader','sass-loader']`. The one question I have remaining, where in the documentation does it state the ordering of loaders and the correct way to write them? 

Feel like [Loader Features](https://webpack.js.org/concepts/loaders/#loader-features) would be a logical place with the current setup. 

> Loaders can be chained. They are applied in a pipeline to the resource. A chain of loaders are compiled chronologically. The first loader in a chain of loaders returns a value to the next. At the end loader, webpack expects JavaScript to be returned.

Wondering if there should be a mention in here about this

**Comment by evilebottnawi** [comment]
@wsfuller Not entirely true, with this logic we must put this information in each `loader`, it is overloading docs, more right place information about this in https://webpack.js.org/concepts/loaders/#loader-features (where you indicated). Btw thanks for using `webpack` :1st_place_medal:

**Comment by wsfuller** [comment]
@evilebottnawi This is still pretty confusing. If I'm coming from Gulp (which I did and to Gulp from Grunt), I'm going to write left to right or top down expecting that order, like any Western speaking person would do. If I do that with Webpack an error will occur. If written right to left order operations work as expected. This is why I was suggesting some type of mention in there. 

http://stackoverflow.com/questions/32234329/what-is-the-loader-order-for-webpack

I don't think it's overloading docs I think it's making them more obtainable and lowers the learning curve a lot. Making more verbose docs (with clear examples) can alleviate a lot of simply questions and  understanding of concepts.

**Comment by evilebottnawi** [comment]
@wsfuller Then you should create `migration-from-gulp-and-grunt` and move this docs in `webpack-docs` not here

**Comment by wsfuller** [comment]
I'm going to put together some documentation so there's a more 1:1 comparison make things a bit easier.

**Comment by evilebottnawi** [comment]
@wsfuller your can do PR and if docs will be good we can merge this :+1:

**Comment by alequiscaruso** [comment]
Hi! I wonder how we can achieve this with Webpack 5.

I'm trying to build css files from scss like: resources/scss/button.scss to src/components/button.css which should be pretty straight forward but because in buttons.scss I have @include rules I can't find a way to do that. I d expect webpack to resolve the @includes (resources/scss/mixins). 

Sorry if I'm asking in the wrong place but this thread seems to be the closest working solution (at least for wp2).  Thank you so much!
