### ISSUE TITLE
Bad substitution if using color keywords as map keys

### ISSUE THREAD

**Issue by maffelbaffel** [webpack-contrib/sass-loader#416]
If you use color keywords, such as `white` oder `black`, and use them to build classes _dynamically_, sass-loader substitutes them with **color hashes**. 
This only happens when using webpack with `-p`.

````
$testMap: (
    white: (color: white)
);

@each $key in map-keys($testMap) {
    .test-btn-#{$key} {
        $colors: map_get($testMap, $key);

        color: map-get($colors, color);
    }
}
````

actual result:
````
.test-btn-#fff{
    color:#fff
}
````

expected result:
````
.test-btn-white {
    color: white; // or #fff because of -p
}
````

Versions: 
````
    ...
    "node-sass": "^4.5.1",
    "sass-loader": "^6.0.3",
    ...
````

Using single curly quote fixes it, thought. 
````
$testMap: (
    'white': (color: white)
);
````
Not sure if this is an actual issue or intended as it is, because sass documentation says: 

> Both the keys and values in maps can be any SassScript object.

**Comment by jeffijoe** [comment]
Libraries like [Bulma](http://bulma.io) rely heavily on this.

**Comment by evilebottnawi** [comment]
@maffelbaffel About `-p` 
```shell
  -p           shortcut for --optimize-minimize --define
               process.env.NODE_ENV="production"                       [boolean]
```
Seems your have `css-loader` and other `postcss-plugin` for minification css (`-p` enable their) and one of them does not work correctly. Can you provide minimal reproducible test repo?

**Comment by maffelbaffel** [comment]
Sry for the late response, I've set up a small repo which shows the issue.
https://github.com/maffelbaffel/sass-substitution

Note:
I tried using `raw-loader` and `css-loader`, both with the same result:
````
     use: [
                {
                    loader: "raw-loader"
                }, {
                // {
                //     loader: "css-loader"
                // }, {
                    loader: "sass-loader"
                }
            ]
````

Results in `bin/styles.bundle.js`:
````
...
t.exports = ".test-btn-#fff{color:white}\n"
...
````

Again, this only happens with `webpack -p`.

**Comment by evilebottnawi** [comment]
Using only `--optimize-minimize` сauses this problem, I investigate this

**Comment by evilebottnawi** [comment]
Problem in `node-sass/libsass`, just try to setup `outputStyle` to `compressed`.

https://gist.github.com/evilebottnawi/c56515c6b4ef5238a714afaba9d626c7

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/sass-loader/blob/master/lib/normalizeOptions.js#L27-L29

Maybe ditch `loaderContext.minimize`

**Comment by evilebottnawi** [comment]
@michael-ciniawsky I also think so, but the problem should be reported in any case

**Comment by evilebottnawi** [comment]
@michael-ciniawsky One good question:
`minimize` === `compressed` or not

**Comment by michael-ciniawsky** [comment]
Does `compress` anything special in terms of SASS 'minification'?  I wonder why this is actually needed at all,  since `minimize`  in `css-loader` will minify the CSS anyways :)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky 
> :compact

> Compact style takes up less space than Nested or Expanded. It also draws the focus more to the selectors than to their properties. Each CSS rule takes up only one line, with every property defined on that line. Nested rules are placed next to each other with no newline, while separate groups of rules have newlines between them. For example:

**Comment by evilebottnawi** [comment]
@michael-ciniawsky seems yes

**Comment by michael-ciniawsky** [comment]
😆 I wanted to post excatly this link rigth now :). Hmm... doesn't `cssnano` (`css-loader`) handle colors aswell (not sure) ?

**Comment by evilebottnawi** [comment]
@michael-ciniawsky yep, `cssnano` handle colors, but maybe some people don't use `cssnano` and use only `compressed` style

**Comment by michael-ciniawsky** [comment]
If `webpack -p || webpack --optimize-minimize` is used css-loader's `loaderContext.minimize` will run `cssnano` :), `sass-loader` can't be used standalone atm. If folks want to use `compressed` mode, set `options.outputStyle` explicitly ?

**Comment by evilebottnawi** [comment]
@michael-ciniawsky yep, they can setup `outputStyle` directly using loader `options`.

**Comment by xzyfer** [comment]
Hallo, I'm the maintainer of LibSass and Node Sass.

This is actually a Sass feature. When CSS colors are unquoted they're treated as Color objects, not Strings as you might expect. This is why you can do things like color math on them.

A feature of Color objects is that when they're output in compressed mode, Sass tries to output the shortest representation i.e. `#fff` is more "compressed" than `white`.

If you want CSS color names to act like strings you should quote them.

**Comment by xzyfer** [comment]
Taking the OPs example

```diff
$testMap: (
-    white: (color: white) // white is a Color object
+    "white": (color: white) // "white" is a String object
);

@each $key in map-keys($testMap) {
    .test-btn-#{$key} {
        $colors: map_get($testMap, $key);

        color: map-get($colors, color);
    }
}
```

**Comment by jeffijoe** [comment]
@xzyfer thank you for clarifying! That does make good sense, and the problem ultimately lies with library authors' lack of quotes.

**Comment by evilebottnawi** [comment]
Thanks all who helped clarify this problem. Close here because not related to `sass-loader`.
