### ISSUE TITLE
Problems importing files with non-standard extensions

### ISSUE THREAD

**Issue by rhys-vdw** [webpack-contrib/sass-loader#420]
In our codebase we have files that end in `[name].sass.erb`. These files need to be transpiled when `@require`d by other stylesheets.

ie.

`application.sass`
```sass
@import 'variables'
```

`variables.sass.erb`
```erb
$someConstant = <%= SomeRubyNamespace::SOME_CONSTANT %>
```

I can get around file extension detection with the following config:

```js
      {
        test: /\.sass(\.erb)?$/,
        use: {
          loaders: 'sass-loader',
          // We must explicitly set `indentedSyntax` to true, because SASS loader
          // determined the language (SCSS or SASS) based on file extension.
          // Since some of our files are `.sass.erb` it will not recognize them
          // as SASS.
          options: {
            indentedSyntax: true
          }
        }
      },
      {
        test: /\.scss(\.erb)?$/,
        loader: 'sass-loader'
      },
```

However, this only works for top level files. It appears that `@import` statements are not resolved by webpack.

I've had a browse through the code base (very readable), but I don't have a full grasp of how this works now. Is it the case that files are piped through webpack when `@import`ed, or is this entirely handled by `node-sass`?

**Comment by jhnns** [comment]
> However, this only works for top level files. It appears that @require statements are not resolved by webpack.

> I've had a browse through the code base (very readable), but I don't have a full grasp of how this works now. Is it the case that files are piped through webpack when @required, or is this entirely handled by node-sass?

We register a [custom importer](https://github.com/webpack-contrib/sass-loader/blob/004807b4e5b13c4101b2c368a0ca5c9ee6dcf0cc/lib/webpackImporter.js#L63-L70) which will be invoked by Libsass as soon as an @import statement is encountered.

Then, [we determine a list of file paths](https://github.com/webpack-contrib/sass-loader/blob/004807b4e5b13c4101b2c368a0ca5c9ee6dcf0cc/lib/importsToResolve.js) that we want to try. This is necessary in order to mimic the original Sass behavior of underscore imports.

For instance, this:

```sass
@require 'variables'
```

will generate this list of possible imports to resolve:

```js
[
'/path/to/_variables.scss', '/path/to/_variables.sass', '/path/to/_variables.css',
'/path/to/variables.scss', '/path/to/variables.sass', '/path/to/variables.css'
]
```

These paths are then passed to webpack's resolver. In your setup, however, these paths won't be resolvable.

This can be fixed in two ways:

### 1

We could add a check for `scss.erb` or `sass.erb` to the sass-loader. In this case, you would need to add the extension to your imports:

```sass
@require 'variables.scss.erb'
```

### 2

You could write [a resolver plugin](https://webpack.js.org/api/plugins/resolver/) which transforms requests that end on `.sass` or `.scss` to `sass.erb` or `scss.erb`. You can also limit this to a specific directory.

---

If you choose option 1, I would like to learn a little bit about your use-case. What is the `erb` file extension about? Is it commonly used? What is this `@require` statement? This is not valid Sass afaik.

If you choose option 2, I can help you 😁

**Comment by rhys-vdw** [comment]
Thanks for the great explanation. :+1: It's all clear now.

> What is this @require statement?

Oops, wrote the wrong command. Definitely mean `@import`. Edited my original post.

> What is the erb file extension about?

It's a Ruby templating language that we precompile to share code from our main app with the stylesheets. Processed by [`rails-erb-loader`](https://github.com/usabilityhub/rails-erb-loader). 

```js
      {
        test: /\.sass(\.erb)?$/,
        use: {
          loaders: 'sass-loader',
          options: {
            indentedSyntax: true
          }
        }
      },
      {
        test: /\.scss(\.erb)?$/,
        loader: 'sass-loader'
      },
      // Compile ERB templated files in the 'pre' section.
      {
        test: /\.erb$/,
        enforce: 'pre',
        loader: 'rails-erb-loader',
      }
```

> Is it commonly used?

It's commonly used in Rails projects compiled via Sprockets. We're migrating away from Sprockets, but it's a useful tool to have.

My preferred solution would be like option 1, but permitting the user to supply a list of extensions to resolve in the options. There is nothing specific to SASS about erb (one could use handlebars-loader or lodash-template-loader similarly). Actually adding a reference to erb in the sass-loader would be inappropriate.

```js
{
  test: /\.s[ac]ss(\.erb)?/,
  loader: 'sass-loader',
  options: { importExtensions: ['.scss', '.scss.erb', '.css'] }
}
```

This would replace [`extPrecedence`](https://github.com/webpack-contrib/sass-loader/blob/004807b4e5b13c4101b2c368a0ca5c9ee6dcf0cc/lib/importsToResolve.js#L6) in the `importsToResolve` function.

One downside of this is that it would fail if given the extension. eg. `some-file.sass.erb`. This could be worked around by providing just a `resolveExtensions` option or similar, but is not essential for my purposes.

I can supply a PR for this if you think it's appropriate.

**Comment by rhys-vdw** [comment]
@jhnns So I've got this running locally (I think), but it doesn't seem to address the issue.

Might it be the case that `@import`ed files are not in fact run through webpack at all, but simply read by node-sass? ie. the `webpackImporter` seems to just [resolve](https://github.com/sass/node-sass/blob/f2b410b7ffecb8b48b11e59b2ce2aa9601367112/README.md#importer--v200---experimental) the filename and then pass that back as `done({ file: resolvedFileName })`.

For my purposes I actually need the resolved content of the file to be passed back to node-sass (so that the ERB files can be transpiled by webpack first!), this seems like a bigger change than was considered above.

So for this to work I think I'd need to do use [loader.loadModule](https://webpack.js.org/api/loaders/#this-loadmodule) to get the source and then pass it back to `node-sass`, so change the code [here](https://github.com/webpack-contrib/sass-loader/blob/43cec39/lib/webpackImporter.js#L48-L56):

```js
            loadModule(dir, importsToResolve[0])
                .then((source, sourceMap, module) => {
                    // Add the file name as dependency.
                    addNormalizedDependency(module.resource);

                    // Actually pass the file data to node-sass so that the `@import`ed file uses webpack loaders.
                    return {
                        content: source
                    };
                }, () => startResolving(
                    dir,
                    tail(importsToResolve)
                ));
```

This suddenly seems like quite a dramatic change to how sass-loader functions, and also makes the task a bit larger than I can justify doing on work time.

**Comment by evilebottnawi** [comment]
@rhys-vdw what status is now? It is worth waiting for pr or not?

**Comment by rhys-vdw** [comment]
@evilebottnawi I ran out of time for the task so we're using Sprockets for now. Ultimately we plan to use Sass via Webpack, and ideally we will be able to use templating (specifically [`rails-erb-loader`](https://github.com/usabilityhub/rails-erb-loader).

I expect to get a chance to revisit this in the next couple of weeks. We still have an open issue referencing this one.

@evilebottnawi, are you able to confirm that I'm understanding the situation correctly based on above discussion?

**Comment by evilebottnawi** [comment]
@rhys-vdw If your want have own loader for `erb` files, be good use `addNormalizedDependency` inside in loader, but if your provide some little demo i can try to resolve this issue and we can migrate to `webpack` and `sass-loader` asap :+1: 
```shell
{
    test: /\.scss(\.erb)?$/,
    loader: 'sass-loader'
}
```

**Comment by rhys-vdw** [comment]
Hey @evilebottnawi. Looks like we're going to try to tackle this another way - by defining the values in Sass and then using [a loader](https://github.com/monvillalon/sass-values-loader) to parse the file and convert any variable values to JS.

Thanks for the help. You can close this issue.

**Comment by evilebottnawi** [comment]
@rhys-vdw great! btw i have same module for extract variables, just for information https://github.com/itgalaxy/get-sass-vars-sync

**Comment by rhys-vdw** [comment]
@evilebottnawi Ah, cool! This one was made by my coworker. He looked at four modules that do this work and found each to be flawed in some way, but I don't think he saw yours. Why sync? Surely an async loader is preferable, no?

**Comment by evilebottnawi** [comment]
@rhys-vdw your can rewrite on async, it is repo for my internal use, feel free to rewrite or we can write common repo based on my work :smile:
