### ISSUE TITLE
Support of @function SaSS functions

### ISSUE THREAD

**Issue by gkohen** [webpack-contrib/sass-loader#423]
All,

On this search in the node-sass I see reference to `@function` sass functions (rather than the functions exposed through the options object.
https://github.com/sass/node-sass/search?utf8=%E2%9C%93&q=colorBlue&type=

Has anyone implemented such SaSS functions?

Thanks

**Comment by evilebottnawi** [comment]
@gkohen your can use https://github.com/sass/node-sass#functions--v300---experimental as option in `loader`. Thanks for using `webpack` and `sass-loader` :+1: 

Closing this out, please feel free to reopen if this doesn't resolve your issue. Thanks!
