### ISSUE TITLE
Resolving `@import` to scoped npm packages

### ISSUE THREAD

**Issue by vanesyan** [webpack-contrib/sass-loader#424]
As continue of issue #382 there is a problem in `sass-loader` or `webpack` with resolving `.scss` files in
scoped npm packages (`node_modules/@org/pkg`) if there no explicit importing path, sass-loader will
not recognize package in `node_modules` and throw `File to import not found or unreadable: ...` error. Also, to note there is no error when using simply `css-loader` to resolve `.css` files.
See example: https://github.com/vanesyan/webpack-npm-scope-css-import-issue

**Comment by demiters** [comment]
I am having the same problem trying to `@import 'material-components-web'` which would work if the package name was prefixed with tilde (~), however the Sass file in the package also internally imports from its own `@material/...` packages without the tilde so I have no idea how to make Webpack/sass-loader deal with that?

**Comment by vanesyan** [comment]
@demiters but issue persists also if I prefix import path with tilde `~`, see example repo. by the link above.

**Comment by jhnns** [comment]
Thanks for providing that example. I'll take a look.

**Comment by vanesyan** [comment]
Any updates on the thread?

**Comment by chikamichi** [comment]
Don't know if that could be the underlying issue, but it has to be just `~`, not `~/`:

``` sass
// NOK:
@import '~/@org/pkg';

// OK:
@import '~@org/pkg/';
```

**Comment by vanesyan** [comment]
@chikamichi as you can see in example I've provided there's the second form (from which you showed) of importing statement is in use (e.g. `@import "~@org/pkg"`).

**Comment by chikamichi** [comment]
I thought you had indeed, but wanted to make it explicit just for clarification.

I'm using sass-loader to @import chunks of a npm-installed inuitcss build which has some bundled .scss files and it works flawlessly. Fixing the paths to abide by Webpack's `~` convention was all I needed to achieve to make it work. Therefore could something else beyond path scheme could be wrong in your setup?

**Comment by vanesyan** [comment]
Issue specifically appears for resolving imports from npm organization packages. Inuitcss doesn't bundle any packages from organization (`~@org/pkg`), inside it. And itself it's named `inuitcss` on npm.

**Comment by westhechiang** [comment]
This is exactly the problem that I am running into when trying to use sass-loader with eyeglass. We bundle our packages from our org. I get a compile error:
```
File to import not found or unreadable:  @eg-modules-header
```

I've been banging my head against this for the better part of this week so any insights would be extremely helpful!

**Comment by vanesyan** [comment]
@westhechiang It is working if you directly set the path to importing file in you `@import` rule, e.g.:
```css
@import "~@foo/bar.scss";
```
Note the `bar.scss` at the end of the importing rule

**Comment by evilebottnawi** [comment]
@vanesyan In your example (`https://github.com/vanesyan/webpack-npm-scope-css-import-issue`), `"~@foo/bar.scss"` don't exists use `"~@foo/bar/index"`. If your want to support `main` field in `package.json` please create separately issue.

**Comment by vanesyan** [comment]
The issue exactly was subjected to the `main` field in `package.json`. Importing from general npm package honors

**Comment by evilebottnawi** [comment]
@vanesyan `webpack` by default `support` `main` field in `package.json`.

**Comment by vanesyan** [comment]
Yes, I know, the behavior also can be customized in webpack 2. But as you can see in provided example by me importing from org. package ignore the `main` field in `package.json` file. That the issue

**Comment by evilebottnawi** [comment]
@vanesyan your right bug in this line https://github.com/webpack-contrib/sass-loader/blob/master/lib/importsToResolve.js#L33 for `@foo/bar` it is false, but should be true

**Comment by evilebottnawi** [comment]
@vanesyan I'll try to find the time to fix it today, but first I need to scrape the issues not related to `sass-loader` :tired_face:

**Comment by vanesyan** [comment]
@evilebottnawi it's ok, thanks :)

**Comment by vanesyan** [comment]
@evilebottnawi hey, I create a new pull request #447 for fixing the issue
