### ISSUE TITLE
includePaths option prepends sass folder path to file locations

### ISSUE THREAD

**Issue by asolopovas** [webpack-contrib/sass-loader#425]
Hi,

Recently I started to get strange effect, the sourceMap refferal to files from included paths prepends path  of sass directory. So in my source-maps refers to files like `C:/vhosts/project/resources/assets/sass/C:\vhosts\project/vendor\zurb\foundation\scss\grid\_gutter.scss`
instead of 'C:\vhosts\3oakdb/vendor\zurb\foundation\scss\grid\_gutter.scss', 

here is the link to my  [webpack.config](https://gist.github.com/asolopovas/3ad6377f9275ca85f75578d4d522fb80`)

**Comment by asolopovas** [comment]
I have updated my sass-loader-test repo https://github.com/asolopovas/sass-loader-test, to reflect the problem if you start index.html in public file and inspect p.animate tag in inspect section the path will be shown as D:/path/sass-loader-test/resources/assets/sass/D:\path\sass-loader-test/resources\assets\sass\app.scss

**Comment by asolopovas** [comment]
Tested it on windows ubuntu bash and sourcemaps path was fine.

**Comment by asolopovas** [comment]
Same happens if you do run npm run test-source-map on the package itself so clearly is something wrong about it.

**Comment by asolopovas** [comment]
Please respond someone its been a month since I created an issue. I have spent some time playing around and found that if I changeline 74 of loader.js,  to `result.map.sourceRoot = '';` problem goes away

**Comment by asolopovas** [comment]
@jhnns it may be related to https://github.com/webpack-contrib/sass-loader/issues/366

**Comment by evilebottnawi** [comment]
@asolopovas wip

**Comment by evilebottnawi** [comment]
@asolopovas hm, works fine for me, can your explain more information? What`browser` your are use?If your can create screenshots this bug?

**Comment by asolopovas** [comment]
@evilebottnawi Hi thanks for responding, here is the screenshots, I have tested it on different machines and few various projects everywhere I get the same problem, I eventually gave up and used gulp sass to generate my stylesheets along with browser-sync to inject them on fly it actually does it a bit faster. If you look at the repository provided above and generate it by simply running npm install + composer install + webpack, it will generate js script with source code in it and then if you open index.html you will see the error that I provided screenshots for. 
![screenshot 1](https://cloud.githubusercontent.com/assets/6893216/25682810/767b0bd4-3051-11e7-9522-d18315324ebf.jpg)
![screenshot 2](https://cloud.githubusercontent.com/assets/6893216/25682811/768087ee-3051-11e7-977f-3becea6186f3.jpg)

**Comment by evilebottnawi** [comment]
@asolopovas oh really, tomorrow try to found solution 👍

**Comment by evilebottnawi** [comment]
i hate `windows`, i spend about 4 hours just to build start to work :sob:

**Comment by asolopovas** [comment]
@evilebottnawi I love windows, I hate their filesystem, they should have adopted it long time ago and nobody would be using mac right now. But if you fiddle a bit you can figure thing oit

**Comment by evilebottnawi** [comment]
@asolopovas i don't use `mac` :smile:

**Comment by evilebottnawi** [comment]
Confirmed, start to searching solution

**Comment by evilebottnawi** [comment]
Seems related to https://github.com/mozilla/source-map/issues/91

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/css-loader/pull/532

**Comment by evilebottnawi** [comment]
Not related to `style-loader`, feel free to reopen if after merge https://github.com/webpack-contrib/css-loader/pull/532 error still exists
