### ISSUE TITLE
[Question/Feature Request] Ignoring devtool value

### ISSUE THREAD

**Issue by mooror** [webpack-contrib/sass-loader#431]
Is there a way that I can make sass-loader just rely on its sourceMap option and totally ignore devtool's value. I'm using devtool: 'cheap-eval-source-map' if webpack is not in production mode. This way my js source maps are quite quick. But ideally I want full fledged scss in development mode. From what I have seen, it appears that sass maps are not being generated in this devtool mode. Therefor I was wondering if it would be possible to create another option in the sass-loader called ignoreDevTool or something. If set to true sass-loader would only listed to its sourceMap option and totally forget about devtool.

**Comment by evilebottnawi** [comment]
@mooror Interesting! Why don't use `devtool: `source-map`` always (poor performance)? Also your can to try https://github.com/sass/node-sass#sourcecomments, https://github.com/sass/node-sass#sourcecomments and other option related to `source maps`. Also some notes about options in source code https://github.com/webpack-contrib/sass-loader/blob/master/lib/normalizeOptions.js#L34. 

If nothing to help with this or something does not work properly let us know about it :+1:

**Comment by evilebottnawi** [comment]
@mooror friendly ping

**Comment by mooror** [comment]
Thanks for the ping @evilebottnawi, I had totally forgot about this issue. The company I work for switched over to a gulp setup and therefor I had no need to look any further into this. While I still think that this feature might still be useful to others, I will close it as I myself no longer have any need for it. 

Thank you for your time,
Mooror
