### ISSUE TITLE
How to use '--relative-urls' in import?

### ISSUE THREAD

**Issue by vifird** [webpack-contrib/sass-loader#432]
How to use '--relative-urls' in import, here is my code ,but it does not work:
```
use: [
    { loader: 'style-loader' },
    { loader: 'css-loader' },
    {
        loader: 'sass-loader',
        options: {
            relativeUrls: true
        }
    }
]
```

**Comment by evilebottnawi** [comment]
@vifird Where did you find `relativeUrls` option for `sass-loader`?

**Comment by vifird** [comment]
@evilebottnawi In sass's document, as i remember.

**Comment by evilebottnawi** [comment]
@vifird `sass-loader` build on top `node-sass` (see all options https://github.com/sass/node-sass#options), also original `sass` don't have this option too. Seems you are confused with `less` (http://lesscss.org/usage/).

**Comment by evilebottnawi** [comment]
Closing this out, please feel free to reopen if this doesn't resolve your issue. Thanks!

**Comment by vifird** [comment]
@evilebottnawi Yeah, it's truely less' document. Thanks.
