### ISSUE TITLE
Invalid CSS after "...-width: $small)": expected "{", was ";"

### ISSUE THREAD

**Issue by throoze** [webpack-contrib/sass-loader#434]
I've been looking for some answer to this mystical  error i keep getting, and i dont really know where else to look. Apparently, there's an offending media query selector, but it seems as normal as any other media query example i had found so far. (Also, im not very good with media queries, really, but i think they are well formed):

```sass
$small: 480px
$medium: 786px
$large: 1140px


@media only screen and (min-width: $small)

@media only screen and (min-width: $medium)
    .some-selector
        border: 1px solid #dedede
        border-radius: 6px
        bottom: 10px
        box-shadow: 0px 0px 12px rgba(0, 0, 0, 0.2)
        height: 500px
        position: absolute
        right: 10px
        width: 320px
         .
         .
         .
```

The error i get is:

```
Module build failed: 
@media only screen and (min-width: $small)
                                        ^
      Invalid CSS after "...-width: $small)": expected "{", was ";"
      in /path/to/mediaqueries.sass (line 6, column 42)
```
I get this error when I use webpack for transpiling using a stack of many loaders for processing the stylesheets:

```js
{
      test: /\.sass$/,
      loaders: ["style", "css?sourceMap", "postcss", "resolve-url",  "sass?sourceMap"]
    }
```
this loader setup has worked well for me so far, so i don't think the problem is there.

I tried removing this set of rules (the ones with media queries) and the rest of the sass code seems to be ok. Any hint where should I look? Thanks for your help.

**Comment by evilebottnawi** [comment]
@throoze A few wrong things :smile:
1. Use options https://github.com/sass/node-sass#indentedsyntax
```shell
{
    loader: "sass-loader",
    options: {
        indentedSyntax: true,
    }
}
```
2. Wrong `sass` syntax.
```sass
$small: 480px
$medium: 786px
$large: 1140px


@media only screen and (min-width: $small)
    font-size: 14px; // Should don't be empty
@media only screen and (min-width: $medium)
    .some-selector
        border: 1px solid #dedede
        border-radius: 6px
        bottom: 10px
        box-shadow: 0px 0px 12px rgba(0, 0, 0, 0.2)
        height: 500px
        position: absolute
        right: 10px
        width: 320px
```
Some note about this syntax http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html.

Closing this out, please feel free to reopen if this doesn't resolve your issue. Thanks!
