### ISSUE TITLE
it will compile 0% when I use from tag  in .scss file

### ISSUE THREAD

**Issue by zhengxkq** [webpack-contrib/sass-loader#442]
# before compile
body,
header,
footer,
section,
div,
span,
p,
img,
a,
ul,
ol,
li,
dl,
dt,
dd,
h1,
h2,
from{
margin:0;
padding:0;
}
# after compile
0%,a,article,aside......{
margin:0;
padding:0;
}

**Comment by evilebottnawi** [comment]
@zhengxkq do your use `postcss` plugins like `cssnano`? also provide you `webpack` config

**Comment by zhengxkq** [comment]
sorry,I found my label wrongly written by form .
Form was written as from！
