### ISSUE TITLE
Invalid CSS after "e"

### ISSUE THREAD

**Issue by dudesweet100** [webpack-contrib/sass-loader#445]
What am I doing wrong?

```
ERROR in ./~/css-loader!./~/sass-loader!./client/index.scss
Module build failed:
/* index.scss */
^
      Invalid CSS after "e": expected 1 selector or at-rule, was "exports = module.ex"
      in /Users/puppeteer/Documents/GitHub/kick-ass-cv/client/index.scss (line 1, column 1)
 @ ./client/index.js 1:0-46
 @ multi ./build/dev-client ./client/index.js
```

index.scss
```
/* index.scss */
.app-content{
  &__info {
    background: red;
  }
}
```

index.js
```
require('sass-loader!./index.scss')
```

**Comment by evilebottnawi** [comment]
@dudesweet100 try `var myCss = require('css-loader!sass-loader!./index.scss');console.log(myCss)` for exporting styles
or `require('style-loader!css-loader!sass-loader!./index.scss')` for including styles in dom immediately.

**Comment by dudesweet100** [comment]
My mistake

**Comment by GoranGjorgievski** [comment]
Could you please point out what was the solution?

**Comment by tw-paraxial** [comment]
Can't say if it's the same originator, but this is the first hit for this error when googling.  In my case, the arguments for css-loader and sass-loader were reversed, and apparently that was enough to cause this.

**Comment by dkowis** [comment]
https://github.com/vuejs-templates/webpack-simple/issues/107#issuecomment-311097791

This was the problem for me. During webpack merging, I had multiple matches for `scss`.

**Comment by tylercreller** [comment]
If anyone is still running into this...

I had to define my css-loader before my sass-loader.
`				{
					test: /\.s?css$/,
					use: [
						{
							loader: MiniCssExtractPlugin.loader,
							options: {
								// publicPath: '/dist/',
								sourceMap: true
							}
						},
						{
							loader: 'css-loader',
							options: {
								sourceMap: true
							}
						},
						{
							loader: 'sass-loader',
							options: {
								sourceMap: true
							}
						}
					]
				},`

**Comment by alphakennyn** [comment]
@tylercreller heroes don't wear cape. ty for sharing!

**Comment by tmartin2089** [comment]
For those wondering why, webpack loaders process from bottom to top.

**Comment by Sohitri216** [comment]
Thanks @tylercreller You just saved a lot of time, and thanks @tmartin2089 for the explanation.
