### ISSUE TITLE
eyeglass support?

### ISSUE THREAD

**Issue by strarsis** [webpack-contrib/sass-loader#454]
Can I use [eyeglass](https://github.com/sass-eyeglass/eyeglass) together with this loader?
Do I have to install eyeglass first? How can I integrate it?

**Comment by evilebottnawi** [comment]
@strarsis i am not familiar with `eyeglass`, best answer on this question is try to integrate this and if your got error put stack trace here. Btw, for question use `stackoverflow`, thanks!

**Comment by strarsis** [comment]
Solution for eyeglass with sass-loader in recent webpack: https://github.com/sass-eyeglass/eyeglass/issues/153#issuecomment-300895607
