### ISSUE TITLE
When using sass loader , background image would not work on <html> tag

### ISSUE THREAD

**Issue by alxtz** [webpack-contrib/sass-loader#457]
I've put the code not working here

https://github.com/alxtz/Buggy

I know styling directly on html tag is a bad practice , but the example I use has something like

> html
> {
>     font-size: 10px;
>     background: url(../Release/assets/images/background.jpg) bottom center;
>     background-size: cover;
> }

I noticed that the background image would be broken(only styling direct on html)，css-loader is working file , and not using webpack is working fine , so I think there's somethin wrong with the sass-loader or resolve-url-loader.

**Comment by evilebottnawi** [comment]
@alxtz I advise using first point from https://github.com/webpack-contrib/sass-loader#problems-with-url. `sass-loader` don't handle `url` and seems it is related to `resolve-url-loader` (he using `rework`, it is bad because `rework` is not deprecated)

**Comment by evilebottnawi** [comment]
Close, not related to `sass-loader`, feel free to reopen if your think problem in `sass-loader`.
