### ISSUE TITLE
DeprecationWarning for sass-loader in newer webpack versions

### ISSUE THREAD

**Issue by dwjft** [webpack-contrib/sass-loader#458]
https://github.com/webpack/loader-utils/issues/56

```
(node:89580) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
sass-loader/lib/loader.js:81:9
sass-loader/node_modules/async/dist/async.js:2243:31
```

Couldn't find an issue here with the search term `DeprecationWarning`.

**Comment by michael-ciniawsky** [comment]
@dwjft `sass-loader` version (`@latest`) ?

**Comment by dwjft** [comment]
Just did a complete wipe of my `package.json` and upgraded everything to latest.

Seems some fragment of the `create-react-app` was keeping versions in the past.

It is fixed with a fresh, latest install.

Thanks.
