### ISSUE TITLE
webpack sassLoaderConfig does not work

### ISSUE THREAD

**Issue by heikkimu** [webpack-contrib/sass-loader#467]
I'm trying to push new settings to node-sass by using webpack's config option.

More elaborate description can be found from here:
https://stackoverflow.com/questions/44281746/storybook-to-import-scss-by-using-package-jsons-style-field

node: '6.9.1'
node-sass: "4.5.3"
sass-loader: "6.0.5"
webpack: "1.13.1"

In short:

Sass-loader doesn't recognize config given on either methods, presented on README.md

Sass-loader does get the name of the config, but doesn't react on that:
console.log at `sass-loader/lib/loader.js:#64`
```
{ config: 'otherSassLoaderConfig', ...}
```

**Comment by evilebottnawi** [comment]
@heikkimu `sass-loader` does't not have `config` option, see `options` in `README.md`.
Example
```js
{
    loader: "sass-loader",
    options: {
        includePaths: ["absolute/path/a", "absolute/path/b"]
    }
}
```

**Comment by evilebottnawi** [comment]
@heikkimu Also your question on `stackoverflow` related to `webpack` v1, please update to `webpack` v1

**Comment by heikkimu** [comment]
Source:
https://github.com/webpack-contrib/sass-loader/tree/archive/webpack-1

![image](https://cloud.githubusercontent.com/assets/7942632/26677277/e1655a1a-46d3-11e7-84fd-0043a5f9abdd.png)

So, how we should proceed with this?

**Comment by evilebottnawi** [comment]
@heikkimu current version of `sass-loader` doesn't support webpack v1 (https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L36), your can update to v2 ( **Recomended** https://webpack.js.org/guides/migrating/) or use old version `sass-loader` (https://github.com/webpack-contrib/sass-loader/tree/v4.1.1, can contains errors and unexpected behavior).
