### ISSUE TITLE
Add webpack 3 support

### ISSUE THREAD

**Issue by tleunen** [webpack-contrib/sass-loader#471]
Webpack 3 rc has been release. It would be great to make sure the loader works as expected with it.

**Comment by michael-ciniawsky** [comment]
It doesn't work at all or does it just displays a warning for an unmet `peerDependency`?

**Comment by evilebottnawi** [comment]
This will done be in https://github.com/webpack-contrib/sass-loader/issues/429
All works fine, your got just a warning for an unmet peerDependency, it's not a critical.

**Comment by d3viant0ne** [comment]
@evilebottnawi - We still support nodejs 4.3, where this would / does blow up the build.

I'll add the peerDep and new Travis file in a smaller PR than defaults.
