### ISSUE TITLE
Option to switch off url parsing

### ISSUE THREAD

**Issue by SirCameron** [webpack-contrib/sass-loader#474]
Hi Guys

Thanks for this tool.
I'm having issues with the url parsing and url rewriting.
I have images in a separate folder to my final css when built.
Problem is that the images are referenced as being within the css dir, like: css/images/logo.png

Is there a way to switch OFF the automatic url parsing and bundling of images?

I would use the file-loader instead and be able to reference my images correctly.

Thanks
C

**Comment by evilebottnawi** [comment]
@SirCameron `sass-loader` don't parse url

**Comment by evilebottnawi** [comment]
@SirCameron handling `url` do `css-loader` https://github.com/webpack-contrib/css-loader#options

**Comment by SirCameron** [comment]
Ok, so the resolve-url-loader that is grabbing and resolving the url specified in the css.
So not sass-loader's baby at all.

The problem is that it is retrieving the resource, but bundling it into the incorrect directory and so the final css can't find the file..  :/

**Comment by evilebottnawi** [comment]
@SirCameron maybe your should setup `file-loader` https://github.com/webpack-contrib/file-loader using `Filename template placeholders` where specify where your want save files.

**Comment by SirCameron** [comment]
@evilebottnawi I am.. Problem is that it's resolving the final url incorrectly.
I'll create an issue there.

Thanks for your help 👍

**Comment by evilebottnawi** [comment]
@SirCameron Can i close issue here? Feel free to reopen if it is not solve your problem. Thanks!

**Comment by SirCameron** [comment]
Yup, totally closable. Apologies for my confusion.
