### ISSUE TITLE
Info and help to others!

### ISSUE THREAD

**Issue by SirCameron** [webpack-contrib/sass-loader#477]
I was getting the "expected 1 selector or at-rule.." error and pulling my hair out.

After saving the file again with Sublime, it compiled correctly.
Returning to Atom and saving the file triggered the error.

ATOM! Not the first time I've wanted to throw my computer in a lake.
To fix this, I switch the Tab Type setting to "soft" in preferences > editor.
I suppose "hard" could be used also, but make sure it's not "auto". 
My guess is that there was a combination of tabs and spaces all up in the mix.

Could this cause sass-loader to lose track of itself?

**Comment by evilebottnawi** [comment]
@SirCameron please, provide your minimal reproducible test repo

**Comment by SirCameron** [comment]
@evilebottnawi This was just meant as a small help for those using Atom and getting the expected rule error.

**Comment by evilebottnawi** [comment]
@SirCameron `sass-loader` don't related to Atom and Atom plugin. Can your provide example where your have unexpected behavior?

**Comment by SirCameron** [comment]
@evilebottnawi Dude, I know it's not related, but the error is a combination of the two. So I'd like to help others not pull their hair out.

Don't worry. Forget it.
Please delete this.

**Comment by evilebottnawi** [comment]
@SirCameron just close. Someone can use the search and find it. Thanks!
