### ISSUE TITLE
Update dependency for webpack 3.0

### ISSUE THREAD

**Issue by marcinant** [webpack-contrib/sass-loader#478]
Installation returns:

```
sass-loader@6.0.5 requires a peer of webpack@^2.0.0 but none was installed.
```

Could you update dependencies to support webpack 3.0 ?

**Comment by evilebottnawi** [comment]
@marcinant already updated https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L57

Just update to 6.0.6 version (https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L3)
