### ISSUE TITLE
Import fails from node_modules

### ISSUE THREAD

**Issue by yogeshgadge** [webpack-contrib/sass-loader#480]
Following works fine from my project 

`@import "~some-node-depedency/dist/scss/icons`

But the `node_modules/some-node-depedency/dist/scss/_iconsscss` file further contains the following:-

```
@import "~font-awesome/scss/variables";
// custom overrides!
$fa-font-path: "~font-awesome/fonts";
@import "~font-awesome/scss/mixins";
@import "~font-awesome/scss/larger";
```

and when I do a webpack build (I am using it via angular-cli) I get following error

> `File to import not found or unreadable: ~font-awesome/scss/variables.`

Asked  https://stackoverflow.com/questions/44808024/importing-scss-from-node-modules-webpack 
but this may be a bug.

**Comment by evilebottnawi** [comment]
@yogeshgadge can your create minimal reproducible test repo? I am use font-awesome in my projects with sass-loader and all works fine

**Comment by yogeshgadge** [comment]
Figured out - I was using `fontawesome` as dependency instead of `font-awesome`. After inspecting node_modules I realized the mistake. It works fine.
