### ISSUE TITLE
style-loader was necessary for installing

### ISSUE THREAD

**Issue by julmot** [webpack-contrib/sass-loader#482]
I was experiencing this issue:

![2017-07-04 12_13_01-cmd](https://user-images.githubusercontent.com/8310677/27826102-2a305284-60b2-11e7-8bd7-a4dc98adf114.png)

https://stackoverflow.com/questions/35171288/error-cannot-resolve-module-style-loader

After running `$ npm install --save-dev style-loader` the issue was solved. If style-loader is required for sass-loader it should be included in the docs.

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/sass-loader#examples

**Comment by julmot** [comment]
Why don't you add it to the installation section?

`npm install sass-loader node-sass webpack --save-dev`
