### ISSUE TITLE
Data option not working

### ISSUE THREAD

**Issue by yantakus** [webpack-contrib/sass-loader#483]
In sass-loader v4 I was able to do the following.

In webpack config:

```
plugins: [
    new webpack.LoaderOptionsPlugin({
      options: {
        sassLoader: {
          data: `
            @import "app/styles/settings/_settings.scss";
          `,
        },
      },
    }),
]
```

Then in any component I could import sass file and use variables from `_settings.scss` there.

But since v5.0 it doesn't work all my variables become undefined, I suppose because of synchronous loading deprecation. 

Is there a way to achieve my use case in v5+?

**Comment by evilebottnawi** [comment]
@yantakus your can use https://github.com/webpack-contrib/sass-loader#environment-variables to setup own variables

**Comment by yantakus** [comment]
@evilebottnawi thanks, I saw this in the README. This is exactly what I was using before. Do you mean I should use all my sass variables directly in webpack config, without importing them with `@import` from another file?

**Comment by evilebottnawi** [comment]
@yantakus your can add `@import "app/styles/settings/_settings.scss"` to each file where your need variables or use `sass variables directly in webpack config`

**Comment by yantakus** [comment]
@evilebottnawi Thanks for the answers.

Adding import to each file is not a desired way to do it as we already have dozens of components. And I suppose webpack will be bundling much longer if it has to import a file dozens of times instead of a single one as it was in my previous config.

Placing variables into webpack config is also not an ideal solution as we loose syntax highlighting and the config gets too long (we have 900+ lines of variables).

Is there any way to import this file into webpack config? Of course we can't do it just as `const Variables = require('../blah/blah.scss)` as interpreter tries to evaluate the code and it's not javascript. Is there any way to require it as text and pass to `data` option?

**Comment by evilebottnawi** [comment]
@yantakus seems there is no solution for this purpose, your can create own loader for this (`css-loader` -> `postcss-loader` -> `sass-loader` -> `inject-sass-variables-loader`), but recommendation way is including `variables.scss` in each file. 

Why? Because each file is module and if your module contain some data (in your case it is variables) which contain in other module, your can import this module (your are doing this for `js` modules).

Also your can use other way: use https://github.com/niksy/get-sass-vars or https://github.com/itgalaxy/get-sass-vars-sync/ for reading variables in JSON format and use
```
options: {
    data: JSON.stringify(variables)
}
```

**Comment by yantakus** [comment]
Thanks a lot for describing al the options. Ended up with importing variables in each file.

**Comment by aSchaffe** [comment]
options: {
              sourceMap: true,
              data: '@import "~@stylesheets/variable/index";',
            },

**Comment by kinoli** [comment]
@aSchaffe , brilliantly simple. Thank you. This worked for me.

```
data: '@import "./src/scss/vue-globals";'
```

**Comment by fvonellerts** [comment]
This seems to be working now:
```sass
{
    loader: 'sass-loader',
    options: {
        prependData: '@import "utilities/variables", "utilities/mixins";',
        sassOptions: {
            includePaths: [path.resolve(__dirname, 'src/sass')]
        }
    }
}
```

**Comment by cgodo** [comment]
Since v9.0.0, the option to specify the @import is now named [additionalData](https://github.com/webpack-contrib/sass-loader#additionaldata).
