### ISSUE TITLE
Bug: Color with Hex Code Replacement Within Class Name

### ISSUE THREAD

**Issue by julmot** [webpack-contrib/sass-loader#487]
```css
.text-field--black .text-field__input
```
becomes:
```css
.text-field--#000 .text-field__input
```

It only occurs if "compression" is set to `compressed` or if you're running Webpack in production mode. I've tried reproducing it on SassMeister (to check if it's a node-sass bug) but I wasn't successful. Therefore I think that it's a sass-loader bug.

**Comment by evilebottnawi** [comment]
@julmot thanks for issue, known limitation for `compressed` style (`https://github.com/webpack-contrib/sass-loader/issues/416#issuecomment-311931867`), Sorry, but we can't fix this.
