### ISSUE TITLE
sass-loader does not appear to work with NormalModuleReplacementPlugin

### ISSUE THREAD

**Issue by narthollis** [webpack-contrib/sass-loader#489]
I have been unable to get `NormalModuleReplacementPlugin` to replace a SASS import.

If this is not something that should work, please feel free to close this issue.

My scenario is that I have a `variables.scss` file that contains common style items, such as colours - I am looking to replace this file as a first pass at theme support the application I am writing. (replace `variables.scss` with `variables-light.scss` for example.

**Comment by evilebottnawi** [comment]
@narthollis only `@import '~your_module'` should be works with `NormalModuleReplacementPlugin`, `@import`'s without `~` don't interpreted as module so `NormalModuleReplacementPlugin` doesn't works as expected (known limitation). But your can do this using own `importer` (https://github.com/sass/node-sass#importer--v200---experimental), it should be very easy implement.

**Comment by narthollis** [comment]
Ah, cool thanks very much.

I ended up working around this issue by using a webpack alias and a `~theme/variables.scss` imports.
Downside of this is that webstorm can't resolve the import anymore so no code completion for variable :(

Ohwell. Thanks for clarifying this
