### ISSUE TITLE
Prepend @import for every sass file

### ISSUE THREAD

**Issue by TimoRuetten** [webpack-contrib/sass-loader#491]
Hi!

I am trying to solve to prepend a @import in any loaded sass file. After I checked your docs I think this should be solved with options: { data: '@import ...' } but in my case it seems that this does not work.

```javascript
// ...
{
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract({
          loader: [
            {
              loader: 'css-loader',
              query: {
                localIdentName: '[hash:8]',
                modules: true,
              },
            },
            {
              loader: 'postcss-loader',
            },
            {
              loader: 'sass-loader',
              options: {
                data: `@import ${path.resolve(__dirname, 'src/both/ui/theme/_theme.scss')};`,
              },
            },
          ],
        }),
      },
// ...
```

I am using webpack **2.2** and sass-loader **6**

My bundled css file does not contain the content of the _theme.scss file.

I am sorry if I am missing smth basic here because webpack and all the loader logic etc. is pretty new for me.

**Comment by evilebottnawi** [comment]
@TimoRuetten thanks for issue, duplicate https://github.com/webpack-contrib/sass-loader/issues/211
Short answer
1. Use common variables.scss file and include in every required file.
2. Use https://github.com/shakacode/sass-resources-loader
3. Implement own loader for this purpose
4. Use `data` option with multiple variables (module for variables https://github.com/itgalaxy/get-sass-vars-sync)
5. https://github.com/Updater/node-sass-json-importer

**Comment by TimoRuetten** [comment]
Thanks for your fast response and sorry for duplicate. I will checkout out your reference!
