### ISSUE TITLE
Media query imports seem to be not working

### ISSUE THREAD

**Issue by catamphetamine** [webpack-contrib/sass-loader#494]
```css
@media all and (max-width: 720px) {
  @import "~react-responsive-ui/small-screen.css";
}
```

Just results in an empty file.
Don't know where exactly is the bug source: either this loader or the project.

**Comment by evilebottnawi** [comment]
@catamphetamine thank for issue, `node-sass` doing this?

**Comment by catamphetamine** [comment]
Yes, the usual Webpack + node-sass + sass-loader.
```
{
    test: /\.(sass|css)$/,
    use: [{
      loader: 'style-loader'
    }, {
      loader : 'css-loader'
    }, {
      loader : 'sass-loader'
    }]
  }
```

**Comment by catamphetamine** [comment]
This is the repo illustrating the issue
https://github.com/catamphetamine/sass-import-bug-illustration

**Comment by evilebottnawi** [comment]
@catamphetamine very strange in my projects all work fine, investigate

**Comment by evilebottnawi** [comment]
1. Fine
```css
@media (max-width: 720px) {
  a {
    color: red;
  }
}
```
2. Fine
```css
@media (max-width: 720px) {
  @import "nested";
}
```
**_nested.scss**
```css
a {
  color: yellow;
}
```
3. Not fine (module empty `exports.push([module.i, "", ""]);`)
```css
@media (max-width: 720px) {
  @import "~react-responsive-ui/small-screen.css";
}
```
I continue the investigation

**Comment by evilebottnawi** [comment]
@catamphetamine don't use `.css` extension.
Works fine.
```css
@media all and (max-width: 720px) {
  @import "~react-responsive-ui/small-screen";
}
```

**Comment by catamphetamine** [comment]
Oh, true, it does work this way.
Thanks for helping 👍.

**Comment by evilebottnawi** [comment]
@catamphetamine http://sass-lang.com/documentation/file.SASS_REFERENCE.html#_import__import
```
@import "foo.css";
@import "foo" screen;
@import "http://foo.com/bar";
@import url(foo);
```
to
```
@import "foo.css";
@import "foo" screen;
@import "http://foo.com/bar";
@import url(foo);
```

**Comment by catamphetamine** [comment]
I see...

> @import takes a filename to import. By default, it looks for a Sass file to import directly, but there are a few circumstances under which it will compile to a CSS @import rule:
* If the file's extension is .css.

**Comment by evilebottnawi** [comment]
@jhnns What do you think about this:
Should we `@import "~react-responsive-ui/small-screen.css";` don't touch and output in result:
```css
@import "~react-responsive-ui/small-screen.css";
```
Or we should throw error about not resolved? Because resolve `modules` (`~`) is out of scope `node-sass`

**Comment by catamphetamine** [comment]
My personal opinion on this: if the path starts with a tilde then it's certainly not meant for a usual CSS `@import` and an error should be thrown.

**Comment by evilebottnawi** [comment]
@catamphetamine agree, but need @jhnns answer, btw thank you for issue.
