### ISSUE TITLE
upgrade node-sass to support node 8 

### ISSUE THREAD

**Issue by spiral2k** [webpack-contrib/sass-loader#496]
upgrade node-sass from 4.5.0 to 4.5.3, adding support for node 8

**Comment by evilebottnawi** [comment]
@spiral2k you manually install `node-sass`, which part need upgrade?

**Comment by spiral2k** [comment]
in the package.json of the plugin the version on node-sass is 4.5.0, we can upgrade it to version 4.5.3 to support node 8

**Comment by evilebottnawi** [comment]
@spiral2k we use `^4.0.0` which mead also `4.5.3`

**Comment by spiral2k** [comment]
@evilebottnawi correct me if I'm wrong but in the package.json in the master branch the version of node-sass is (from the file):  "node-sass": "^4.5.0".

**Comment by evilebottnawi** [comment]
@spiral2k it is `devDependencies` only for tests, you should add `node-sass` manually in your `package.json`.

**Comment by spiral2k** [comment]
@evilebottnawi thank you man 🤘
