### ISSUE TITLE
Module build failed: SyntaxError: .../cart.scss: Unexpected token (6:0)

### ISSUE THREAD

**Issue by pedrotainha** [webpack-contrib/sass-loader#498]
I'm facing this issue with sass-loader, can somebody help please. I had the sass working with _**grunt**_ and **_compass_** before, but now i want to migrate to use sass-loader.

' [324] ./node_modules/core-js/fn/regexp/escape.js 108 bytes {0} [built]
 [327] ./scripts/checkout/cart/app-cart.jsx 45 bytes {0} [built]
 [328] ./scss/checkout/cart.scss 519 bytes {0} [built] [failed] [1 error]
    + 314 hidden modules

ERROR in ./scss/checkout/cart.scss
Module build failed: SyntaxError: D:/sources/issue reproduce/scss/checkout/cart.scss: Unexpected token (6:0)

  4 |
  5 | /* -- commun -- */
> 6 | @import '../_global';
    | ^

 @ ./scripts/checkout/cart/app-cart.jsx 3:0-43
 @ multi babel-polyfill ./scripts/checkout/cart/app-cart'

with this configuration:
'var path = require('path'),
    webpack = require('webpack'),
    fs = require('fs'),
    utils = require('../modules/utils');

//webpack plugins:
var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin,
    HappyPack = require('happypack'),
    CompressGzipPlugin = require("../modules/webpack/webpack-compress-gzip"),
    WrapperPlugin = require("../modules/webpack/webpack-wrapper"),
    ExtendIE10Plugin = require("../modules/webpack/webpack-extend-ie10");

module.exports = function (grunt) {

    var rootPath = path.join(__dirname, '..');
    var entries = utils.getAppFiles('./scripts', ['babel-polyfill']);

    var bundleanalyzer = grunt.option('bundleanalyzer') ? true : false;
    var isDEV = process.env.NODE_ENV === 'development';

    var commonPlugins = [
        new ExtendIE10Plugin({
            src: path.resolve(rootPath, 'scripts/')
        }),
        new WrapperPlugin({
            footer: "//example",
            chunks: ['common']
        }),
        new webpack.EnvironmentPlugin({
            NODE_ENV: process.env.NODE_ENV,
            DEBUG: false
        }),
        // https://webpack.js.org/plugins/ignore-plugin/ if you don't want to load any locale
        new webpack.ContextReplacementPlugin(/moment[\\\/]locale$/, /^\.\/(en|fr)$/),
        new webpack.LoaderOptionsPlugin({
            debug: isDEV,
            minimize: !isDEV
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: "common",
        }),
        new HappyPack({
            id: "1",
            threads: 4,
            loaders: ['babel-loader?cacheDirectory=true']
        }),
        new HappyPack({
            id: "2",
            threads: 4,
            loaders: ['sass-loader']
        }),
        new webpack.optimize.ModuleConcatenationPlugin()
    ];

    return {
        options: {
            stats: {
                warnings: false
            },
            devtool: 'source-map',
            resolve: {
                modules: [path.resolve(rootPath, 'scripts'), "node_modules"],
                extensions: ['.js', '.jsx'],
                symlinks: false
            },
            output: {
                path: path.resolve(rootPath, 'target/scripts'),
                filename: '[name].bundle.js'
            },
            module: {
                rules: [{
                        test: /\.(scss|sass)$/,
                        include: [path.resolve(rootPath, 'scss')],
                        use: [{
                            loader: "happypack/loader?id=2", // compiles Sass to CSS
                            options: {
                                includePaths: [
                                    path.resolve(rootPath, 'scss'),
                                    path.resolve(rootPath, 'node_modules/compass-mixins/lib'),
                                    path.resolve(rootPath, 'node_modules')
                                ]
                            }
                        }]
                    },
                    {
                        test: /\.jsx?$/,
                        loader: 'happypack/loader?id=1',
                        include: path.resolve(rootPath, 'scripts'),
                        exclude: /node_modules/,
                        query: {
                            plugins: ['transform-runtime'],
                            presets: ['react', ['es2015', {
                                modules: false
                            }], 'stage-0', 'es2015-loose']
                        }
                    }
                ]
            }
        },
        dev: {
            entry: entries,
            plugins: commonPlugins
        },
        prod: {
            entry: entries,
            plugins: commonPlugins.concat([
                new webpack.optimize.UglifyJsPlugin({
                    sourceMap: false,
                    compress: {
                        dead_code: false,
                        unused: false,
                        drop_console: true
                    }
                }),
                new CompressGzipPlugin({
                    src: path.resolve(rootPath, 'target/')
                })
            ])
        }
    }
};'

Attached is the zip with source code to reproduce.
[issue reproduce.zip](https://github.com/webpack-contrib/sass-loader/files/1371872/issue.reproduce.zip)

To run do 
`npm install` and then `grunt webpack:prod`

Thank you in advance

**Comment by evilebottnawi** [comment]
@pedrotainha please create **minimum** reproducible test repo, thank you

**Comment by pedrotainha** [comment]
@evilebottnawi . I shared a zip with the mininum source code in the description. Do i really need to create a repo?

Thanks

**Comment by evilebottnawi** [comment]
@pedrotainha no thanks

**Comment by evilebottnawi** [comment]
Btw seems something wrong with `happypack` setup

**Comment by pedrotainha** [comment]
ok, removed happyPack and it works. I will report this to them. 

But then i get further on this minimum example and i'm not able to have a css file as output. Probably i'm not getting well how the sass loader works????

again a new zip with modified content:
[issue reproduce.zip](https://github.com/webpack-contrib/sass-loader/files/1372046/issue.reproduce.zip)
