### ISSUE TITLE
Problem parsing selector variable

### ISSUE THREAD

**Issue by artvader** [webpack-contrib/sass-loader#504]
I created simple loop with a variable:
@for $i from 1 through 3 { h#{$i} { font-size: #{$i}px;  }

When compiling, I get this error:
Module build failed: Syntax Error 
    (99:8) Unknown word

and it points to the '$' character in h#{$i}

**Comment by evilebottnawi** [comment]
@artvader can you provide scss scripts, seems problem in you scss script, not in sass-loader

**Comment by artvader** [comment]
Upon correcting the scss (missing closing bracket) found out it was caused by another plugin. Thank you.
