### ISSUE TITLE
Images in scss files not showing on dev server or building to dist

### ISSUE THREAD

**Issue by joshuaaron** [webpack-contrib/sass-loader#505]
Sorry to plague this with another image issue but I haven't been able to find a solution after crawling through multiple of these related posts.

I can't seem to reference images in my .scss files and some are also not being moved to my dist folder when running webpack build:prod script

webpack.config.js:
```javascript
var path = require('path');
var autoprefixer = require('autoprefixer');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var extractPlugin = new ExtractTextPlugin({
	filename: 'css/main.css',
});

var HtmlWebpackPlugin = require('html-webpack-plugin');
var CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = {
	entry: './src/js/index.js',
	output: {
		path: path.resolve(__dirname, 'dist'),
		filename: 'js/bundle.js', 
		// publicPath: '/dist' // (dont need w/ HtmlWebpackPlugin)
	},
	devtool: 'source-map',
	devServer: {
		historyApiFallback: true,
	},
	module: {
		rules: [
		       {
                            test: /\.js$/,
                            exclude: /node_modules/,
                            use: 'babel-loader'
                       },
		       {
		            test: /\.css$|\.scss$/,
			    use: extractPlugin.extract({  
				fallback: "style-loader",
				use: [
				    { loader: 'css-loader', options: { importLoaders: 2, sourceMap: true }},
				    { loader: 'postcss-loader', options: { sourceMap: true, plugins: () => [autoprefixer] }},
				    { loader: 'sass-loader', options: { sourceMap: true }},
				],
			    }) 
			},
			{
			    test: /\.html$/,
			    use: ['html-loader']
			},
			{
			    test: /\.(jpe?g|png|gif)$/,
			    use: [
				{
				    loader: 'url-loader',
				    options: {
					limit: 8000,
					name: 'img/[name].[ext]',
				    }
				}
			    ]
			}
		]
	},
	plugins: [
		extractPlugin,
		new HtmlWebpackPlugin({ // adding this option will fill the template with your index.html file:
			template: './src/index.html'
		}),
		new CleanWebpackPlugin(['dist'])
	]
};
```

Project directory as such
```asci
| - webpack.config
| - src
      | - scss
          | - layout
              | - _about.scss
              | - _featured.scss
              | - _index.scss
          | - root.scss
      | - img
          .... three more images
          | - texture-bg.png
          | - featured.png
      | - js
          | - index.js
      | - index.html
| - dist 
      | - css
          | - main.css
      | - img
          | - texture-bg.png
          | - featured.png
      | - js
          | - bundle.js
      | - index.html
```

Referencing Images in my scss files:
```scss
// about.scss
.selector { background: url(~/img/texture-bg.png) }

// featured.scss
.selector { background: url(~/img/texture-bg.png) }
```

I have tried 
```scss
background: url(../img/texture-bg.png);
background: url(./img/texture-bg.png);
```
as well and other paths similar. 

Also, when running my build:prod script, only two of my five images (left out for brevity above) are copied over 95% of the time, the other 5% all five images get copied across? Is this a configuration setup issue?? 

Referencing the images in index.html works fine however. Also these are the two images that are copied over to the dist folder on build.

Any help would be greatly appreciated!

**Comment by evilebottnawi** [comment]
@joshuaaron why you use `~` for images? Also `sass` don't have url rewriting (https://github.com/webpack-contrib/sass-loader#problems-with-url). `importLoaders: 2` => `importLoaders: 1`

**Comment by joshuaaron** [comment]
In the midst of finding a solution was trying other methods I had seen on similar issues - Half the time that works for one and will load, the other half it won't load. 

Also I assumed I would need to importLoaders: 2 since I am using two loaders after css-loader? Apologies this is my first webpack setup for a site and struggling.

**Comment by evilebottnawi** [comment]
@joshuaaron `importLoaders` means:
```scss
@import "test.css";
// if you use `importLoaders: 2`: `scss-loader` => `postcss-loader` run on this import
// if you use `importLoaders: 1`: `postcss-loader` run on this import

// Other scss code
```
About url, use `full` relative url - `../../img/my-img.png` (relative `root.scss`)

**Comment by joshuaaron** [comment]
@evilebottnawi  thanks for the reply.
Using the full relative URL throws:
Module not found: Error: Can't resolve '../../img/texture.png' in '/[local-directory]/src/scss'
     @ ./node_modules/css-loader?{"importLoaders":2,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"plugins":[null]}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./src/scss/root.scss 6:12733-12765

**Comment by joshuaaron** [comment]
@evilebottnawi Will get one to you later today

**Comment by joshuaaron** [comment]
@evilebottnawi  https://github.com/joshuaaron/test-repo
email me at josh_reynolds_@hotmail.com if you need to, first webpack setup ive done so theres probably a few places to optimise this. 
Using the ~/img .. path in dev mode seems to work fine. When creating a prod build, that no longer works, and i cant get a path to work for it at all. This is only for images in scss files. img tags in index.html working fine

**Comment by joshuaaron** [comment]
@evilebottnawi were you able to find any solution or have any tips on this?

**Comment by evilebottnawi** [comment]
@joshuaaron in near future i investigate you problems, sorry for delay, many work :disappointed:

**Comment by evilebottnawi** [comment]
Sorry for delay, WIP

**Comment by evilebottnawi** [comment]
All works fine in dev and dist :confused: Maybe problem was in `file-loader` (we fixed a lot of issue around outputPath and publicPath). Feel free to feedback. Thanks!
