### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jainshravan123** [webpack-contrib/sass-loader#508]
I tried to put the console logs inside sass-loader node-module . Here i can see that the flow is going inside startResolving function which is inside webpackImporter.js of sass-loader file. Can anyone please help me soon.

**Comment by evilebottnawi** [comment]
@jainshravan123 what do you mean?

**Comment by jainshravan123** [comment]
@evilebottnawi We are using sass-loader in our project. I was facing following issue.
```
(node:18807) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

TypeError: undefined is not a function
```

So i tried to put the console logs inside sass-loader node-module . Here i can see that the flow is going inside startResolving function which is inside webpackImporter.js of sass-loader file.

Is there any quick solution for this?

**Comment by evilebottnawi** [comment]
@jainshravan123 update `sass-loader` to `latest` version, if it is not solve you problem, please create minimum reproducible test repo

**Comment by jainshravan123** [comment]
@evilebottnawi I already updated `sass-loader` to it's latest version i.e. `6.0.6` but still i am facing the same issue.

**Comment by michael-ciniawsky** [comment]
@jainshravan123 Are you sure this warning comes from `sass-loader` (maybe invalid npm cache)? The loader is updated to use the new method for [`options` parsing](https://github.com/webpack-contrib/sass-loader/blob/master/lib/normalizeOptions.js#L21) for a while now

**Comment by jainshravan123** [comment]
@michael-ciniawsky I added some console logs in `sass-loader`. So It was getting stuck somewhere and all of the valid logs were not printing. So i came to know that it's happening because of `sass-loader` only. And i tried to run my project without `sass-loader` too so without that it's running absolutely fine.

**Comment by michael-ciniawsky** [comment]
Where did you add them could you search for `loaderUtils.parseQuery`in `node_modules/sass-loader` ?  Did you delete `node_modules` && your  lockfile (maybe `npm cache clean --force`) and a tried a fresh install ?

**Comment by evilebottnawi** [comment]
@jainshravan123 `npm cache clear --force` and `npm i`. Seems you have old `sass-loader`. Just check `package-lock.json` which version installed. Feel free to reopen if problem still exists.
