### ISSUE TITLE
Environment variables / data: possibility to use a function

### ISSUE THREAD

**Issue by crazyx13th** [webpack-contrib/sass-loader#510]
would be cool to use a function to get somthing like "load context / [name]" to add more dynamic stuff
thx!

greetings
crazyx13th

**Comment by evilebottnawi** [comment]
@crazyx13th can you provide example?

**Comment by crazyx13th** [comment]
```loader: "sass-loader",
options: {
	data: ()=>{ return
		'$isDesktop:' + (this.resourcePath === 'desktop' ? 'true' : 'false') + ';' +
		'$isTablet:' + (this.resourcePath=== 'tablet' ? 'true' : 'false') + ';' +
		'$isMobile:' + (this.resourcePath=== 'mobile' ? 'true' : 'false') + ';' +
		'$isWide:' + (this.resourcePath!== 'mobile' ? 'true' : 'false') + ';'
	}
}
```

something like this :-)
https://webpack.github.io/docs/loaders.html#loader-context

Thx!

**Comment by crazyx13th** [comment]
target is to get the current **entry-name** (e.g.` c2g-desktop`)
![grafik](https://user-images.githubusercontent.com/8912561/32942255-c950ee00-cb88-11e7-99e2-13d1723732ab.png)

see also https://stackoverflow.com/questions/44970996/reactjs-getting-sperated-css-output-using-webpack-extracttextplugin

**Comment by michael-ciniawsky** [comment]
@crazyx13th Is `data` for e.g passing custom variables ? If so feel free to tackle this and sending a PR I will assist if needed or do it when I have time. This is also needed to implement watching these

**Comment by evilebottnawi** [comment]
@crazyx13th PR welcome

**Comment by neotech-starassov** [comment]
You can use getter instead of function 🚀

**Comment by aprilmintacpineda** [comment]
You can get around this by doing:

```js
options: {
  functions: {
    env (name, done) {
      if (name in process.env === false) throw Error(`${name} does not exists in process.env`);
      done(nodeSass.types.String(process.env[name]));
    }
  }
}
```

Then on scss

```scss
background-color: env('theme-color')
```

Not a great solution, but should help out.

**Comment by evilebottnawi** [comment]
@aprilmintacpineda Can you send a PR to documentation about this?
