### ISSUE TITLE
Module build failed: Unknown word  #{$key}

### ISSUE THREAD

**Issue by gaponenkodv** [webpack-contrib/sass-loader#511]
I have a problem
` ERROR in ./node_modules/css-loader!./ClientApp/scripts/scss/material.scss
    Module build failed: Unknown word (530:29)

      528 |
      529 |     @each $key, $val in $colors {
    > 530 |         &:checked.chk-col-#{$key} {
          |                             ^
      531 |             + label {
      532 |                 &:before {
      533 |                     border-right: 2px solid $val;

webpack:

                {
                    test: /\.ts$/, include: /ClientApp/, use: isDevBuild ? [{
                        loader: 'ng-router-loader',
                        options: {
                            loader: 'async-import',
                            genDir: 'compiled',
                            aot: !isDevBuild
                        }
                    }, 'awesome-typescript-loader?silent=true', 'angular2-template-loader']
                        : '@ngtools/webpack'
                },
                { test: /\.html$/, use: 'html-loader?minimize=false' },
                { test: /\.css$/, use: ['to-string-loader', isDevBuild ? 'css-loader' : 'css-loader?minimize'] },
                { test: /\.scss$/, use: ['to-string-loader' ,'css-loader', 'sass-loader']},
                { test: /\.(jpg|png|gif)$/, use: 'file-loader' },
                { test: /\.(woff|woff2|eot|ttf|svg)$/, use: 'file-loader' }
            `
why? could somebody help me?

**Comment by evilebottnawi** [comment]
@gaponenkodv which version `node-sass` and `libsass` you use?

**Comment by gaponenkodv** [comment]
"node-sass": "4.6.1",
libsass i dont know, I thought inside the node-sass it

2017-11-20 15:09 GMT+03:00 Evilebot Tnawi <notifications@github.com>:

**Comment by evilebottnawi** [comment]
@gaponenkodv can you create minimum reproducible test repo?

**Comment by gaponenkodv** [comment]
https://github.com/gaponenkodv/sample
there dotnet created a lot of files in default angular project, but you need using files with webpack and ClientApp/styles

**Comment by gaponenkodv** [comment]
@evilebottnawi, do you know anithing about it?

**Comment by evilebottnawi** [comment]
@gaponenkodv seems problem in configuration, i am not familiar with angular sass configuration, better create issue there, sorry

**Comment by evilebottnawi** [comment]
what tests do you mean?
