### ISSUE TITLE
Getting Error : You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by Debananda** [webpack-contrib/sass-loader#515]
Getting below rrror : 
ERROR in ./src/app.scss
Module parse failed: Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
| body {
|     color: pink;
| }
 @ ./src/app.js 1:12-33

**webpack.config.js**

> 

 plugins: [new HtmlWebpackPlugin({
        title: "My App Testing",
        minify: {
            collapseWhitespace: true
        },
        module: {
           rules: [{
                test: /\.scss$/,
                use: [{
                    loader: "style-loader" // creates style nodes from JS strings
                }, {
                    loader: "css-loader" // translates CSS into CommonJS
                }, {
                    loader: "sass-loader" // compiles Sass to CSS
                }]
            }]
        },
        hash: true,
        template: __dirname + "/src/index.html"
    })]

package.json
"devDependencies": {
    "css-loader": "^0.28.7",
    "html-webpack-plugin": "^2.30.1",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.19.0",
    "webpack": "^3.10.0"
  }

**Comment by michael-ciniawsky** [comment]
Does `html-webpack-plugin` support passing the whole `module.rules` ? It uses a `childCompilation` internally so maybe you need to setup `module.rules` in your `webpack.config.js`  aswell for `.scss` files not included there 

**webpack.config.js**
```js
const config = {
   module: {
      rules: [ ...rules ]
   },
   plugins: [ new HTMLPlugin({ ...options })]
}
```

**Comment by Debananda** [comment]
@michael-ciniawsky : Thanks. its working.
