### ISSUE TITLE
ver 6.06 requires "node-sass" package as peerDependencies instead of dev 

### ISSUE THREAD

**Issue by asafMasa** [webpack-contrib/sass-loader#519]
"peerDependencies": {
   **"node-sass": "^4.0.0",**
    "webpack": "^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0"
  },

sass-loader is required by angular cli (node-sass as **optional** dependency) and you enter node-sass in the backdoor as a **must** depenency...

**Comment by michael-ciniawsky** [comment]
That's intended so the user controls the version of `node-sass` freely
