### ISSUE TITLE
 Module parse failed: Unexpected character '�'

### ISSUE THREAD

**Issue by shivamkumar110** [webpack-contrib/sass-loader#522]
I am migrating from webpack 1 to 3. After going through so many errors and now I am stuck on this. Can someone please **HELP**!

 I am getting these errors -

```
ERROR in ./src/main/js/styles/common.scss
Module build failed: ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
    at doBuild (/Users/shivam/TMS/tms-ui/node_modules/webpack/lib/NormalModule.js:303:19)
    at runLoaders (/Users/shivam/TMS/tms-ui/node_modules/webpack/lib/NormalModule.js:209:11)
    at /Users/shivam/TMS/tms-ui/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/shivam/TMS/tms-ui/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at Array.<anonymous> (/Users/shivam/TMS/tms-ui/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/shivam/TMS/tms-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
    at /Users/shivam/TMS/tms-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
    at /Users/shivam/TMS/tms-ui/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
 @ ./src/main/js/components/TimeZone.jsx 25:0-32
 @ ./src/main/js/containers/AccountSettingsPage.jsx
 @ ./src/main/js/containers/index.js
 @ ./src/main/js/routes.jsx
 @ ./src/main/js/index.jsx
```

```
ERROR in ./src/main/js/images/loader.gif
Module parse failed: Unexpected character '' (1:7)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./src/main/js/containers/App.jsx 35:14-45
 @ ./src/main/js/containers/index.js
 @ ./src/main/js/routes.jsx
 @ ./src/main/js/index.jsx

```
```
ERROR in ./src/main/js/images/down-arrow.png
    Module parse failed: Unexpected character '�' (1:0)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/main/js/styles/common.scss 6:72596-72631 6:84280-84315
```

Here's my **webpack.config.js** -
```

var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var path = require('path');

var SRC = path.resolve(__dirname, 'src/main/js');
var DEST = path.resolve(__dirname, 'src/main/resources/static/app');
var config = {
    cache: true,
    entry: SRC,
    target: 'web',
    resolve: {
        extensions: ['.js', '.jsx']
    },
    output: {
        path: DEST,
        filename: 'bundle.js',
        publicPath: '/tms-ui/app/',
        library: 'TMS'
    },
    module: {
        rules: [{
            test: /\.js(x)?$/,
            use: [{
                loader: 'eslint-loader'
            }],
            enforce: 'pre',
            include: SRC
        },  {
            test: /\.js(x)?$/,
            use: [{
                loader: 'babel-loader'
            }],
            include: SRC
        },  {
            test: /(\.css|\.scss)$/,
            include: SRC,
            use: ExtractTextPlugin.extract({
                use: [{
                      loader: "css-loader"
                  }, {
                      loader: "sass-loader"
                  }],
                  // use style-loader in development
                  fallback: "style-loader"
            })
          },  {
            test: /\.ico$/,
            include: SRC,
            use: [{
                loader: 'file-loader?name=[name].[ext]'
            }],
        },  {
            test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            include: SRC,
            use: [{
                loader: 'url-loader?limit=10000&mimetype=application/font-woff'
            }],
        },  {
            test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            include: SRC,
            use: [{
                loader: 'file-loader'
            }]
        }]
    },
    plugins: [
        new ExtractTextPlugin({
            filename: "bundle.css",
            disable: false,
            allChunks: true
        }),
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify('production')
            }
        }),
        new webpack.optimize.UglifyJsPlugin({
            sourceMap: true,
            compress: {
                warnings: true
            }
        })
    ]
};
module.exports = config;
```

**package.json**
```
"dependencies": {
    "autoprefixer-loader": "^3.2.0",
    "babel-core": "^6.7.6",
    "babel-eslint": "^8.0.3",
    "babel-loader": "^7.1.2",
    "babel-plugin-react-transform": "^3.0.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "classnames": "^2.2.5",
    "css-loader": "^0.28.7",
    "es6-promise": "^4.1.1",
    "eslint": "^4.13.1",
    "eslint-loader": "^1.3.0",
    "eslint-plugin-react": "^7.5.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "1.1.6",
    "history": "^4.7.2",
    "jsbarcode": "^3.5.5",
    "lodash.isequal": "^4.3.1",
    "node-sass": "^4.7.2",
    "object-assign": "^4.1.0",
    "postcss-cssnext": "^3.0.2",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.9",
    "postcss-plugin": "^1.0.0",
    "rc-progress": "^2.2.1",
    "react": "^16.2.0",
    "react-addons-update": "^15.1.0",
    "react-day-picker": "^7.0.5",
    "react-dom": "^16.2.0",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-redux": "^4.0.2",
    "react-select": "^1.0.0-beta13",
    "react-transform-hmr": "^1.0.4",
    "redux": "^3.4.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.0.1",
    "rimraf": "^2.5.2",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.19.1",
    "sugarss": "^1.0.1",
    "superagent": "^3.8.2",
    "url-loader": "^0.6.2",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.9.7",
    "webpack-hot-middleware": "2.21.0"
  },
```

**Comment by michael-ciniawsky** [comment]
```diff
- test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
+ test: /\.(ttf|eot|svg|gif)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            include: SRC,
            use: [{
                loader: 'file-loader'
            }]
```

**Comment by shivamkumar110** [comment]
It only solved gif loader problem. Module parse error still exist.

**Comment by evilebottnawi** [comment]
@shivamkumar110 can you create minimum reproducible test repo?

**Comment by shivamkumar110** [comment]
@evilebottnawi https://github.com/shivamkumar110/webpack-3-test

**Comment by Apoorv2345** [comment]
Any update on it. I'm facing similar issue?

**Comment by WhiteLeash** [comment]
^same

**Comment by shivamkumar110** [comment]
Yeah, Sorry to respond late. Seems like there was a problem with my eslint configuration where I made it to fail my build if any linting error is there. And I wasted a lot of time in correcting webpack configs. Silly me.  Pass option emitWarning:false in option of eslint.
Here's my latest webpack config which works fine.

```
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var path = require('path');

var SRC = path.resolve(__dirname, 'src/main/js');
var DEST = path.resolve(__dirname, 'src/main/resources/static/app');

const extractPlugin = new ExtractTextPlugin({ filename:'bundle.css',
disable: false,
allChunks: true });

var config = {
    cache: true,
    entry: SRC,
    target: 'web',
    resolve: {
        extensions: ['.js', '.jsx']
    },
    output: {
        path: DEST,
        filename: 'bundle.js',
        publicPath: '/tms-ui/app/',
        library: 'TMS'
    },
    module: {
        rules: [
        {
            test: /\.jsx?$/,
            use: [
                {
                    loader: 'eslint-loader',
                    options: {
                        emitWarning: true
                    }
                }
            ],
            include: SRC,
            enforce: 'pre'
        },  {
            test: /\.jsx?$/,
            loaders: ['babel-loader'],
            include: SRC
        }, {
            test: /(\.css|\.scss)$/,
            include: SRC,
            use: ['css-hot-loader'].concat(extractPlugin.extract({
                use: [
                    {
                        loader: 'css-loader',
                        options: {
                            sourceMap: true
                        }
                    },
                    {
                        loader: 'postcss-loader',
                        options: {
                            sourceMap: true
                        }
                    },
                    {
                        loader: 'sass-loader',
                        options: {
                            sourceMap: true
                        }
                    }
                ],
                fallback: 'style-loader'
            }))
        }, {
            test: /\.(jpe?g|png|gif|mp3)$/i,
            include: SRC,
            loaders: ['file-loader']
        }, {
            test: /\.ico$/,
            include: SRC,
            use: [
                {
                    loader: 'file-loader',
                    options: {
                        name: '[name].[ext]'
                    }
                }
            ]
        }, {
            test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            include: SRC,
            use: [
                {
                    loader: 'url-loader',
                    options: {
                        limit: 1000,
                        mimetype: 'application/font-woff'
                    }
                }

            ]
        }, {
            test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            include: SRC,
            loader: 'file-loader'
        }]
    },
    plugins: [
        extractPlugin,
        new webpack.LoaderOptionsPlugin({
            options: {
                context: __dirname,
                debug: true
            }
        }),
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify('production')
            }
        }),
        new webpack.optimize.UglifyJsPlugin({
            minimize: true})
    ]
};
module.exports = config;

```

Hope this helps @Apoorv2345 @WhiteLeash

**Comment by maxime-rainville** [comment]
I gave a go at fixing this and I think I found the problem. In our webpack config, the rule for handling font files goes something like this:
```js
{ 
  test: /fonts\/([\w_-]+)\.(woff|eot|ttf|svg)$/,
  loader: 'file-loader',
  options: { name: 'fonts/[name].[ext]' } 
}
```

I think the Windows directory separator is tripping off our test regex because if I change it to `/fonts\\([\w_-]+)\.(woff|eot|ttf|svg)$/` the build script manages to conclude normally.

**Comment by keshav00001** [comment]
please help .............for this problem..

C:\Users\Noargs\Documents\Angular>cd my-app

C:\Users\Noargs\Documents\Angular\my-app>ng serve --open
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-08-24T06:23:17.081Z
Hash: 45253f019453bff022b4
Time: 7394ms
chunk {main} main.js, main.js.map (main) 11.1 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 227 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 15.6 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.26 MB [initial] [rendered]

ERROR in ./ansi-html
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/bin/sh
| basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
|
i ｢wdm｣: Failed to compile.
Terminate batch job (Y/N)? y

C:\Users\Noargs\Documents\Angular\my-app>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.1.5
Node: 8.11.3
OS: win32 x64
Angular: 6.1.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2

**Comment by keshav00001** [comment]
C:\Users\Noargs\Documents\Angular>cd my-app

C:\Users\Noargs\Documents\Angular\my-app>ng serve --open
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-08-24T06:23:17.081Z
Hash: 45253f019453bff022b4
Time: 7394ms
chunk {main} main.js, main.js.map (main) 11.1 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 227 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 15.6 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.26 MB [initial] [rendered]

**ERROR in ./ansi-html
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/bin/sh
| basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
|
i ｢wdm｣: Failed to compile.**


Terminate batch job (Y/N)? y

C:\Users\Noargs\Documents\Angular\my-app>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.1.5
Node: 8.11.3
OS: win32 x64
Angular: 6.1.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2

**Comment by nmish2005** [comment]
```diff
- test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
+ test: /\.(ttf|eot|svg|gif|png)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            include: SRC,
            use: [{
                loader: 'file-loader'
            }]
```
(Simply add png to `test` and it will load...)

**Comment by ezenwankwogabriel** [comment]
> ```diff
> - test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
> + test: /\.(ttf|eot|svg|otf|gif)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
>             include: SRC,
>             use: [{
>                 loader: 'file-loader'
>             }]
> ```

for me, the error was on the font face i added with extension .otf
so ill say, check for the extension giving the issue, and add it to the above.
worked for me

**Comment by kadimi** [comment]
```
    rules: [
      // ... 
      {
        test: /\.(eot|gif|otf|png|svg|ttf|woff)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        use: [ 'file-loader' ],
      },
    ],
```

**Comment by GaddMaster** [comment]
Thanks all, this post helped me solve my insane long list of red writing terror bugs

**Comment by aravind33** [comment]
I had a problem with png file and it's still unsolved

**Comment by kvz** [comment]
I had to add `webp` to the `test` property of my url-loader rule, fwiw
