### ISSUE TITLE
sass worker hangs on js compilation errors under certain circumstance

### ISSUE THREAD

**Issue by JLHwung** [webpack-contrib/sass-loader#523]
I come across webpack hanging on company building machine. After hours and hours I manage to craft a tiny example ( [link](https://github.com/JLHwung/webpack-sass-worker-hang-example) ) and reproduce it on my mac as well as travis ( [link](https://travis-ci.org/JLHwung/webpack-sass-worker-hang-example]) ).

Travis errored due to timeout and it is expected to fail immediately.

When webpack throws js compilation errors, chances are `node-sass` just setup a worker to compile sass and this worker does not get closed while the `webpack` exits. Thue `webpack` is hang.

Related issues may be https://github.com/sass/node-sass/issues/857 but I am not sure if it is same issue.

This issue may involve several teams and I hope we can work together to fix. Before we fix the issue

As noted by @crvv the following is invalid and does not work at all.
<s>I also find a workaround for this specific hanging situation:-
```
UV_THREADPOOL_SIZE=1 webpack --config ./config.js
```
It will disable the `asyncQueue` of `sass-loader`. Use at your own risk. </s>

**Comment by evilebottnawi** [comment]
@JLHwung can you provide minimum reproducible test repo?

**Comment by JLHwung** [comment]
> After hours and hours I manage to craft a tiny example ( [link](https://github.com/JLHwung/webpack-sass-worker-hang-example) ) and reproduce it on my mac as well as travis ( [link](https://travis-ci.org/JLHwung/webpack-sass-worker-hang-example]) ).

@evilebottnawi The minimal example is https://github.com/JLHwung/webpack-sass-worker-hang-example.

It shall be fixed by https://github.com/webpack/webpack/pull/6193, yet any further explanation is also definitely welcome.

**Comment by JLHwung** [comment]
Closed since https://github.com/webpack/webpack/pull/6193 is merged.
