### ISSUE TITLE
No sense calc() results

### ISSUE THREAD

**Issue by leonimurilo** [webpack-contrib/sass-loader#524]
I have the following sass code for a grid column:
```sass
// 1rem = 10px
$grid-width: 114rem
$gutter-horizontal: 6rem
.row
  max-width: $grid-width
  .col-1-of-2
    width: calc((100% - #{$gutter-horizontal}) / 2)
```

```jsx
<div className="row">
  <div className="col-1-of-2">Col 1 of 2</div>
  <div className="col-1-of-2">Col 1 of 2</div>
</div>
```

Since the grid width is 1140px (max size triggered) and $gutter-horizonta is 60px, each column width should be 540px so I would have 540px + 60px + 540px = 1140px. However for some reason the column width that appears when I inspect the element in any browser is 47% which is no sense since 47% is 535.8px not 540px.

Why is the following code being converted to no sense percentages?
`    width: calc((100% - #{$gutter-horizontal}) / 2)`

It should be converted to 540px not 47%
![screen shot 2017-12-30 at 10 46 31](https://user-images.githubusercontent.com/14261943/34454352-c4d01c86-ed50-11e7-91b3-4b410c50ca02.png)

Of course I end with a unexpected spacement aftet the second column:

![screen shot 2017-12-30 at 10 07 22](https://user-images.githubusercontent.com/14261943/34454351-c4ae222a-ed50-11e7-834f-e28cf88de23c.png)

**Comment by evilebottnawi** [comment]
@leonimurilo seems problem in `node-sass`, can you create minimum reproducible test repo? Also do you use `postcss` (which plugins)?

**Comment by evilebottnawi** [comment]
@leonimurilo not related to `sass-loader`, look https://www.sassmeister.com/

Input:

```sass
// 1rem = 10px
$grid-width: 114rem
$gutter-horizontal: 6rem
.row
  max-width: $grid-width
  .col-1-of-2
    width: calc((100% - #{$gutter-horizontal}) / 2)
```

Output:

```css
.row {
  max-width: 114rem;
}
.row .col-1-of-2 {
  width: calc((100% - 6rem) / 2);
}
```

Maybe you use `postcss` plugin or minifier. Thanks for issue.

**Comment by leonimurilo** [comment]
I found that the issue was being caused by the less-loader being applied to the same files after the sass loader.
