### ISSUE TITLE
Use of bootstrap sass does not work

### ISSUE THREAD

**Issue by bm-stschneider** [webpack-contrib/sass-loader#526]
Although I already added the path to node modules folder for bootstrap sass it is not resolved and the build exits with an error.
```
Module build failed:
@import 'bootstrap/variables';
^
      File to import not found or unreadable: bootstrap/variables.
```

**Comment by klis87** [comment]
I have exactly the same problem, with below configuration:
```js
        {
          test: /\.scss$/,
          use: [
            {
              loader: 'css-loader/locals',
              options: {
                modules: true,
                localIdentName: '[path][name]__[local]--[hash:base64:5]',
              },
            },
            { loader: 'postcss-loader' },
            {
              loader: 'sass-loader',
              options: {
                includePaths: [path.resolve(__dirname, 'node_modules', 'bootstrap-sass', 'assets', 'stylesheets')],
              },
            },
          ],
        },
```
It seems that `includePaths` isn't picked up, as `@import "~bootstrap/sass/assets/stylesheets/bootstrap/variables"` works, and `@import "bootstrap/variables"`doesn't.

What is interesting, it doesn't work only for server side rendering, for client side it works fine.

**Comment by evilebottnawi** [comment]
Somebode can create minimum reproducible test repo?

**Comment by evilebottnawi** [comment]
@klis87 don't use `node_modules` inside `includePaths`, using `~` already meaning what you want load from `node_modules`. If you have `bootstrap-sass` outside `node_modules` please confirm what it is inside `webpack.context` directory and use `@import "variables"`. 

Example:
`webpack.context` => `/path/to/src`

`bootstrap-sass` directory => `/path/to/src/bootstrap-sass` (`includePaths: [path.resolve(__dirname, "bootstrap-sass")]`)

`@import "variables";` => load from `/path/to/src/bootstrap-sass/_variables.scss`

But best add `src` only to `includePaths` and use `@import "bootstrap-sass/variables";`

**Comment by evilebottnawi** [comment]
@bm-stschneider use `@import "~bootstrap-sass/assets/stylesheets/bootstrap/variables"`

**Comment by bm-stschneider** [comment]
Am I right that this ~ is only usable with webpack? Can't find anything in the sass documentation about that.

**Comment by evilebottnawi** [comment]
@bm-stschneider yes `~` only for `webpack`

**Comment by andrebautista** [comment]
@bm-stschneider Did you figure out how to fix this? Running into the same issue right now with the bootstrap package.

**Comment by bm-stschneider** [comment]
No, there seems to be no way other than a webpack specific syntax.

**Comment by andrebautista** [comment]
I was banging my head against the wall for quite some time earlier but I stumbled upon a stopgap solution.
`
{
                  loader: 'sass-loader',
                  options: {
                    includePaths: ['node_modules']
                  }
                }
`
By using includePaths I can now reference bootstrap in my manifest file like so:
`@import "bootstrap/scss/functions.scss";` Notice how I leave out the `node_modules` directory in the path because the loader is already aware of it.

The source of the bug is due to the fact that the bootstrap scss files i.e. `bootstrap/scss/variables|mixins|functions.scss` include imports within those files to other helper modules which are not prefixed with the ~ like the parent file when you import it - `@import ~bootstrap/scss/variables.scss` - the loader is then unaware and the build breaks.

**Comment by double-reinbows** [comment]
I don't think i have the configuration file in my repo. Is it ok if I just make it? if so, where?
