### ISSUE TITLE
bootstrap4 beta 3 build fails

### ISSUE THREAD

**Issue by bschelling** [webpack-contrib/sass-loader#527]
Disclaimer: I'm not sure if this is a bootstrap or a loader issue so please correct me if I'm reporting in the wrong project.

boostrap4 beta 2 builds worked, now beta 3 was released and the webpack build fails with

```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/scss/main.scss
Module build failed:
 padding: $kbd-padding-y $kbd-padding-x;
```

thx for hints!

**Comment by evilebottnawi** [comment]
@bschelling can you create minimum reproducible test repo, seems you don't include all sass files

**Comment by evilebottnawi** [comment]
@bschelling also maybe related https://github.com/webpack-contrib/sass-loader/issues/527?

**Comment by arajay** [comment]
Same but mine fails on the following:
`$custom-file-text               : (
    placeholder: ( en: "Choose file..." ),
    button-label: ( en: "\f019" )
);`

this compiled fine in v4beta 2

**Comment by bschelling** [comment]
just set it up from scratch with webpack and i don't have any issues yet, still researching..

**Comment by evilebottnawi** [comment]
@bschelling @arajay don't reproducible, seems you have old version `node-sass`, update `node-sass` to latest version (`npm cache clear --force && npm install` to ensure you will get latest version). Also you can see you installed version in `package-lock.json`. Feel free to reopen issue if you still have problem with minimum reproducible test repo. Thanks for issue!
