### ISSUE TITLE
Support for max() in combination with env(safe-area-inset-*)

### ISSUE THREAD

**Issue by MikeSpencer42** [webpack-contrib/sass-loader#528]
I'm trying to update an app to account for the iPhone X notch. [Webkit.org has a really good article](https://webkit.org/blog/7929/designing-websites-for-iphone-x/) on how to do this. The suggested CSS looks like this:

```
padding-left: max(12px, env(safe-area-inset-left));
```

However, when I apply similar code into my SCSS, I get the following error in the terminal:

```
ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js!./app/suite/sass/style.scss
Module build failed: 
        padding-left: max(16px, env(safe-area-inset-left));
                     ^
      "env(safe-area-inset-left)" is not a number for `max'
```

Note: the older standard `constant()` also does not work with `max()`.

Any insight would be helpful.

**Comment by evilebottnawi** [comment]
@MikeSpencer42 can you show webpack config?

**Comment by MikeSpencer42** [comment]
@evilebottnawi Sorry for the delay. Here's a snippet from the config:

```
module: {
    rules: [
        {
            test: /\.css$/,
            use: ['style-loader', 'css-loader']
        },
        {
            test: /\.scss$/,
            use: ['style-loader', 'css-loader', 'sass-loader']
        }
    ]
}
```

**Comment by evilebottnawi** [comment]
@MikeSpencer42 we don't provide `env` helper. See https://github.com/webpack-contrib/sass-loader#environment-variables. Add to config:
```js
{
    loader: "sass-loader",
    options: {
        data: "$safe-area-inset-left: 200px; $another-value: 100px"
    }
}
```

```scss
a {
  padding-left: max(16px, $safe-area-inset-left);
  width: $another-value;
}
```

Thanks for issue.

**Comment by dyatko** [comment]
@evilebottnawi It's not a fix, please learn Webkit article on a reason for such combination:
https://webkit.org/blog/7929/designing-websites-for-iphone-x/

**Comment by dyatko** [comment]
@MikeSpencer42 I found a fix https://github.com/sass/sass/issues/2378
`margin-left: m#{a}x(12px, env(safe-area-inset-left));`

**Comment by MikeSpencer42** [comment]
@dyatko I ended up modifying my Webpack build process to allow for a CSS file to be injected into the `<head>` after my CSS that is generated via SCSS. The nice thing is that all of my iPhone X code is in one overriding CSS file, but the downside is that I had to use plain CSS to get around sass-loader's limitation. It's certainly not the ideal solution, but it did allow us to move on.

**Comment by evilebottnawi** [comment]
@MikeSpencer42 PR welcome to `sass-loader`, if you solution will be simple and elegant we will merge it

**Comment by entioentio** [comment]
[sorry for spam, guys]
Big shout out to @dyatko for one of the most elegant fixes of all the times. Git bless you.

**Comment by evilebottnawi** [comment]
I don't know who disvote my answer, but it sass feature, don't know what we should do here
