### ISSUE TITLE
Switch to node-sass-chokidar?

### ISSUE THREAD

**Issue by sant123** [webpack-contrib/sass-loader#531]
[node-sass-chokidar](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc)

Why?

node-sass has been reported as having the following issues:

+ node-sass --watch has been reported to have performance issues in certain conditions when used in a virtual machine or with docker.

+ Infinite styles compiling [#1939](https://github.com/facebookincubator/create-react-app/issues/1939)

+ node-sass has been reported as having issues with detecting new files in a directory [#1891](https://github.com/sass/node-sass/issues/1891)

+ node-sass-chokidar is used here as it addresses these issues.

Thank you!

**Comment by evilebottnawi** [comment]
@sant123 it is loader, `node-sass-chokidar` is for watching (cli using), we don't provide watch mechanism, it is do `webpack` using [watchpack](https://github.com/webpack/watchpack) that already use `chokidar`. Can you describe problem in watch mode?

**Comment by sant123** [comment]
Sorry @evilebottnawi, I missed that detail. Closing.
