### ISSUE TITLE
@mixin not compiling

### ISSUE THREAD

**Issue by bostiq** [webpack-contrib/sass-loader#534]
so I'm new to sass so pls be gentle.. "it's my first time!" XD

didn't know where else to ask so here it is:

I copied this snippets straight from sass-lang.com and testing the compiler through sublime and mac osx terminal to make sure they don't output differently.. they don't.

this is the snippet that create the issue
```
@mixin large-text {
    font: {
        family: Arial;
        size: 20px;
        weight: bold;
        }
    color: #ff0000;
}

.page-title {
  @include large-text;
  padding: 4px;
  margin-top: 10px;
}
```

I made sure all indentation are consistent in the whole document and this returns
`Error: Invalid CSS after "": expected expression (e.g. 1px, bold), was "{" on line 38`

Now I took away graphs `{` put tabulations before instead than space.. put only one set and then tried the other... no matter what I do this doesn't compile.

What am I doing wrong???

**Comment by evilebottnawi** [comment]
@bostiq can you provide `webpack` config file? Seems you have something wrong in configuration, should be work

**Comment by bostiq** [comment]
I'd be happy to! how do I do it??? 😅

**Comment by evilebottnawi** [comment]
@bostiq `cat webpack.config.js` and post here

**Comment by bostiq** [comment]
Sorry mate.... I can't locate the file... where should it be?

**Comment by evilebottnawi** [comment]
@bostiq search in you repo/project `webpack.config.js` and past here, i don't known location in your project, default it is in root project directory, also can be place in `config` or `tools` directory

**Comment by bostiq** [comment]
dude.. not sure if I even have `webpack.config.js`
My project folder is set by Sublime and has not such file.
Sublimes than take advantage of sass previously installed via terminal.

**I really appreciate** you are trying to help me, but as I said I'm pretty new to this.

I know that to install sass, I had install ruby and gem, but I haven't got the slightest idea of what they do. I have a basic understanding that to run certain programs it's required a framework around or libraries... but that's all of my knowledge about it.

**Comment by evilebottnawi** [comment]
@bostiq hm, do you use `webpack`? How you build you project?

**Comment by bostiq** [comment]
for the moment I don't need to.. as I'm studying... I'm learning php, js, ..already know css pretty well.. and I want to learn sass
then I will put all pieces together and use a framework for it all

**Comment by evilebottnawi** [comment]
@bostiq seems you create issue in the wrong repository :smile: `sass-loader` require only for `webpack`, you issue related to `node-sass` (`sass/scss` - https://github.com/sass/node-sass), we only wrapper around `node-sass` to compile `sass/scss` for `webpack`

**Comment by bostiq** [comment]
awesome 'creating issues' is my job right now... gosh!
thanks for the help !
