### ISSUE TITLE
Simplify importing index.scss in an npm package

### ISSUE THREAD

**Issue by sindresorhus** [webpack-contrib/sass-loader#535]
Let's say an npm package named `foo` contains:

```
.
├── index.scss
├── package.json
```

Currently, I can use the following to import it:

```scss
@import "~foo/index";
```

But it would be nicer if we could just import it as:

```scss
@import "~foo";
```

Like with JS npm packages.

**Comment by evilebottnawi** [comment]
@sindresorhus thanks for issue, maybe we can use `sass` field from `package.json`, maybe we already support this :smile: Can you check this (https://github.com/webpack-contrib/sass-loader/blob/master/lib/loader.js#L40), `resolve` from `webpack` api. If it is not support we can fix in `webpack`

**Comment by sindresorhus** [comment]
I'm not sure what `sass` field you're referring to, but that's not really what I'm requesting here. I'm requesting the above to just work without any extra config in either package.json or webpack.

**Comment by michael-ciniawsky** [comment]
`config.resolve.mainFields = [ 'style' ]`. e.g `normalize.css` supports the [`pkg.style`](https://github.com/necolas/normalize.css/blob/master/package.json#L6) property, which is the most widely used approached I'm aware of atm. `style` could eventually be supported by `webpack` as a default `mainField`, but not sure.... or `sass-loader` programmatically passes  `options` to the resolver, the question is which...

**Comment by evilebottnawi** [comment]
@michael-ciniawsky need add tests for this :+1:

**Comment by TheLarkInn** [comment]
Only problem is not everyone will expect this behavior no? It would be a webpack/webpack@WebpackOptionsDefaulter change.

**Comment by xzyfer** [comment]
Note node-sass@5 will automatically support `@import "foo";` resolving to `@import "foo/index.scss";` if `foo` is a folder.

**Comment by pitpit** [comment]
Thanks to [mainFields](https://webpack.js.org/configuration/resolve/#resolve-mainfields)  in webpack.config.js, you can resolve file to import with "sass" or "style" fields from package.json of the npm package.

```
    module: {
      rules: [
        {
          test: /\.scss|\.css$/,
          use: [
              "style-loader",
              'css-loader',
              "sass-loader"
          ],
          resolve: {
            mainFields: ['sass', 'style']
          }
        }
      ]
    },
```

**Comment by evilebottnawi** [comment]
@pitpit Maybe will be good create issue about this in webpack, loader can't register own `resolve` options, this feature will fix also https://github.com/webpack-contrib/sass-loader/issues/556

**Comment by pitpit** [comment]
@evilebottnawi actually a loader can register its own resolve option. It does works 
 (webpack@4.20.0)

**Comment by evilebottnawi** [comment]
@pitpit how? Without hacks?

**Comment by pitpit** [comment]
no hacks. Look at this repo https://github.com/pitpit/saas-field

**Comment by evilebottnawi** [comment]
Need support `sass` field in `package.json` too
