### ISSUE TITLE
Style loader throw Module build failed: ModuleParseError: Module parse failed: Unexpected character '�' (1:0) error

### ISSUE THREAD

**Issue by ngohungphuc** [webpack-contrib/sass-loader#542]
I got this error when using sass-loader. If i have a scss file doesnt have external image link the loader will work perfectly.

![error](https://user-images.githubusercontent.com/13591213/36859500-20cc5d3e-1db1-11e8-9886-362990ecb08b.png)

**Comment by evilebottnawi** [comment]
@ngohungphuc don't duplicate issues
