### ISSUE TITLE
background-image: url(...) broken in browser console, might be related to missing sourcemap?

### ISSUE THREAD

**Issue by ishraqiyun77** [webpack-contrib/sass-loader#544]
Been trying to get assistance on SO regarding this, but getting no where.

The issue is related to `url()` which the `sass-loader` documentation predicts there might be. Followed the related documentation and am not able to produce the desired result. Essentially, I have a `background-image: url(...)` that isn't loading in the browser despite it point at the correct file and location. The image file is being moved into my `./bundles/img/` directory, the browser is looking at the file in the directory, it just isn't displaying it--it is a broken image icon.

My server does have 404 on these, so it might be related:

![image](https://user-images.githubusercontent.com/33135849/36914692-036550d2-1e03-11e8-9a9c-22c8fab36c4a.png)

My `webpack.config.js` should be producing any relevant sourcemaps:

```
var path = require('path');
var webpack = require('webpack');
var BundleTracker = require('webpack-bundle-tracker');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

const VENDOR_LIBS = [
  'axios', 'history', 'lodash', 'prop-types', 'react', 'react-dom', 'react-dropzone', 'react-redux', 'react-router-dom', 'react-router-redux', 'redux', 'redux-form', 'redux-thunk', 'reactstrap', 'react-responsive'
]

module.exports = {
  context: __dirname,

  entry: {
    app: '../react/index',
    vendor: VENDOR_LIBS
  },

  output: {
      path: path.resolve('./src/assets/bundles/'),
      filename: './js/[name].[chunkhash].js'
  },

  module: {
    rules: [
      { 
        loader: 'babel-loader',
        test: /\.js$/, 
        exclude: /node_modules/, 
        query: {
          presets: ["react", "es2015", "stage-1"]
        }
      },
      {
        test: /\.json$/,
        loader: ['json-loader'] 
      },
      {
        test: /\.png|jpg$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              publicPath: path.resolve('./src/assets/bundles/img/'),
              outputPath: 'img/',
              include: path.join(__dirname, 'assets/img'),
              
            }
          }
        ]
      },
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader',
              options: {
                sourceMap: true
              }
            },
            {
              loader: 'resolve-url-loader'            
            },
            {
              loader: 'sass-loader?sourceMap',
              options: {
                sourceMap: true
              }
            }
          ]
        })      
      },   
    ],
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      names: ['vendor', 'manifest']
    }),
    new BundleTracker({filename: './src/config/webpack-stats.json'}),
    new ExtractTextPlugin({filename: './css/[name].[hash].css', allChunks: true})
  ],
  resolve: {
    extensions: ['*', '.js', '.jsx', '.json', '.gif', '.png'],
  },
}
```

The produced CSS does have sourcemap sections in it.

This is the Sass I am working with:
```
@mixin cust-box($color) {
    background-color: $color;
    padding: 20px;
}

.products {
    .custom-blue-box {
        @include cust-box($blue);
        background-image: url('../img/bg_homebluebox.png');
        margin: 7px;
    }
}
```

This is my directory structure:
```
/app
    /src
        /assets
            /bundles
                /css
               /img
                    a65erg66.png // related to bg_homebluebox.png
                /js
            /img
                bg_homebluebox.png
            /scss
                login.scss
        /config
            webpack.config.js
        /react
            /containers
                /authentication
                    signin.js
            index.js // entry point
```
Here you can see it looking at the image but it isn't loading:

![image](https://user-images.githubusercontent.com/33135849/36914903-b2569a24-1e03-11e8-9c5a-4f1e3b6da588.png)

**Comment by evilebottnawi** [comment]
@ishraqiyun77 You use `dev-server`?

**Comment by ishraqiyun77** [comment]
@evilebottnawi Hi, I do not.

**Comment by evilebottnawi** [comment]
@ishraqiyun77 can you create minimum reproducible test repo?

**Comment by ishraqiyun77** [comment]
Will do. I have Django and webpack-loader running server side. Would you like that as well?

**Comment by evilebottnawi** [comment]
@ishraqiyun77 just add README with command how install and reproduce and all ok :+1:

**Comment by ishraqiyun77** [comment]
Ok, made the following repo. I didn't add Django because the issue is being reproduced just on the front-end: according to Network in the browser Console, it is "looking" right at the file, but it is not loading it.

https://github.com/ishraqiyun77/url-issue

**Comment by zemadz** [comment]
I'm pretty sure that this issue is caused  by `file-loader` which `useRelativePath` option behavior changed (was broken) with version 1.1.8. Try to install v1.1.7 and see if it helps temporarily.

**Comment by ishraqiyun77** [comment]
Hi, I gave it a shot, but still having the same issue.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ishraqiyun77** [comment]
Hi, I just wanted to check in for any other suggestions. I have been trying various other configurations over the past few days to no avail.

**Comment by ishraqiyun77** [comment]
Figured I'd try try linking to an external `http://` to see if it worked and it did. `background-image:  url('https://www.ocrmobile.com/images/2016/12/21/cloud.png` as a test. Guess I'll find a reliable place to store these until the app is moved into Azure.

**Comment by ishraqiyun77** [comment]
Yes, it does. Just tested it. I had to move images to a image hosting service so I could read them in from http:// instead of local.

**Comment by evilebottnawi** [comment]
Problem in `resolve-url-loader`, please try to update to latest version or avoid using this loader (they are very buggy). Thanks!
