### ISSUE TITLE
Splitting into multiple files

### ISSUE THREAD

**Issue by falconmick** [webpack-contrib/sass-loader#548]
Hey I've been trying to pull every ounce of performance into my web app and one of my biggest issues is that my css file could be better.

I've built my sites mobile first, so theoretically there is a TON of css that could be deffered from downloading via style's media attribute. So here's the goal:

create base.css which is all of the css minus my media queries
tablet.css which is the media > $mobile-max-width
desktop.css which is the media > $tablet-max-width

google page about render blocking css: https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css

Is this possible?

Cheers.

**Comment by evilebottnawi** [comment]
@falconmick yes, please use right configuration for `CCP` plugin (`webpack@3`) or use right configuration for `splitChunks` (`webpack@4`). Without example your config and application, i can't help. Also please use `stackpverflow/slack/gitter` for question. Thanks!
