### ISSUE TITLE
Compilation errors in calc()

### ISSUE THREAD

**Issue by McBenny** [webpack-contrib/sass-loader#549]
Hi,
I have a scss declaration with:
`height: calc(100vh - (50px + 2rem));`

The intended result according to the rule should be:
`height: calc(100vh - 50px - 2rem);`

But I get:
`height: calc(100vh - 50px + 2rem);`

The minus sign is not applied to the following elements in the parenthesis. Or maybe the parenthesis are just stripped.
I use sass-loader@^3.1.2 in my webpack config, in a React project.

**Comment by evilebottnawi** [comment]
@McBenny we don't change `sass` code or any changes (we just wrapper around `node-sass`), please open issue in `node-sass` or `libsass`
