### ISSUE TITLE
Loader is mixing up variables and creating properties

### ISSUE THREAD

**Issue by phiterf** [webpack-contrib/sass-loader#550]
I'm using Laravel Mix, which uses node-sass, which uses sass-loader(If I'm not mistaken).
I made those css variables in a sass file:

```
--sg-card-produto-hover-bg: #c3c3c3;
--sg-card-produto-hover-box-shadow: 0 0 15px rgba(0, 0, 0, .8);
--sg-card-produto-hover-border-width: 2px;
--sg-card-produto-hover-border-style: solid;
--sg-card-produto-hover-border-color: var(--sg-cor-botao);
```

When I run `npm run dev` or `npm run watch`, I'm getting the expected result:

![image](https://user-images.githubusercontent.com/12252332/37980202-fcc5160a-31c0-11e8-8640-5e646d4b2abb.png)

But when I run `npm run prod`, it seems like the loader is taking those variables and it thinks they are border properties that can be arranged as one `border` property, and creates this instead:

![image](https://user-images.githubusercontent.com/12252332/37980248-187d87ba-31c1-11e8-8050-6568a69f4665.png)

I don't know why this is happening but I don't think it should. Maybe the way it's trying to match the properties is ignoring css variables or something.

I have also put up a [question on StackOverflow](https://stackoverflow.com/questions/49516072/wrong-output-on-npm-run-prod).

**Comment by phiterf** [comment]
I renamed those variables that are getting mixed up like this:

    --sg-card-produto-hover-border_style: solid;
    --sg-card-produto-hover-border_width: 2px;
    --sg-card-produto-hover-border_color: var(--sg-cor-botao);

But then, it mixed up the previous variables:

![image](https://user-images.githubusercontent.com/12252332/37981110-1c7b13e4-31c3-11e8-98ae-ebca58d88bbd.png)

I noticed that it's mixing up only the last ocurrences of when it detects an expanded property.

So I used this quick fix:

    --sg-card-produto-bg: #d3d3d3;
    --sg-card-produto-border-width: 2px;
    --sg-card-produto-border-style: solid;
    --sg-card-produto-border-color: #222;
    
    --sg-card-produto-hover-bg: #c3c3c3;
    --sg-card-produto-hover-box-shadow: 0 0 15px rgba(0, 0, 0, .8);
    --sg-card-produto-hover-border-style: solid;
    --sg-card-produto-hover-border-width: 2px;
    --sg-card-produto-hover-border-color: var(--sg-cor-botao);
  
    border-style: none;
    border-width: 0;
    border-color: transparent;

And this is the result: 
![image](https://user-images.githubusercontent.com/12252332/37981168-45cf49cc-31c3-11e8-81f6-e70f5e1a49fd.png)

Weird, no?

**Comment by evilebottnawi** [comment]
@phiterf do you use `cssnano` for minification?

**Comment by phiterf** [comment]
I don't think I do. How do I check? As I said, I'm using Laravel Mix so it's all "automatic".

Those are my dependencies:

```
"devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "browser-sync": "^2.18.8",
    "browserify": "14.4.0",
    "cross-env": "^5.0.5",
    "laravel-mix": "^2.1.11",
    "node-sass": "^4.8.3",
    "sass-loader": "^6.0.7",
    "webpack": "^3.11.0"
  },
  "dependencies": {
    "axios": "^0.16.2",
    "bootstrap": "^4.0.0-alpha.6",
    "bootstrap-tagsinput": "^0.7.1",
    "bootstrap-vue": "^2.0.0-rc.1",
    "chart.js": "^2.7.0",
    "ckeditor": "^4.8.0",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "jquery-ui": "1.10.x",
    "moment": "^2.18.1",
    "popper.js": "1.12.5",
    "postcss": "^6.0.12",
    "select2": "^4.0.6-rc.1",
    "store": "^2.0.12",
    "toastr": "^2.1.4",
    "urlify": "^0.3.6",
    "vue": "^2.5.13",
    "vue-template-compiler": "^2.5.13",
    "webpack-cli": "^2.0.13"
  },
```

**Comment by evilebottnawi** [comment]
@phiterf you deps is hell :smile: `postcss` in `dependencies`, why? :smile: Can you create minimum reproducible test repo or try to disable `cssnano` in your config and check again?

**Comment by phiterf** [comment]
Yeah I'm new to this whole webpack/node thing, this was put there by the previous guy and I decided not to touch it too much.

I'm not sure how I could disable cssnano, but I saw that Laravel Mix allows for extra options. I'll see what I can do.

**Comment by evilebottnawi** [comment]
I confirm this is problem in `cssnano@3`, you can use `cssnano@4-rc.2`, there this issue already fixed. Thanks!
