### ISSUE TITLE
Imports should be evaluated relative to the imported file

### ISSUE THREAD

**Issue by mkampmey** [webpack-contrib/sass-loader#560]
Right now I am trying to import jquery ui styles into my module. So I have jquery ui as a dependency and I use this code to import the css:
`@import "~jquery-ui/themes/base/all";`
Unfortunately the file "all.css" depends on other css files in the same folder. But instead of trying to find those files there, the sass-loader looks for them in my custom module from where I execute the script. Shouldn't import statement always be evaluated relative to the file which gets imported?

**Comment by evilebottnawi** [comment]
@mkampmey can you create minimum reproducible test repo with some comments?

**Comment by kaisermann** [comment]
Have you tried https://github.com/bholloway/resolve-url-loader? ([see the third bullet](https://github.com/webpack-contrib/sass-loader#problems-with-url))

**Comment by evilebottnawi** [comment]
@mkampmey `sass-loader` doesn't rewrite `url` and other assets in source file, please use loader for this, also many libraries allow change this through variable (example `bootstrap`). Sorry, it is out of scope `sass-loader`

**Comment by evilebottnawi** [comment]
You can request new feature (rewriting url assets) in `sass` (if it is approved and merged, it is shipped in `node-sass/dart-sass/other-sass` and allow rewrite url using function as option for `sass-loader`.
