### ISSUE TITLE
Handle node-sass "Missing binding" Error

### ISSUE THREAD

**Issue by DotJoshJohnson** [webpack-contrib/sass-loader#561]
Just a suggestion to handle the "Missing binding" error if thrown by node-sass. Currently, you'll get the following message: `` `sass-loader` requires `node-sass` >=4. Please install a compatible version.``. Letting the user know about the missing binding error would make the failure a bit clearer.

**Comment by evilebottnawi** [comment]
@DotJoshJohnson PR welcome

**Comment by evilebottnawi** [comment]
Fixed in https://github.com/webpack-contrib/sass-loader/pull/562
