### ISSUE TITLE
Error: `sass-loader` requires `node-sass` >=4 but node-sass is already at v4

### ISSUE THREAD

**Issue by SundownDEV** [webpack-contrib/sass-loader#563]
ran `encore dev --watch`

get this error :

~~~
Module build failed: ModuleBuildError: Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
    at Object.sassLoader (/var/www/VulcanoCMS/node_modules/sass-loader/lib/loader.js:31:19)
    at runLoaders (/var/www/VulcanoCMS/node_modules/webpack/lib/NormalModule.js:195:19)
    at /var/www/VulcanoCMS/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/VulcanoCMS/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/var/www/VulcanoCMS/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/var/www/VulcanoCMS/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at /var/www/VulcanoCMS/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at /var/www/VulcanoCMS/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:70:14
    at process._tickCallback (internal/process/next_tick.js:112:11)
~~~

but node-sass is at v4.8.3 in package.json : 

~~~
{
    "devDependencies": {
        "@symfony/webpack-encore": "^0.20.1",
        "node-sass": "^4.8.3",
        "sass-loader": "^7.0.1"
    },
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
        "dev-server": "encore dev-server",
        "dev": "encore dev",
        "watch": "encore dev --watch",
        "build": "encore production"
    },
    "dependencies": {
        "bootstrap": "^4.1.0",
        "jquery": "^3.3.1"
    }
}
~~~

already tried deleting node-modules folder and package-lock.json

**Comment by evilebottnawi** [comment]
@SundownDEV `ls -l node_modules`

**Comment by SundownDEV** [comment]
Of course the folders exist.

**Comment by evilebottnawi** [comment]
@SundownDEV looks like you don't have `node_modules/node-sass` directory with package

**Comment by evilebottnawi** [comment]
@SundownDEV `rm -rf node_modules && npm/yarn cache clear --force && npm/yarn install`

**Comment by evilebottnawi** [comment]
@SundownDEV looks like a bug in `npm`, prove your `node/npm` version

**Comment by SundownDEV** [comment]
Fixed with https://github.com/npm/npm/issues/19989

but I get the same error on node-sass : 

~~~
Module build failed: ModuleBuildError: Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
~~~

**Comment by SundownDEV** [comment]
Fixed by deleting node_modules, package.json packages-lock.json and installing each package one by one on npm 5.6.0. Also fixing an node-sass installation issue using `sudo`.

**Comment by gencay** [comment]
I had the exact same problem. It was because of a cached version of node-sass.
This solution worked for me:
- Remove the node-sass from npm-cache (For Windows users %userprofile%\AppData\Roaming\npm-cache)
- Remove node-sass from your project's node_modules dir
- Do npm install to reinstall node-sass

**Comment by NicolasLetellier** [comment]
I've also got the same error when upgrading node from v6.12 to v8.11.1 (now npm v5.6.0):
`Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.`

This worked for me: `npm rebuild node-sass`

**Comment by 2WheelCoder** [comment]
I got this consistently even after clearing out node_modules and yarn's cache. Upgraded from node 6.13.1 to 8.11.1, did `yarn remove node-sass and ` and `yarn add node-sass` and everything worked again.

**Comment by abraham** [comment]
On newer version of npm you can probably fix this with `npm ci`.

**Comment by simeyla** [comment]
This is going to be a popular topic with Angular 6 now requiring node 8.
Is there any benefit to running `npm rebuild` `https://docs.npmjs.com/cli/rebuild` for all packages - or is this just needed for sass?

**Comment by alejonext** [comment]
The soluctions... All time is fails!

* `Delete`  the proyect is "new", is starts!! no exist de `node_modules`
* `rebuild` exist many problems in when run root. And `"postinstall" : "npm rebuild"`. Well, thats is not a solution.

**Comment by searene** [comment]
I fixed it by downgrading node from 10.0.0 to 8.9.4

```bash
nvm install 8.9.4
nvm use 8.9.4

# set v8.9.4 as the default version
nvm alias default 8.9.4
```

**Comment by deftomat** [comment]
The same here, node 8.11.2 and nothing helps. I've tried to clear cache and upgrade all packages and still nothing.

**Comment by matiishyn** [comment]
Having exactly the same issue here
`sass-loader` doesn't work with node10
and another module requires node>9
What should I do?
plz help

**Comment by NigelThorne** [comment]
I was getting this issue, so I added some debug logging to sass-loader.

For me the problem was the following code: 
```
function sassLoader(content) {
    if (asyncSassJobQueue === null) {
        let sass;
        let sassVersion;

        try {
            sass = require("node-sass");
            sassVersion = /^(\d+)/.exec(require("node-sass/package.json").version).pop();
        } catch (e) {
            throw new Error(   //  <---- this swallows the exception.
                ""+e.message+" "+require("node-sass/package.json").version+" - `sass-loader` requires `node-sass` >=4. Please install a compatible version."
            );
        }
   ...
```
I got the following errors... 
```
Module build failed: Error: Missing binding f:\code\commitment_coach\code\vue-firebase-tutorial\node_modules\node-sass\vendor\win32-x64-48\binding.node       
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x                                                              
                                                                                                                                                              
Found bindings for the following environments:                                                                                                                
  - Windows 64-bit with Node.js 8.x                                                                                                                           
```

So for me... I just upgraded node to v8 and I was good.

**Comment by Oliboy50** [comment]
@SundownDEV reopen the issue please, this is a real issue
```
Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
front_1  |     at Object.sassLoader (/home/node/app/node_modules/sass-loader/lib/loader.js:31:19)
```

**Comment by Oliboy50** [comment]
after downgrading to `sass-loader@6.0.7`, I had a clearer error:

```
front_1  | Module build failed: Error: Missing binding /home/node/app/node_modules/node-sass/vendor/linux-x64-57/binding.node
front_1  | Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x
front_1  | 
front_1  | Found bindings for the following environments:
front_1  |   - OS X 64-bit with Node.js 8.x
front_1  | 
front_1  | This usually happens because your environment has changed since running `npm install`.
front_1  | Run `npm rebuild node-sass --force` to build the binding for your current environment.
```


Seems like my issue was to run `npm install` first on my Mac before building the Docker image based on Debian then binding `node_volumes` from the Mac to the Debian container using a `volume`


... I'm still looking for a better volume system though ...

**Comment by kolkov** [comment]
`npm rebuild node-sass` fixed it for me. Thanks!

**Comment by SundownDEV** [comment]
Reopening the issue until it gets fixed.

Quick fix solutions : 
- `npm rebuild node-sass`
- `yarn remove node-sass` and `yarn add node-sass`
- Upgrade node, it will downgrade npm to 5.6.0, upgrade it to the latest version, then `npm install` (reference:https://github.com/npm/npm/issues/19989#issuecomment-371739104)
- Remove node-sass from global npm-cache, remove node-sass from node_modules dir, then `npm install` to reinstall it (reference:https://github.com/webpack-contrib/sass-loader/issues/563#issuecomment-384751280)

**Comment by Oliboy50** [comment]
I think that the principal issue here is that `sass-loader 7.x` displays a wrong error message:

```
Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
```

when `node-sass 4.x` is installed but unusable (e.g. when it is compiled for another environment)

Whereas `sass-loader 6.x` displays a clearer and more accurate error message:

```
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x
...
Run `npm rebuild node-sass --force` to build the binding for your current environment
```

(see https://github.com/webpack-contrib/sass-loader/issues/563#issuecomment-390435456 for full output)

**Comment by evilebottnawi** [comment]
Feel free to send a PR with showing original errors.

**Comment by Tenmak** [comment]
Add to add `    "node-sass": "^4.9.0",` to devDependencies to avoid the issue.

**Comment by mauriciopiber** [comment]
The point is, on any previous error during installation, even if install successful afterwards on retype, sass-node will fail. If occurs any, remove node_modules and run npm install from scratch instead of just fix the command and rerun.

**Comment by iansamz** [comment]
`npm rebuild node-sass` worked for me too.

**Comment by tcrite** [comment]
I'm having this same issue...which I was able to fix locally, but is there a workaround for this issue from a build server?

**Comment by antonevane** [comment]
I moved back to very old npm 3.10.10  that has been in our build for a while  and it works like a charm.
