### ISSUE TITLE
Version 7.x imports js files by the same name before sass files

### ISSUE THREAD

**Issue by webark** [webpack-contrib/sass-loader#572]
I have an import statement of `@import 'libraries/redactor';` with files of `libraries/redactor.js` and `libraries/redactor.scss`. On version 6.0.7, it correctly loads the scss file, but on 7.0.1, it tries to load the `libraries/redactor.js` instead, and errors out.

**Comment by evilebottnawi** [comment]
Related https://github.com/webpack-contrib/sass-loader/issues/556
