### ISSUE TITLE
Doesn't respect `context` webpack option

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/sass-loader#578]
/cc @jhnns what do you think about this? In many case people use `includePaths: ["src"]` to avoid using long imports like `@import "src/path/to/my/scss";`. Other loader like `file-loader`/`css-loader`/etc support `context`. It is possible solve?

**Comment by jhnns** [comment]
The sass-loader does already support using the [`resolve.modules`](https://webpack.js.org/configuration/resolve/#resolve-modules) option. That should be enough, I guess? :)

The `context` at the `file-loader` has a different purpose (it's about the output folder) and I don't find a `context` option at the `css-loader`.

**Comment by evilebottnawi** [comment]
@jhnns hm, looks no.
**webpack.config.js**
```js
module.exports = {
  resolve: {
    extensions: [
      ".scss",
      ".js"
    ]
    modules: ["node_modules", "src"] 
  }
};
```

**app.scss**
```scss
@import "shared/styles/main";
```

**src/shared/styles/main.scss**
```scss
a {
  color: red;
}
```

Output:
```
@import "shared/styles/main";
^
      File to import not found or unreadable: shared/styles/main.
```

**Comment by evilebottnawi** [comment]
My problem, invalid configuration
