### ISSUE TITLE
Property must be followed by a ':'

### ISSUE THREAD

**Issue by drullo** [webpack-contrib/sass-loader#582]
Disclaimer... I am new to Sass!

The following Sass code produces the error:
`div {
    border: {
        style: solid;
        width: 1px;
        color: black;
    }
}`

`Property "border" must be followed by a ':'`

I am working in Angular 6 and my sass-loader version is 7.0.3.

I am confused by the error because border is indeed followed by a colon and this syntax matches many examples that I've found online.

**Comment by evilebottnawi** [comment]
@drullo looks you have invalid scss syntax, we just wrapper around node-sass and don't change your code, this error from `node-sass`. Can you create minimum reproducible test repo?
