### ISSUE TITLE
`Module build failed` error because undefined variables, etc. regardless of the files being imported

### ISSUE THREAD

**Issue by acstll** [webpack-contrib/sass-loader#586]
I have a main.scss file in which I only `@import` other files. Some of these files use variables, mixins, etc. being defined in some other files. Regular SASS stuff.

When trying to build I get an error like the following: 

```
ERROR in ./templates/scss/generic/_global.scss (./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./templates/scss/generic/_global.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

    font-size: $size-1;
              ^
      Undefined variable: "$size-1".
```

Facts:
- All those things missing are not really missing, and they're being imported correctly from main.scss
- Building with `node-sass` directly works without problems (`npx node-sass ...`)
- I get the error whether the files are being imported or not (I think webpack reads and parses the entire directory where the entry is located)
- I tried removing PostCSS, it's the same

Here's the configuration related:

```js
const cssRules = {
    test: /\.css|.scss$/,
    use: [
        isProd() ? MiniCssExtractPlugin.loader : 'style-loader',
        {loader: 'css-loader', options: {importLoaders: 1}},
        {
            loader: 'postcss-loader',
            options: {
                config: {
                    path: path.join(__dirname, '../config/postcss.config.js')
                }
            }
        },
        {loader: 'sass-loader', options: {importer: sassGlobImporter()}}
    ]
};
```

Any ideas? could I be missing anything in the configuration?

**Comment by evilebottnawi** [comment]
@acstll looks you don't have `$size-1`, without minimum reproducible test repo i can't help

**Comment by acstll** [comment]
I'm going to close this for now. The repo I created specifically to reproduce the bug, works. It's all the same expect for some JS configuration that I left out, so I'm going to explore it further until I can reproduce and isolate the bug.

Thanks again!
