### ISSUE TITLE
node-sass should be a dependency or a peerDependency, not a devDependency?

### ISSUE THREAD

**Issue by veltman** [webpack-contrib/sass-loader#590]
Previously, `node-sass` was in both `peerDependencies` and `devDependencies`. In https://github.com/webpack-contrib/sass-loader/pull/533 it was removed from `peerDependencies`. Now it's only listed in `devDependencies`, so the package only works if dev dependencies are installed and there's no warning if it's missing. Shouldn't `node-sass` be in `dependencies` instead, so it's always installed even in production mode? The package requires it to function, it's not just there for development purposes.

**Comment by evilebottnawi** [comment]
@veltman you should add `node-sass` to you dependencies, we write about this in docs, it is require to use `sass-loader` in boilerplate such as `create-facebook-app` and etc. Also we have PR with supporting `dart-sass`, i.e. it will be allow to install `dart-sass` instead `node-sass`. Also we throw error if `node-sass` not found.

**Comment by veltman** [comment]
I'm confused about this. The docs say:

"The sass-loader requires node-sass and webpack as peerDependency."

But this isn't true anymore, node-sass was removed as a peerDependency (https://github.com/webpack-contrib/sass-loader/pull/533)

It seems like it should EITHER be in `peerDependencies` or `dependencies`.

Currently, if the module is installed without dev dependencies you won't get a warning and the module will not work.

if `node-sass` is moved back to `peerDependencies`, then at least installing the module without installing `node-sass` will produce a warning.

If `node-sass` moved to `dependencies`, then the module will work, at the possible expense of duplicate installs.

Am I missing something? Shouldn't `devDependencies` be dependencies that are only needed for running tests or recompiling the module, not dependencies that the module will always crash without?
