### ISSUE TITLE
Undefined operation: times

### ISSUE THREAD

**Issue by obabichev** [webpack-contrib/sass-loader#592]
Hallo,

I have a problem with undefined operation:
>ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js?{"outputStyle":"expanded","includePaths":["/home/obabichev/www/project/~/compass-mixins/lib"]}!./scss/project/default.scss
>Module build failed: 
>    @return  0.2126 * $R + 0.7152 * $G + 0.0722 * $B;
>            ^
>      Undefined operation: "0.2126 times pow(1, 2.4)".
>      in /home/obabichev/www/project/scss/misc/mixins/_colorFunctions.scss (line 20, column 14)
> @ ./scss/project/default.scss 2:14-135

I looked through sass-loader and node-sass and if I am right this is problem of old versions of node-sass and it was fixed in version 4.8.0 of node-sass,

Please, is it possible to fix it in sass-loader too or to explain what can I do wrong.

My webpack settings:
```javascript
{
        test: /\.scss$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader'
          },
          {
            loader: 'sass-loader',
            options: {
              outputStyle: 'expanded',
              includePaths: [
                path.resolve(__dirname, './node_modules/compass-mixins/lib')
              ]
            }
          }
        ]
      }
```
node version : v4.8.4

Best regards,
Babichev Oleg

**Comment by evilebottnawi** [comment]
We don't modify original source of sass/scss/css files, you have invalid `scss` syntax, you can see this in your error. If you think it is bug `node-sass` please open issue in their repo, thanks!
