### ISSUE TITLE
Dart Sass doc error?

### ISSUE THREAD

**Issue by philwareham** [webpack-contrib/sass-loader#600]
Hi!

With the new `implementation` option to allow Dart Sass, shouldn't it be?:

    implementation: require('dart-sass'),

Instead of:

    implementation: require('sass'),

That got it working for me.

**Comment by evilebottnawi** [comment]
@philwareham please send PR, thanks

**Comment by GouJieShinee** [comment]
@philwareham how you resolved this problem? i set implementation: require('sass'), it's dosen't work.when i use @use at-rule , it error: Unknown at rule @usescss(unknownAtRules).

**Comment by philwareham** [comment]
@GouJieShinee I use this...

    {
        loader: 'sass-loader',
        options: {
            implementation: require('sass'),
            sassOptions: {
                outputStyle: 'expanded'
            }
        }
    }

...but I don't use `@use` rules - so can't say if your problem is directly related to sass-loader.

**Comment by GouJieShinee** [comment]
use your vue.config.js code, error: ERROR  Invalid options in vue.config.js: "loader" is not allowed. "options" is not allowed. (my vue/cli version is 3.12.0).And, you just use sass to compile scss file,and don't use it's new module system?

**Comment by GouJieShinee** [comment]
my vue.config.js code is: 
`
const sass = require('sass');
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        implementation: sass,
      },
    },
  },
};
`

and my package.json is:
`
"sass": "^1.23.0",
    "sass-loader": "^8.0.0",
`
