### ISSUE TITLE
 ERROR in ./src/sass/app.scss (./node_modules/css-loader??ref--7-2!./node_modules/sass-loader/lib/loader.js!./src/sass/app.scss) Module build failed (from ./node_modules/sass-loader/lib/loader.js):

### ISSUE THREAD

**Issue by halilertekin** [webpack-contrib/sass-loader#604]
`ERROR in ./src/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

    @include aligner(between, center);
            ^
      No mixin named aligner
      in /var/www/html/xxx/src/sass/layout/header.scss (line 9, column 14)
    at runLoaders (/var/www/html/xxx/node_modules/webpack/lib/NormalModule.js:286:20)
    at /var/www/html/xxx/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/html/xxx/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/var/www/html/xxx/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/var/www/html/xxx/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/var/www/html/xxx/node_modules/neo-async/async.js:7974:18)
    at options.error (/var/www/html/xxx/node_modules/node-sass/lib/index.js:294:32)
 @ ./src/sass/app.scss

ERROR in ./src/sass/app.scss (./node_modules/css-loader??ref--7-2!./node_modules/sass-loader/lib/loader.js!./src/sass/app.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

    @include aligner(between, center);
            ^
      No mixin named aligner
      in /var/www/html/xxx/src/sass/layout/header.scss (line 9, column 14)
 @ ./src/sass/app.scss 2:14-131
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--7-2!node_modules/sass-loader/lib/loader.js!src/sass/app.scss:

    ERROR in ./src/sass/app.scss (./node_modules/css-loader??ref--7-2!./node_modules/sass-loader/lib/loader.js!./src/sass/app.scss)
    Module build failed (from ./node_modules/sass-loader/lib/loader.js):

        @include aligner(between, center);
                ^
          No mixin named aligner
          in /var/www/html/xxx/src/sass/layout/header.scss (line 9, column 14)
Child html-webpack-plugin for "index.html":
     1 asset`

-Node v6.14.4
-npm v3.10.10

I have a problem. How we can fix please help me. I am dealing with this problem for a long time.

**Comment by bencergazda** [comment]
@halilertekin It looks like your configuration is ok. The error message says you are calling the **aligner** mixin, but it is not defined yet at that point of the `header.scss`. You should check where do you declare the `@mixin aligner`, it needs to be declared in the header.scss file before line 9 (or you should import the file containing the mixin declaration somewhere earlier in the code).

**Comment by evilebottnawi** [comment]
@halilertekin Read @bencergazda message, he is right, we just wrapper around `node-sass/sass`, we don't change your code
