### ISSUE TITLE
Wrapping @page selector makes url() lookup fail

### ISSUE THREAD

**Issue by Lesik** [webpack-contrib/sass-loader#610]
Hey,

in a simple project with the following structure
```
project/
├── assets
│   ├── images
│   │   └── Cathédrale_Marie-Rheine-du-Monde_by_Thierry_Pon.jpg
│   ├── js
│   │   └── test.js
│   └── scss
│       ├── subdirectory
│       │   └── stylesheet-with-url.scss
│       ├── style.scss
│       └── stylesheet-with-at.scss
└── webpack.config.js
```
and the files `test.js`
```js
import '../scss/style.scss';
```
`style.scss`
```scss
#wrapper {
  @import 'stylesheet-with-at';
  @import 'subdirectory/stylesheet-with-url';
}
```
`stylesheet-with-at.scss`
```scss
@page {
  size: 1px;
}
```
and `stylesheet-with-url.scss`
```scss
.test {
  background-image: url('../../images/Cathédrale_Marie-Rheine-du-Monde_by_Thierry_Pon.jpg');
}
```

I get the following error:
```
ERROR  Failed to compile with 1 errors

This relative module was not found:

* ../../images/Cathédrale_Marie-Rheine-du-Monde_by_Thierry_Pon.jpg in ./node_modules/css-loader??ref--4-2!./node_modules/resolve-url-loader??ref--4-3!./node_modules/sass-loader/lib/loader.js??ref--4-4!./assets/scss/style.scss
```

Please note that adding a webpack entry for `style.scss` instead of `test.js` results in the same error. So it doesn't matter if `style.scss` is imported by `test.js` or compiled directly.

---

Workarounds so far:
- move `stylesheet-with-url.scss` out of the `subdirectory`
- remove the `@page` selector from `stylesheet-with-at.scss`

Thus I assume this must be related to the `@page` selector. Please see [my minimal working sample](https://github.com/Lesik/sass-bug-test) (run `yarn install` and then `yarn encore dev`).

---

## Without Webpack (compiling with node-sass)

If I compile `style.scss` directly, without Webpack, there seems to be no error. Please check the branch [`without-webpack`](https://github.com/Lesik/sass-bug-test/tree/without-webpack) (run `yarn install` and then `./test.sh`).

I assume this is a bug. Thanks in advance for your help!

**Comment by evilebottnawi** [comment]
@Lesik Thanks for issue, very very strange, we just wrapper around `node-sass`. Are you sure it is bug `sass-loader`? Maybe problem in `postcss-loader/css-loader`. Anyway i can look on this in near future. Feel free to investigate.

**Comment by evilebottnawi** [comment]
Problem in `resolve-url-loader`, please create issue in their repo
