### ISSUE TITLE
Pb Background Url() when Scss is compiled - Webpack Encore/Symfony 3.4

### ISSUE THREAD

**Issue by Hery-Rs** [webpack-contrib/sass-loader#611]
Hello This is my first Issue :-)

Background Url() in my compiled scss doesn't appear.
I follow Sass Loader documentation, and i try to look at other Issues (like [#276](https://github.com/symfony/webpack-encore/issues/276)) related the same Pb, but I don't understand how to resolve it with my configuration :

```
// package.json
{
  "devDependencies": {
    "@symfony/webpack-encore": "^0.20.1",
    "bootstrap": "^4.1.3",
    "css-loader": "^1.0.0",
    "node-sass": "^4.9.3",
    "popper.js": "^1.14.4",
    "resolve-url-loader": "^2.3.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.0"
  },
  "dependencies": {
    "jquery": "^3.3.1",
    "webpack-notifier": "^1.6.0"
  },
  "name": "pde2018_project",
  "version": "1.0.0",
  "main": "index.js",
  "author": "hery",
  "license": "MIT"
}
```
```

// webpack.config.js
var Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('web/build/')
    .setPublicPath('/web')

    .addEntry('app', './assets/js/app.js')
    .addEntry('lightboxJs', './assets/js/lightbox.js')
    .addEntry('hamburger', './assets/js/hamburger.js')

    .addEntry('base', './assets/scss/base.scss')
    .addEntry('accueil', './assets/scss/accueil.scss')
    .addEntry('portrait', './assets/scss/portrait.scss')
    .addEntry('lightboxCss', './assets/scss/lightbox.scss')

    .autoProvidejQuery()
    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSassLoader()

module.exports = Encore.getWebpackConfig();
```

```
// lightbox.scss
.lb-data .lb-close {
...
  background: url(../images/close.png);
...
}
```

The Url is compiled to ---------> background: url(/web/images/close.2299ad0b.gif);

How can i set my "webpack.config.js" ? I also tried to install "[Resolve Url loader](https://github.com/bholloway/resolve-url-loader)", but how to adapt it and where can i insert the example of documentation in my code ?

Thanks I'm Newbieeee :-)

**Comment by evilebottnawi** [comment]
@Hery-Rs please create minimum reproducible test repo

**Comment by Hery-Rs** [comment]
@evilebottnawi  here [pde2018_project](https://github.com/Hery-Rs/pde2018_project) my repo.

On page "portraits" (localhost:8000/portraits), when you click on portfolio images, a lightbox appear. But normally there is "loading", "close", "next" and "prev" images.

**Comment by evilebottnawi** [comment]
@Hery-Rs look problem in `@symfony/webpack-encore`, i am not familiar with this package, maybe better create issue in their repo?

**Comment by Hery-Rs** [comment]
Ok thanks @evilebottnawi

**Comment by ebuildy** [comment]
Hi @Hery-Rs , with encore you can change the images loader options like this:

```
.configureLoaderRule('images', (loaderRule) => {
    loaderRule.options.esModule = false;
  })
```
