### ISSUE TITLE
Confused about usage.

### ISSUE THREAD

**Issue by andyhasit** [webpack-contrib/sass-loader#612]
According to the README, this package:

> Compiles Sass to CSS

However none of the example seem to actually do this, and I've also been told on [stackoverflow](https://stackoverflow.com/questions/52279931/why-would-i-want-to-integrate-css-into-javascript/52280683?noredirect=1#comment91527989_52280683) that it doesn't actually do this.
 
I've tried various loaders and the output is either CSS as JavaScript, **which is not what I want**.

Here is my config:

    ```javascript
    module: {
      rules: [
        {
          test: /\.(sa|sc)ss$/,
          use: [
            "style-loader", // creates style nodes from JS strings
            "css-loader", // translates CSS into CommonJS
            "sass-loader" // compiles Sass to CSS, using Node Sass by default
          ]
        }
      ]
    }
    ```
If I comment out  `style-loader` I still get Js output. If I comment out `css-loader` I get this error so presumably I do need one of the others:

> Module parse failed: Unexpected token (1:4)
  You may need an appropriate loader to handle this file type.

I also spotted this in the readme:

> Use the css-loader or the raw-loader to turn it into a JS module and the mini-css-extract-plugin to extract it into a separate file. 

But I don't think that's what applies to my scenario (or the readme would surely say something like "If you just want to convert sass to css (default usage) then use these other two plugins like so (demo below).")

There is an example of using MiniCssExtractPlugin for production, but this seems to chunk files, which is also not what I want. Basically, I *just* want to compile Sass to CSS, which is what this package says it does.

**Comment by evilebottnawi** [comment]
@andyhasit `css-loader` convert css to js, how it is related to sass-loader?

**Comment by andyhasit** [comment]
@evilebottnawi how does that answer any of my questions?

**Comment by michael-ciniawsky** [comment]
@andyhasit The `sass-loader` does indeed just transpile SASS/SCSS => CSS but `webpack` relies on the JS module system to bundle it and that's why you either need the `raw-loader` or the `css-loader` (recommended) to make it work with `webpack`. What is your use case? Why is that an issue for you? Maybe a simple task (e.g gulp/CLI) would be sufficient in your case?

**Comment by andyhasit** [comment]
@michael-ciniawsky that makes more sense with you explaining it that way. I was explicitly asked to use webpack to handle all the ES6 & SASS compiling and bundling for a django project as a replacement to django-pipeline. 

There are multiple sass and es6 files which need compiled & concatenated to various end output files, and the idea was to manage the whole thing with one webpack config file, because that's what we were recommended, but it seems this really isn't what webpack is for.

I think I'm going to use rollup and npm's sass instead.

I still think the readme should be updated to make it a bit clearer what this package does.

**Comment by michael-ciniawsky** [comment]
> that makes more sense with you explaining it that way. I was explicitly asked to use webpack to handle all the ES6 & SASS compiling and bundling for a django project as a replacement to django-pipeline.

I never used `django-pipeline` but in general If you don't use a component based approach like e.g `react` you don't really need to go extra lengths for CSS here. A simple gulp/grunt/cli task and adding a link to the HTML template should be sufficient. `webpack` is entirely different from the traditional workflow and not a per se drop in replacement for e.g `gulp` without underlying architectural changes to the application. 

> There are multiple sass and es6 files which need compiled & concatenated to various end output files, and the idea was to manage the whole thing with one webpack config file, because that's what we were recommended, but it seems this really isn't what webpack is for.

As mentioned it depends on the application structure. `webpack` builds a dependency graph based on JS Module syntax and semantics (`import/export`) while tools like `gulp` rely on the file tree. The latter is definitely easier for CSS handling

> I think I'm going to use rollup and npm's sass instead.

If JS and CSS is 'cleanly'  separated that is a good way to go yes.

> I still think the readme should be updated to make it a bit clearer what this package does.

Well... at the point one reaches the `sass-loader` README for the first time it is more or less assumed that the basic webpack concepts are already 'known' to keep the README focused on the package itself. For a general overview of `webpack` better head to https://webpack.js.org with time and passion in case you need it :)
