### ISSUE TITLE
Cannot import files when using a resource query

### ISSUE THREAD

**Issue by dimitarnestorov** [webpack-contrib/sass-loader#615]
![image](https://user-images.githubusercontent.com/8790386/45590214-4a44cf80-b93c-11e8-9d7a-20c227586155.png)

If I omit `?external` it imports the image but inline, forcing me to use data URIs.

**Comment by evilebottnawi** [comment]
@dimitarnestorov can you create minimum reproducible test repo?

**Comment by dimitarnestorov** [comment]
Sure.
https://github.com/dimitarnestorov/sass-loader-resource-query-test

**Comment by evilebottnawi** [comment]
Problem in `extract-loader`, better use `MiniCssWebpackPlugin`
