### ISSUE TITLE
Webpack alias and import throw http_server error

### ISSUE THREAD

**Issue by shunxing** [webpack-contrib/sass-loader#618]
Hi guys

I'm struggling with the import in sass file. I'd like to import a sass file through an alias created in webpack.

**product-bis.sass**
` @import "~app/pages/product.scss"; ` 

**webpack.conf.js** 
```
resolve: {
    alias : {
	'app': resolve(__dirname, 'src', 'app'),
    }
}
```

When i'm using webpack hot-reload, there is no problem, it just imports the right file (i can see the imported css). However when i stop the server and try to build again, i'm able to build but when i try to access the URL, it just crashes throwing this error

```
RangeError: Invalid status code: 1
    at ServerResponse.writeHead (_http_server.js:194:11)
    at ServerResponse._implicitHeader (_http_server.js:185:8)
    at write_ (_http_outgoing.js:632:9)
    at ServerResponse.end (_http_outgoing.js:751:5)
```

When i remove the alias and use relative path to import my sass file, the build works fine and it doesn't crash

has anyone get an issue like that and is there a solution to use alias instead of relative path ?

**Comment by evilebottnawi** [comment]
@shunxing please create minimum reproducible test repo
