### ISSUE TITLE
Fail to use only to produce CSS from SCSS

### ISSUE THREAD

**Issue by JavaPantry** [webpack-contrib/sass-loader#619]
Hi all
I'm trying to use 2 modules in webpack.config
Along with building js bundle I'd like to build CSS for web page, but always got error

```
ERROR in ./src/sass/company-style.scss 1:3
    Module parse failed: Unexpected token (1:3)
    You may need an appropriate loader to handle this file type.
    > h1 {
    |   color: #c43f4c; }
    | 

```

company-style.scss
```
$myred: #c43f4c;
h1 {
  color: $myred;
}
```

Could you please look at **cssConfig** in following listing. I can't understand how to properly config
```js
const path = require('path')

var config = {
    // common Configuration
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: 'babel-loader',
                }
            }

            ,{
                test: /\.scss$/,
                use: [{
                    loader: 'style-loader'
                }, {
                    loader: 'css-loader'
                }, {
                    loader: 'sass-loader'
                }]
            }

            ,{
                test: /\.(png|svg|jpg|gif)$/,
                use: [
                    {
                        loader: 'file-loader'
                    }
                ]
            }
        ]
    }

};

var bundleConfig = Object.assign({}, config, {
    name: "js-bundle",
    entry: './src/index.js',
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist')
    }
});


// need to install node-sass >webpack-demo_v4>npm install node-sass --save-dev
var cssConfig = Object.assign({}, config,{
    name: "css-bundle",
    entry: "./src/sass/company-style.scss",
    output: {
        filename: "company-style.css",
        path: path.resolve(__dirname, 'dist')
    },

    module: {
        rules: [
            {
                test: /\.scss$/,
                /*use: [{
                    loader: 'sass-loader'
                }]*/
                use: ['sass-loader']
            }
        ]
    }
});

// Return Array of Configurations
module.exports = [
    bundleConfig, cssConfig
];
```

**Comment by evilebottnawi** [comment]
@JavaPantry you have invalid config, don't use `Object.assign` on config because it is not merge deep properties (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign). Please provide minimum reproducible test repo (without `Object.assign` and other stuff).

**Comment by JavaPantry** [comment]
Thank you, evilebottnawi
- I've switch from Object.assign to use `merge = require('webpack-merge')` 
- Project compiled without errors but output file is javascript instead of desired CSS
- just for consistency change output file to `company-style.js` and modify index.html
- style applied to html `h1` tag as expected

Is there any option to produce pure CSS file, instead JavaScript?

For oyur convinience I put demo project to [GitHub](https://github.com/JavaPantry/WebpackTutorial)
Project itself in [webpack-demo_v4_SASS](https://github.com/JavaPantry/WebpackTutorial/tree/master/webpack-demo_v4_SASS)

**Comment by evilebottnawi** [comment]
@JavaPantry https://github.com/webpack-contrib/mini-css-extract-plugin, please read README , also for questions please use `stackoverflow` or `gitter`, thanks!
