### ISSUE TITLE
node-sass: 4.5.x version is too old to run in latest macOS mojave 10.14

### ISSUE THREAD

**Issue by my101du** [webpack-contrib/sass-loader#622]
I was developing a project, before it works fine, but today got an error when run 

npm run dev

it response an error:

Node Sass does not yet support your current environment: macos 64-bit with Unsupported runtime (67)
please..... node-sass   4.9.x

then I saw the package.json in sass-loader is still using 4.5.x.

I remember last week I update my macbook to 10.14.

please fix the issue, thanks.

**Comment by evilebottnawi** [comment]
@my101du just add `node-sass` with supported version in you `package.json` (you can pin package - `node-sass: "4.5.0"` to avoid future  problems), we can't solve this problem on our side
