### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bgm5d** [webpack-contrib/sass-loader#623]
Hello!  Could you confirm that sass-loader-v7.0.1 is also covered by the MIT License (which I see for the master).  Any help you could provide is very much appreciated.

Thank you!!

**Comment by evilebottnawi** [comment]
@bgm5d yes, it is MIT

**Comment by bgm5d** [comment]
Thank you!!!

On Mon, Oct 29, 2018 at 5:29 AM Evilebot Tnawi <notifications@github.com>
wrote:

> @bgm5d
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bgm5d&d=DwMCaQ&c=pLULRYW__RtkwsQUPxJVDGboCTdgji3AcHNJU0BpTJE&r=53ETeLIrYy3xQSeY0QdYzBZDCVzlhcvQ3XYg7yAIKxc&m=JgQI_weI2tMWkT9aL_J9EByCXusedGvYHOP172JoroI&s=9v7M86nwtMOV30JDSOmFqroGQ4ru78ANvwpqISAqbEc&e=>
> yes, it is MIT
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_webpack-2Dcontrib_sass-2Dloader_issues_623-23issuecomment-2D433842275&d=DwMCaQ&c=pLULRYW__RtkwsQUPxJVDGboCTdgji3AcHNJU0BpTJE&r=53ETeLIrYy3xQSeY0QdYzBZDCVzlhcvQ3XYg7yAIKxc&m=JgQI_weI2tMWkT9aL_J9EByCXusedGvYHOP172JoroI&s=YtAFm_v_tRc35vY2HJ02TjRyn_F-5Revu6NOM6-26jk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AqcSohvY6YdwfSIc86n5g2Yi6y333zk0ks5upspggaJpZM4X8aDd&d=DwMCaQ&c=pLULRYW__RtkwsQUPxJVDGboCTdgji3AcHNJU0BpTJE&r=53ETeLIrYy3xQSeY0QdYzBZDCVzlhcvQ3XYg7yAIKxc&m=JgQI_weI2tMWkT9aL_J9EByCXusedGvYHOP172JoroI&s=ybWI4mZCcnEnYHWknFXqujROkOF6uazp86uBMk48va0&e=>
> .
>


-- 

*Bridget Morris*

Manager, Counsel
804-512-2273
bridget.morris@capitalone.com
________________________________________________________

The information contained in this e-mail is confidential and/or proprietary to Capital One and/or its affiliates and may only be used solely in performance of work or services for Capital One. The information transmitted herewith is intended only for use by the individual or entity to which it is addressed. If the reader of this message is not the intended recipient, you are hereby notified that any review, retransmission, dissemination, distribution, copying or other use of, or taking of any action in reliance upon this information is strictly prohibited. If you have received this communication in error, please contact the sender and delete the material from your computer.
