### ISSUE TITLE
Can't get the common scss content when using webpack4.

### ISSUE THREAD

**Issue by MOONLIGHTV** [webpack-contrib/sass-loader#628]
This is the link about my issue:
https://stackoverflow.com/questions/53219805/cant-get-the-common-scss-when-use-sass-loader
When I use sass-loader+css-loader+mini-css-extract-plugin, only .css file can be created a common css file, the .scss can't get.

**Comment by evilebottnawi** [comment]
@MOONLIGHTV I can't understand you, what you expected?

**Comment by MOONLIGHTV** [comment]
@evilebottnawi
I have two .scss files(index.scss & about.scss), they use "@import" import one same common.scss, After run webpack, index.css & about.css all included the common.scss conten, can't make the same common.scss to common.css,.

**Comment by evilebottnawi** [comment]
@MOONLIGHTV Because in `sass`/`scss` all `import` inlined,  we just wrapper around `node-sass`/`sass` and we can't change behaviour
