### ISSUE TITLE
Make env variables available in sass / Nuxt

### ISSUE THREAD

**Issue by Yackbz** [webpack-contrib/sass-loader#632]
Hi,

can someone tell me how to make env variables setup in the env object in nuxt.config.js available in all sass files?
The docs mention the sassLoder object. I tried something like this, but it won't work.
```
extend(config, ctx) {
	config.sassLoader = {
             data: "$test: green"
	}
},
```

**Comment by evilebottnawi** [comment]
Please create this issue in `nuxt` repo
