### ISSUE TITLE
Support for Server Side Rendering?

### ISSUE THREAD

**Issue by hassanshaikley** [webpack-contrib/sass-loader#635]
Hey all,

In my build (that gets imported into my core application that uses SSR) I am getting errors because the output file has references to document and window that are not compatible with SSR.

For example this function. There needs to be `typeof window !== 'undefined' && window` where we use window.

Granted I am not sure if I am in the wrong and doing things wrong since I don't see any information on this.

```
var isOldIE = memoize(function () {
        // Test for IE <= 9 as proposed by Browserhacks
        // @see http://browserhacks.com/#hack-e71d8692f65334173fee715c222cb805
        // Tests for existence of standard globals is to allow style-loader
        // to operate correctly into non-standard environments
        // @see https://github.com/webpack-contrib/style-loader/issues/177
        return window && document && document.all && !window.atob;
});

```

**Comment by evilebottnawi** [comment]
@hassanshaikley not related to `sass-loader`, feel free to create issue in `style-loader`

**Comment by hassanshaikley** [comment]
Oh man, I am sorry! I did a small test and thought it was sass-loader. I am just doing a workaround now. 

Thanks for your incredible work.
