### ISSUE TITLE
Vulnerability due to usage of lodash.tail:4.1.1

### ISSUE THREAD

**Issue by darrynten** [webpack-contrib/sass-loader#652]
DepShield is reporting vulnerabilities for the version of lodash.tail (4.1.1) in the `package.json` file as you can see here: https://github.com/UnicornGlobal/data-table/issues/89

There is a newer version of lodash.tail available.

**Comment by evilebottnawi** [comment]
Bug thanks for the PR, we solve this in other way https://github.com/webpack-contrib/sass-loader/pull/707, release will be on next week
