### ISSUE TITLE
Unable to use node-sass-import-once and tilde/node_modules references

### ISSUE THREAD

**Issue by xenobytezero** [webpack-contrib/sass-loader#659]
* Operating System: Win 10 1809
* Node Version: 10.15.0
* NPM Version: 6.4.1
* webpack Version: 4.29.0
* sass-loader Version: 7.1.0

### Expected Behavior

`sass-loader` should be able to use both tilde node_modules references and the `node-sass-import-once` at the same time

### Actual Behavior

When using the [`node-sass-import-once` ](https://github.com/at-import/node-sass-import-once) importer, SASS `@import` references that use the tilde(~) to refer to node_modules do not seem to resolve correctly. After `node-sass-import-once` is removed from the chain, the paths seem to resolve find

### How Do We Reproduce?

1. Check out repo [xenobytezero/webpack-sass-loader-error](https://github.com/xenobytezero/webpack-sass-loader-error)
2. `yarn`
3. `npm run build`

Note that `dist/pages/index.css` is built, but with a duplicated `h1` rule at the bottom of the file

5. Modify `webpack.config.js` to add the `NodeSassImportOnce` loader (currently commented out)
6. `npm run build`

Note the error message

```
ERROR in ./sass/page/single.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

    @include fa-icon();
            ^
      No mixin named fa-icon
```

This suggests that the tilde reference no longer works.

**Comment by evilebottnawi** [comment]
@xenobytezero `node-sass-import-once` can't work with `sass-loader` due limitation `node-sass-import-once`, also it is impossible due `resolve` aliases in some case. Won't fix it.

**Comment by xenobytezero** [comment]
Thanks for the response.

I can't be the first person to have noticed this incompatibility, is there another way of doing this without the use of the importer?

Is there a specific area I could look at to start seeing if this could be patched in?

I did notice a project [`sass-loader-once`](https://github.com/zdzDesigner/sass-loader-once#readme) which looks like what I want, but doesn't seem to work with V4. I could look at that to see if there is a way via that?

**Comment by evilebottnawi** [comment]
@xenobytezero It is impossible to fix, because it is way how webpack works and how it is should works in right way, why you need `sass-loader-once`?

**Comment by jayarjo** [comment]
~ doesn't work for me at all and looking at the [source](https://github.com/webpack-contrib/sass-loader/blob/master/lib/importsToResolve.js#L19) I do not get how it even can? It's late here - I might be overlooking something, but from what I see, [urlToRequest](https://github.com/webpack/loader-utils/blob/master/lib/urlToRequest.js#L18), will convert any non absolute url (including those with tildas) to relative ones, if second argument (which is never passed from `sass-loader`) is falsy.

**Comment by evilebottnawi** [comment]
`sass-loader-once` doesn't compatibility with `sass-loader` due impossible do use right resolve algorithm, if you have perf problem with `node-sass`/`sass` better create issue in their repo

**Comment by jayarjo** [comment]
It's not `sass-loader-once` related, it's kind of generic problem. I probably should not have posted it in this thread.

**Comment by evilebottnawi** [comment]
Sorry won't fix due design

**Comment by evilebottnawi** [comment]
Anyway if somebody has idea how we can solve this feel free to feedback or send a PR

**Comment by xenobytezero** [comment]
Apologies for the late reponse, other projects have been taking my time.

So if this is not a thing that is supported by Webpack, I'm going to assume my approach is incorrect generally.

I'm building a Wordpress Theme and am essentially building multiple blocks of individual functionality, all of which use the same base vars/mixins/etc. This means I want to be able to include the same file at the top of each block so that I can use them, and also IDEs can see where I'm pulling these random vars/mixins from.

Without something like `node-sass-import-once`, using other build methods up till now (Grunt, Brunch, etc) my compiled CSS will have multiple copies of my core SASS import. 

I would like to be able to just include this file as standard at the top since it's much easier to maintain rather than hand building a SASS tree myself. This doesn't seem like a crazy use case, especially with more modular codebases.

Since `node-sass-import-once` is incompatible, does Webpacks alternative dependency tree algorithm already do this where the normal SASS compiler does not? Is there some switch I have to hit to make this work? Am I approaching this totally wrong?

**Comment by ankurarora** [comment]
I have a similar use case. I want node-sass-import-once but sass-loader seems to be ignoring it completely. What's the best way to accomplish it with sass-loader?
