### ISSUE TITLE
sourcemaps in style-loader config in documentation

### ISSUE THREAD

**Issue by bugzpodder** [webpack-contrib/sass-loader#660]
In the current documentation for sass-loader (https://github.com/webpack-contrib/sass-loader#source-maps), to turn on sourcemaps we don't need it on styled-loader:
```
use: [{
                loader: "style-loader"
            }, {
                loader: "css-loader", options: {
                    sourceMap: true
                }
            }, {
                loader: "sass-loader", options: {
                    sourceMap: true
                }
            }]
```

However, this is different from the recommendations in postcss-loader:
https://github.com/postcss/postcss-loader#sourcemap
https://github.com/webpack-contrib/style-loader#options

It appears that it would work as recommended here, but I'd like to ask for clarification about this omission.

**Comment by evilebottnawi** [comment]
You should use `sourceMap: true` for all loaders, if you want source maps for css, we need fix documentation, can you send a PR?

**Comment by lgbcscs** [comment]
i set all `sourceMap : ture` ,but it do not work at all. why?

this is my module option:

<pre>
module: {
        rules: [
            {
                test: /\.(png|svg|jpg|gif)$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {

                        }
                    }
                ]
            },
            {
                test: /\.(woff|woff2|eot|ttf|otf)$/,
                use: [
                    'file-loader'
                ]
            },
            {
                test: /\.(sa|sc|c)ss$/,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader,
                        options: {
                            hmr: process.env.NODE_ENV === 'development',
                            sourceMap: true,
                        },
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            sourceMap: true,
                            importLoaders: 2
                        }
                    },
                    {
                        loader: 'resolve-url-loader',
                        options: {
                            sourceMap: true,
                            debug: true
                        }
                    },
                    {
                        loader: 'sass-loader',
                        options: {
                            sourceMap: true,
                        }
                    },
                ],
            }
        ]
</pre>
