### ISSUE TITLE
Add node-sass package as deps or peer-deps

### ISSUE THREAD

**Issue by maryjanyes** [webpack-contrib/sass-loader#664]
* Operating System:
* Node Version:
* NPM Version:
* webpack Version:
* sass-loader Version:

### Feature Proposal
* add _node-sass_ module to peer-dependencies or etc for better start with.

### Feature Use Case
* please add node-sass because if i try using sass-loader forward i can see errror _node-sass_ not found will be better install it autommatically with deps.

**Comment by evilebottnawi** [comment]
Here describe why we don't use `peer` deps https://github.com/webpack-contrib/sass-loader#install, you can isntall `sass` (`dart-sass`) as alternative and we can't have 2 peer deps
