### ISSUE TITLE
Problem using sass-loader with latest bootstrap release

### ISSUE THREAD

**Issue by joterr** [webpack-contrib/sass-loader#665]
* Operating System: macOS
* Node Version: 8.12.0
* NPM Version: 6.5.0
* webpack Version: 4.29.3
* sass-loader Version: 7.1.0
* boostrap Version: 4.3.0

### Expected Behavior

The following sass line should work:

`$input-height-inner-half:               calc(#{$input-line-height * .5em} + #{$input-padding-y}) !default;`

### Actual Behavior

sass-loader and bootstrap 4.3.0 do not work together:

`ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib??ref--1-3!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js?sourceMap!./src/styles.scss
Module build failed: 
$input-height-inner-half:               calc(#{$input-line-height * .5em} + #{$input-padding-y}) !default;
                                                                                               ^
      0.625em*rem isn't a valid CSS value.
      in .../node_modules/bootstrap/scss/_variables.scss (line 492, column 97)
 @ ./src/styles.scss 4:14-268
 @ multi ./src/styles.scss`

### Code

```js
            {
                exclude: [
                    path.join(process.cwd(), "src/styles.scss")
                ],
                test: /\.scss$|\.sass$/,
                loaders: [
                    "exports-loader?module.exports.toString()",
                    "css-loader?{\"sourceMap\":false,\"importLoaders\":1}",
                    {
                        loader: "postcss-loader",
                        options: {
                            sourceMap: true,
                            config: {
                                path: ".build/postcss.config.js"
                            }
                        }
                    },
                    "resolve-url-loader",
                    "sass-loader?sourceMap"
                ]
            }
```

### How Do We Reproduce?

Basic sass-loader integration.

**Comment by evilebottnawi** [comment]
We don't change your code, looks you have invalid `scss`, if you think what you code is valid please report about problem in `node-sass`/`sass`

**Comment by evilebottnawi** [comment]
Also please check redefined variable, bootstrap can change some variables
