### ISSUE TITLE
node-sass peer dependency

### ISSUE THREAD

**Issue by arcanis** [webpack-contrib/sass-loader#668]
### Expected Behavior / Situation

The `sass-loader` package requires `node-sass`, and as such `node-sass` should be a dependency (or a peer dependency).

### Actual Behavior / Situation

The `sass-loader` package doesn't list `node-sass` at all.

### Modification Proposal

The peer dependency should be listed. I've seen that removing it was a conscious choice in #532, hence why I'm opening this issue rather than a PR (I can open a PR once we agree) cc @gaearon

Note that the problem described in #532 is partially fixed already - Yarn supports [optional peer dependencies](https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md) through the use of the `peerDependenciesMeta` field. We have an intent to implement from pnpm, only remains npm which doesn't communicate much anyway.

**Comment by evilebottnawi** [comment]
Already discussed, no, we can't add `node-sass` to peer deps, because you can use `sass` (`dart-sass`) package, please use search before post issue. Information https://github.com/webpack-contrib/sass-loader#install

**Comment by arcanis** [comment]
As mentioned the situation is different because optional peer dependencies are a thing now. You could potentially list both `node-sass` and `dart-sass` as peer dependency (the package manager wouldn't warn if they are missing, only if it exists and the range doesn't match).

**Comment by evilebottnawi** [comment]
@arcanis it is bad solution, we will get many issue about this warning

**Comment by arcanis** [comment]
It would look like this:

```json
{
  "peerDependencies": {
    "node-sass": "*"
  },
  "peerDependenciesMeta": {
    "node-sass": {
      "optional": true
    }
  }
}
```

**Comment by evilebottnawi** [comment]
@arcanis can you give link on `peerDependenciesMeta` documentation?

**Comment by evilebottnawi** [comment]
We can't add something in `peerDependencies`

**Comment by evilebottnawi** [comment]
Also we can't break `npm` (even if they develop slowly), we should prefer stable/lts solution rather new feature

**Comment by evilebottnawi** [comment]
We can't use `peerDependenciesMeta` field, it is requires to use `peerDependencies`, we need to search solution where we don't add anything in `peerDependencies`

**Comment by arcanis** [comment]
> @arcanis can you give link on `peerDependenciesMeta` documentation?

At the moment the best documentation is [the merged RFC](https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md). It's fairly complete so I didn't put up a duplicate page on the website yet.

> Also we can't break `npm` (even if they develop slowly)

They wouldn't break, they would start to get a warning. The reason I'm not seeing adding something to `peerDependencies`  as a blocker are:

- If you see it as a breaking change, then I guess it can be postponed to the next major bump.
- Packages are locked, meaning that they won't cause new warnings until they upgrade `sass-loader`.

As a side note I'm sure npm would be more enthusiast about fixing things if they are held accountable for it (just like we've implemented the optional peer dependencies because we've seen that people were using hacks instead).

> we should prefer stable/lts solution rather new feature like `pnp`

Note that PnP isn't broken. It works fine, even with `node-sass` and even with `create-react-app` (because we have a special case for it, which you'll agree would be better avoided).

My point is that by not listing the peer dependency, you're actively making use of an undefined behavior. It's a dangerous thing, even outside of the PnP mode. Peer dependencies have implications regarding how the hoisting work, and not listing them open the room to errors. That's why PnP enforces it. This is not about PnP - the problem simply is highlighted.

**Comment by yangxuanxing** [comment]
In our project, we flatten all dependencies to the top node_modules folder.
as ```node-sass``` is not in the dependencies, when excute, it cannot resolve the module

![image](https://user-images.githubusercontent.com/3397523/57187699-97a29b00-6f25-11e9-8794-0e5b005226ae.png)
