### ISSUE TITLE
Few features are unreleased (including data as a funciton)

### ISSUE THREAD

**Issue by znck** [webpack-contrib/sass-loader#669]
There are many [changes since last release](https://github.com/webpack-contrib/sass-loader/compare/v7.1.0...master), are planning to publish a new release?

**Comment by bugzpodder** [comment]
https://github.com/facebook/create-react-app is planning a 3.0 alpha release (https://github.com/facebook/create-react-app/issues/6475), it would be great to include a new version of sass-loader in it!

**Comment by evilebottnawi** [comment]
It is in my todo list, sorry doesn't have time on finish new major right now, also we have some little bug in `doResolve` and we need fix it before release

**Comment by FlyDreame** [comment]
When will the new version be released? I hate node-sass !!!!

**Comment by evilebottnawi** [comment]
Release will be tomorrow, we have some problem with npm access, hope it will be solved in near future

**Comment by evilebottnawi** [comment]
`7.2.0` published, feel free to update and feedback
