### ISSUE TITLE
Sourcemap entry path is 'stdin' with dart-sass

### ISSUE THREAD

**Issue by WolfspiritM** [webpack-contrib/sass-loader#671]
* Operating System: Windows 10
* Node Version: 10.9.0
* NPM Version: 6.2.0
* webpack Version: 4.29.5
* sass-loader Version: 7.1.0

### Expected Behavior
Sourcemap entrypoint is a path to a file.

### Actual Behavior
Sourcemap entrypoint (one of the sources) is "stdin" and that causes loaders in the chain that rely on sourcemaps (resolve-url-loader) to fail.

### Code

```js
  // webpack.config.js
...
                        "css-loader",
                        {
                            loader: 'postcss-loader',
                            options: {
                                plugins: () => [require('autoprefixer')],
                                config: {
                                    path: path.join(__dirname, "./postcss.config.js")   
                                }
                            }
                        },
                        {
                            loader: 'resolve-url-loader',
                            options: {
                                debug: true,
                                sourceMap: true
                            }
                        },
                        {
                            loader: 'sass-loader',
                            options: {
                                sourceMap: true,
                                sourceMapContents: true,
                                sourceMapRoot: "/web/",
                                implementation: require('sass'),
                            }
                        }
...
```

The reason for this issue is that the "stdin" overwrite is harcoded overwriting the first element in the source.map:
```
   result.map.sources[0] = path.relative(process.cwd(), resourcePath);
``` 

However in my test for dart-sass the "stdin" element is at the end of the array!
That also means that one sourcemap source path is wrongly overwritten.
As soon as I changed the loader to:

```
            var index = result.map.sources.indexOf("stdin");
            if(index >= 0) {
                result.map.sources[index] = path.relative(process.cwd(), resourcePath);
            }
```

Everything is fine again!

### How Do We Reproduce?
Use resolve-url-loader together with dart-sass and try to:
```
background-image: url('../test.png');
```

Reason is that resolve-url-loader isn't able to get the path to the containing file from the source maps.

**Comment by evilebottnawi** [comment]
@WolfspiritM yep, but, PR welcome

**Comment by FractalBoy** [comment]
i went ahead and fixed this since i've been fighting with this issue for hours...

**Comment by strarsis** [comment]
With latest dependencies (everything up to date) I still get an error message for non-resolved resources with webpack 5, sass-loader, dart sass and sourcemaps enabled.
