### ISSUE TITLE
link for sass loader goes to wrong page

### ISSUE THREAD

**Issue by firezdog** [webpack-contrib/sass-loader#674]
https://webpack.js.org/loaders/sass-loader: this is actually a page on the React proxy loader.  I have to follow the link to the github repo to find documentation on the sass loader.

(Note -- to reproduce to the issue, you actually need to click on "sass-loader" in the navigation -- the above link goes to the correct page.  I'm not sure what is going on.  Can't consistently reproduce it -- but I know it happened once.)

**Comment by evilebottnawi** [comment]
@firezdog where link is wrong, can you add link to page?
