### ISSUE TITLE
not finding sass in node_modules

### ISSUE THREAD

**Issue by george-norris-salesforce** [webpack-contrib/sass-loader#683]
* Operating System: OS X
* Node Version: 10
* NPM Version: 6.4.1
* webpack Version: 4.29.6
* sass-loader Version: 7.1.0

### Expected Behavior

sass-loader finds sass in node_modules

### Actual Behavior

sass-loader not finding sass in node_modules

### Code

```js
module.exports = {
  entry: {
    ...
  },
  output: {
   ...
  },
  context: pathFor('client'),
  resolve: {
    extensions: ['.js', '.jsx', '.scss', '.css', '.woff', 'woff2', '.png', '.gif', 'jpeg', 'jpg', '.svg'],
    modules: ['node_modules'],
    alias: {
      components: pathFor('client/javascripts/components/'),
      utils: pathFor('client/javascripts/utils/'),
      reducers: pathFor('client/javascripts/reducers/'),
      actions: pathFor('client/javascripts/actions/'),
      shared: pathFor('shared/'),
      constants: pathFor('constants/'),
      images: pathFor('client/images/')
    }
  },
  node: {
    fs: 'empty'
  },
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader' },
          {
            loader: 'sass-loader',
            options: {
              includePaths: ['./node_modules'],
              sourceMap: true
            }
          }
        ]
      },
    ]
  },
  plugins: [
   ....
  ]
};
```

and including `@import '~bootstrap-sass/assets/stylesheets/bootstrap';`

produces..

```
@import '~bootstrap-sass/assets/stylesheets/bootstrap';
^
      File to import not found or unreadable: ~bootstrap-sass/assets/stylesheets/bootstrap.
```

Also tried removing the `~` and using `/node_modules/path/to/css` as well..

**Comment by christophehenry** [comment]
Somehow same behaviour here, also using Bootstrap (4). Except this time, `bootstrap.scss` is correctly found but its imports are not:

```
Error in ./src/components/streams/stamped_elements/TagStampedElement.vue?vue&type=style&index=0&id=c6407636&scoped=true&lang=scss&

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Can't find stylesheet to import.
    ╷
  8 │ @import "./functions";
    │         ^^^^^^^^^^^^^
    ╵
    ~/Dev/socialhome/socialhome/frontend/node_modules/bootstrap/scss/bootstrap.scss 8:9  @import
    stdin 1:9                                                                                      root stylesheet
```

It looks like relative imports from a file present in `node_modules` are reloved relatively to the project and not to the folder countaining the sourced file from `node_modules`.

I'm using a fairly standard `vue-cli` configuration (not a pure Webpack one).

**Comment by evilebottnawi** [comment]
sass-loade can't find `./functions` something wrong with your configuratin, please create minimum reproducible test repo and I'll show you what's wrong

**Comment by evilebottnawi** [comment]
Resolving relative path in node_modules works fine, something wrong in your setup as i said before

**Comment by christophehenry** [comment]
[Here it is](https://github.com/christophehenry/mrt). Just run:

```
git clone https://github.com/christophehenry/mrt.git && cd mrt
npm i
npm run test:unit
```
You will see full stacktrace:

```
 WEBPACK  Failed to compile with 1 error(s)

Error in ./src/components/HelloWorld.vue?vue&type=style&index=0&id=469af010&scoped=true&lang=scss&

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Can't find stylesheet to import.
    ╷
  8 │ @import "functions";
    │         ^^^^^^^^^^^
    ╵
    ./mrt/node_modules/bootstrap/scss/bootstrap.scss 8:9  @import
    stdin 1:9                                                           root stylesheet
        in http:/localhost/$HOME/mrt/node_modules/bootstrap/scss/bootstrap.scss (line 8, column 9)

 ERROR  mocha-webpack exited with code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mrt@0.1.0 test:unit: `vue-cli-service test:unit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mrt@0.1.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-05-24T12_37_52_638Z-debug.log
```

As I said: this is a fairly standard `vue-cli` project. All I did is create it, install BS4 and source it in the code. Not further modifications.

Please reopen this issue. The problem is reproductible.

**Comment by evilebottnawi** [comment]
Not sure it is related to loader, look on error - `ERROR  mocha-webpack`, something wrong with setup, please open issue in vue, i can't reproduce problem with pure sass-loader setup

**Comment by christophehenry** [comment]
Alright. Thank you.

**Comment by gAusWeb** [comment]
Hope this helps someone else. 

Using Storybook (SB) V 8.4.7 and as mentioned somewhere (which i cannot find where, now 😅), SB already ships with SASS/SCSS working out of the box, so the resolve for my situation was to not use the style-loader, css-loader, sass-loader etc import and just reference the main scss file.

```
// original:
import siteName from '!!style-loader?injectType=lazyStyleTag!css-loader!sass-loader!../../[site-name]/src/assets/main.scss';

// updated
import siteName from '../../[site-name]/src/assets/main.scss';
