### ISSUE TITLE
dart-sass doesn't resolve includePaths in sass-loader configuration.

### ISSUE THREAD

**Issue by syntacticsolutions** [webpack-contrib/sass-loader#684]
* Operating System: OSX
* Node Version: 12.3.0
* NPM Version: 6.9.0
* webpack Version: 4.x
* sass-loader Version: 7.1.0

### Expected Behavior

The path should be resolved because it is configured to in the includePaths array.

### Actual Behavior

```shell     
Error in ./src/components/QRCodeGenerator/QRCodeGenerator.scss?vue&type=style&index=0&id=51be641b&lang=scss&scoped=true&

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  
                          ^
        Can't find stylesheet to import.
    ╷
  2 │                     @import '...';
    │                             ^^^^^^^^^^^^^^^^^
```
### How Do We Reproduce?

`$ git clone https://github.com/syntacticsolutions/sass-test.git`

`$ cd sass-test`

`$ npm i`

`$ npm run test:unit`

**Comment by syntacticsolutions** [comment]
Here is a link to a basic project that is experiencing the issue.

https://github.com/syntacticsolutions/sass-test

**Comment by evilebottnawi** [comment]
@syntacticsolutions please format issue as template otherwise it was closed, thanks

**Comment by syntacticsolutions** [comment]
I didn't see any template?

**Comment by evilebottnawi** [comment]
@syntacticsolutions so we can close issue?

**Comment by syntacticsolutions** [comment]
no

**Comment by thasmo** [comment]
@evilebottnawi, I guess @syntacticsolutions fixed the issue format, not the problem.

**Comment by evilebottnawi** [comment]
Strange works find without `sass-loader`:
```
const sass = require('sass');

sass.render({
  includePaths: ['./src/assets/css'],
  data: `
  @import 'test';
  
  h3 {
    margin: 40px 0 0;
  }
  
  ul {
    list-style-type: none;
    padding: 0;
  }
  
  li {
    display: inline-block;
    margin: 0 10px;
  }
  
  a {
    color: #42b983;
  }
  `,
  importer: function(url, prev, done) {
    return done({ file: url });
  },
}, function(error, result) {
 if (error) {
   throw error;
 }

 console.log(result.css.toString())
});

```

continue investigation

**Comment by evilebottnawi** [comment]
Problem only for `sass` (`dart-sass`), on `node-sass` all work fine

**Comment by evilebottnawi** [comment]
@syntacticsolutions something in test env modify `fs` (maybe auto mocking?), so `sass` (`dart-sass`) can't resolve you file. Pure setup works fine (just run npm run build in your repo), problem is not related to `sass-loader`. 

Why it is works with `node-sass`? Because `node-sass` has implementation on `C++` and don't use `nodejs` modules for resolving.

**Comment by lujunpeng** [comment]
@syntacticsolutions Has this problem been solved?
