### ISSUE TITLE
sass-loader has unmet peer dependency webpack

### ISSUE THREAD

**Issue by HermannBjorgvin** [webpack-contrib/sass-loader#685]
I am getting a warning when I run `yarn install` on my project.

`sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0"`

I am using @vue/cli-service which has webpack as a dependency, so my application works as expected but sass-loader raises this warning. This feels like it could be improved by removing webpack as a peer dependency.

Does anyone have any thoughts about this?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

You need install webpack please read how peer dep working https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by HermannBjorgvin** [comment]
Opened a new issue under https://github.com/webpack-contrib/sass-loader/issues/686
