### ISSUE TITLE
Unexpected warning during installation with vue-cli

### ISSUE THREAD

**Issue by HermannBjorgvin** [webpack-contrib/sass-loader#686]
* Operating System: Ubuntu 18.04
* Node Version: v10.15.3
* Yarn Version: 1.16.0
* webpack Version: webpack@>=4 < 4.29
* sass-loader Version: ^7.1.0

### Expected Behavior

No warnings on installation

### Actual Behavior

`sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0"`

### Code

`yarn install`

### How Do We Reproduce?

`vue create reproduce-bug`

> manually select features
> enable css preprocessors
> select SCSS/SASS
> select default options for the rest (just hit enter a lot)

the @vue/cli tool hides this warning when it first runs via `vue create`, delete node_modules and run `yarn install` then you will get this warning.

`warning " > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".`

**Comment by evilebottnawi** [comment]
Please open issue in vue cli, you need install webpack to use this loader

You need install webpack please read how peer dep working https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by HermannBjorgvin** [comment]
@evilebottnawi thanks for responding.

I don't need to install webpack. My application abstracts webpack via vue-cli. If I install webpack I get a million dedupe warnings.

For some reason raw-loader does not raise this same warning with peer dependencies even though it also has webpack as a peer dependency. Do you have any clue as to why?

Also sorry for ignoring you, you responded so fast and so formally that I assumed you were a bot.

**Comment by evilebottnawi** [comment]
@HermannBjorgvin i don't know why you don't get warning about raw-loader(maybe old version or something other).

> My application abstracts webpack via vue-cli

You should install webpack in your app. 

If you app also layout for other app you should add `peerDeps` to app too.

It is require to right deps tree, because if some package have webpack in deps you can get invalid webpack version.

**Comment by HermannBjorgvin** [comment]
@evilebottnawi yes it was an older version. I tried the latest and it gives me this same warning.

I also tried adding webpack to my peer dependencies but this causes a lot of errors relating to the version that vue uses.

If I can use the package without webpack installed is it truly a peer dependency? If someone made a webpack competitor that was compatible and could use webpack loaders then it wouldn't really make sense for webpack to still be a peer dependency.

Still I agree the vue team are doing weird stuff but not anything that should raise warnings I think.

**Comment by evilebottnawi** [comment]
I think better ask vue command about this, because it is normal practice for libraries and packages

**Comment by HermannBjorgvin** [comment]
@evilebottnawi fair enough. If it's the current best practice then I'll see about raising the issue in a more general manner.

**Comment by brendon** [comment]
@HermannBjorgvin, did you ever raise this with VueCLI?

**Comment by HermannBjorgvin** [comment]
@brendon nope. It's not really their issue, they are using webpack as a dependency and then exposing an interface where I can load webpack plugins via the vue.config.js file (which is just a webpack-chain config file basically).

So I still feel is more of a webpack community issue of specifying webpack as peer dependency when frameworks can use webpack as a dependency and still load webpack plugins. So it is in my view not a true peer dependency, and who really needs to be warned not to use webpack plugins without webpack anyway, it's kind of a given.

**Comment by vcavallo** [comment]
What a surprise, another sad dead-end issue in the JS world where communities kick the responsibility back and forth to each other, complain about how issues are opened, recommend opening other ones, and there's no obvious solution posted anywhere.

I wish this whole JavaScript ecosystem never evolved.

**Comment by HermannBjorgvin** [comment]
@vcavallo seems to happen a lot in the Python community as well, recently ran into Django Rest Framework requiring the `Authorization` header for `OPTION` calls to protected routes, which is not the W3C but they feel like they know better than the W3C.

These errors are still in our development process today and I just have to tell people "Yes ignore this, it's not really a warning"

**Comment by epileftro85** [comment]
npm install -D sass-loader@^10 sass
