### ISSUE TITLE
Sourcemap wrong lines

### ISSUE THREAD

**Issue by betorobson** [webpack-contrib/sass-loader#689]
It looks like that sass-loader is generating a sourcemap which point out wrong lines.

I am not sure if it is a bug or a bad rule configuration however, after a long few days looking for a answer I was not able to find and solution.

Here a example of what is wrong, it is possible to see on first screenshot my css on `line 12` is point out by the source map at `line 6`.

![Screenshot from 2019-06-03 14-16-08](https://user-images.githubusercontent.com/13212208/58822005-d1da8780-860c-11e9-8526-7cca5fce3aea.png)

![Screenshot from 2019-06-03 14-15-48](https://user-images.githubusercontent.com/13212208/58822007-d3a44b00-860c-11e9-9445-69e3a3515a22.png)

Could you please guys help me out to get what could be wrong here?

* Operating System: Ubuntu 18.04
* Node Version: 10.15.3
* NPM Version: 6.9.0
* webpack Version: 4.29.6
* sass-loader Version: 7.1.0

### Code - webpack - Sass rules
```js
	// Docs SASS files
	{
		test: /[\\/]dev-tools[\\/]docs[\\/].+\.scss$/,
		use: [
			MiniCssExtractPlugin.loader,
			{
				loader: 'css-loader',
				options: {
					sourceMap: true
				}
			},
			{
				loader: 'resolve-url-loader',
				options: {
					sourceMap: true
				}
			},
			{
				loader: 'sass-loader',
				options: {
					sourceMap: true
				}
			}
		]
	},
```

**Comment by evilebottnawi** [comment]
We don't modify source maps, looks like bug in node-sass, please open issue in their repo

**Comment by betorobson** [comment]
@evilebottnawi I generated the CSS by node-sass command line and it works perfect.
It looks like something on webpack.

**Comment by betorobson** [comment]
@evilebottnawi I found the solutions and this can help others.
I just added the `outputStyle: 'compressed'  in sass-loader, so my config is like that:
```javascript
{
	loader: 'sass-loader',
	options: {
		outputStyle: 'compressed',
		sourceMap: true,
	}
}
```

* Please, could you share this at the documentation?
I am sure that there are many other developers facing the same issue.

**Comment by evilebottnawi** [comment]
PR welcome, it is problem on node-sass, try to use sass (dart version)

**Comment by SweetsXob** [comment]
I also tried this configuration, but some selectors are normal, some selectors are not normal

**Comment by SweetsXob** [comment]
> ```js
> {
> 	loader: 'sass-loader',
> 	options: {
> 		outputStyle: 'compressed',
> 		sourceMap: true,
> 	}
> }
> ```
#### I also tried this configuration, but some selectors are normal, some selectors are not normal

**Comment by SharakPL** [comment]
For node-sass@6 above config didn't work for me anymore. It seems `outputStyle: 'expanded'` is now required.
```js
{
   loader: 'sass-loader',
   options: {
     implementation: require('node-sass'),
     sassOptions: {
        outputStyle: 'expanded',
     },
   },
},
