### ISSUE TITLE
sass-loader can't resolve path to _index.scss file when using import alias

### ISSUE THREAD

**Issue by sqal** [webpack-contrib/sass-loader#691]
* Operating System: Windows 10
* Node Version:  12.2.0
* NPM Version: 6.9.0
* webpack Version: 4.33.0
* sass-loader Version: 7.1.0

### Issue
Dart-sass allows us to import an _index.scss or _index.sass file without explicitly adding the _index part at the end of imported file. Currently it only works for relative imports and fails when I try to import _index.scss using an alias in my import path.

### Expected Behavior

This code should work

```js
// @/scss is an alias to some-absolute-path/scss and functions/_index.scss exists
@import "~@/scss/functions";
```
### Actual Behavior

Compilation failed

```
ERROR in ./src/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/lib/loader.js??ref--4-2!./src/style.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import "~@/scss/functions";
       ^
      Can't find stylesheet to import.
  ╷
5 │ @import "~@/scss/functions";
  │         ^^^^^^^^^^^^^^^^^^^
  ╵
  stdin 5:9  root stylesheet
      in C:\dev\sass-test\src\style.scss (line 5, column 9)
 @ ./src/style.scss 2:14-130
 @ ./src/index.js
```

### Code

Reproduction https://github.com/sqal/sass-loader-bug-repro

### How Do We Reproduce?

- clone my reproduction repositor and try build the project (`npm run build`)
- also please check my comment in src/style.scss

**Comment by evilebottnawi** [comment]
What you expected? You should use package name, like `~@bootstrap/scss/functions`

**Comment by sqal** [comment]
@evilebottnawi `~@bootstrap/scss/functions` ? why bootstrap? I don't use bootstrap. Have you checked my reproduction? I just want to import a _index.scss file e.g. `@import "~@/scss/functions"` which should resolve to e.g. `C:\my-prroject\packages\scss\functions\_index.scss` but it currently doesn't work without adding `/_index` to the path. I listed all possible options for importing scss file in my reproduction repo (src/syle.scss)

**Comment by imkremen** [comment]
@sqal Looks like it's not related to `sass-loader`.
https://github.com/sass/node-sass/issues/2339

**Comment by evilebottnawi** [comment]
Yes, it is node-sass feature, you can use `dart-sass` he supports this

**Comment by sqal** [comment]
@evilebottnawi buti don't use node-sass :( I'm using dart-sass implementation and it supports importing _index file since version 1.0.0 https://github.com/sass/dart-sass/blob/master/CHANGELOG.md#100-rc1.

**Comment by evilebottnawi** [comment]
mark as feature, because it is support only `sass` (`dart-sass`)
