### ISSUE TITLE
font awesome icons _variables.scss are not getting compiled as expected

### ISSUE THREAD

**Issue by getsetgopi** [webpack-contrib/sass-loader#695]
* Operating System: Windows 10
* Node Version: 11.14.0
* NPM Version: 6.9.0
* webpack Version: 4.33.0
* sass-loader Version: 7.1.0

### Expected Behavior
.fa-address-book:before {
  content: "\f2b9"; }

.fa-address-book-o:before {
  content: "\f2b9"; }

### Actual Behavior
output.css
.fa-address-book:before {
  content: ""; }

.fa-address-book-o:before {
  content: ""; }

### Code

```js
const config = {
    entry: [
        './scss/aaaaaaaaaaa.scss',
        './scss/bbbbbbbbbbb.scss',
        './scss/ccccccccccc.scss',
        './scss/dddddddddd.scss',
        './scss/eeeeeeeeeee.scss',
        './scss/ffffffffffffffff.scss'
    ],
    output: {
        path: path.resolve(__dirname, 'css'),
        filename: 'bundle.js'
    },
    module: {
        rules: [{
            test: /\.scss$/,
            use: [{
                    loader: 'file-loader',
                    options: {
                        name: '[name].css'
                    }
                },
                {
                    loader: "sass-loader",
                    options: {
                        name: '[name].scss',
                        sourceMap: false
                    }
                }
            ]
        }],
    },
```
### How Do We Reproduce?
create the below files and run webpack build to compile scss to css.
xxxx.scss
@import "main.scss"

main.scss
@import "variables";
@import "icons";

variables.scss
$fa-var-address-book: "\f2b9";
$fa-var-address-book-o: "\f2ba";

icons.scss
.fa-address-book:before { content: $fa-var-address-book; }
.fa-address-book-o:before { content: $fa-var-address-book-o; }

output.css
.fa-address-book:before {
  content: "\f2b9"; }

.fa-address-book-o:before {
  content: "\f2b9"; }

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by getsetgopi** [comment]
@evilebottnawi, Unfortunately create/check out public repo from Github is blocked and copying code out of office network is also blocked. I'm attaching the testable zip.
Download and unzip the file.
Run npm install. After installation
Run npm run build
[scss-loader-test.zip](https://github.com/webpack-contrib/sass-loader/files/3287454/scss-loader-test.zip)

**Comment by evilebottnawi** [comment]
Thanks

**Comment by getsetgopi** [comment]
@evilebottnawi - Do you have any update?

**Comment by JParkinson1991** [comment]
Just to chime in, when using fontawesome provided varaibles you should pass them through the `fa-content` function.

```
// Convenience function used to set content property
@function fa-content($fa-var) {
  @return unquote("\"#{ $fa-var }\"");
}
```

Im currently using **fontawesome 5.9.0** and it compiles fine using the above function.

Also created the following mixins which can be used to simplify creation if icons via variables.
[_fontawesome.scss.txt](https://github.com/webpack-contrib/sass-loader/files/3338656/_fontawesome.scss.txt)

An examaple:
```
/// Creates a font awesome icon.
///
/// This mixin will fail to compile etc without prior inclusion of the font awesome package.
///
/// @param {string} $icon
///     The font/character of the icon to render.
///     It is strongly recommended to use $fa-var- variables
///
@mixin fontAwesomeIcon($icon){
    // sass-lint:disable mixin-name-format, function-name-format
    @include fa-icon();
    font-family: 'Font Awesome 5 Free', sans-serif;
    font-weight: 400;
    content: fa-content($icon);
}

.add-icon {
    @include fontAwesomeIcon($fa-var-address-book)
}
```

I would recommend closing this issue as it's not a problem with sass-loader, moreso improper use of the font awesome library.

**Comment by getsetgopi** [comment]
Thanks for the update. I will give it a try and update the ticket.

**Comment by getsetgopi** [comment]
@JParkinson1991 - The above fix may work for 5.x version of font awesome. But not work for 4.x.x.
I found the fix for 4.x.x [here](https://github.com/FortAwesome/Font-Awesome/pull/6728).
Here is what I did.
In my _variable.scss
@function prepend-slash($value) {
    @return unquote('"\\#{$value}"');
}
$fa-var-500px: unquote('"\\f26e"');
$fa-var-address-book: unquote('"\\f2b9"');
$fa-var-address-book-o: unquote('"\\f2ba"');
$fa-var-address-card: unquote('"\\f2bb"');
$fa-var-address-card-o: unquote('"\\f2bc"');
$fa-var-adjust: unquote('"\\f042"');
$fa-var-adn: unquote('"\\f170"');

Output:
.fa-glass:before {
  content: "\f000"; }

.fa-music:before {
  content: "\f001"; }

.fa-search:before {
  content: "\f002"; }

.fa-envelope-o:before {
  content: "\f003"; }

.fa-heart:before {
  content: "\f004"; }

**Comment by JParkinson1991** [comment]
Glad you got it sorted!
