### ISSUE TITLE
Sourcemap not emmit

### ISSUE THREAD

**Issue by sxzctzppyw** [webpack-contrib/sass-loader#696]
* Operating System: Windows 10 Pro 1803
* Node Version: 10.15.3
* NPM Version: 6.4.1
* webpack Version: 4.33.0
* sass-loader Version: 7.1.0

### Expected Behavior
Include inline sourcemap in css file

### Actual Behavior
Sourcemap not emmit

### Code

```js
 https://gist.github.com/sxzctzppyw/ab3af3303e376d7b326db9db23438083
```

**Comment by evilebottnawi** [comment]
Yes, because file-loader doesn't emit source maps, you just load compiled sass as url. What you expected? Where will be emit?

**Comment by sxzctzppyw** [comment]
Hi,
I expected that "sass-loader" and "dart sass" compile to CSS and emmit sourcemap. "file-loader" save this CSS to file.

I have a configuration that works in this way
https://gist.github.com/sxzctzppyw/e8a45922869162eb0993661c7d6ceb08

The problem with the sourcemap is that it does not show exactly the error in imports SCS. Only line on main SCSS.

**Comment by evilebottnawi** [comment]
> The problem with the sourcemap is that it does not show exactly the error in imports SCS. Only line on main SCSS.

Can you provide example (screenshot and example of code, you can create minimum reproducible test repo with screenshot, it is help to me solve the problem, thanks)?

**Comment by sxzctzppyw** [comment]
https://github.com/sxzctzppyw/testN7eq5oo

**Comment by evilebottnawi** [comment]
Thanks!

**Comment by sxzctzppyw** [comment]
In my opinion

**postcss-loader**
Emit sourcemap and file-loader save this to file.

**sass-loader**
Should emmit sourcemap but not emmit

**How to check?**
When postcss-loader is disabled/commented output CSS not contains sourcemap.
But should contain sourcemap from sass configuration.
sourceMap: true,
sourceMapEmbed: true

**Comment by sxzctzppyw** [comment]
@evilebottnawi 
You are right from the beginning.

I use:
css-loader
MiniCssExtractPlugin
instead of
file-loader

I modified postcss.config, becouse "map: true" it caused problems.

And its works.
