### ISSUE TITLE
[Bug Report] importing a SCSS file with only variables output an empty CSS file

### ISSUE THREAD

**Issue by jimblue** [webpack-contrib/sass-loader#697]
* Operating System: MacOS Mojave 10.14.5
* Node Version: 10.16.0
* NPM Version: 6.9.0
* webpack Version: 4.34.0
* sass-loader Version: 7.1.0

### Expected Behavior

When importing a SCSS file with only variables inside, it shouldn't output a CSS file.

### Actual Behavior

I have a `variables.scss` file with only SCSS variables inside.
To share some SCSS variables with Javascript I use the following method: https://til.hashrocket.com/posts/sxbrscjuqu-share-scss-variables-with-javascript

It's working greating as I can use the exported SCSS variables inside Javascript.

The only problem is that webpack output an empty CSS file with it's source-map...

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo
