### ISSUE TITLE
enable sass bundles analysis

### ISSUE THREAD

**Issue by yuxizhe** [webpack-contrib/sass-loader#698]
* Operating System: linux
* Node Version: 10
* NPM Version: 4
* webpack Version: 4
* sass-loader Version: 7

### Feature Proposal
In a big project, styles files size always be huge. So we need to analyze style modules' sizes to find out which style part is big. For example, I use `webpack-bundle-analyser`. If I only use `css` and `css-loader`, everything works out fine. As the pic shows below, We can see `css.js` is made up of `a.css` and `b.css`.

But If I use `sass` and add `sass-loader`, I cannot see the relationship between style files, without detail information, only `index.sass`

Here is the demo project 
> https://github.com/yuxizhe/webpack-css-loader-test

Here shows the result

![image](https://user-images.githubusercontent.com/14990734/59660804-038e4980-91dc-11e9-813f-cac7a1c2a965.png)

![image](https://user-images.githubusercontent.com/14990734/59662345-50bfea80-91df-11e9-8bd7-b65ed46a130f.png)

maybe webpack `Module Dependencies` explains why:
> https://webpack.js.org/contribute/writing-a-loader#module-dependencies

> In the case of the less-loader, it cannot transform each @import to a require because all .less files must be compiled in one pass for variables and mixin tracking. Therefore, the less-loader extends the less compiler with custom path resolving logic. It then takes advantage of the second approach, this.resolve, to resolve the dependency through webpack.

less-loader or sass-loader transform `@import` to `this.resolve` instead of `require`，maybe webpack can't work out the relationship between style files without `require`. 

But can we find out a way to solve this?

### Feature Use Case

style files size analysis

### Relation Issue
https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/187

**Comment by evilebottnawi** [comment]
It is not solved on sass loader level, better open issue in webpack, we don't have API for the this

**Comment by evilebottnawi** [comment]
Also it is invalid use this as require because it is not require

**Comment by yuxizhe** [comment]
@evilebottnawi  I open the issue in webpack, they said its less and sass cause the problem. https://github.com/webpack/webpack/issues/9301
> The way less and sass work makes the dependencies invisible to webpack, so this can't be fixed... Sorry... I dislike it too.

**Comment by evilebottnawi** [comment]
Unfortunately we can't solve this on loader level right now, maybe we can improve api for adding additional information from loaders, but it is require implement more logic in `webpack-bundle-analyzer`

/cc @th0r any ideas how we can solve this? I think we can solve this using code in loader like:
```
const callback = this.async();
// Logic
renderSass(arg, (result) => {
  callback(null, result, { additionalInformation: { importedTree: importedFiles } })
})
```

but it is require implement logic on webpack side too

**Comment by evilebottnawi** [comment]
I like this improvement, but nothing to do here, it should be part of https://github.com/webpack-contrib/webpack-bundle-analyzer, we can't implement this on our side, sorry, closing in favor https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/187
