### ISSUE TITLE
Make dart-sass default?

### ISSUE THREAD

**Issue by epicfaace** [webpack-contrib/sass-loader#703]
Why does sass-loader use node-sass by default? Could we perhaps use dart-sass by default? That may make it easier to work with.

**Comment by bugzpodder** [comment]
You'll need to install either sass or node-sass along with sass-loader.
The only ambiguity is when you have *both* node-sass and sass installed, but I don't really see that happening

**Comment by evilebottnawi** [comment]
in next major release we first search sass, when node-sass, so if you installed dart-sass (have in devDeps) it will be used by default

**Comment by epicfaace** [comment]
I see, makes sense. Thanks for the clarification!

**Comment by artaommahe** [comment]
@evilebottnawi 7.2.0 is here, it's not a major one or plans have been changed?

**Comment by bugzpodder** [comment]
Also 7.2.0 isn't on npm, its only 7.1.0
https://www.npmjs.com/package/sass-loader

**Comment by artaommahe** [comment]
@bugzpodder it's here https://github.com/webpack-contrib/sass-loader/releases and no sass by default in changelog

**Comment by evilebottnawi** [comment]
@artaommahe it breaking change, we change by default for 8.0.0

**Comment by evilebottnawi** [comment]
dart-sass is slower than node-sass, i think we need avoid prefer dart-sass by default for next major release, anyway we already support auto resolve node-sass and dart-sass
