### ISSUE TITLE
@import "file" is not the same as @import "./file";

### ISSUE THREAD

**Issue by khiav223577** [webpack-contrib/sass-loader#704]
* Operating System: macOS 10.13.6
* Node Version: 12.1.0
* NPM Version: 6.9.0
* webpack Version: 4.30.0
* sass-loader Version: 7.1.0

### Expected Behavior

This code should work
```scss
// project_root/app/assets/stylesheets/animations/frame5.scss
// The following line should import project_root/app/assets/stylesheets/_global_mixins.scss successfully
@import 'global_mixins'; 
```

### Actual Behavior

`@import '../global_mixins';` works.
`@import '_global_mixins'; ` works.
`@import 'global_mixins';` fails.
`@import './global_mixins';` fails.

```
ERROR in project_root/app/assets/stylesheets/animations/frame5.scss (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/postcss-loader/src??ref--8-2!./node_modules/sass-loader/lib/loader.js??ref--8-3!project_root/app/assets/stylesheets/animations/frame5.scss 
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import 'global_mixins'; // File to import not found or unreadable: global_mixins.
^
      File to import not found or unreadable: global_mixins.

```

### Code

I use [rails/webpacker](https://github.com/rails/webpacker) to setup webpack environments.
```js
// config/webpacker.yml
resolved_paths:
    - 'app/assets/stylesheets'
```

This is the implementation of resolved_paths: https://github.com/rails/webpacker/pull/557

### How Do We Reproduce?

I'm not sure what causing this problem.
I add `console.log` in this method.
https://github.com/webpack-contrib/sass-loader/blob/2adcca3d73135d4f6292c531f695603688da5a28/lib/webpackImporter.js#L47-L50
The result is:
```js
dir = 'project_root/app/assets/stylesheets/animations'
importsToResolve = [
  './_global_mixins.scss',
  './_global_mixins.sass',
  './_global_mixins.css',
  './global_mixins.scss',
  './global_mixins.sass',
  './global_mixins.css',
  'global_mixins'
]
```

I tried to add this line
```js
`_${basename}.scss`, `_${basename}.sass`, `_${basename}.css`,
```
to
https://github.com/webpack-contrib/sass-loader/blob/2adcca3d73135d4f6292c531f695603688da5a28/lib/importsToResolve.js#L51-L59
and it worked!

**Comment by evilebottnawi** [comment]
Can't reproducible this pure setup, looks bug in `webpacker`

**Comment by evilebottnawi** [comment]
Can you compile you stylesheets using `node-sass` and `sass` without webpack?

**Comment by khiav223577** [comment]
I think the bug is caused by relative paths.
In `sass-loader`, `@import "_global_mixins"` is the same as `@import "./_global_mixins";`
https://github.com/webpack-contrib/sass-loader/blob/69c6f91f56b181c9513aecf73a018cb0929d798c/README.md#L212

But in `webpack`, `@import "_global_mixins";` is regarded as `Module paths` and are searched for inside all directories specified in `resolve.modules`. 
https://webpack.js.org/concepts/module-resolution/#module-paths

While `@import "./_global_mixins";` is regarded as `Relative paths`. The relative path specified in the `import` is joined to this context path to produce the absolute path to the module. So actually it will search the absolute path: `project_root/app/assets/stylesheets/animations/_global_mixins`
https://webpack.js.org/concepts/module-resolution/#relative-paths

Adding
```js
`_${basename}.scss`, `_${basename}.sass`, `_${basename}.css`,
```
to
https://github.com/webpack-contrib/sass-loader/blob/2adcca3d73135d4f6292c531f695603688da5a28/lib/importsToResolve.js#L51-L59

May be a proper way to solve this.

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo, module resolution is same as in `node-sass`/`sass`, we can't change something as you describe above

**Comment by evilebottnawi** [comment]
Here logic `sass` (dart-sass):

Example used when `includePaths` in `undefined`

### `@import 'test.scss';`

```scss
@import 'test.scss'; // same as @import './test.scss';
```

Means:
```
- `./test.scss`
- `./_test.scss`
```

### `@import '_test';`

```scss
@import '_test'; // same as @import './_test';
```

Means:
```
- `./_test.scss`
- `./_test.sass`
- `./_test.css`
- `./_test/_index.scss`
- `./_test/_index.sass`
- `./_test/_index.css`
- `./_test/index.scss`
- `./_test/index.sass`
- `./_test/index.css`
```

### `@import 'test';`

```scss
- `./_test.scss`
- `./_test.sass`
- `./_test.css`
- `./test.scss`
- `./test.sass`
- `./test.css`
- `./_test/_index.scss`
- `./_test/_index.sass`
- `./_test/_index.css`
- `./_test/index.scss`
- `./_test/index.sass`
- `./_test/index.css`
```

### `@import 'directory/test';`

```scss
@import 'directory/test'; // same as @import './directory/test';
```

Means:
```
- `./directory/_test.scss`
- `./directory/_test.sass`
- `./directory/_test.css`
- `./directory/test.scss`
- `./directory/test.sass`
- `./directory/test.css`
- `./directory/test/_index.scss`
- `./directory/test/_index.sass`
- `./directory/test/_index.css`
- `./directory/test/index.scss`
- `./directory/test/index.sass`
- `./directory/test/index.css`
```

**Comment by khiav223577** [comment]
> /cc @khiav223577 friendly ping

@evilebottnawi It seems a bug in `@rails/webpacker`. I'd submitted a PR to it: https://github.com/rails/webpacker/pull/2203. Still waiting for a reply. I'm not familiar with `webpack` and it's ecosystem, can you take a look at it?

**Comment by nex3** [comment]
@evilebottnawi I think that's correct. Note that if `includePaths` *are* specified, it will also look for the same set of files relative to each include path.

It's also worth noting that we're hoping to improve the JS API and the default Sass behavior to make this much more foolproof, probably in early 2020.

**Comment by evilebottnawi** [comment]
@khiav223577 yes it is bug in `@rails/webpacker`, seems this package doesn't support `includePaths`

/cc @nex3 thanks for feedback!
