### ISSUE TITLE
Media query "prefers-color-scheme" gives different output

### ISSUE THREAD

**Issue by SuperDJ** [webpack-contrib/sass-loader#706]
* Operating System: Windows 10 x64
* Node Version: v10.16.0
* NPM Version: 6.10.0
* webpack Version: 4.39.1
* sass-loader Version: 7.1.0

### Expected Behavior

Expected output: `@media (prefers-color-scheme: light)`

### Actual Behavior

Actual output: `@media (color-index: 48)`. When using `@media (prefers-color-scheme: dark)` the output is as expected

### Code

```js
  // webpack.config.js
test: /\.(sa|sc|c)ss$/,
				exclude: ['/node_modules', '/dist', '/src/js', '/docs'],
				use: [
					{
						loader: MiniCSSExtractPlugin.loader,
						options: {
							sourceMap: true,
							minimize: process.env.NODE_ENV === 'production',
						}
					},
					'css-loader',
					{
						loader: 'postcss-loader',
						options: {
							sourceMap: true,
							syntax: postCssScss,
							plugins: () => [
								autoprefixer,
								postCssPresetEnv({
									stage: 0,
									features: {
										'color-mod-function': true,
										'alpha-hex-colors': true
									}
								}),
							],
						},
					},
					{
						loader: 'sass-loader',
						options: {
							sourceMap: true
						}
					}
				]
```

### How Do We Reproduce?

Clone the following repo: https://github.com/SuperDJ/material. Run `npm run prod` in the `docs > dist > css` are the stylesheets.

**Comment by evilebottnawi** [comment]
We don't change your input/output, maybe problem in `postCssPresetEnv`, but not `sass-loader`
