### ISSUE TITLE
Keep loaderContext._module.issuer in production mode

### ISSUE THREAD

**Issue by Maorey** [webpack-contrib/sass-loader#714]
* Operating System: window 10
* Node Version: 12.8.0
* NPM Version: 6.10.2
* webpack Version: 4.39.1
* sass-loader Version: 7.2.0

### Feature Proposal
Keep [loaderContext._module](https://webpack.js.org/api/loaders/#this_module).issuer same with `development` [mode](https://webpack.js.org/configuration/mode/) in `production` mode

### Feature Use Case
I want to inject variables to scss files by different entry (or directory):

``` JavaScript
function includes(module, entry) {
  return (
    !!module &&
    (module.context.includes(entry) || includes(module.issuer, entry))
  )
}
// ...
{
  loader: 'sass-loader',
  options: {
    data({ _module }) {
      if (includes(_module, 'src/main')) {
        return '$value: 100px;'
      } else if (includes(_module, 'src/about')) {
        return '$value: 200px;'
      }
      return ''
    },
  },
}
```
It works in `development` mode, but ineffective in `production` mode for which `loaderContext._module.issuer` is `null`.

Can sass-loader keep `module. issuer`, or there is a way to implement this?

**Comment by Maorey** [comment]
@evilebottnawi 

In this case, I need to know where the scss file was imported: the skin of different html(or PWA router view) was  different:

``` JavaScript
import { Button } from 'element-ui'
import 'element-ui/packages/theme-chalk/src/button.scss'
```

So I can inject different scss variables(find a specified file to `@import`) cover it's default value to set theme globally.

Otherwise:

``` scss
// scss/button.scss
@import '~element-ui/packages/theme-chalk/src/button.scss'
```

``` JavaScript
import { Button } from 'element-ui'
import './scss/button.scss'
```

That's not elegant.

That's why I use `_module` and find superior reference recursively by `issuer`.

**Comment by evilebottnawi** [comment]
@Maorey can you create minimum reproducible test repo and describe in readme what you actually have and what you expected, i will help, maybe we improve loader API for some cases

**Comment by Maorey** [comment]
@evilebottnawi 
repo [here](https://github.com/Maorey/scss-vars-test)

**Comment by evilebottnawi** [comment]
@Maorey 

no that's not possible. It's often abused as kind of parent, but that's not correct. There could be multiple parents, but only one of them is the issuer. It could be a race condition which one. Avoid using issuer to determine module content.

**Comment by evilebottnawi** [comment]
It is rare case, so i recommend use multiple loader with difference issuer (option for loader) or use include/exclude, also better avoid using data to inject variables because it can potentially break source maps, maybe we remove this feature in future, you can reorganize your project structure and solve this using pure sass
