### ISSUE TITLE
How does the sass multi-entry split the common code separately

### ISSUE THREAD

**Issue by karmiy** [webpack-contrib/sass-loader#729]
My webpack configures multiple entries:

entry: {
        button: './src/styles/button.scss', 
        grid: './src/styles/grid.scss'
    },

And then button and grid share base.scss

@import './base.scss'

I need to pack out three files:
button.css
grid.css
common.css

How can I achieve this?
Thanks

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use gitter and stackoverflow for questions, it is bug tracker
