### ISSUE TITLE
Using sourceMaps with Chrome devtools breaks the layout

### ISSUE THREAD

**Issue by JFGHT** [webpack-contrib/sass-loader#731]
- Operating System: Ubuntu
- Node Version: 10
- NPM Version: Yarn 1.17.3
- webpack Version: 4.28.4
- sass-loader Version: 7.1.0

### Expected Behavior

Changing any property in devtools from the actual css classes should display the change.

### Actual Behavior

Whenever I change any css, the whole layout breaks.

### Code

```js
// vue.config.js
module.exports = {
  css: {
    sourceMap: process.env.NODE_ENV === 'development',
  },
};
```

### Create a vue project with latest vue-cli. Add those lines to the configuration and check the bug as described above.

```js
// Fixing the problem
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        sourceMap: false,
      },
    },
    sourceMap: process.env.NODE_ENV === 'development',
  },
};
```

This is the same as: https://github.com/webpack/webpack/issues/7199

**Comment by evilebottnawi** [comment]
Please open issue in `vue-cli`
