### ISSUE TITLE
sass-loader@8.0.0 requires a peer of sass@^1.3.0 but none is installed

### ISSUE THREAD

**Issue by rmkanda** [webpack-contrib/sass-loader#749]
I am getting the below error after upgrading sass-loader to 8.x. 

`sass-loader@8.0.0 requires a peer of sass@^1.3.0 but none is installed. You must install peer dependencies yourself.`

My package.json

```
"devDependencies": {
   "webpack": "^4.39.3",
   "node-sass": "^4.12.0",
   "sass-loader": "^8.0.0"
}
```

**Comment by isellsoap** [comment]
I have the exact opposite. I’m using `sass` instead of `node-sass` and get the error

`npm WARN sass-loader@8.0.0 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by evilebottnawi** [comment]
Ignore this, it is bug on `npm` side, we can't do something here, you can open new issue on npm, but they ignore this bug a long time, this fields require for `pnp` and it is optional deps https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L43

**Comment by jsg2021** [comment]
Maybe move those to `optionalDependencies` instead of peer?

**Comment by jsg2021** [comment]
Ooh, nevermind, `peerDependenciesMeta` marks them optional, and npm will support: https://github.com/npm/cli/pull/224

**Comment by evilebottnawi** [comment]
Yep, but they still can't fix warning, despite the fact that these packages (in `peerDependenciesMeta`) are taken into account when building the dependency tree

**Comment by lunelson** [comment]
There is still a problem however, in that the `sass` optional peer dependency is marked as `^1.3.0` but there is no current version of sass that can satisfy this. Current as of today is `1.23.3`.

**Comment by evilebottnawi** [comment]
Please read how semver works

**Comment by cdefy** [comment]
Hi there, I'm new to Nuxt.js and try to understand how to maintain dependencies up to date.

I have "node-sass": "^4.13.0" and "sass-loader": "^7.3.1". If I try to update sass-loader to 8.0.0 I got those two warnings:
```
npm WARN sass-loader@8.0.0 requires a peer of sass@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
```

I read in that thread that it's maybe a npm bug but I would like to be sure and maybe have some advice on how I could update sass-loader and get rid of the warnings. Should I install the two others dependencies? (But sass 1.3.0 is a really old version and fibers 3.1.0 bit old also).

Thanks for your time and help :)

**Comment by Aladendo** [comment]
@cdefy try:

npm install --save-dev sass

**Comment by DirtyJose** [comment]
> 
> 
> @cdefy try:
> 
> `npm install --save-dev sass fibers`

Thanks,thats work for me!

**Comment by cdefy** [comment]
Thanks a lot @CodCase , installing sass fibers removed the two warnings.

**Comment by mgtmom** [comment]
@CodCase  Thanks a lot !!!!
now it is working !

**Comment by evilebottnawi** [comment]
NPM should respect `peerDependenciesMeta` configuration (https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L43) and does not show warninga, yarn works as expected with that, but NPM still show warnings. 

My recommendation - just ignore this warning, open new issue in their bug tracker again, it is not break your code, it is just warning

**Comment by TheVrai** [comment]
Thanks @CodCase , installing sass fibers removed the two warnings on install.

**Comment by GeriHAl** [comment]
Thanks @CodCase it work!

**Comment by w4ctech** [comment]
You can use ``sass-loader@7.3.1`` to solve this problem
``npm uninstall sass-loader ``
``npm install sass-loader@7.3.1 --save-dev``

**Comment by evilebottnawi** [comment]
Do not install old verison, it will be incompatibility in new future

**Comment by w4ctech** [comment]
> Do not install old verison, it will be incompatibility in new future

But the old version is the fastest solution

**Comment by evilebottnawi** [comment]
@w4ctech it is not **bug**, it is bug in `npm` and it is just warning, ignore warning it is not break your code, without lines pnp is not working

**Comment by laymont** [comment]
@CodCase work for me!

**Comment by miladxandi** [comment]
> @cdefy try:
> 
> `npm install --save-dev sass fibers`

Thanks
