### ISSUE TITLE
Sass loader 8.0.0 does not prepend data in vue-cli 3

### ISSUE THREAD

**Issue by Goldziher** [webpack-contrib/sass-loader#751]
- Operating System: Mac OSx / docker + node
- Node Version: LTS 10
- NPM Version: using yarn 1.17
- webpack Version: latest
- sass-loader Version: 8.0.0

### Expected Behavior

Sass loader loads and prepends the data correctly

### Actual Behavior

Sass loader ignores the data, doesn't through an error but still doesn't inject the code.

### Code

This is working when using v7.3.1 (vue.config.js)

```
css: {
    loaderOptions: {
        sass: {
            data: "@import '~::shared/assets/variables.scss';",
        },
    },
},
```

This is not working when using v8.0.0 (vue.config.js):

```
css: {
    loaderOptions: {
        sass: {
            prependData: "@import '~::shared/assets/variables.scss';",
        },
    },
},
```

### How Do We Reproduce?

Create a project using the latest stable vue cli. Add a similar code as the above. See that it does not work

**Comment by evilebottnawi** [comment]
Please open issue in `vue-cli`
