### ISSUE TITLE
options has an unknown property 'indentedSyntax'

### ISSUE THREAD

**Issue by vflash** [webpack-contrib/sass-loader#752]
options has an unknown property 'indentedSyntax'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }

version 8.0.0

**Comment by evilebottnawi** [comment]
Use `sassOptions: { indentedSyntax: true }`, please read CHANGELOG and use issue template

**Comment by evilebottnawi** [comment]
Also you don't need this option, we automatically set `true` if your files have `sass` extension

**Comment by vflash** [comment]
thank
