### ISSUE TITLE
sass loader 8.0.0 dose not use scss in vue-cli

### ISSUE THREAD

**Issue by IsolatedTraveler** [webpack-contrib/sass-loader#754]
- Operating System: window
- Node Version:v10.15.2
- NPM Version:6.4.1
- webpack Version:3.6.0
- sass-loader Version:8.0.0
- vue Version: 2.5.2

### Code
```
vue init webpack <packageName>
cd <packageName>
npm install
npm install sass-loader node-sass --save-dev
```
### Expected Behavior

Supporting SCSS grammar

### Actual Behavior

![image](https://user-images.githubusercontent.com/33714399/64125661-58099400-cddd-11e9-9f1f-c0f46cc1748a.png)

**Comment by evilebottnawi** [comment]
Minimum supported webpack version is `4.36.0` (https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L38)

**Comment by IsolatedTraveler** [comment]
> Minimum supported webpack version is `4.36.0` (https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L38)

Thanks
