### ISSUE TITLE
includePaths in sassOption on README.md doesn't work.

### ISSUE THREAD

**Issue by idpokute** [webpack-contrib/sass-loader#755]
- Operating System: Ubuntu 18
- Node Version: 10.15.3
- NPM Version: 6.4.1
- webpack Version: 4
- sass-loader Version: 4.12

### Expected Behavior

The example of sassOptions on README.md doesn't include paths. 
[code](https://github.com/webpack-contrib/sass-loader#object)
It seems includePaths doesn't work in sassOption. When I move to options, not sassOptions, it works. 

### Code

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.s[ac]ss$/i,
        use: [
          'style-loader',
          'css-loader',
          {
            loader: 'sass-loader',
            options: {
              includePaths: ['absolute/path/a', 'absolute/path/b'], // I think it should be here.
              sassOptions: {
                indentWidth: 4,
              },
            },
          },
        ],
      },
    ],
  },
};
```

**Comment by evilebottnawi** [comment]
`includePaths` should be in `sassOptions`

**Comment by sebastian-zarzycki-es** [comment]
Did you even read what he wrote?

**Comment by evilebottnawi** [comment]
@sebastian-zarzycki-es Did you read what I answer?

**Comment by sebastian-zarzycki-es** [comment]
Yes. Did you read what he wrote?

**Comment by evilebottnawi** [comment]
You answers is hot helpful, what is not working?

**Comment by lukeed** [comment]
@evilebottnawi OP wrote:

> It seems includePaths doesn't work in sassOption. When I move to options, not sassOptions, it works.

In other words, the documentation says that `options.sassOptions.includePaths` is supposed to work – it doesn't.

However, `options.includePaths` **does** work, even though documentation says it's not supposed to.

I can verify this. Ran into this problem for ~30 minutes. Should be reopened IMO.

**Comment by evilebottnawi** [comment]
Update sass-loader version, `options.includePaths` was removed in previous major release

**Comment by lukeed** [comment]
Apologies. I was still on 7.x

**Comment by ri0t** [comment]
Not sure if it's sensible to comment here, but i suspect it is either a local problem or maybe related. Anyway:

Where i put the "includePaths" doesn't make a difference, here. I don't want to load files in node_modules but avoid stuff like `@import '../../../scss/colors';` all over the place, so i added `includePaths: ['scss']` (which is in the source root) to the loader's options. 

Yet, still, doing `@import '~colors';` doesn't work.
