### ISSUE TITLE
options has an unknown property 'includePaths'. if .scss file is empty

### ISSUE THREAD

**Issue by kambbado** [webpack-contrib/sass-loader#756]
Hello,

I updated to version 8.0.0 and started getting the error below for all .scss files that are empty.
I'm not sure if I missed something

>  Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
>  - options has an unknown property 'includePaths'. These properties are valid:
>    object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }

**Comment by evilebottnawi** [comment]
You can see error and fix problem in setup, move `includePaths` in `sassOptions`, pelase read CHANGELOG before open issue

**Comment by tony-kopanev** [comment]
`More about includePaths in sassOptions is [here](https://webpack.js.org/loaders/sass-loader/#sassoptions).

      {
        loader: 'sass-loader',
        options: {
          sassOptions: {
            includePaths: [
              // ... <your path>
            ]
          }
        }
      }`

**Comment by JS1307** [comment]
> Hello,
> 
> I updated to version 8.0.0 and started getting the error below for all .scss files that are empty. I'm not sure if I missed something
> 
> > Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> > ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
> > 
> > * options has an unknown property 'includePaths'. These properties are valid:
> >   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }

Is it resolved? Can you please help me with that
