### ISSUE TITLE
Error: Dart Sass version 1.23.0-module.beta.1 is incompatible with ^1.3.0

### ISSUE THREAD

**Issue by HoldYourWaffle** [webpack-contrib/sass-loader#757]
- Operating System: Windows 10
- Node Version: 10.12.0
- NPM Version: 6.10.1
- webpack Version: 4.39.3
- sass-loader Version: 8.0.0

### Expected Behavior

I want to use the latest version of `sass` with `sass-loader`.

### Actual Behavior

When using the latest version of `sass` I get the following error:
```
Error: Dart Sass version 1.23.0-module.beta.1 is incompatible with ^1.3.0
```

### How Do We Reproduce?

Install `sass-loader` and `sass` and try to make them work together.

**Comment by evilebottnawi** [comment]
It is expected, because it is beta, we support only stable version, you can pass flag to yarn to avoid this error

**Comment by HoldYourWaffle** [comment]
That makes a lot of sense.

Weird that `sass` doesn't put their beta versions behind `sass@next`...

**Comment by j4hangir** [comment]
This error is suddenly back in my build!
