### ISSUE TITLE
Doesn't work with `npm install dart-sass`

### ISSUE THREAD

**Issue by epicfaace** [webpack-contrib/sass-loader#758]
- Operating System: Ubuntu
- Node Version: 10
- NPM Version: 6.9.2
- webpack Version: 4.3.1
- sass-loader Version: 8.0.0

### Description

Running `npm install dart-sass` and then using sass-loader gives an error saying that it can't find node-sass. However, doing  `npm install sass` works fine.

**Comment by evilebottnawi** [comment]
Because `dart-sass` is outdated repo, you need use `sass` package

**Comment by epicfaace** [comment]
Are you sure it's outdated though? It seems like it's also been updated regularly: https://www.npmjs.com/package/dart-sass

**Comment by evilebottnawi** [comment]
It is not official package according docs https://github.com/sass/dart-sass#from-npm, please use `sass` package

**Comment by GouJieShinee** [comment]
@evilebottnawi why i use @use at-rule , it error: Unknown at rule @usescss(unknownAtRules).

**Comment by GouJieShinee** [comment]
@evilebottnawi why i use @use at-rule , it error: Unknown at rule @usescss(unknownAtRules). 
my vue.config.js code is: 
`
const sass = require('sass'); module.exports = { css: { loaderOptions: { sass: { implementation: sass, }, }, }, };
`

my package.json is: 
`"sass": "^1.23.0", "sass-loader": "^8.0.0"`

**Comment by evilebottnawi** [comment]
@GouJieShinee ask this in vue-cli
