### ISSUE TITLE
Webpack process never exits on missing JS import

### ISSUE THREAD

**Issue by lneveu** [webpack-contrib/sass-loader#759]
- Operating System: Debian 8 (jessie)
- Node Version: 10.15.3
- NPM Version: 6.9.0
- webpack Version: 4.39.2
- sass-loader Version: 8.0.0

### Expected Behavior

In `bail` mode, Webpack build process should fail out and stop on first error (in this case, a missing import file).

### Actual Behavior

Webpack build process get stuck after throwing the expected error. The process never exits.

### Code

```js
// webpack.config.js
const path = require('path');
module.exports = {
  mode: 'production',
  bail: true,
  entry: {
    app: ['./src/app.js', './src/foo.scss']
  },
  output: {
    path: path.resolve(__dirname, './dist')
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: 'babel-loader'
      },
      {
        test: /.s?css$/,
        use: ['css-loader', 'sass-loader']
      }
    ]
  }
};
```

```js
// src/app.js
import './missing-module'; // <-- this import will fail on purpose
console.log('app');
```
```scss
// src/foo.scss
@import './bar';
body { color: red; }
```
```scss
// src/bar.scss
h1 { color: blue; }
```

### How Do We Reproduce?

Run Webpack using the given configuration.
Mandatory conditions to reproduce the bug:
- `bail` mode must be enabled
- a scss file must be specified in the entry list
- the scss entry point (_foo.scss_, here) must contains a valid `@import`. If _foo.scss_ is replaced by _bar.scss_, everything works as expected.

Let me know if you need more details.
Thanks!

**Comment by lneveu** [comment]
I found similar issues here: https://github.com/nodejs/node/issues/17872 and here: https://github.com/webpack-contrib/sass-loader/issues/523.

A fix was proposed and merged in the main Webpack repository: https://github.com/webpack/webpack/pull/6193/. I tried to apply the same patch, but in webpack/cli (since the code was moved there: https://github.com/webpack/webpack-cli/blob/master/bin/cli.js#L317) and it seems to fix the bug.
I'll submit a pull request in the cli repo.

**Comment by evilebottnawi** [comment]
let's close in favor https://github.com/webpack/webpack-cli/pull/1078, anyway thanks for the issue and the PR
