### ISSUE TITLE
'fiber' option not in schema

### ISSUE THREAD

**Issue by alexsasharegan** [webpack-contrib/sass-loader#762]
- Operating System: Linux amd-64
- Node Version: 12.10.0
- NPM Version: 6.11.3
- webpack Version: 4.40.2
- sass-loader Version: 8.0.0

### Expected Behavior

As documented, fiber should be allowed as an option. Currently it's value type appears to allow a boolean or the type of the fibers package export. Also, I find the `additionalProperties: false` schema option to be a PITA. Maybe this is just transitional, but I'm not sure invalid properties merit more than a strong warning. Do with that side-issue what you will.

### Actual Behavior

Currently, the [options schema](https://github.com/webpack-contrib/sass-loader/blob/master/src/options.json) doesn't define this option

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'fiber'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/my-project/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/my-project/node_modules/sass-loader/dist/index.js:36:28)
```

### How Do We Reproduce?

Pretty much just put absolutely anything in the options.fiber and watch it :boom:

**Comment by alexsasharegan** [comment]
I see what's happening. This option has moved and is now nested inside `sassOptions`. This seems like a nice way to move forward with additional options, but seems like unnecessary pain for legacy configurations.

**Comment by evilebottnawi** [comment]
Expected, please change you configuration. It is breaking change so we can move/remove/change options
