### ISSUE TITLE
[sass-loader] always return compressed CSS file

### ISSUE THREAD

**Issue by jimblue** [webpack-contrib/sass-loader#763]
Since a recent update my CSS output are always compressed even without minifier configured.

After a long investigation, I found out **sass-loader** use **dart-sass** with `outputStyle:'compressed'` option by default.

To fix it, I've forced `outputStyle: 'expanded'` like so:

```js
{
  loader: 'sass-loader',
  options: {
    sourceMap: true,
    implementation: require('sass'),
    sassOptions: {
      outputStyle: 'expanded',
    },
  },
},
```
IMO, **sass-loader** should not compressed CSS file, there is other tool for that.

Cheers

**Comment by jimblue** [comment]
Probably because **dart-sass** accept only two options **outputStyle**...
 As their doc says:

> Only the "expanded" and "compressed" values of outputStyle are supported.

**Comment by evilebottnawi** [comment]
Look here https://github.com/webpack-contrib/sass-loader/blob/master/src/getSassOptions.js#L68, by default we yse compressed output when you in production mode, you can change this using `sassOptions.outputStyle`, but it is not recommend

**Comment by haakenlid** [comment]
This bug caused some really annoying problems for us, which I just wasted many hours trying to figure out.

With the `compressed` output, autoprefixer comments are stripped out, which disables postcss-preset-env features. But this happens silently, and only when building for production. 

Here's a related bug with further explanation:
https://github.com/symfony/webpack-encore/issues/638

**Comment by andreyvolokitin** [comment]
I think this is more of a convention of minifying all resources for production. I simply turned off SASS minification and had no problems

**Comment by haakenlid** [comment]
I'd rather have the postcss-loader get the same input in production as in development. 

I use a minifier as the last webpack loader for css files in production, so I don't need sass-loader to magically determine whether to minify its output or not. 

It would make more sense that people who use sass-loader by itself pass in `outputStyle: 'compressed'` instead, if that's what they want.

**Comment by FloatingShuYin** [comment]
Time has passed so long, hasn't this issue been taken seriously?
sass-loader should not do minify!

https://github.com/FullHuman/purgecss/issues/294

**Comment by wangxianfa** [comment]
The root cause is loaderContext.mode is undefined. so isProductionLikeMode function return true

`function isProductionLikeMode(loaderContext) {
  return (
    loaderContext.mode === 'production' ||
    !loaderContext.mode ||
    loaderContext.minimize
  );
}`

**Comment by kirkbross** [comment]
> I think this is more of a convention of minifying all resources for production. I simply turned off SASS minification and had no problems

how do you  turn it off? no matter what outputStyle I pass to sass it returns compressed. 'expanded' or 'compressed' result in compressed.

**Comment by WangZhenHao** [comment]
In production mode "sass-loader": "^7.2.0" compressed CSS file had bug。It change that CSS's content property  value

![1677138796874](https://user-images.githubusercontent.com/26181934/220850301-d21dfa3e-08bf-4393-8e71-b8169eddb283.jpg)

**Comment by Wiktor102** [comment]
It seems like the option is called `style` and not `outputStyle` (at least for `dart-sass` using the `sass` package). [Documentation](https://sass-lang.com/documentation/js-api/interfaces/options/#style).
The following works as expected:
```js
{
  loader: "sass-loader",
  options: {
    sassOptions: {
      style: "expanded"
    }
  }
}
