### ISSUE TITLE
Add support for SASS modules - @use

### ISSUE THREAD

**Issue by donnysim** [webpack-contrib/sass-loader#766]
- Operating System: -
- Node Version: -
- NPM Version: -
- webpack Version: -
- sass-loader Version: -

### Feature Proposal
While `@use` is new and libsass, ruby sass does not support it yet, you can fully use it with dart sass, so it would be awesome if it could track imports from `@use` statements and trigger watchers.

### Feature Use Case
http://sass.logdown.com/posts/7858341-the-module-system-is-launched

**Comment by donnysim** [comment]
Might've been my bad, it does seem to track @use imports.

**Comment by evilebottnawi** [comment]
@donnysim `use` already supported?

**Comment by donnysim** [comment]
@evilebottnawi using it with dart sass 1.23.0 and everything works, it tracks dependencies etc. just fine. I thought it didn't work, but I just messed up the use path to the wrong file so it didn't track the correct file for changes. Haven't tried it with node_modules but don't really have anything requiring it atm..

**Comment by evilebottnawi** [comment]
@donnysim thanks for feedback, will be great if we add tests for `@use`, you can help :smile:

**Comment by donnysim** [comment]
I'm not sure what would be the way to add a test when only dart sass supports it for the time being.

**Comment by evilebottnawi** [comment]
Just add tests only for dart sass :smile:
