### ISSUE TITLE
Unable to use sass-loader with Foundation. Issue with module resolution and includePaths

### ISSUE THREAD

**Issue by itrew** [webpack-contrib/sass-loader#767]
- Operating System: Windows 10
- Node Version: 10.16.3
- NPM Version: 6.9.0
- webpack Version: 4.41.0
- sass-loader Version: 8.0.0

### Expected Behavior

Sass to be compiled properly. Dart Sass on its own is able to render with the same options passed.

### Actual Behavior

Unable to correctly resolve a folder with `node_modules/foundation-sites/scss`
```
ERROR in ./src/main.scss
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @import 'util/util';
  │         ^^^^^^^^^^^
  ╵
  src\_settings.scss 1:9  @import
  C:\development\sass-loader-issue\src\main.scss 2:9               root stylesheet
 @ ./src/index.js 1:0-31
```

### How Do We Reproduce?

I have created a repo [here](https://github.com/itrew/sass-loader-issue) for reproducing the bug.

Possibly related to #684

**Comment by evilebottnawi** [comment]
Interesting problem - for resolving modules we use webpack resolver and respect user options in `resolve` option (by default webpack use https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L328 and https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L329)

But in your project you have package `node_modules/util/util.js` and webpack resolve this for `@import 'util/util';`, i will look what we can do in this case. 

Workarounds: 
- use only `includePaths` and disable `webpackImporter` (https://github.com/webpack-contrib/sass-loader#webpackimporter)
- use only `webpack` resolve and don't use `includePaths`

You example is edge where webpack resolver convict with `includePaths`, anyway we should fix it.

**Comment by tarjei** [comment]
I tried this workaround, but still got the same error:
```js
{
        loader: 'sass-loader',
        options: {
          // https://github.com/webpack-contrib/sass-loader/issues/767
          webpackImporter: false,
          sassOptions: {
            includePaths: [
              path.resolve(rootPath, 'node_modules/foundation-sites/scss'),
              path.resolve(rootPath, 'scss'),
            ],
          },
        },
      },
```

Gives:

```

  ModuleBuildError: Module build failed (from ../node_modules/sass-loader/lib/loader.js):
  
  @import 'util/util';
  ^
        File to import not found or unreadable: util/util.
 
```

**Comment by ranisalt** [comment]
Same happens with every single `@material` package.

**Comment by evilebottnawi** [comment]
@ranisalt can you create reproducible test repo, it is allow to me ensure all bugs was fixed

**Comment by itrew** [comment]
@evilebottnawi So in `importsToResolve.js` no matches are found, it passes the url as a potential target for webpack to try and resolve.

https://github.com/webpack-contrib/sass-loader/blob/69e3ddcc8bdb33ef5ed0c030f03f84d80fb75a39/src/importsToResolve.js#L86-L87

Would it make sense to remove those two lines and lean on the `~<module-name>` syntax to explicitly say that webpack should handle this import, and if not preceded by `~` let sass handle it (with the benefit of `includePaths`)? Otherwise if no match is found, it still passes to webpack, making the `~` essentially optional.

**Comment by evilebottnawi** [comment]
@itrew do you mean check path using `includePaths`? Example:
```
if (isIncludePaths(path)) {
  // Return it to sass/node-sass
  return path;
}

// Other resolution's logic
```

**Comment by itrew** [comment]
@evilebottnawi That seems like it would work well.

**Comment by evilebottnawi** [comment]
Found solution
