### ISSUE TITLE
Export variables through the module with a special field

### ISSUE THREAD

**Issue by resolritter** [webpack-contrib/sass-loader#768]
:exclamation:  I do know this has been brought up in https://github.com/webpack-contrib/sass-loader/issues/617 but I'm not sure if I agree with the "good solution". For instance, if you're transitioning stylesheets between different code bases, those custom functions will be absent and the whole code would need to be refactored around those places. It's not "natural" SCSS dialect and the approach seems overly complicated.

### System

- Operating System: Arch Linux
- Node Version: v12.10.0
- NPM Version: 6.11.3
- webpack Version: 4.40.2
- sass-loader Version: 8.0.0

### Expected Behavior / Situation

I was trying to use Sass variables in JS context. In this case I use some color values for drawing SVGs using React's JSX syntax, and also generating textures and graphics with Three.js.

### Actual Behavior / Situation

After importing the module, I do not get the variables. e.g.

Suppose this is `_variables.scss`

```scss
$background: #333333
```
From JS

```js
import vars from "./_variables.scss"
```

It does not work

### Modification Proposal

Variables could be brought together with the classes, like this:

```json
{
   "~VARS~": {
   "background": "#333333"
   }
}
```

If we make the variables' field name start with some character which would be invalid SCSS syntax, there would never be collisions.

**Comment by evilebottnawi** [comment]
It is out of scope `sass-loader`, you can store variables in json/js, you offer a completely non-standard solution for organizing the code in the project, you can write own loader for this purposes, sass-loader do not generate js code and `import vars from "./_variables.scss"` do not work, you can look in css-loader and find how it can be completed
