### ISSUE TITLE
mini-css-extract-plugin not extract vendors from /node_modules/

### ISSUE THREAD

**Issue by HairyRabbit** [webpack-contrib/sass-loader#769]
- Operating System:
- sass-loader Version: 8.0.0

Hi. would any way to extract module from `node_modules` when bundle css vendor code? disable `webpackImporter` was ok, but it will broken `resolve.alias`.

### Code

```js
const CssExtract = require('mini-css-extract-plugin')

module.exports = {
  mode: 'production',
  entry: './style.scss',
  module: {
    rules: [{
      test: /css$/,
      use: [ 
        CssExtract.loader, 
        {
          loader: 'css-loader',
          options: {
            importLoaders: 1
          }
        },
        'sass-loader'
        }
      ]
    }]
  },
  plugins: [
    new CssExtract()
  ],
  optimization: {
    splitChunks: {
      cacheGroups: {
        vendor: {
          test: /node_modules/,
          name: 'vendor',
          chunks: 'all',
          priority: 1000,
          enforce: true
        }
      }
    }
  }
}
```

**Comment by evilebottnawi** [comment]
I can't understand problem

**Comment by HairyRabbit** [comment]
I write a test repo at [here](https://github.com/HairyRabbit/test-sass-loader-vendor-bundle).

The code:

```scss
@import '~normalize.css';
body { color: red; }
```

bundled main.css only. would this split `normalize.css` code to vendor.css ?

the webpack output, with webpackImporter:

```sh
Hash: dcd6bd65521b6271b170
Version: webpack 4.41.0
Time: 658ms
Built at: 10/07/2019 7:30:55 PM
   Asset       Size  Chunks             Chunk Names
main.css   1.83 KiB       0  [emitted]  main
 main.js  932 bytes       0  [emitted]  main
Entrypoint main = main.css main.js
[0] ./style.scss 39 bytes {0} [built]
    + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--4-1!node_modules/sass-loader/dist/cjs.js!style.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/sass-loader/dist/cjs.js!./style.scss 1.99 KiB {0} [built]
        + 1 hidden module
```

disable webpackImporter:

```sh
Hash: d7a24467a0edf814632f
Version: webpack 4.41.0
Time: 346ms
Built at: 10/07/2019 7:41:52 PM
     Asset      Size  Chunks             Chunk Names
  main.css  17 bytes       0  [emitted]  main
   main.js  1.49 KiB       0  [emitted]  main
vendor.css  1.81 KiB       1  [emitted]  vendor
 vendor.js  61 bytes       1  [emitted]  vendor
Entrypoint main = vendor.css vendor.js main.css main.js
[0] ./style.scss 39 bytes {0} [built]
    + 2 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--4-1!node_modules/sass-loader/dist/cjs.js??ref--4-2!style.scss:
    Entrypoint mini-css-extract-plugin = *
    [1] ./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/sass-loader/dist/cjs.js??ref--4-2!./style.scss 305 bytes {0} [built]
        + 2 hidden modules
```

**Comment by evilebottnawi** [comment]
Please use stackoverflow or gitter for questions, you can do it using `cacheGroups`, for example:
```
cssVendors: {
  // You can use "all", if you need
  // chunks: "initial",
  enforce: true,
  name: "vendor",
  priority: -10,
  test: module => {
    const moduleName = module.nameForCondition
      ? module.nameForCondition()
      : "";

    return (
     /[\\/]node_modules[\\/]/i.test(moduleName) &&
     /\.css/i.test(moduleName)
    );
  }
}
```

Please read documentation how it is work on official site. Problem not related to sass-loader

**Comment by HairyRabbit** [comment]
@evilebottnawi Thanks for reply.
I already tested you code before comment this issue, because I use similar code to bundle other type css library. In my case, some code can bundle to vendor, and some not. see the code:

```scss
@import '~sanitize.css';
@import '~sanitize.css/typography.css';
@import '~sanitize.css/forms.css';
```

The `sanitize.css` will not bundle to vendor. but the `sanitize.css/typography.css` and `sanitize.css/forms.css` will go. Looks like the resolver not read main field from package.json. So I think this maybe a bug of webpackImporter.

So that, the code will generate vendor and entry two bundles with same content:

```scss
@import '~normalize.css';
@import '~normalize.css/normalize.css';
```

```sh
Hash: 5820868279755358507d
Version: webpack 4.41.0
Time: 360ms
Built at: 10/08/2019 8:01:45 PM
     Asset      Size  Chunks             Chunk Names
  main.css  1.81 KiB       0  [emitted]  main
   main.js  1.49 KiB       0  [emitted]  main
vendor.css  1.81 KiB       1  [emitted]  vendor
 vendor.js  61 bytes       1  [emitted]  vendor
Entrypoint main = vendor.css vendor.js main.css main.js
[0] ./style.scss 39 bytes {0} [built]
    + 2 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--4-1!loader.js!node_modules/sass-loader/dist/cjs.js??ref--4-3!style.scss:
    Entrypoint mini-css-extract-plugin = *
    [1] ./node_modules/css-loader/dist/cjs.js??ref--4-1!./loader.js!./node_modules/sass-loader/dist/cjs.js??ref--4-3!./style.scss 2.15 KiB {0} [built]
        + 2 hidden modules
```

**Comment by evilebottnawi** [comment]
sass-loader just compile scss/sass to css, no logic for exporting/extracting and etc.

`And the code will build twice to entry bundle` because you import multiple time, node-sass and sass (dart-sass) compile multiple times when you use multiple import we don't change this logic because it can wrong and potentially break other applications

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo and describe in readme what you have and what you expected. Hard to understand problem, thanks

**Comment by HairyRabbit** [comment]
Ok, the question may convert to "would sass-loader resolve mainFileds from package.json". Please move to [this repo](https://github.com/HairyRabbit/test-sass-loader-vendor-bundle).

**Comment by evilebottnawi** [comment]
@HairyRabbit 
> would sass-loader resolve mainFileds from package.json

Yes,
https://github.com/webpack-contrib/sass-loader/blob/master/src/index.js#L43 but you need minimum `4.36.0` version (https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L38)

**Comment by HairyRabbit** [comment]
@evilebottnawi well, I checked source code, known this already setup, but also not work for me. my webpack version was latest 4.41.0.

**Comment by evilebottnawi** [comment]
I will look on this in near future

**Comment by evilebottnawi** [comment]
@HairyRabbit here interesting case, `sass` (`dart`) and `node-sass` have difference behavior for `@import "something.css"`: `sass` (`dart`) ignore all `@import` ending with `.css` http://www.sass-lang.com/documentation/at-rules/import#plain-css-imports so all `@import` keeping as is

Explanation (`npm run start:disabled`):
1. We have code:
```scss
@import '~normalize.css';
@import '~normalize.css/normalize.css';
```
2. sass-loader output this (keeping `@import` as is according libsass spec):
```css
@import '~normalize.css';
@import '~normalize.css/normalize.css';
```
3. `css-loader` handle all `@import` and run `sass-loader` for each `@import` because you use `importLoaders: 1` 
4. So you got this file after build:
```
/* Code from `@import '~normalize.css';` */
/* Code from `@import '~normalize.css/normalize.css'; */
```
5. When `splitChunks` split code on main and vendor

**Don't forget you can't split code from `sass-loader`** Why? Because `sass-loader` just run node-sass/sass (dart) and output compiled code (it is default behavior for libsass).

If you need split something you should use `import`/`require` from `JS` file. Perhaps we can implement this in the future, but for the moment sass do not output enough information for splitting.

**Comment by HairyRabbit** [comment]
@evilebottnawi ye, as a matter of fact, I found that the problem was moving code from js entry to css file. At css, the import order was important, if some part not split out, they may got a wrong load order, because vendor usually load before other module. 

Now would we still keep this behave? I wish sass-loader can manage `@import` rule then safe pass to css-loader. Sass already has other way to include code like `@include` or `@use`. and sass-loader already has some different from sass like prepend `~`.

If not, would we add some documents about this. :)

**Comment by evilebottnawi** [comment]
@HairyRabbit 

> Now would we still keep this behave? I wish sass-loader can manage @import rule then safe pass to css-loader.

What do you mean? sass-loader handle all `@import` according spec, sometimes you need what each `@import` in css uses `postcss-loader`/`sass-loader` (maybe both), so we have option for this in css-loader, you can notice it is `0` by default.

What we should documented?
