### ISSUE TITLE
Upgraded to latest npm and now getting compile errors

### ISSUE THREAD

**Issue by DavidLozzi** [webpack-contrib/sass-loader#775]
- Operating System: MacOSX Mojave AND Windows 10
- Node Version: v12.13.0
- NPM Version: 6.12.0
- webpack Version: 4.41.2
- sass-loader Version: 8.0.0

### Expected Behavior
It to install and function
### Actual Behavior
When we run `npm install` on our project, we get some errors (long list) 
Then when we try to run our ReactJs app, I get the following:
![image](https://user-images.githubusercontent.com/3543383/68326111-cfd39380-0098-11ea-89d5-614f201dda86.png)

I reverted back to npm 6.9, node 10.16.3, deleted our node_modules folder and ran npm install again and everything is fine again.

Unsure if this is a bug on npm side or this library. Also we are not using sass-loader directly in our project, it's a dependency for react-scripts

### How Do We Reproduce?

Using create-react-app, run on the versions mentioned above

**Comment by evilebottnawi** [comment]
Can reproduce, what are steps you do?

**Comment by DavidLozzi** [comment]
updated above, it's a create-react-app running on the latest npm

**Comment by evilebottnawi** [comment]
You need install `node-sass`, please read https://create-react-app.dev/docs/adding-a-sass-stylesheet/, if you still have problem please open issue in `create-react-app`, we can't do something on our side

**Comment by DavidLozzi** [comment]
thanks, I thought it was something like that, but I couldn't google it.
