### ISSUE TITLE
What about the options.outputStyle parameter?

### ISSUE THREAD

**Issue by silversonicaxel** [webpack-contrib/sass-loader#779]
I upgraded the sass-loader from version 7.1.0 to version 8.0.0

The webpack configuration was the following (sass loader 7.1.0)

```
       {
        loader: 'sass-loader',
        options: {
          outputStyle: 'compressed',
          sourceMap: true
        }
      }
```

After migrating I have this issue:

```
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
[build:css] [build:css:MYTHEME]  - options has an unknown property 'outputStyle'. These properties are valid:
[build:css] [build:css:MYTHEME]    object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
```

I was wondering what should be the new configuration (sass loader 8.0.0)

```
       {
        loader: 'sass-loader',
        options: {
          sassOptions: {
            outputStyle: 'compressed'
          }
          sourceMap: true
        }
      }
```

If that's correct, I would be more specific in the README at this comment

> ℹ In some rare cases node-sass can output invalid source maps (it is a node-sass bug). In order to avoid this, you can try to update node-sass to latest version or you can try to set the outputStyle option to compressed.

**Comment by evilebottnawi** [comment]
Feel free to send a PR to docs

**Comment by silversonicaxel** [comment]
Created here, thanks https://github.com/webpack-contrib/sass-loader/pull/780
