### ISSUE TITLE
Warning Peer dependency of Node-Sass, but I am using Dart Sass

### ISSUE THREAD

**Issue by ggedde** [webpack-contrib/sass-loader#787]
- Operating System: MacOS 10.14.6
- Node Version: v12.3.1
- NPM Version: 6.9.0
- webpack Version: 4.41.4
- sass-loader Version: 8.0.0
- sass Version: 1.24.0

### Expected Behavior / Situation
When using Dart Sass I shouldn't get warnings about a peer dependency of Node-Sass is required
### Actual Behavior / Situation
When using Dart Sass I am getting warnings about a peer dependency of Node-Sass is required.
```
npm WARN sass-loader@8.0.0 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
```
### Modification Proposal
I think that this peer dependency warning should only be shown if both sass and node-sass are not present.  Or just remove this peer dependency all together since Dart Sass is much better now and more and more people are using it.

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/sass-loader/issues/749#issuecomment-526541292
