### ISSUE TITLE
Help: how can i add webpack loader to handle scss-loader @import scss file

### ISSUE THREAD

**Issue by Mrwaite** [webpack-contrib/sass-loader#790]
my webpack.config.js file is:
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.s[ac]ss$/i,
        use: [
          'style-loader',
          'css-loader',
          'sass-loader',
          // custom webpack loader
          'theme-loader',
        ],
      },
    ],
  },
};
```

a simple scss file is that:
```
@import "./scss/variable.scss";
.a{
background: white;
} 
```

how can i make `./scss/variable.scss` file also to be processed by `theme-loader`, which is a custom webpack loader in order to handle some sass conversion

**Comment by evilebottnawi** [comment]
Please use stackoverflow or glitter for questions, you can solve this using different approaches:
1. using alias
2. using https://github.com/sass/node-sass#importer--v200---experimental
3. parse sass file and change path to `"./scss/variable.scss"`
