### ISSUE TITLE
Devops artifact not resolving webpack alias

### ISSUE THREAD

**Issue by roro1000** [webpack-contrib/sass-loader#799]
I have 3 projects inside a solution. One project is a shared project which holds react components and shared js files.

I use aliases in the other two projects to reference the shared files. This works locally. However, when I build the other two projects in devops and run the artifact against an iis website I get 'module not found' one one of my shared js files in the shared project.

Does anyone have any ideas? Is it possible that the aliases don't work when the projects are built in devops?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use stackoverflow and gitter for questions

**Comment by atilkan** [comment]
@evilebottnawi Update the docs. importer not supported anymore. Give useful information at least.
