### ISSUE TITLE
Doesn't work by default with yarn v2 / berry

### ISSUE THREAD

**Issue by andreialecu** [webpack-contrib/sass-loader#802]
### Actual Behavior / Situation

The new version of Yarn, v2, packs dependencies in `.zip` files instead of keeping them in `node_modules`. `sass-loader` uses `node-sass` which is a native binary and it bypasses the module resolution of yarn, resulting in errors such as:

```
ERROR in ./src/styles/app.scss (./.yarn/$$virtual/css-loader-virtual-25ac65d05c/0/cache/css-loader-npm-3.4.2-300ee159b3-1.zip/node_modules/css-loader/dist/cjs.js?sourceMap=true!./.yarn/$$virtual/sass-loader-virtual-528b2c3b95/0/cache/sass-loader-npm-8.0.2-f0d209ad64-1.zip/node_modules/sass-loader/dist/cjs.js!./src/styles/app.scss)
Module build failed (from ./.yarn/$$virtual/sass-loader-virtual-528b2c3b95/0/cache/sass-loader-npm-8.0.2-f0d209ad64-1.zip/node_modules/sass-loader/dist/cjs.js):
SassError: File to import not found or unreadable: .yarn/$$virtual/bootstrap-virtual-a4283f726d/0/cache/bootstrap-npm-4.4.1-16b3a7c0d2-1.zip/node_modules/bootstrap/scss/bootstrap-reboot.scss.
        on line 1 of /src/styles/app.scss
>> @import '~bootstrap/scss/bootstrap-reboot';
```
Notice how the path of the file is shown as `.../.yarn/$$virtual/bootstrap-virtual-a4283f726d/0/cache/bootstrap-npm-4.4.1-16b3a7c0d2-1.zip/node_modules/bootstrap/scss/bootstrap-reboot.scss.` (there's a .zip file in the middle)

### Modification Proposal

The only way this can work right now is by setting the [implementation option](https://github.com/webpack-contrib/sass-loader#implementation) to `sass` instead of `node-sass`. Since `sass` is a javascript implementation, it will be able to resolve files from the `.zip` files through yarn's pnp resolution mechanism.

The alternative is to run commands like `yarn unplug bootstrap`, so that files are stored unzipped in the yarn cache.

I think it would be a good idea to detect if yarn v2 is being used and show a better error message than the one above. I feel this is going to start becoming a common problem.

**Comment by soloalex1** [comment]
I have a similar problem here. When I run my app, it throws me the `A package is trying to access a peer dependency that should be provided by its direct ancestor but isn't` error.

**Comment by andreialecu** [comment]
@soloalex1 That's not related to sass loader though. Try the yarn discord if you're stuck. You can get clues there.

**Comment by wegry** [comment]
To get sass-loader to play nicely with yarn 2, I had to add this to my `.yarnrc.yml`

```yaml
# .yarnrc.yml
packageExtensions:
  'sass-loader@*':
    optionalDependencies:
      node-sass: '*'
```

Does the concept of `optionalDependencies` exist in regular `package.json`s?

**Comment by DimitrK** [comment]
Same here. 

```
@import '../../css/mixins/keyframes.scss';
^
      File to import not found or unreadable: ~/.yarn/$$virtual/shared-virtual-723db036ba/1/shared/ui/css/mixins/keyframes.scss.
```


any update on this?

**Comment by evilebottnawi** [comment]
I found a problem - `includePaths` is not compatibility with yarn pnp, because it is try to read a file from `node_modules`, but we don't have `node_modules`, not sure we can't fix it on our side

@DimitrK Can you create reproducible test repo?

**Comment by kubijo** [comment]
FYI to all weary search results travelers… I think I've managed to get `node-sass` working with PNP by creating custom `importer` (I wasn't able to persuade the Dart version, but then again I didn't give it too much attention as it's reportedly much slower).

Here's the Gist (it should hopefully contain everything needed).
https://gist.github.com/kubijo/8c2346dcfe6a3380a700906c4bd6bb04

Can't really say much about it in terms of speed or bugs as I've just finished it and got our project working after a long day… so if your cat catches on fire, it's on you ;-)

**Comment by evilebottnawi** [comment]
@kubijo current importer uses `enhanced-resolve@4` package for resolving (it is provided by webpack@4) and that package doesn't supported PnP, webpack@5 will have `enhanced-resolve@5` with supporting PnP, i think it should solve problem, anyway if somebody create minimum reproducible test repo I will investigate it and try to solved or provide workarounds

**Comment by kubijo** [comment]
@evilebottnawi You got me a little lost there.

My problem was that after migration to yarn 2 sass-loader stoped resolving imports from 3rd-party modules. Somewhere I found a tip to change the implementation to `require('sass')`, but didn't work either.

My solution was then to create custom importer for `node-sass` as I've mentioned & linked above.

--------

Anyway
- Is there any problem of using `enhanced-resolve@5` in `webpack@4`?
- Is there any expected date for `webpack@5` stable release?

**Comment by evilebottnawi** [comment]
> Is there any problem of using enhanced-resolve@5 in webpack@4?

No, breaking changes

> Is there any expected date for webpack@5 stable release?

No due covid

Anyway can you create minimum reproducible test repo?

**Comment by kubijo** [comment]
I'll make a note to re-visit this later on and will try to create both working and broken examples… now I just need to finish-up the migration so that the rest of my team can use it.

I'd like to finish that today.

**Comment by DimitrK** [comment]
I went with `sass` instead of `node-sass` for the time being and worked fine.

I understand the urgency on something being a stopper @kubijo  but it was straight forward. 
All I had to do was to add in package.json the 3rd party css libraries along with `"sass": "^1.26.3"` & change in webpack config the sass loader  in `module.rules` to the following:
```js
            {
              loader: require.resolve('sass-loader'),
              options: {
                implementation: require('sass'),
              }
            }
```

**Comment by evilebottnawi** [comment]
We switch on `sass` (`dart`) by default (you can still use `node-sass`) in the next version, so there should be no more problems, I will update the documentation for `yarn` pnp users, I think it is enough, don't know how we can improve error message in this case, because for `importer` any value in `@import`/`@use` is URL, in theory we can check `.yarn` directory in resolved path, but I don't think we really need extra check here, maybe `node-sass` improve `yarn` PnP support in future, anyway if somebody have ideas how to improve it better feel free to send more information to docs.

**Comment by thefoxie** [comment]
Hey @evilebottnawi, I still get the error.
```
SassError: Can't find stylesheet to import.
@import "~bulma/sass/utilities/_all";
```
```
"sass": "^1.26.10",
"sass-loader": "^10.0.2",
```

**Comment by evilebottnawi** [comment]
@thefoxie check your configuration, if it is unresolved then it doesn't exist

**Comment by thefoxie** [comment]
@evilebottnawi actually that's the point of pnp. There's nothing in node_modules, but it should be resolved from yarn's cache anyway.

**Comment by evilebottnawi** [comment]
@thefoxie for pnp you need to use webpack@5 or webpack@4 with pnp plugin, otherwise it will not work

**Comment by thefoxie** [comment]
Well I think the issue will be in webpack configuration. I use vue-cli and tried both adding pnp plugin and webpack@5. Nothing resolves those scss files from pnp.

**Comment by evilebottnawi** [comment]
@thefoxie Please create reproducible test repo

**Comment by thefoxie** [comment]
@evilebottnawi here it is https://github.com/thefoxie/vuecli-yarn2

**Comment by evilebottnawi** [comment]
@thefoxie looks like `vue-cli` does not support PnP right now, there are a lot of strange things, I would suggest you open the issue in their repository,

**Comment by evilebottnawi** [comment]
@thefoxie Maybe you can reproduce the problem without `vue-cli`? Sorry, I don't have enough time for this right now, the previous original was resolved and everything worked fine

**Comment by thefoxie** [comment]
@evilebottnawi everything worked so far but I got your point. Thank you anyway :)

**Comment by thefoxie** [comment]
@evilebottnawi yeah I will try but webpack can be bitch to configure and it should work in vue-cli as well, theoretically at least

**Comment by evilebottnawi** [comment]
@thefoxie PnP is not easy features, so it can work in webpack, but can't work in `vue-cli` :smile: Feel free to ping me and I will help you

**Comment by arcanis** [comment]
Fwiw it's supposed to work in vue-cli, Yarn has [an E2E test](https://github.com/yarnpkg/berry/blob/master/.github/workflows/e2e-vue-cli-workflow.yml) to monitor that 🤔

**Comment by evilebottnawi** [comment]
@andreialecu `sass` and the `includePaths` option do not have good compatibility with yarn PnP

**Comment by rtritto** [comment]
Same error in a `video-js.scss` file in `video.js` module.
File path: `.yarn/cache/video.js-npm-7.12.1-53ac059ebb-e371896a4d.zip/node_modules/video.js/src/css/video-js.scss`
> SassError: Can't find stylesheet to import.
@import "node_modules/videojs-font/scss/icons";

> "sass": "^1.32.11"
"sass-loader": "^10.0.5"
"yarn": "2.4.1"

**Comment by ShaMan123** [comment]
any updates?

**Comment by rtritto** [comment]
Still not work.
I don't use `react-scripts`.

**Comment by arcanis** [comment]
@rtritto your problem has nothing to do with either Yarn nor Webpack. As the error hints, your third-party (video.js) hardcodes `node_modules` in the sass files they ship, which cannot work when installs are made without node_modules (which has been the default starting from 2.0).

https://cdn.jsdelivr.net/npm/video.js@7.11.8/src/css/video-js.scss

**Comment by alamothe** [comment]
Has anyone got `node-sass` to work with PNP?

The issue with `sass` is that it is just too slow, our big project needs around 2-3 minutes to start in dev mode with it, while with `node-sass` it is only around 10s.

**Comment by Lonli-Lokli** [comment]
In my case this line does not work too, reported to stylesheet found `@include meta.load-css('tippy.js/dist/tippy.css');`

**Comment by yoyo837** [comment]
I get the same error when I use `@include meta.load-css('tailwindcss/lib/css/preflight.css');` I am also based on `vue-cli@5`. Any suggestions?
