### ISSUE TITLE
prependData not working at all for sass-loader 8.0.2

### ISSUE THREAD

**Issue by novaknole** [webpack-contrib/sass-loader#803]
- Operating System: Mac
- Node Version: 12.14.1
- NPM Version: 6.13.4
- webpack Version: 4.41.5
- sass-loader Version: 8.0.2

### Expected Behavior

I want to use prepentData functionality of sass-loader. Basically I have the .scss file in which I got something like this:

```$static-url: '';```

in my other scss files, I include above scss and use $static-url in one of the tag's src's attribute. Like this.

```
src: url($static-url + '/assets/fonts/gotham-rounded/GothamRounded-LightItalic.woff2') format('woff2');
```

Now, in webpack, in scss loader, I got the following thing:

```
{
                test: /\.scss$/,
                use: [
                    isDev ? 'vue-style-loader' : MiniCSSExtractPlugin.loader, 
                    'css-loader', 
                    {
                        loader: 'sass-loader',
                        options: {
                          prependData: '$static-url: ' + process.env.NODE_ENV + ';',
                        },
                      },
                ]
            },
```

Now, What I expect is that after the build, if i look for the bundled css, static-url in font-face should be the string - process.env.NODE_ENV instead of the empty one.

### Actual Behavior
After sass-loader, it generates css file and when I check css file, it has:

```src: url('/assets/fonts/gotham-rounded/GothamRounded-LightItalic.woff2') format('woff2');``` which is wrong, url should start with process.env.NODE_ENV value.

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

```js
// additional code, HEY YO remove this block if you don't need it
```

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, `prependData` added on top of files so you have code like that:

```
$static-url: 'production'; // Here process.env.NODE_ENV
$static-url: '';

a {
  src: url($static-url + '/assets/fonts/gotham-rounded/GothamRounded-LightItalic.woff2') format('woff2');
}
```

You can rewrite code like:
```
$static-url: 'test';
$static-url: '' !default;

a {
  src: url($static-url + '/assets/fonts/gotham-rounded/GothamRounded-LightItalic.woff2') format('woff2');
}
```

**Comment by novaknole** [comment]
Still not working. I made the demo.

https://github.com/novaknole/test123 here it is. if you clone this and run ```npm run prod```, you will see that it will generate `css` file in dist folder. in that css, the color is still `test` instead of the `production`.

the entry point of webpack is app.js. 

Looking forward to hearing from you.

**Comment by evilebottnawi** [comment]
Delete that line https://github.com/novaknole/test123/blob/master/test.scss#L1 and
use `prependData: '$static-url: ' + JSON.stringify(process.env.NODE_ENV) + ';',` here https://github.com/novaknole/test123/blob/master/webpack.conf.js#L41
