### ISSUE TITLE
Importer option doesn't exist anymore in v8?

### ISSUE THREAD

**Issue by IgorSushko1** [webpack-contrib/sass-loader#805]
- Operating System: windows 10 pro
- Node Version: v10.15.3
- NPM Version: 6.4.1
- webpack Version: ^4.41.6
- sass-loader Version: 8.0.2

### Expected Behavior

I use in webpack sass-loader with options -  importer: globImporter(), in ^7.3.1 version is importer work

### Actual Behavior

In new 8.0.2 i have an error -- 
    ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
     - options has an unknown property 'importer'. These properties are valid:
       object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }

### How Do We Reproduce?
Install sass-loader 8.0.2 and write importer option in webpack.config

**Comment by evilebottnawi** [comment]
Moved to `sassOptions`, because it is the option for sass https://github.com/webpack-contrib/sass-loader#sassoptions

**Comment by yangdan8** [comment]
Closed for no reason??

**Comment by evilebottnawi** [comment]
Please read answer

**Comment by IgorSushko1** [comment]
> Please read answer

I remember that it was a change in api, so I just find a new command name or chain of commands
