### ISSUE TITLE
ERROR in ./src/private/sass/base.scss (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js!./src/private/sass/base.scss) Module build failed (from ./node_modules/sass-loader/dist/cjs.js)

### ISSUE THREAD

**Issue by patrickmsieber** [webpack-contrib/sass-loader#818]
**Already tried out**
npm install --save-dev webpack
npm rebuild node-sass

**Current Error**
`ERROR in ./src/private/sass/base.scss (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js!./src/private/sass/base.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Base-level rules cannot contain the parent-selector-referencing character '&'.
        on line 135 of src/private/sass/components/_cross_button.scss
        from line 16 of src/private/sass/components/_all.scss
        from line 6 of /Users/username/workspace/myproject/Resources/Public/src/private/sass/base.scss
>> .collapsed &  .navbar-toggler {

   -----------^

 @ ./src/private/sass/base.scss 2:26-201
 @ ./src/private/js/style.js`

**webpack.config.js**
`const webpack = require('webpack');
const path = require('path');
const merge = require('webpack-merge');
const babel_polyfill = require('babel-polyfill');

const middleware = require('webpack-dev-middleware');
const express = require('express');
const app = express();

const parts = require('./webpack_config/lib');

const ProgressBarPlugin = require('progress-bar-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');

const autoprefixer = require('autoprefixer');

const APP_ROOT = path.join(__dirname, '/src/private');
const STATIC_ROOT = path.join(__dirname, 'src/static');

const PATHS = {
    app: path.join(APP_ROOT, '/js/app'),
    style: path.join(APP_ROOT, 'js/style'),
    build: path.join(STATIC_ROOT, 'dist')
};

const common = {
    entry: {
        app: ['babel-polyfill', PATHS.app],
        style: PATHS.style,
    },
    output: {
    	path: path.resolve(PATHS.build),
        publicPath: '/static/dist/',
    },
    module: {
        rules: [
            {
                test: /\.js?$/,
                exclude: /node_modules\/(?!(dom7|ssr-window|swiper)\/).*/,
                use: {
                    loader: 'babel-loader',
                    query: {
                      presets: ['@babel/preset-env'],
                      plugins: ['add-module-exports']
                    }
                }
            }, 
            {
            	test: /\.scss?$/,
                use: [
                    'style-loader',
                    { loader: 'css-loader', options: { importLoaders: 1 } },
                    'postcss-loader',
                    'sass-loader'
                ]
            }, 
            {
            	test: /\.css?$/,
            	use: [
                    'style-loader',
                    { loader: 'css-loader', options: { importLoaders: 1 } },
                    'postcss-loader'
                ]
            },
            {test: /\.(jpg|gif|png)$/, loader: 'url-loader?limit=100000' },
            {test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/font-woff'},
            {test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/octet-stream'},
            {test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: 'file'},
            {test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=image/svg+xml'}
        ],
    },
    resolve: {
        alias: {
            'root': __dirname,
        },
        modules: ['node_modules']
    },
    plugins: [
        // autoprefixer({ browsers: ['last 2 versions'] }),
        require('precss'),
        require('autoprefixer'),
        new MiniCssExtractPlugin(),
        new ProgressBarPlugin(),
        new CleanWebpackPlugin(['dist'], {
            root: __dirname,
            verbose: true,
            dry: false
        }),
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery"
        })
    ]
};

var config;
// Detect how npm is run and branch based on that
switch(process.env.npm_lifecycle_event) {
    case 'build':
        config = merge(common, parts.production());
    break;
    default:
        config = merge(common, parts.production());
        // const compiler = webpack(config); development
        // app.use(middleware(compiler, {
        //     index: 'src/html/index.html'
        // }));
}

module.exports = config;

`

**package.json**
`{
  "name": "webpack-intro",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "./node_modules/webpack/bin/webpack.js",
    "dev": "./node_modules/webpack/bin/webpack.js -w",
    "dev-server": "./node_modules/webpack-dev-server/bin/webpack-dev-server.js --content-base example/"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "autoprefixer": "^6.7.7",
    "babel-loader": "^8.1.0",
    "babel-plugin-add-module-exports": "^0.2.1",
    "clean-webpack-plugin": "^0.1.9",
    "css-loader": "^3.4.2",
    "mini-css-extract-plugin": "^0.9.0",
    "node-sass": "^4.13.1",
    "postcss-custom-properties": "^9.1.1",
    "postcss-loader": "^3.0.0",
    "progress-bar-webpack-plugin": "^1.8.0",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.1.3",
    "sugarss": "^2.0.0",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "webpack": "^4.42.1",
    "webpack-bundle-tracker": "0.4.3",
    "webpack-cli": "^3.3.11",
    "webpack-dev-middleware": "^3.7.2",
    "webpack-dev-server": "^3.10.3",
    "webpack-merge": "^4.2.2"
  },
  "dependencies": {
    "@fancyapps/fancybox": "3.3.5",
    "babel-polyfill": "^6.26.0",
    "bootstrap": "^4.0.0",
    "dom7": "^2.1.3",
    "dotenv": "^4.0.0",
    "extract-text-webpack-plugin-last": "^4.0.0-beta.0",
    "file-loader": "^0.9.0",
    "install": "^0.8.2",
    "jquery": "^3.1.1",
    "node": "^13.11.0",
    "npm": "^4.6.1",
    "popper.js": "^1.12.2",
    "precss": "^4.0.0",
    "shopify-buy": "^1.8.0",
    "slick-carousel": "^1.6.0",
    "swiper": "^4.0.7",
    "url-loader": "^0.5.7"
  }
}
`

Thanks a lot for your help!

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by patrickmsieber** [comment]
> It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

I just updated the issue with the template. Please reopen issue.
Thanks

**Comment by evilebottnawi** [comment]
Please read the error message `SassError: Base-level rules cannot contain the parent-selector-referencing character '&'.`, it is sass error, not sass-loader

**Comment by patrickmsieber** [comment]
To cut a long story short, I haven't worked on this project for a while and the client wanted a change. Meanwhile I have worked on projects with more recent node and npm versions (not webpack projects though). Now I wanted to webpack the change and spit on problems due to old versions. After many fixes and version adjustments this is now the last error I get.

Since the scss files have been compiled before and the change is minimal, I assume that the scss files are correct. 

Or is it possible that I have a syntax error where I include sass-loader?
Because in the file "webpack.config.js" on line 51 it used to be something like this:
`loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader!sass-loader')`

Am I doing something wrong there, actually I do not use a webpack but grunt and therefore I am not that skilled.
Thanks

**Comment by evilebottnawi** [comment]
As I said above it is sass problem, maybe you use `node-sass` before, now we use `sass` by default, there are some incompatibilities between `sass` and `node-sass`

**Comment by patrickmsieber** [comment]
this is a good hint!
I'll look into it, and i think the issue can be closed.
Thanks a lot
