### ISSUE TITLE
Please update version at npmjs.com

### ISSUE THREAD

**Issue by alexkuc** [webpack-contrib/sass-loader#845]
- Operating System: OSX `10.13.6`
- Node Version: `v13.13.0`
- NPM Version: `6.14.4`
- Yarn Version: `1.22.4`
- webpack Version: `webpack@5.0.0-beta.15`
- sass-loader Version: `8.0.2`

### Expected Behavior

Successfully compile SCSS when there are file names with the same name but different extensions

### Actual Behavior

```bash
[webpack-cli] /Users/alexkucheryuk/Downloads/sass-loader-npm/src/style.scss

[webpack-cli] Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after ";": expected selector, was "(function(root, fac"
        on line 1 of node_modules/motion-ui/dist/motion-ui.js
        from line 1 of /Users/alexkucheryuk/Downloads/sass-loader-npm/src/style.scss
>> ;(function(root, factory) {

   -^
```

Instead of loading `motion-ui.scss`, loader used `motion-ui.js` instead which caused an error.

### How Do We Reproduce?

Using `npmjs` version:

1. `git clone https://github.com/alexkuc/sass-loader-npm`
2. `yarn`
3. `yarn build`
4. get error shown above

Using `source` version:

1. `git clone https://github.com/webpack-contrib/sass-loader`
2. `yarn`
3. `yarn link`
4. `git clone https://github.com/alexkuc/sass-loader-npm`
5. `yarn`
6. `yarn link "sass-loader"`
7. get no errors

**Comment by evilebottnawi** [comment]
Yes, release will be soon, please be patient, we have one bug which needs to be fixed before release

**Comment by sebastianmilia** [comment]
in which version has this been fixed?
