### ISSUE TITLE
Can't compile sass while using Vue Storybook

### ISSUE THREAD

**Issue by Rusinas** [webpack-contrib/sass-loader#861]
Hello. I'm trying to create storybook on vue. My components written using sass. So, I made this in .storybook/main.js: 

```
webpackFinal: (config) => {
        config.module.rules.push({
            test: /\.s[ac]ss$/i,
            use: [
                // Creates `style` nodes from JS strings
                'style-loader',
                // Translates CSS into CommonJS
                'css-loader',
                // Compiles Sass to CSS
                'sass-loader',
            ],
        })

        return config
}
```

And the styles looks like this:
```
<style lang="sass" scoped>
button
    background-color: red
</style>
```

So I'm getting this error when trying to compile:
```
SassError: Invalid CSS after "": expected 1 selector or at-rule, was "button"
        on line 1 of C:\Code\testproj\src\components\UI\TestComponent.vue
```

And if I change my style to this: 
```
<style lang="sass" scoped>
button {
    background-color: red
}
</style>
```

All works, but that's not a sass syntax.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please open a new issue in vue-loader
