### ISSUE TITLE
Can't compile sass while using Vue Storybook

### ISSUE THREAD

**Issue by Rusinas** [webpack-contrib/sass-loader#862]
- Operating System: Win10
- Node Version: 14.4.0
- NPM Version: 6.14.5
- webpack Version: 4.43.0
- sass-loader Version: 8.0.2

### Expected Behavior

Successful compile when I use sass syntax in component.

### Actual Behavior

Error while compiling:
```
SassError: Invalid CSS after "": expected 1 selector or at-rule, was "button"
        on line 1 of C:\Code\testproj\src\components\UI\TestComponent.vue
```

### Code

Config:
```
webpackFinal: (config) => {
        config.module.rules.push({
            test: /\.s[ac]ss$/i,
            use: [
                // Creates `style` nodes from JS strings
                'style-loader',
                // Translates CSS into CommonJS
                'css-loader',
                // Compiles Sass to CSS
                'sass-loader',
            ],
        })

        return config
}
```

And the styles looks like this:
```
<style lang="sass" scoped>
button
    background-color: red
</style>
```

And if I change my style to this: 
```
<style lang="sass" scoped>
button {
    background-color: red
}
</style>
```

All works, but that's not a sass syntax. 

### How Do We Reproduce?

1) Install Vue
2) Install [Storybook for vue](https://storybook.js.org/docs/guides/guide-vue/)
3) Add a story with component which styles written using sass syntax
4) Try to run storybook

**Comment by evilebottnawi** [comment]
Please open an issue in vue-loader, we can't fix it on our side

**Comment by Rusinas** [comment]
But I don't have vue-loader package in my project
