### ISSUE TITLE
The newly added prependData in 8.x was changed in 9.0, there is no documentation

### ISSUE THREAD

**Issue by yangdan8** [webpack-contrib/sass-loader#865]
The newly added prependData in 8.x was changed in 9.0, there is no documentation??
Configure as follows in Vue-cli3 & sass-loader8.x:
loaderOptions: {
      sass: {
        prependData: `@import "@/assets/css/pi-theme-default.scss";`,
      },
    }
How to configure after sass-loader9.0?
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'prependData'. These properties are valid:
   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }

**Comment by yangdan8** [comment]
Change to additionalData seems to be OK

**Comment by okboy5555** [comment]
It works for me
