### ISSUE TITLE
prependData underfind at versions 9.0.2 thanks

### ISSUE THREAD

**Issue by truthiswong** [webpack-contrib/sass-loader#870]

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

It was renamed to https://github.com/webpack-contrib/sass-loader/blob/master/src/options.json#L20
