### ISSUE TITLE
prependData underfind

### ISSUE THREAD

**Issue by truthiswong** [webpack-contrib/sass-loader#871]
- Operating System: macOs
- Node Version: 12.18.3
- NPM Version: 6.14.6
- webpack Version:4.15.1
- sass-loader Version: 9.0.2

### Code

![image](https://user-images.githubusercontent.com/40853135/88357515-1dff0300-cd9e-11ea-9fd6-710e6368534b.png)

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
options has an unknown property 'prependData'. These properties are valid:
object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

```js
// additional code, HEY YO remove this block if you don't need it
```

**Comment by evilebottnawi** [comment]
Please read CHANGELOG `prependData` is now renamed to `additionalData`
