### ISSUE TITLE
After adding additionalData I got module build failed error

### ISSUE THREAD

**Issue by rzkhosroshahi** [webpack-contrib/sass-loader#880]
Hey 
I used Vue CLI and change it webpack configs and a sass file as an additionalData. but after add this option my l got module build error from my sass styles that just I already use them.
I saw this issue #530 its seem similar issue but it's not helped me.

`Note:` additionalData loaded properly and it works though before adding my component style into component

- Operating System: ubuntu
- NPM Version: 10.9
- webpack Version: -
- sass-loader Version: latest = 9

#### Error
```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected ";".
  ╷
2 │ body {
  │      ^
  ╵
  components/App/style.scss 2:6  
```
#### App/styles.scss
``` css
body {
  background-color: #ccc;
}
```

**Comment by evilebottnawi** [comment]
You don't provide steps to reproduce and configurations, sorry I can't help, please fill out all fields in the issue template and I will reopen issue and help you

**Comment by rzkhosroshahi** [comment]
I've just added configuration files

> You don't provide steps to reproduce and configurations, sorry I can't help, please fill out all fields in the issue template and I will reopen the issue and help you

**Comment by evilebottnawi** [comment]
additionalData: '@import "~@/styles/main.scss"', to `additionalData: '@import "~@/styles/main.scss";',`

**Comment by rzkhosroshahi** [comment]
> `additionalData: '@import "~@/styles/main.scss"'` change on `additionalData: '@import "~@/styles/main.scss";',`, you should always put `;` after `@import`, sorry we can't validate string on valid scss

Thank it works.
