### ISSUE TITLE
Version ^10.0.2 is giving  Cannot find module 'sass-loader/dist/importsToResolve' when used in webpack config 

### ISSUE THREAD

**Issue by vjagetiya-jeavio** [webpack-contrib/sass-loader#890]
- Operating System: Ubuntu
- Node Version: 14.12.0
- NPM Version: 6.14.8
- webpack Version: 4.42.0
- sass-loader Version: ^10.0.2

### Expected Behavior

The compilation of the scss file should work.

### Actual Behavior

giving error Cannot find module 'sass-loader/dist/importsToResolve' when used in webpack config  as loader for .scss files

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

```js
// additional code, HEY YO remove this block if you don't need it
```

**Comment by evilebottnawi** [comment]
Because this file doesn't exists anymore, you should not rely on internal files

**Comment by vjagetiya-jeavio** [comment]
Can you provide work around for the same, as I am using it to have SASS based custom theme for AntD using AntdScssThemePlugin and Craco (for changing webpack config in create react app)

**Comment by evilebottnawi** [comment]
You need to open a new issue in `AntdScssThemePlugin` repo, it is not safe to rely on non publish API
