### ISSUE TITLE
Error while compiling scss

### ISSUE THREAD

**Issue by getsetgopi** [webpack-contrib/sass-loader#891]
- Operating System: Windows 10
- Node Version: 13.5.0
- NPM Version: 6.14.8
- webpack Version: 4.44.2
- sass-loader Version: 10.0.2

### Expected Behavior

Should compile .scss imported inside a .js file

### Actual Behavior

Getting the below error
ERROR in ./src/scss/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/scss/style.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Package exports for 'C:\projects\jquery_testing\node_modules\klona' do not define a valid './full' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\projects\jquery_testing\node_modules\sass-loader\dist\utils.js:19:13)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
 @ ./src/scss/style.scss 2:26-136
 @ ./src/js/main.js
 @ multi ./src/js/main.js ./src/scss/main.scss

### Code

```js
const webpack = require("webpack");
const path = require("path");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const HtmlWebpackPluginConfig = new HtmlWebpackPlugin({
	template: "./src/index.html",
	filename: "index.html",
	inject: "body",
});

module.exports = (env, options) => {
	const isDevelopment = options.mode === "development";
	return {
		entry: {
			vendor: ["jquery", "bootstrap", "parsleyjs"],
			app: ["./src/js/main.js", "./src/scss/main.scss"],
		},
		output: {
			path: path.resolve(__dirname, "dist"),
			filename: "bundle.js",
		},
		module: {
			rules: [
				{
					test: /\.scss$/,
					use: [
						isDevelopment === "production"
							? MiniCssExtractPlugin.loader
							: "style-loader",
						"css-loader",
						"sass-loader",
					],
				},
				{
					test: /\.m?js$/,
					exclude: /(node_modules|bower_components)/,
					use: {
						loader: "babel-loader",
						options: {
							presets: ["@babel/preset-env"],
						},
					},
				},
			],
		},
		optimization: {
			splitChunks: {
				automaticNameDelimiter: "-",
				cacheGroups: {
					vendor: {
						test: /[\\/]node_modules[\\/]/,
						name: "vendor",
						chunks: "all",
						priority: 10,
						enforce: true,
					},
				},
			},
		},
		plugins: [
			new webpack.ProvidePlugin({
				$: "jquery",
				jQuery: "jquery",
			}),
			new MiniCssExtractPlugin({
				filename: "[name].css",
				chunkFilename: "[id].css",
			}),
			HtmlWebpackPluginConfig,
		],
	};
};
```
```
//package.json
main: "./src/index.html,
	"devDependencies": {
		"@babel/core": "^7.11.6",
		"@babel/preset-env": "^7.11.5",
		"@popperjs/core": "^2.5.3",
		"babel-loader": "^8.1.0",
		"bootstrap": "^4.5.2",
		"css-loader": "^4.3.0",
		"html-webpack-plugin": "^4.5.0",
		"mini-css-extract-plugin": "^0.11.3",
		"node-sass": "^4.14.1",
		"parsleyjs": "^2.9.2",
		"sass": "^1.26.11",
		"sass-loader": "^10.0.2",
		"style-loader": "^1.0.0",
		"webpack": "^4.44.2",
		"webpack-cli": "^3.3.12",
		"webpack-dev-server": "^3.11.0"
	},
	"dependencies": {
		"jquery": "^3.4.1",
		"popper.js": "^1.16.1"
	}
```

```js
//JS file
import "../scss/style.scss";
import "bootstrap";
import "parsleyjs";
var testing = "hello"
console.log("testing")
```

**Comment by evilebottnawi** [comment]
Do not use `13` node, it is broken in some versions, use `12` or `14`
