### ISSUE TITLE
SassError: expected ";".

### ISSUE THREAD

**Issue by HomyeeKing** [webpack-contrib/sass-loader#900]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- sass-loader Version:

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

```js
// additional code, HEY YO remove this block if you don't need it
```

### How Do We Reproduce?

![image](https://user-images.githubusercontent.com/49113249/98228535-a8f1bb00-1f93-11eb-9b07-d5893868447d.png)

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
