### ISSUE TITLE
Error: Node Sass version 5.0.0 is incompatible with ^4.0.0.

### ISSUE THREAD

**Issue by jsuton00** [webpack-contrib/sass-loader#901]
I have installed your new updated version sass-loader, but it seems no longer supported by Create React App starter kit.
./src/index.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/index.scss)
Error: Node Sass version 5.0.0 is incompatible with ^4.0.0.

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please update `sass-loader` to latest version
