### ISSUE TITLE
Support .import.scss suffix

### ISSUE THREAD

**Issue by bgotink** [webpack-contrib/sass-loader#904]
- Operating System: any
- Node Version: any
- NPM Version: any
- webpack Version: 4.x
- sass-loader Version: 10.0.5

### Feature Proposal

Support loading files with the `.import.scss` extension when used with `@import`

### Feature Use Case

As a Sass library author I can support usage of my library using `@use` and `@import` by providing two files: `/path/to/_file.scss` for `@use` and `/path/to/_file.import.scss` for `@import`.
The `_file.scss` uses regular names for all variables and mixins, while the `_file.import.scss` exposes all of these things with a prefix to prevent name clashes.

Sass doesn't pass what method is used to the importer as far as I could tell, so it doesn't look like the importer can perform this logic itself.
However, by resolving the path to `/path/to/_file` without any extensions sass itself will resolve this correctly, finding `.import.scss` files when they exist.

**Comment by alexander-akait** [comment]
Sorry, it is not official, if you need this, please open an issue in sass repo and when they implement this we will support it too

**Comment by bgotink** [comment]
@alexander-akait  I'm not sure what I have to ask in the sass repo.
While the `.import.scss` system is not widely documented on the sass website, this is officially supported: https://sass-lang.com/documentation/at-rules/import#import-only-files

My usecase simply explains the usecase. I'm not asking for you to invent something new.

**Comment by alexander-akait** [comment]
If it is in docs we are supported this

**Comment by bgotink** [comment]
Thanks for clarifying that!

Could this ticket be re-opened? This feature doesn't work with sass-loader at this point in time.

**Comment by alexander-akait** [comment]
I can't open it, because it works, if it doesn't work provide reproducible test repo, double check you use `sass` (`dart-sass`), it doesn't work on `node-sass`

**Comment by bgotink** [comment]
It doesn't work, that's why I opened the ticket in the first place.

I'll be happy to provide a repro

**Comment by alexander-akait** [comment]
Please provide reproducible test repo and I will reopen this if we will have bug

**Comment by bgotink** [comment]
I've opened #905, which contains a failing test.

While creating the test I noticed there's a pretty clean workaround, there's more info in the PR.
