### ISSUE TITLE
Resource resolve errors with sourcemaps enabled

### ISSUE THREAD

**Issue by strarsis** [webpack-contrib/sass-loader#910]
- Operating System:
- Node Version: v14.15.3
- NPM Version: 6.14.10
- webpack Version: 5.
- sass-loader Version: 

### Expected Behavior

`webpack` and `sass-loader` should compile fine with sourcemaps disabled.

### Actual Behavior

Resource resolve build errors with sourcemaps disabled.
````
 ERROR  Failed to compile with 1 errors                                                                                       9:52:59 PM
 error  in ./resources/assets/styles/main.scss

Module build failed (from ../../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '../../images/test.svg' in '/home/build/src/sage/resources/assets/styles'
    at finishWithoutResolve (/home/build/src/sage/node_modules/enhanced-resolve/lib/Resolver.js:293:18)
    at /home/build/src/sage/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /home/build/src/sage/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/home/build/src/sage/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/build/src/sage/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/home/build/src/sage/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/build/src/sage/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /home/build/src/sage/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/home/build/src/sage/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/build/src/sage/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at processResult (/home/build/src/sage/node_modules/webpack/lib/NormalModule.js:583:19)
    at /home/build/src/sage/node_modules/webpack/lib/NormalModule.js:676:5
    at /home/build/src/sage/node_modules/loader-runner/lib/LoaderRunner.js:397:11
    at /home/build/src/sage/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/home/build/src/sage/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/home/build/src/sage/node_modules/css-loader/dist/index.js:155:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

assets by status 84.2 KiB [cached] 3 assets
webpack compiled with 2 errors
npm ERR! code ELIFECYCLE
````

### Code

```js
      {
        test: /\.scss$/,
        use: [
          MiniCssExtractPlugin.loader,
          { loader: 'css-loader', options: { sourceMap: false } },
          {
            loader: 'postcss-loader', options: {
              postcssOptions: {
                config: path.join( __dirname, 'postcss.config.js' ),
                ctx: config,
              },
              sourceMap: false,
            },
          },
          { loader: 'resolve-url-loader', options: { sourceMap: false } },
          {
            loader: 'sass-loader', options: {
              sassOptions: {
                sourceComments: true,
              },
              sourceMap: true, // false causes the resolve issue
            },
          },
        ],
      },
```

### How Do We Reproduce?
Run the webpack build with and without sourcemaps disabled for the `sass-loader`.

**Comment by alexander-akait** [comment]
resolve-url-loader break sass url, do not use this loader, you don't need it anymore

**Comment by valignatev** [comment]
Hey, I'm having exactly the same issue, and not using resolve-url-loader doesn't fix the issue. Even more - removing resolve-url-loader breaks resolving regardless of sass-loader settings. 

The caveat is that I have a rather old legacy project - resolve-url-loader is v2.3.1 and sass-loader is v6.0. Could that be the issue? Should update to the newest versions fix it?

**Comment by alexander-akait** [comment]
It means you have invalid url, can you provide example? I will help you

**Comment by valignatev** [comment]
I doubt that the url is invalid, because it fails on each one of URLs we have. Also, it builds successfully with sourcemaps enabled. I'm not sure if I'll be able to provide somewhat reproducible example, but I can try. Don't really want to waste your time if it might just potentially be an issue with very-very outdated versions of the libraries :)

**Comment by alexander-akait** [comment]
@valignatev I will be glad to look, maybe we can improve some edge cases or improve docs to help other developers

**Comment by valignatev** [comment]
Hey @alexander-akait, sorry for disappearing. I actually invested into upgrading that legacy frontend tooling, and after learning more about how resolve-url-loader works I would say that maybe this is intended behavior and not really an issue. resolve-url-loader actually requires source map to be present in order to resolve URLs, and new version actually has a user-friendly error message if you omit it:
```
Error: resolve-url-loader: error processing CSS
  a valid source-map is not present (ensure preceding loaders output a source-map)
```

Their docs' example also have source map explicitly enabled on sass-loader that comes after it

**Comment by alexander-akait** [comment]
Why do you use `resolve-url-loader`?

**Comment by valignatev** [comment]
Mostly to resolve fonts referenced with `url(...)` in `@font-face` declarations. I like them being relative to the `.scss` file, and sass-loader wants them to be relative to the output dist dir. resolve-url-loader helps with it.

**Comment by alexander-akait** [comment]
@valignatev maybe you package have variables so change URL on valid, most of package have it

**Comment by valignatev** [comment]
I'm not only using packages who do that, I'm also structuring my own code in the same way because it's more comfortable for me. I'm ok with having source maps available on my production sites to be honest, I don't consider it's an issue, especially since new versions of resolve-url-loader have a decent error message that explain exactly what's happening :)
