### ISSUE TITLE
Imported CSS inside SCSS file is prepended instead of following import order

### ISSUE THREAD

**Issue by thecrypticace** [webpack-contrib/sass-loader#911]
- Operating System: macOS Big Sur 11.1
- Node Version: v15.3.0
- NPM Version: 7.0.14
- webpack Version: 5.11.1 (cli 4.3.1)
- sass-loader Version: 10.1.0

### Expected Behavior

When importing a mix of Sass/SCSS files and CSS files import order should be followed.

### Actual Behavior

CSS imports are prepended instead of following source order.

### Code
Example:

```js
// webpack.config.js

const MiniCssExtractPlugin = require("mini-css-extract-plugin")

module.exports = {
  plugins: [ new MiniCssExtractPlugin() ],
  module: {
    rules: [
      {
        test: /\.scss$/i,
        use: [
          MiniCssExtractPlugin.loader,
          "css-loader",
          "sass-loader",
        ],
      },
    ],
  },
};
```

```scss
// index.js

@import "./order-1";
@import "./order-2";
@import "./order-3.css";

// The first two are SCSS files and the third is a CSS file.
// They have each have a single CSS class.
```

### How Do We Reproduce?

I've prepared a repository: https://github.com/thecrypticace/sass-import-order

Clone it and run `yarn run repro`

**Comment by thecrypticace** [comment]
It appears that the CSS loader exports are in an incorrect order:

```js
___CSS_LOADER_EXPORT___.i(/* reference to third import */);
___CSS_LOADER_EXPORT___.push([module.id, "Single blob of all SCSS-compiled CSS here", ""]);
```

The way this is structured makes me think that mixed SASS/CSS imports may not be simple to support because the compiled SASS would have to be broken into multiple pieces if there are interleaved, mixed imports.

**Comment by alexander-akait** [comment]
No bugs here, let's do it without webpack, let's compile sass file without `sass-loader`, using CLI
```
$ node_modules/.bin/sass src/index.scss
```
Output:
```css
@import "./order-3.css";
.order-1 {
  color: #000;
}

.order-2 {
  color: #000;
}

.info {
  content: "The order above should be order-1, order-2, order-3";
}

```

So when `css-loader` handles `@import`, so you have (pseudo core):

```js
module.exports = [
  // From `@import "./order-3.css";`
  ['.order-3 { color: #000 }'],
  // Compiled core 
  [
  '.order-1 {
  color: #000;
}

.order-2 {
  color: #000;
}

.info {
  content: "The order above should be order-1, order-2, order-3";
}'
  ]
]
```

When mini-css-extract-plugin concat them using parse order...

Now I think you can already understand why order is wrong, we can't fix it, because this is how `sass` works, just try to avoid using `@import` CSS files inside SASS/SCSS files.

Feel free to feedback

**Comment by thecrypticace** [comment]
Ah, this is a dart-sass bug then it seems. I did a bit of source diving though the compiled dart-sass -> JS implementation but I couldn't figure out if it was or not.

**Comment by alexander-akait** [comment]
Yes it's a little implicit and confusing, for future debug, I recommend open `sass-loader` and looks on sass compiled result

**Comment by thecrypticace** [comment]
Yeah, I actually did that but completely missed the import at the top of the output. My apologies. I'll see what I can figure out regarding dart-sass and hopefully PR a fix there. Thanks!
