### ISSUE TITLE
i got this error when upgrade to sass loader v11

### ISSUE THREAD

**Issue by YallaDealz** [webpack-contrib/sass-loader#922]
✖ Nuxt Fatal Error                                                                                    │
   │                                                                                                         │
   │   Error: Rule can only have one resource source (provided resource and test + include + exclude) in {   │
   │   "use": [                                                                                              │
   │   {                                                                                                     │
   │   "loader": "/home/yalladealz/Dashboard/node_modules/babel-loader/lib/index.js",                        │
   │   "options": {                                                                                          │
   │   "configFile": false,                                                                                  │
   │   "babelrc": false,                                                                                     │
   │   "cacheDirectory": false,                                                                              │
   │   "envName": "client",                                                                                  │
   │   "presets": [                                                                                          │
   │   [                                                                                                     │
   │   "/home/yalladealz/Dashboard/node_modules/@nuxt/babel-preset-app/src/index.js",                        │
   │   {                                                                                                     │
   │   "corejs": {                                                                                           │
   │   "version": 2                                                                                          │
   │   }                                                                                                     │
   │   }                                                                                                     │
   │   ]                                                                                                     │
   │   ]                                                                                                     │
   │   },                                                                                                    │
   │   "ident": "clonedRuleSet-4[0].rules[0].use[0]"                                                         │
   │   }                                                                                                     │
   │   ]                                                                                                     │
   │   }

**Comment by alexander-akait** [comment]
Sorry, please open an issue in `nuxt` repo, also v11 require webpack@5

**Comment by YallaDealz** [comment]
i opened there
