### ISSUE TITLE
v11 ~ import - broken? "SassError: File to import not found or unreadable: ~_variables.scss."

### ISSUE THREAD

**Issue by ntucker** [webpack-contrib/sass-loader#925]
- Operating System: WSL2 on win10
- Node Version: 14
- NPM Version: 6
- webpack Version: 5
- sass-loader Version: 11.0.0

### Expected Behavior

Release notes say it's deprecated, not removed - so I would expect it to still work

### Actual Behavior

"SassError: File to import not found or unreadable: ~_variables.scss."

### Code

```js
[
    {
      loader: MiniCssExtractPlugin.loader,
      options: {},
    },
    {
      loader: 'css-loader',
      options: {},
    },
    {
      loader: 'postcss-loader',
      options: {
        postcssOptions: {
          plugins: [autoprefixer(), cssPresetEnv()],
        },
      },
    },
    {
      loader: 'sass-loader',
      options: { sassOptions: { outputStyle: 'expanded' } },
    },
{
      loader: 'sass-resources-loader',
      options: {
        resources: sassResources,
      },
    }
]
```
https://github.com/ntucker/anansi/blob/master/examples/typescript/src/style/export.scss

### How do we reproduce?

Branch is here: https://github.com/ntucker/anansi/pull/75

Once checked out run:

```bash
yarn install
yarn build
```

**Comment by alexander-akait** [comment]
`~_variables.scss`, if you use `resolve.alias` you still need this, otherwise it will be resolved relative to file

**Comment by ntucker** [comment]
Are you saying I need to add option resolve.alias that I did not need before?

**Comment by alexander-akait** [comment]
You don't provide code or configuration, that is why ignoring fields in the issue template is bad, I can't say what is wrong and why it is not work without `~`

**Comment by alexander-akait** [comment]
Is `_variables.scss` relative where you import it?

**Comment by alexander-akait** [comment]
In your case you can't remove it due `sass-resources-loader`

**Comment by ntucker** [comment]
I'm not interested in removing it - the release notes say it should still work? If this is not true, the documentation needs to be updated to reflect that.

**Comment by alexander-akait** [comment]
Can you provide simple example how I can reproduce it?

**Comment by ntucker** [comment]
Is the repo linked not simple enough?

**Comment by alexander-akait** [comment]
I try to do it, but don't understand how I can reproduce it, I don't investigate deeply, please provide steps

**Comment by ntucker** [comment]
Branch is here: https://github.com/ntucker/anansi/pull/75

**Comment by alexander-akait** [comment]
Bug, WIP

**Comment by alexander-akait** [comment]
This previously worked due to a bug, but we fixed, I removed `~` from your code and build is fine

**Comment by alexander-akait** [comment]
Updated https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#1100-2021-02-05, my recommendation is avoiding using `~`. Why?
- it is webpack behavior, so if you try to compiler sass to css without webpack you will get the error 
- no `~` in sass/js/css/etc rfc/specifications/docs
- you don't need this in 99% cases

**Comment by ntucker** [comment]
I think it's fine to no longer support ~ in a breaking change version. I think it would help people if you removed "but we still support it for historical reasons." from the release notes. This tells me it is supported - which it is not.

**Comment by alexander-akait** [comment]
`~` is still supported, but now it resolve modules from `node_modules` and `resolve.alias`/`resolve.fallback`, I am very surprised that this worked for you before, because this is a bug
