### ISSUE TITLE
Image URLs not relative to source file when @use other file

### ISSUE THREAD

**Issue by xenobytezero** [webpack-contrib/sass-loader#928]
- Operating System: Windows 10
- Node Version: 15.3
- NPM Version: 7.0.14
- webpack Version: 5.21.2
- sass-loader Version: 11.0.1

### Expected Behavior

Resolution of asset URLs should be relative to source file even when including other files

### Actual Behavior

Resolution of asset URLs appear to be relative to the included file.

### Code

Public reproducible repo can be found at 

https://github.com/xenobytezero/sass-loader-github-bug

### How Do We Reproduce?

1/ `npm run build`
2/ Note that the URL to the `boat.png` asset is the same for both `dist/index.css` and `dist/custom/custom-1.css`

This will fail if the `custom-1.css` is included on the page as it will not be able to find the PNG.  

### Attempted Solutions

* `resolve-url-loader` made no difference
* Changing from using `output.publicPath` to sass-loader option `publicPath` made no difference
* `@import` made no difference

**Comment by alexander-akait** [comment]
Yep, bug, not related to `sass-loader` (duplicate https://github.com/webpack-contrib/mini-css-extract-plugin/issues/691), workaround - using `publicPath: "/dist/"` (i.e. do not rely on relative URLs, also it is unsafe in some cases) and remove `publicPath` from `mini-css-extract-plugin`, nothing to fix here

**Comment by xenobytezero** [comment]
Unfortunately I can't use that workaround (building a Wordpress site so cant hardcode to server root) but I have another workaround atm.

Will watch https://github.com/webpack-contrib/mini-css-extract-plugin/issues/691 for updates.
