### ISSUE TITLE
var(--variable) is not a member for max / min / clamp

### ISSUE THREAD

**Issue by bencresty** [webpack-contrib/sass-loader#930]
- Operating System: Windows
- Node Version: 14.15.3
- NPM Version: Not sure if this is relevant, because using **p**npm, but npm version is 6.14.9
- webpack Version: 4.44.2
- sass-loader Version: 10.1.1

### Expected Behavior

Using a css variable inside a css function like min(), max() or clamp() to work, just like in plain css (where this works):

``` css
--test: 80px;
min-width: max(40px, var(--test));
```

(Using css variables inside the calc() function work fine though, so it seems to only be the min(), max() and clamp() functions, or maybe other functions, not to work)

Not sure if this is an issue in sass-loader or in sass itself. And if I'm missing something please let me know!

### Actual Behavior

Sass-loader throws an error: `var(---test) is not a member for max`

### How Do We Reproduce?

Write above scss in a scss file and load it with sass-loader.

**Comment by alexander-akait** [comment]
Sorry, not related to `sass-loader`, we just wrapper for `node-sass`/`dart-sass` and don't touch your code, please open an issue in `sass` repo, won't fix

**Comment by bencresty** [comment]
Alright, just found the issue. It's in sass. The min() and max() functions are available as Sass' own functions, conflicting with the actual css functions. So the error thrown is by Sass trying to use the min() and max() sass functions at compiletime, instead of output the css min() and max() functions. Crazy.

So somebody in this thread: https://github.com/sass/sass/issues/2849 has an ugly, but great workaround to still use the native css min() and max() functions:

So like this it works fine now:

``` css
--test: 80px;
min-width: m#{a}x(40px, var(--test));
```

It's a pitty that Sass still doesn't have a better way to avoid this though.
