### ISSUE TITLE
this.getOptions is not a function

### ISSUE THREAD

**Issue by wut1** [webpack-contrib/sass-loader#932]
- sass-loader Version:11.0.1

### Actual Behavior

```
Syntax Error: TypeError: this.getOptions is not a function
```

### Code

[code](https://github.com/webpack-contrib/sass-loader/blob/master/src/index.js#L20)

**Comment by alexander-akait** [comment]
You need webpack v5 to use latest version

**Comment by alexander-akait** [comment]
Run `npm ls webpack`

**Comment by mdodge-ecgrow** [comment]
Here is a snippet of what I see from that command:
```
| +-- optimize-css-assets-webpack-plugin@5.0.4
| | `-- webpack@4.44.2 deduped
| +-- sass-loader@10.1.1
| | `-- webpack@4.44.2 deduped
| +-- style-loader@1.3.0
| | `-- webpack@4.44.2 deduped
| +-- terser-webpack-plugin@4.2.3
| | `-- webpack@4.44.2 deduped
```

**Comment by alexander-akait** [comment]
with webpack v4 you should not get this error, do you have webpack globally?

**Comment by mdodge-ecgrow** [comment]
No I do not have it installed globally, should I?

**Comment by alexander-akait** [comment]
No, if you got this error, it means you still on webpack v4

**Comment by mdodge-ecgrow** [comment]
But i don't have webpack at all in my package.json, just webpack-cli.  What do I need to do?

**Comment by alexander-akait** [comment]
Please provide `package.json` content

**Comment by DonikaV** [comment]
I have 4.46 and i get same error 

```
vendors~init_react_context~server_rendering-78c329f7ea8b64b78f91.chunk.js:47270 Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
```

 "sass-loader": "11.0.1",
 "node-sass": "4.14.1",
 "sass": "^1.32.11",

**Comment by alexander-akait** [comment]
You need webpack v5 to use the latest version of loader
