### ISSUE TITLE
How to use sass in a new ejected create react app project?

### ISSUE THREAD

**Issue by kopax-polyconseil** [webpack-contrib/sass-loader#938]
- Operating System: Debian buster
- Node Version: 14 
- yarn Version: 1.2
- webpack Version: 4
- sass-loader Version: 10

### Expected Behavior

I run `npx create-react-app myapp; cd myapp; yarn eject` and try to use sass in it, nothing work while I expect to be working out of the box.

I have tried to downgrade `postcss-loader` to v4 but then I couldn't get my image assets due to a resolution problem.

I have also tried to downgrade `sass-loader` until v8, without success.

I just want to use sass within a new create-react-app project, how can I do?

### Actual Behavior

I am having the following error when I start my application:

```bash
TypeError: this.getOptions is not a function
```

### Code

This is my `devDepednencies`:

```json
{
  "@babel/core": "^7.13.16",
  "@babel/plugin-proposal-export-default-from": "^7.12.13",
  "@babel/preset-env": "^7.13.15",
  "@babel/preset-react": "^7.13.13",
  "@babel/preset-typescript": "^7.13.0",
  "@svgr/webpack": "^5.5.0",
  "@types/node": "^14.14.41",
  "@types/webpack": "^5.28.0",
  "@types/webpack-dev-server": "^3.11.3",
  "babel-loader": "^8.2.2",
  "babel-plugin-named-asset-import": "^0.3.7",
  "babel-preset-react-app": "^10.0.0",
  "camelcase": "^6.2.0",
  "case-sensitive-paths-webpack-plugin": "^2.4.0",
  "copy-webpack-plugin": "^6.4.1",
  "css-loader": "^5.2.4",
  "dotenv": "^8.2.0",
  "dotenv-expand": "^5.1.0",
  "file-loader": "^6.2.0",
  "fork-ts-checker-webpack-plugin": "^6.2.1",
  "fs-extra": "^9.1.0",
  "html-webpack-plugin": "^4.5.2",
  "mini-css-extract-plugin": "^1.5.0",
  "optimize-css-assets-webpack-plugin": "^5.0.4",
  "pnp-webpack-plugin": "^1.6.4",
  "postcss-flexbugs-fixes": "^5.0.2",
  "postcss-loader": "^5.2.0",
  "postcss-normalize": "^9.0.0",
  "postcss-preset-env": "^6.7.0",
  "postcss-safe-parser": "^5.0.2",
  "react-app-polyfill": "^2.0.0",
  "react-dev-utils": "^11.0.4",
  "resolve": "^1.20.0",
  "resolve-url-loader": "^3.1.2",
  "sass": "^1.32.11",
  "sass-loader": "^10.1.1",
  "style-loader": "^2.0.0",
  "terser-webpack-plugin": "^4.2.3",
  "ts-loader": "^9.0.1",
  "ts-node": "^9.1.1",
  "ts-pnp": "^1.2.0",
  "url-loader": "^4.1.1",
  "webpack": "^4.44.2",
  "webpack-cli": "3.3.12",
  "webpack-dev-server": "^3.11.2",
}
```
### How Do We Reproduce?

```
npx create-react-app myapp
```

`yarn eject` and try to configure sass

I just want to use sass within a new create-react-app project, how can I do?

**Comment by alexander-akait** [comment]
You need webpack v5 to use latest version of `sass-loader`, please use https://github.com/webpack-contrib/sass-loader/tree/v10.1.1 for webpack v4
