### ISSUE TITLE
Syntax Error: SassError: This file is already being loaded. With additionalData.

### ISSUE THREAD

**Issue by VasiliyRusin** [webpack-contrib/sass-loader#940]
I create a new issue with the repo as recommend in the #908 issue.

- Operating System: macOS 11.2.3 (I think this isn't important)
- Node Version: v14.15.4
- NPM Version: 6.14.10
- webpack Version: 4.46.0
- sass-loader Version: from 9.0.0

For version less than 9.0.0, which uses `prependData`, everything works fine.

### Expected Behavior

`additionalData` should work like `prependData`.

### Actual Behavior

`additionalData` causes compile error.

### Code

```js
 error  in ./src/scss/_problem.scss

Syntax Error: SassError: This file is already being loaded.
  ╷
1 │ @import "problem";
  │         ^^^^^^^^^
  ╵
  src/scss/_module.scss 1:9    @import
  src/scss/_problem.scss 2:19  root stylesheet

```
### How Do We Reproduce?

Use this [repo](https://github.com/VasiliyRusin/sass-loader-problem).

1. Clone. Run `npm i`.
2. Run `npm run serve`.
3. See error in console.

Webpack settings you can find in `vue.config.js`

**Comment by alexander-akait** [comment]
You can use it as function https://github.com/webpack-contrib/sass-loader#sync and insert value where you want `return content + "$value: 200px;";`

**Comment by VasiliyRusin** [comment]
> I think here another problem, because you use `node-sass` (it will be used by default in v8 and low), now you use `sass` (i.e. `dart-sass`), and `sass` catch your problem

I don't have `node-sass` in my project. `sass` works in both cases.

**Comment by alexander-akait** [comment]
Can you provide example when it will work? Because I can't do it, even without webpack

**Comment by VasiliyRusin** [comment]
What do you mean? I have provided a repository containing code that reproduces the error.

**Comment by alexander-akait** [comment]
@VasiliyRusin Doesn't work, otherwise I will not ask you about it, it is not work on any version.

**Comment by alexander-akait** [comment]
Problem from sass and your code doesn't work even without webpack (run you example using `node_modules/.bin/sass`) and you will got the same problem, won't fix, sorry. If you provide example of repo where it works I will look at the problem and reopen.

**Comment by alexander-akait** [comment]
You can exclude import for specific file, using:
```
additionalData: (content, loaderContext) => {
          if (loaderContext.resourcePath.endsWith('src/scss/_problem.scss')) {
            return content;
          }
          
          return `
          @import "~@/scss/_module.scss";
          ${content}
        `;
        }
```

**Comment by alexander-akait** [comment]
You can't import the same file twice, if you need more information you can look at docs for `sass` and read about import, other solutions is migrate on `@use`
