### ISSUE TITLE
Cannot load sass file that contains variables from node_modules

### ISSUE THREAD

**Issue by atomicpages** [webpack-contrib/sass-loader#941]
- Operating System: macOS Catalina
- Node Version: 14.15.5
- NPM Version: 7.11.1
- webpack Version: 5.36.2
- sass-loader Version: 11.0.1

### Expected Behavior

We should be able to `@use` files with variables

### Actual Behavior

Errors happen:

```
ERROR in ./src/styles/main.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
3 │ .#{$pretty--class-name} * {
  │    ^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/pretty-checkbox/src/scss/_core.scss 3:4  @use
  src/styles/main.scss 5:1                              root stylesheet
```

### Code

Code is longer than 20 lines. Providing a small repro here: https://github.com/atomicpages/sass-loader-error

### How Do We Reproduce?

See repro here: https://github.com/atomicpages/sass-loader-error
I also tried using `additionalData` and `sass-resources-loader`, but no dice.

**Comment by alexander-akait** [comment]
Not related to `sass-loader`, change your code on:
```
@use "../../node_modules/pretty-checkbox/src/scss/variables" with (
  $pretty--color-default: var(--radio--color)
);

@use "../../node_modules/pretty-checkbox/src/scss/core";
@use "../../node_modules/pretty-checkbox/src/scss/elements/default/outline";
@use "../../node_modules/pretty-checkbox/src/scss/extras/disabled";
@use "../../node_modules/pretty-checkbox/src/scss/extras/round";
@use "../../node_modules/pretty-checkbox/src/scss/states/focus";

:root {
  --radio--color: #000;
  --radio--disabled--color: grey;
}

.#{$pretty--class-name} {
  input {
    &[disabled] {
      & ~ * {
        border-color: var(--radio--disabled--color);
      }
    }
  }
}
```

under the hood webpack do pretty much the same and run `node_modules/.bin/sass src/styles/main.scss`

output:
```
Error: Undefined variable.
  ╷
3 │ .#{$pretty--class-name} * {
  │    ^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/pretty-checkbox/src/scss/_core.scss 3:4  @use
  src/styles/main.scss 5:1                              root stylesheet
```

Why, because `@use` create namespace, i.e you need to use `variables.$pretty--class-name` to get variable.

Nothing to fix here, sorry, you need to use `@import` here, because `pretty-checkbox` is not in sass modules format
