### ISSUE TITLE
Validation error on options.sourceMap when using devtool default

### ISSUE THREAD

**Issue by timstallmann** [webpack-contrib/sass-loader#942]
Apologies if this is some other issue, but this keeps showing up when I upgrade to sass-loader `11.0.1`, and it seems to be due to the default devtool value getting passed through and then being an invalid option?

- Operating System: Mac OS X
- Node Version: v12.16.2
- NPM Version: yarn 1.22.5
- webpack Version: 5.36.2
- sass-loader Version: 11.0.1

### Expected Behavior

If I set webpack config `devtool` setting to `eval` or `eval-source-map` in development mode, -or- add `EvalSourceMapDevToolPlugin`, project builds.

### Actual Behavior

I get a validation error:
`Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options.sourceMap should be a boolean.`

**Comment by alexander-akait** [comment]
sass-loader supports only `boolean` values for the `sourceMap` option

**Comment by alexander-akait** [comment]
Double check you will not use:
```
const devtool = 'value';

module.exports = { devtool, module: { rules: [ { loader: 'sass-loader', options: { sourceMap: devtool } }] } }
```

**Comment by timstallmann** [comment]
The full webpack config is kinda complex for this project, but here are what I think are the relevant parts. Note this error does not show up on 10.x branch of `sass-loader`, with the exact same config:

```js
 ...
 module: {
      ...
        {
          test: /\.scss$/,
          use: [
            "style-loader",
            "css-loader",
            "postcss-loader",
            "sass-loader"
          ]
        },
        ...
      ],
     plugins: [
        ...
       new webpack.EvalSourceMapDevToolPlugin({ columns: false }),
    ]
    },
```

**Comment by alexander-akait** [comment]
hm, maybe you can create example? using `EvalSourceMapDevToolPlugin` should not break `sass-loader`

**Comment by timstallmann** [comment]
Good call. Creating an example it turns out that the error is in https://github.com/shakacode/bootstrap-loader being incompatible with sass-loader 11.x, not in sass-loader itself. Thanks for helping talk me through it!
