### ISSUE TITLE
How to set `quietDeps` option for dart-sass

### ISSUE THREAD

**Issue by gcangussu** [webpack-contrib/sass-loader#954]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...

It is not clear how to set the [`quietDeps`](https://github.com/sass/dart-sass/blob/master/CHANGELOG.md#command-line-interface) flag on the sass options. I have tried the below which **doesn't** work:

```js
const sassLoader = {
  loader: 'sass-loader',
  options: {
    sassOptions: {
      quietDeps: true,
    },
  },
};
```

This option is useful since deprecation of division with `/`. Many dependencies trigger the deprecation warning, and these warnings are making very difficult to see the warnings of my own code.

### Your Proposal for Changes

I need some help in figuring how to configure this. Once figured out I can open a PR documenting it.

**Comment by alexander-akait** [comment]
> Add a quietDeps argument to compile(), compileString(), compileAsync(), and compileStringAsync() which silences compiler warnings from stylesheets loaded through importers, load paths, and package: URLs.

Because we use `sass.render` to compile sass/scss to css, and `render` doesn't support the `quietDeps` option

**Comment by alexander-akait** [comment]
> compile(), compileString(), compileAsync(), and compileStringAsync()

is dart API, you need to open an issue in `sass` repo and ask them to add the `quietDeps` option to Node.js API

**Comment by gcangussu** [comment]
> is dart API, you need to open an issue in `sass` repo and ask them to add the `quietDeps` option to Node.js API

Thank you, will do that

**Comment by alexander-akait** [comment]
Let's close here (we can't fix it in our code), when `sass` will add this option to Node.js API we will support it out of box without any problems

**Comment by pataar** [comment]
Weirdly enough, I've set the option in `sassOptions` but still getting deprecation warnings.

Using `1.35.0` with the updated JS API: https://github.com/sass/sass/issues/3065#issuecomment-861086560

**Comment by phil-w** [comment]
Aye, I still can't get rid of these warnings. I know I'm using stuff which "sass" wants to fill my screen with dire warnings about, but  all that is really not my fault and I can't do anything about it. 

The result is screens of garbage output from sass which just gets in the way of messages which could possibly be important to me. 

Up to and including 1.32.12.  I wasn't harassed because someone thinks some dependency over which I've no control over broke some rules I don't care about. Later versions remain unusable: a shot to the foot.

**Comment by alexander-akait** [comment]
We have this options https://webpack.js.org/configuration/other-options/#ignorewarnings, just put simple regexp and it will fix the problem

**Comment by kubijo** [comment]
That shouldn't, however, be needed since they added the JS API option to silence these warnings… (as @pataar mentioned).
Can you @alexander-akait, please take a look on what is the issue there?

**Comment by alexander-akait** [comment]
@kubijo hm, if they added this option, it should work, we just close your options and pass to sass https://github.com/webpack-contrib/sass-loader/blob/master/src/utils.js#L128, I will look at near future

**Comment by pataar** [comment]
This might be the same issue: https://github.com/sass/dart-sass/issues/1360. Not sure though. But as @alexander-akait mentioned, It wouldn't require any changes to `sass-loader`.

**Comment by pataar** [comment]
https://github.com/sass/dart-sass/releases/tag/1.35.1 has been released, which might fix the issue. Testing this later today.

**Comment by alexander-akait** [comment]
Anybody can check this, should I check it (because it in my todo)?

**Comment by gcangussu** [comment]
I can confirm that on my project `quietDeps` flag is working correctly since dart-sass 1.35.1

```js
{
  loader: require.resolve('sass-loader'),
  options: {
    sassOptions: { quietDeps: true },
  },
}
```

**Comment by alexander-akait** [comment]
@gcangussu thanks

**Comment by kubijo** [comment]
It doesn't seem like it did anything for me… I'm suspecting yarn's PNP to be tripping up the detection, but I have no idea how to check that

**Comment by kubijo** [comment]
I'm pretty sure that is not the case here as yarn flattens the hierarchy and do have only one version
```bash
 λ yarn why sass
└─ root-workspace-0b6124@workspace:.
   └─ sass@npm:1.35.1 (via npm:1.35.1)
```

**Comment by hamzahsn** [comment]
It seems `quietDeps: true` works perfectly with sass `"sass": "^1.34.1"` so give it a try.

**Comment by xavierfoucrier** [comment]
@hamzahsn It shouldn't be possible, because it's part of `1.35+` API, according to https://github.com/sass/dart-sass/blob/master/CHANGELOG.md#1350.

@alexander-akait Can you have a look and confirm that it works? On my side even after `rm -rf node_modules` and installing again with `npm i` it doesn't seem to do anything. Using `sass@1.35.1` with `sass-loader@12.1.0`.

Thanks :wink:

**Comment by alexander-akait** [comment]
Her confirmation from other developers https://github.com/webpack-contrib/sass-loader/issues/954#issuecomment-862297684, if you need personal help with your project please create share link or create reproducible example

**Comment by xavierfoucrier** [comment]
@alexander-akait I will have a look (again) later. Thanks for answering as usual :wink:

**Comment by hamzahsn** [comment]
@xavierfoucrier  could you share some code so we can reproduce your project?

**Comment by xavierfoucrier** [comment]
@hamzahsn I will try again and share if it doesn't work. I am using Foundation framework with @use rule and @forward, tried with @import and looks like it's the same result. Need to investiguate further. Thanks!

**Comment by carlosHerz** [comment]
Any solution to this? Even setting `quietDeps: true` i still get like a hundred warnings like this one `WARNING: You probably don't mean to use the color value purple in interpolation here.`

**Comment by gcangussu** [comment]
@carlosHerz I can think on some possibilities for those warnings:

- The warning is in your own code, not on a dependency
- The sass compiler is wrongly flagging a dependency as your own code
- You've miss-configured `quietDeps`, maybe a typo or it's on the wrong object on the config.

**Comment by gotts2swim** [comment]
In my case it appears the sass compiler is wrongly flagging dependencies as my code because `quietDeps` was set to true, but `isDependency` was set to false. No clue why though.

Anyone have any ideas why this might be the case?

**Comment by mokone91** [comment]
Hi! have same problem..
![image](https://user-images.githubusercontent.com/2384641/145998431-f6d439ff-1843-410d-8ea6-ff3e63cd7c62.png)
![image](https://user-images.githubusercontent.com/2384641/145998507-30362f71-8744-4fac-9dc3-ca5008c42633.png)

**Comment by bowerscodes-COP** [comment]
Hi, I'm getting the same problem after trying to migrate COP from `node-sass` to `sass`. I'm no Sass expert but my understanding, from what I've read around the subject, is that this is a deprecated syntax but the warnings can be avoided by changing things like `$govuk-gutter / 2` to `$govuk-gutter * 0.5` (in the below screenshot). Bearing in mind that this thread is now 2 years old, are there any plans to update this syntax, or have I completely misunderstood the problem? 🙃 (I have very little Sass experience so this is entirely possible)

At the moment, with `sass` installed, we're getting hundreds of these warnings - and the amount of extra time it's adding every time we spin up the app makes it unfeasible for us to commit the new dependency to Main. However at at the same time, node-sass is now deprecated so we need to switch it over.

I've read through the `quietDeps` solution but isn't that just silencing the warnings (i.e. not resolving the issue)? I'm also unsure of how to implement that on COP, as I can't see that we ever instantiate sass via js anywhere.

Appreciate i'm late to the party but what's the latest on this?

![Screenshot 2023-09-14 at 10 44 59 (2)](https://github.com/webpack-contrib/sass-loader/assets/107939282/2d0c3a50-fa99-40cb-bc87-9610e0f93b6d)
