### ISSUE TITLE
Cannot set property webpackLoaderContext of undefined

### ISSUE THREAD

**Issue by wassim-k** [webpack-contrib/sass-loader#955]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I'm using a custom importer in my project and since the latest update I've been getting the following error:
` SassError: Cannot set property 'webpackLoaderContext' of undefined`

I've tested it on **node** `v12.22.1` and `14.17.0`

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/sass-loader/dist/utils.js b/node_modules/sass-loader/dist/utils.js
index 6dac02c..24fc595 100644
--- a/node_modules/sass-loader/dist/utils.js
+++ b/node_modules/sass-loader/dist/utils.js
@@ -93,8 +93,8 @@ function isProductionLikeMode(loaderContext) {
 
 function proxyCustomImporters(importers, loaderContext) {
   return [].concat(importers).map(importer => function proxyImporter(...args) {
-    this.webpackLoaderContext = loaderContext;
-    return importer.apply(this, args);
+    const self = { webpackLoaderContext: loaderContext };
+    return importer.apply(self, args);
   });
 }
 
```

**Comment by alexander-akait** [comment]
Please provide code of your custom importer or steps to reproduce

**Comment by wassim-k** [comment]
Thanks for the quick response, I've uploaded a minimal reporoduction of the issue to [this repository](https://github.com/wassim-k/sass-loader-issue)

It's a minimal Angular v12 repo with [@angular-builders/custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack) which allows modifying the webpack config in order add the custom sass importer.

I've added a dummy importer because the issue does not seem to be with the implementation of the importer but rather with the way it's invoked, there's a chance the way Angular's [SassWorkerImplementation](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/sass/sass-service.ts) invokes the importer logic using workers is what causes `this` to be undefined in an anonymous function.

This could be related too:
[Why is “this” in an anonymous function undefined when using strict?](https://stackoverflow.com/questions/9822561/why-is-this-in-an-anonymous-function-undefined-when-using-strict)

**Comment by alexander-akait** [comment]
I see, feel free to send a fix, as you can see it is easy :+1:

**Comment by wassim-k** [comment]
PR created #956
