### ISSUE TITLE
Loading a module with the configuration does not work for multiple @forward blocks.

### ISSUE THREAD

**Issue by lesha38** [webpack-contrib/sass-loader#961]
- Operating System: Windows
- Node Version: 14.17.0
- NPM Version: 6.14.11
- webpack Version: 5.38.1
- sass-loader Version: 12.0.0
- sass Version: 1.34.1

### Expected Behavior

Loading a module with [configuration](https://sass-lang.com/documentation/at-rules/forward#configuring-modules)  working with all `@forward` blocks in `_opinionated.scss`.

### Actual Behavior

Loading a module with [configuration](https://sass-lang.com/documentation/at-rules/forward#configuring-modules) working with only first `@forward` block in `_opinionated.scss`.

### Code
```
// _opinionated.scss
@forward 'library' with (
  $black: #222 !default,
  $border-radius: 0.1rem !default
);
@forward 'another-library' with (
  $yellow: #FBFF00 !default,
  $font-size: 14px !default
);
```
```
// style.scss
@use 'opinionated' with ($black: #333, $yellow: #333);
```

```
// log
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: This variable was not declared with !default in the @used module.
   $yellow: #444,
   ^^^^^^^^^^^^^^^^^^
   src\styles\index.scss 19:3  @use
```

**Comment by alexander-akait** [comment]
This error from `sass` (try to compile code without webpack and you will get the same error), we can't fix it, please read the text of error and fix it on your side, sorry

**Comment by lesha38** [comment]
Oh, i was unsure where to write issue. Sorry and thank you!
