### ISSUE TITLE
ERROR with compiling sass file

### ISSUE THREAD

**Issue by priya454** [webpack-contrib/sass-loader#963]
I've migrated webpack from 4 to 5. Running into issues with sass loader. How to approach this problem?

**ERROR in ./assets/scss/index/index_PA.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/lib/loader.js??ruleSet[1].rules[3].use[2]!./node_modules/file-loader/dist/cjs.js??ruleSet[1].rules[6].oneOf[1]!./assets/scss/index/index_PA.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):**

@import '../vendors/bootstrap-4.3.1/css/bootstrap';
^
Expected "{".
╷
1 │ export default webpack_public_path + "static/media/index_PA.c1419108.scss";
│ ^
╵
stdin 1:79 root stylesheet
in /Users/spa/assets/scss/index/index_PA.scss (line 1, column 79)

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please respect time of other developers. Without more information nobody can help, please fix it and I will help.

**Comment by alexander-akait** [comment]
And look at the error, you apply file-loader before `sass-loader` and `css-loader`

**Comment by priya454** [comment]
@alexander-akait  Where is the template that you are referring to?

**Comment by priya454** [comment]
@alexander-akait I added "file-loader" before style-loader and css-loader. It fixed the issue. But can you explain how you figured out that "file-loader" is missing

```
{
                    test: /\.s[ac]ss$/i,
                    use: [
                         **"file-loader"**,
                        "style-loader",
                        "css-loader",
                        {
                            loader: "sass-loader",
                            options: {
                                // Prefer `dart-sass`
                                implementation: require("sass"),
                                sassOptions: {
                                    fiber: false,
                                },
                            },
                        },
                    ],
                },
```

**Comment by alexander-akait** [comment]
@priya454 

Here template https://github.com/webpack-contrib/sass-loader/issues/new?assignees=&labels=&template=BUG.md

> But can you explain how you figured out that "file-loader" is missing

Based on error message, look at `file-loader`/`css-loader`/etc works, they should have the right order, i.e. firstly `file-loader`, then `css-loader`, then `sass-loader` and etc

Note: `file-loader` is deprecated (they still will work for webpack v5), but I strongly recommend migrate on https://webpack.js.org/guides/asset-modules/ (better support, more abilities, faster, no extra deps).
