### ISSUE TITLE
Compatibility table

### ISSUE THREAD

**Issue by gustawdaniel** [webpack-contrib/sass-loader#965]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

In `node-sass`

https://www.npmjs.com/package/node-sass

there is clear and readable table with info about compatible node versions with node-sass versions.

### Your Proposal for Changes

I propose to add there similar table because of migrations of node and node sass leads to problems with sass-loader

**Comment by alexander-akait** [comment]
No related to `sass-loader`, you can look this  in `node-sass` repo, sorry, also the latest version of `node-sass` supports all LTS Node.js versions https://github.com/sass/node-sass/releases/tag/v6.0.0
