### ISSUE TITLE
ERROR in ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/styles/styles.scss Module build failed: TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by welcomepk** [webpack-contrib/sass-loader#969]
"dependencies": {
    "babel-cli": "^6.24.1",
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-env": "1.5.2",
    "babel-preset-react": "6.24.1",
    "css-loader": "^5.2.6",
    "live-server": "^1.2.1",
    "node-sass": "^6.0.0",
    "react": "^16.0.0",
    "react-dom": "^16.14.0",
    "react-modal": "^2.2.2",
    "sass-loader": "^12.1.0",
    "style-loader": "^2.0.0",
    "webpack": "3.1.0",
    "webpack-cli": "^4.7.2",
    "webpack-dev-server": "^2.11.5"
  }

these are packages i am using.. , what wrong is happening.. plz help me

**Comment by alexander-akait** [comment]
You need webpack v5 to use the latest version, please consider to update your webpack version

**Comment by welcomepk** [comment]
thanks a lot...,
it works........

**Comment by welcomepk** [comment]
> You need webpack v5 to use the latest version, please consider to update your webpack version

👍
