### ISSUE TITLE
sass-loader 12 no longer compatible with node-sass-import-once

### ISSUE THREAD

**Issue by ThiefMaster** [webpack-contrib/sass-loader#972]
- Operating System: Linux
- NPM Version: 14.16.1
- Node Version: 7.18.1
- webpack Version: 5.39.1
- sass-loader Version: 12.1.0

### Expected Behavior

https://github.com/at-import/node-sass-import-once working fine to de-duplicate imported css rules

### Actual Behavior

It doesn't work, I get many duplicate rules in my final css file, since my (rather large) scss has some imports repeated in multiple files (usually to get some mixins etc, but we have both css rules and mixin in some of those files)

---

I do not have a minimal example yet, so I'm hoping it's something obvious, e.g. some API change that broke this (very old) library.

**Comment by alexander-akait** [comment]
Please open an issue in `node-sass-import-once`, also it is unsafe to de-duplicate imported css rules

**Comment by alexander-akait** [comment]
Also we don't change API for v12, only drop old Node.js version

**Comment by ThiefMaster** [comment]
> Please open an issue in node-sass-import-once`

Last activity 5 years ago, so I doubt that'll do any good.

> also it is unsafe to de-duplicate imported css rules

But usually it works fine.... With many different CSS files and modules in a larger application it is not feasible to rewrite the scss to remove the duplicates without a massive amount of work.

**Comment by alexander-akait** [comment]
If you really need help please - create reproducible example (you can just create minimal example), without code I can't say what is wrong and this problems will be never resolved

**Comment by ThiefMaster** [comment]
Sure, I hoped you might have a idea what could have caused this :) I'll try to debug it a bit myself and then create a minimal testcase to reproduce it.

**Comment by alexander-akait** [comment]
@ThiefMaster feel free to ping me, note - by default we use `sass` (`dart-sass`), but look like `node-sass-import-once` for `node-sass`, you can start with this

**Comment by ThiefMaster** [comment]
I haven't been able to reproduce it in a minimal example yet (would have been too easy I guess...), but I did manage to track down the problem: It's in https://github.com/webpack-contrib/sass-loader/pull/958/files - node-sass-import-once stores the cache on `this` but with the change in #958 that no longer works, so it always sees a new cache.

**Comment by ThiefMaster** [comment]
@alexander-akait here's a minimal testcase to reproduce it: https://github.com/ThiefMaster/sass-loader-test

**Comment by ThiefMaster** [comment]
I managed to work around the issue using this wrapper:

```js
function _importOnce(...args) {
  // Due to https://github.com/webpack-contrib/sass-loader/pull/958/files we need to
  // use a different context for the importOnce plugin in order to keep the cache
  // between calls to this function.
  // Using a global one might work as well but like this it's scoped with the same
  // lifetime which we had before the sass-loader update as `options` is cloned at
  // the same time the object previously used in `this` was created (`context` in
  // `getOptions`).
  this.options._ctx = this.options._ctx || {options: this.options};
  return importOnce.apply(this.options._ctx, args);
}
```

**Comment by alexander-akait** [comment]
@ThiefMaster I see... but really on `this`, is not safe due multi threading, ideally cache should be stored in independent variable/file
