### ISSUE TITLE
CSS charset rule is ignored in production mode.

### ISSUE THREAD

**Issue by scream87** [webpack-contrib/sass-loader#973]
When .scss file holds some non-ASCII character, then sass is adding `@charset "UTF-8";` row to the begining of output css file. It works fine for "development" webpackge mode, but in "production" mode this css rule is not being added.

- Operating System: Windows 10
- Node Version: 14.17.0
- NPM Version: 6.14.13
- webpack Version: ^5.11.1
- sass-loader Version: ^12.1.0
- sass: ^1.35.1

### Expected Behavior

With webpack "production" mode, css charset rule is also added to output css file.

### Actual Behavior

With webpack "production" mode, css charset rule is not being added.

### Code

```js
// webpack.config.js
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const mode = process.env.NODE_ENV || "development";
const target = process.env.NODE_ENV === "production" ? "browserslist" : "web";

module.exports = {
  mode: mode,
  plugins: [new MiniCssExtractPlugin()],
  module: {
    rules: [{
        test: /\.(s[ac]|c)ss$/i,
        use: [
          MiniCssExtractPlugin.loader,
          "css-loader",
          "postcss-loader",
          "sass-loader"
        ]
    },{
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
        },
    }],
  },
  target: target,
  devtool: "source-map",
  devServer: { contentBase: "./dist" },
};
```

### How Do We Reproduce?

Follow instructions in this repo - https://github.com/scream87/css-charset-with-sass-loader

**Comment by alexander-akait** [comment]
Please provide configuration file for `postcss`

**Comment by scream87** [comment]
https://github.com/scream87/css-charset-with-sass-loader/blob/main/postcss.config.js

Which is:
```
// postcss.config.js
module.exports = {
  plugins: [require("postcss-preset-env")],
};
```

**Comment by alexander-akait** [comment]
I think something with `sass` (`dart-sass`) here on Windows, I am using linux (Ubuntu), after running `npm run build` my output:

**main.css**

```css
@charset "UTF-8";
/*!  Force output of above line by adding a unicode character. ♫ */
.hello-world:after {
  content: "привет мир";
  display: block;
}

/*# sourceMappingURL=main.css.map*/
```

**Comment by scream87** [comment]
Sorry, my bad, package.json script was Windows specific - `set NODE_ENV=production&& webpack`. It seemes that linux ignored first part (setting up environment for production) but still manages to invoke "webpack" command, which by default runs in development mode. And I can see that your output is created in development mode, since it is not minimized.

I had made some changes and updated git repo, could you please try again. Same commands "npm build" and "npm run build-dev".

**Comment by alexander-akait** [comment]
> Sorry, my bad, package.json script was Windows specific - set NODE_ENV=production&& webpack. It seemes that linux ignored first part (setting up environment for production) but still manages to invoke "webpack" command, which by default runs in development mode. And I can see that your output is created in development mode, since it is not minimized.

I seen this and fix it using `set NODE_ENV=production && webpack --mode production` and still have `charset`...

**Comment by alexander-akait** [comment]
Maybe problem in `postcss-preset-env`, try to comment `postcss-loader`, can't reproduce...

**Comment by alexander-akait** [comment]
Also check encoding of your file

**Comment by scream87** [comment]
> I seen this and fix it using `set NODE_ENV=production && webpack --mode production` and still have `charset`...

`webpack --mode production` will not take affect, since `mode` is specified directly in webpack config. I am pretty sure you had compiled development version. Please fetch last commit from git-repo and run test again.

File encoding is UTF-8, also tried without `postcss-loader` - same result.

**Comment by alexander-akait** [comment]
Bug in `sass` (`dart-sass`) https://github.com/sass/dart-sass, please report them about it, problem with the `outputStyle` option (https://sass-lang.com/documentation/js-api#outputstyle), for `production` we use "compressed" value to remove unnecessary stuff from CSS, but `compressed` removes `@charset`, it is definitely bug, you can reproducible it without `sass-loader`, using:
```bash
node_modules/.bin/sass src/style.scss --style compressed
```

output:
```css
﻿/*!  Force output of above line by adding a unicode character. ♫ */.hello-world:after{content:"привет мир";display:block}
```

as workaround you can use and them compress file using `csnano` or other css minimizer https://github.com/webpack-contrib/css-minimizer-webpack-plugin:
```js
{
  loader: "sass-loader",
  options: {
    sassOptions: {
      outputStyle: "expanded"
    }
  }
}
```

**Comment by scream87** [comment]
Ok, I see. Thanks for the operative and quick reaction.

**Comment by Danon** [comment]
@alexander-akait Was the bug reported in `dart`?
