### ISSUE TITLE
Not compatible with CSS-modules loading

### ISSUE THREAD

**Issue by OttlikG** [webpack-contrib/sass-loader#978]
- Operating System: Mac OS Big Sur Version 11.5
- Node Version: v14.17.3
- NPM Version: 6.14.13
- webpack Version: 4.46.0
- sass-loader Version: 12.1.0

This is the thread where the solution was only working for version 10.
https://github.com/storybookjs/storybook/issues/12464#issuecomment-824107014

### Expected Behavior
The scss applies to the story.

### Actual Behavior
The app throws an error with sass-loader@12.1.0
it works with sass-loader@10 tho.

```js
ERROR in ./component/section/section.module.scss (./node_modules/css-loader/dist/cjs.js?modules&importLoaders!./node_modules/sass-loader/dist/cjs.js!./component/section/section.module.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/Users/Gabor_Ottlik/Personal/bug-reproduce/node_modules/sass-loader/dist/index.js:25:24)
 @ ./component/section/section.module.scss 2:26-167 53:4-74:5 56:18-159
 @ ./component/section/section.tsx
 @ ./component/section/section.story.tsx
```

### Code

```js
https://gist.github.com/OttlikG/8dac0471f12dd4d031a99cfe48ffffc6#file-storybook-webapck-config
```

### How Do We Reproduce?

https://github.com/OttlikG/sass-loader-bug

Run `yarn dev`.

**Comment by alexander-akait** [comment]
> TypeError: this.getOptions is not a function

You need webpack v5 to use the latest version of `sass-loader` https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L44
