### ISSUE TITLE
SassError: @use rules must be written before any other rules.

### ISSUE THREAD

**Issue by jmfrancois** [webpack-contrib/sass-loader#982]
Hello !

Since I have updated from node-sass to `sass` I have deprecated errors about the following breaking change:
https://sass-lang.com/documentation/breaking-changes/slash-div

I have quite a big code base and we use the `additionalData` option to prepend our theme variables.
But since then If I try to use the math.div it complains about the following error:

```
ERROR in ./src/app/components/TokensPanel/TokensTile.scss (./node_modules/css-loader/dist/cjs.js??ref--9-1!./node_modules/postcss-loader/src??ref--9-2!./node_modules/resolve-url-loader??ref--9-3!./node_modules/sass-loader/dist/cjs.js??ref--9-4!./src/app/components/TokensPanel/TokensTile.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: @use rules must be written before any other rules.
       ╷
    14 │ @use 'sass:math';
       │ ^^^^^^^^^^^^^^^^
       ╵
      /Users/xxx/Developments/project/src/app/components/TokensPanel/TokensTile.scss 14:1  root stylesheet
```
      
But this line is in first line of the file.

Does it means I can't use prependData if I want to be able to use math ?

**Comment by alexander-akait** [comment]
`additionalData` can be function so you can place `@use` where you want (and not only `@use`) https://github.com/webpack-contrib/sass-loader#function-1, unfortunately we cannot do more here, only provide ability to insert something at any position
