### ISSUE TITLE
Getting error, when trying to compile scss files

### ISSUE THREAD

**Issue by and-bulk** [webpack-contrib/sass-loader#984]
### Actual Behavior

I get error when trying to compile all scss files

![image](https://user-images.githubusercontent.com/79831859/131996373-d7d98fa7-625a-4f80-a277-654d64c7ac09.png)

### Expected Behavior

It should compile scss files, without error `cannot find module ./ranges/simplify`

### How Do We Reproduce?

**webpack config**

```js
module.exports = {
  entry: ['babel-polyfill', './src/index.js'],
  output: {
    filename: 'static/bundle.[hash].js',
    path: path.join(__dirname, '/dist'),
    publicPath: '/',
  },
  module: {
    rules: [
      {
        test: /\.(scss|css|sass)$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
          },
          {
            loader: 'sass-loader',
          },
        ],
      },
    ],
  },
};
```

**Comment by alexander-akait** [comment]
sass-loader get resolve `./ranges/simplify`, check your imports, without reproduce example I can't help

**Comment by and-bulk** [comment]
```
rm -rf node_modules
npm install
```

helped
