### ISSUE TITLE
Module parse failed: Unexpected character ''

### ISSUE THREAD

**Issue by juanchehin** [webpack-contrib/sass-loader#986]
Hello, I am new to webpack, when trying to run 

> npm run build

 I get the following error:

![err](https://user-images.githubusercontent.com/40132117/132858829-58c0f6f7-1018-48a5-8650-b89443cd1758.png)

This is my code https://github.com/juanchehin/webpack2

**Comment by alexander-akait** [comment]
Please use `test` here https://github.com/juanchehin/webpack2/blob/main/js_modules/webpack.config.js#L18
