### ISSUE TITLE
sourcemap fix for node-sass doesn't work anymore

### ISSUE THREAD

**Issue by SharakPL** [webpack-contrib/sass-loader#987]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
It [states ](https://webpack.js.org/loaders/sass-loader/#sourcemap):

> In some rare cases node-sass can output invalid source maps (it is a node-sass bug).
> 
> > In order to avoid this, you can try to update node-sass to latest version or you can try to set within sassOptions the **outputStyle** option to **compressed**
>

I've been strugling to get correct source maps from my config and turnes out compressed output was the problem. Changing to `expanded` finaly fixed it. Seems the bug is slightly different in `node-sass@6.0.1` I'm using now.

**webkack.config.js**
``` js
devtool: 'source-map', // 'inline-source-map' also works
module: {
    rules: [
      {
        test: /\.scss$/,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: {
              importLoaders: 2,
            },
          },
          'postcss-loader',
          {
            loader: 'sass-loader',
            options: {
              implementation: require('node-sass'),
              sassOptions: {
                outputStyle: 'expanded',
              },
            },
          },
        ],
      },
      ...
    ],
  },
```

### Your Proposal for Changes
Suggest `outputStyle: 'expanded'` for node-sass ^6.0.0

**Comment by alexander-akait** [comment]
Migrate on `sass` (`dart-sass`), `node-sass` is not working good with source maps, nothing to fix on our side sorry, we don't do magic here, just get source maps which returned from `node-sass`

**Comment by SharakPL** [comment]
I said IT WORKS! Just not with the option suggested in the docs. With node-sass@6 `outputStyle: 'expanded'` is required.

**Comment by alexander-akait** [comment]
It is luck, in some cases it will not work, we have failed tests on this

**Comment by SharakPL** [comment]
Ok, thanks
