### ISSUE TITLE
CSS Modules and SASS modules with at-use rules

### ISSUE THREAD

**Issue by GabenGar** [webpack-contrib/sass-loader#988]
First off the terms:
- SASS module - any `.scss` file which gets referenced by `@use` rule.
- CSS Module - the stylesheet files which have `.module` prepended before their extension in their filename by the convention so they could be processed by webpack differently. Technically CSS Module can also be a SASS module, but that kinda defeats the point of the former.

### Bug report
The newest SASS version requires a `@use` rule in each file using SASS variables. This also means all SASS modules have to compile into a single file, which is mildly annoying. But CSS Modules seem to create separate "entries" or whatever SASS uses to differentiate between modules. This makes the output CSS to repeat declarations coming with each CSS Module, which is opposite of what SASS modules were supposed to do.
Also it seems CSS Module rules go before the generic declarations regardless of CSS Module loader order in `Config.module.rules`.

### Actual Behavior
All `@use` imports within resulting CSS repeat per CSS module file and CSS Module declarations go before the generic rules.

### Expected Behavior
All `@use` imports only used once in the whole file and CSS Module rules go after generic rules.

### How Do We Reproduce?
```sh
git clone https://github.com/GabenGar/repros.git
cd repros/webpack/sass-loader-css-modules-at-use/
cp .env.example .env # set the FRONTEND_OUTPUT_PATH value to an absolute path
npm run install-all
npm run build
```
Look at `main.css` in `{FRONTEND_OUTPUT_PATH}/public/bundle/styles` and you will see 4 blocks of variable declarations, 3 from CSS Modules and 1 from the generic file. Notice the generic declaration doesn't repeat, despite being referenced in `/client/src/styles/base.scss`, the same way as module files. You can comment out `@use` at any of the components in `/client/src/components`, run the build again and end in the crash, thus confirming this is the way SASS requires to deal with its variables.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
Don't think it's related to any packages beyond the ones required by `sass` and `sass-loader`.

**Comment by alexander-akait** [comment]
Expected, sass generate that in this way, you need minimizer here to merge `:root` declarations, we can't change logic for `@use`, sorry, also you can move all common variables to separate file and import them (for example in `layout`). Feel free to feedback, even more merging them as you want can be unsafe in some cases (you can override variable for one commonent), it is job of minimizer.

**Comment by alexander-akait** [comment]
Each component doesn't know about other component, they can be loaded on initial phase (page loading) or lazy (using `import()` in js), there are another cases. My recommendation is separate sass variables from custom properties, they have different meaning, also I recommend to use only one approach, not mix them. Also `:root { }` is more related layout, because they are hoisted and available even in HTML, try to write `<div style="color: var(--colour0-primary)">Text</div>`.

**Comment by GabenGar** [comment]
Yeah I've figured the sass stuff will have to be separate for this to work. Kinda annoying that I'll have to have two files for variables, but manageable.

> My recommendation is separate sass variables from custom properties, they have different meaning, also I recommend to use only one approach, not mix them.

I know the difference between sass and css variables and the latter can't really replace the former, since css vars are DOM-bound and thus can't be used in `@media` queries at the very least. And the former get pretty verbose (both in lines of text and bundle size) when trying to accomplish the same runtime tricks as css vars.

> Also `:root { }` is more related layout, because they are hoisted and available even in HTML, try to write `<div style="color: var(--colour0-primary)">Text</div>`.

`:root {}` is just a way to target `<html>` element with specificity higher than `0.0.0.1`. Also layout is more about markup than colors, so at the very least it is decided on `<body>` element. In SPA apps it goes even deeper to the app root element.

**Comment by alexander-akait** [comment]
Sorry, we can't solve this here
