### ISSUE TITLE
CSS content value changed after using sass loader

### ISSUE THREAD

**Issue by hiepnh610** [webpack-contrib/sass-loader#989]
I am using sass loader with webpack to compile my styling.

I have custom icon font.

My css file
```
.icon-cancel:before {
  content: '\e900';
}
```

After run through `sass-loader` my css changed. I want to keep original value of content property.
```
icon-cancel:before{
  content: ""
}
```

How can I solve this issue? Thanks!

**Comment by alexander-akait** [comment]
Please ask that in `sass` repo, we don't change your content, just run `sass`/`node-sass`
