### ISSUE TITLE
Sass-loader can't parse unicode-range value

### ISSUE THREAD

**Issue by nenravitsa** [webpack-contrib/sass-loader#997]
### Bug report

![image](https://user-images.githubusercontent.com/10672224/140926430-77da5ed8-cad3-45c5-85ec-50502842b74e.png)

### Expected Behavior

Range values should be preserved after compile.

### How Do We Reproduce?

``
{
          test: /\.scss$/,
          exclude: /\.module\.scss$/,
          use: [
            { loader: IS_DEV ? "style-loader" : MiniCssExtractPlugin.loader },
            {
              loader: "css-loader",
              options: {
                importLoaders: 1,
                modules: {
                  mode: "icss",
                },
              },
            },
            {
              loader: "sass-loader",
              options: {
                implementation: require("sass"),
                sourceMap: IS_DEV,
              },
            },
          ],
        },
``
Adding @charset "utf-8"; to the top of the file didn't help

Webpack: 5.62.1
Sass-loader: 12.3.0
Sass: 1.43.4
Node: 14.17.6

**Comment by alexander-akait** [comment]
Please open an issue in `sass` https://github.com/sass/dart-sass/, also `npm ls sass`, maybe you still have old version

**Comment by nenravitsa** [comment]
Moved issue to sass 
https://github.com/sass/dart-sass/issues/1551
