### ISSUE TITLE
variables are not global as they were before?

### ISSUE THREAD

**Issue by patrick99e99** [webpack-contrib/sass-loader#998]
I have recently upgraded from webpack 4 to webpack 5, and previously my stylesheets did something like:

```
# application.scss
$color: golden-brown;
@import 'waffles';
```

```
# waffles.scss
.yummy { color: $color }
```

Now I get `Undefined Variable $color`

Sass' documentation says:
`Variables declared at the top level of a stylesheet are global`

Why am I getting Undefined Variable errors?

**Comment by alexander-akait** [comment]
Please open an issue in `sass`

**Comment by patrick99e99** [comment]
I did, and they said:

> I'm unable to reproduce this in Sass on it's own, which makes me think this is indeed a sass-loader bug (and should be reopened there).

https://github.com/sass/sass/issues/3204
