### ISSUE TITLE
variables are not global as they were before? (re-opening #998)

### ISSUE THREAD

**Issue by patrick99e99** [webpack-contrib/sass-loader#999]
I previously opened this issue: https://github.com/webpack-contrib/sass-loader/issues/998 in which I was told to open the issue in sass.

I did so:
https://github.com/sass/sass/issues/3204

and was told:
> I'm unable to reproduce this in Sass on it's own, which makes me think this is indeed a sass-loader bug (and should be reopened there).

So I am attempting to "reopen" this here.

**Comment by alexander-akait** [comment]
Again, we don't modify your code, sorry we can't fix it here, also if you need help, please create reproducible test repo, and fill out all fields in the issue template, closing, I will reopen when you fix it
